### ISSUE TITLE
Incorporating partial knowledge of future values of time-series

### ISSUE THREAD

**Issue by vincent-lange** [facebook/prophet#1000]
I am trying to **forecast product-volume at delivery-date**, and so far Prophet is able to capture the different time-components quite nicely since the delivery-date is very dependent on time-features.

However in my case, **users most of the time order a delivery prior (up to 2 weeks or more) to the eventual delivery-date**, which means that I do have partial knowledge about the future values of the volume at delivery-date, which I am trying to predict. The date of the order in itself does not show strong time-dependence, that's why I want to forecast at delivery-date.

_e.g. let's say a huge order for delivery in 2 weeks came in already; this should then be reflected in a higher predicted volume for that particular future delivery-day_

**Now my question is, how can I utilize the orders which I already know are going to be delivered in the future, to inform the forecast of the product-volume of my Prophet-model?**

I am aware of the possibility of adding a **regressor**, however I can't wrap my head around how this would apply in my particular case, so I hope you guys can help me out 👍

**Comment by bletham** [comment]
This is an interesting problem. Basically, you have `y(t)` that is orders to be delivered at t, but also a separate time series `z(t' ; t)` which is at time t' how many orders have already come in for future time t. That is,
```
y(t) = z(t;t)
y(t) >= z(t' ; t) for all t' <= t
```
`y(t)` and `z(t';t)` can both be considered as random variables, and we expect them to be jointly distributed and positively correlated. How do we capture that in the model?

This could be done with an entirely new model that explicitly models z(t';t) and the relationship with y, but I think there are also two things you could do with Prophet that would not require too much additional work.

The first is using extra regressors. Suppose we want to make predictions two weeks out. For every t in the history, we can compute `z( (t - 2 weeks) ; t)`, that is, at every time t, how many orders had been made 2 weeks prior. We then include that in the model as an extra regressor. What this would be doing is essentially
```
y(t) = trend(t) + seasonality(t) + beta * z( (t - 2 weeks) ; t)
```
where the parameter beta will be fit to the data. Thus if `y(t)` and `z( (t - 2 weeks) ; t)` are (linearly) correlated, that will be captured by the model. Higher-than-average values of `z( (t - 2 weeks) ; t)` will lead to a corresponding increase in `y(t)`.

The main downside of this approach is that you can only predict out as far as the lag that you use in z (in this example, 2 weeks). That's because the extra regressor needs to be known in the future. So if you want to predict out a month, you would need to use z lagged at a month - which will be a lot less correlated with y than z lagged at 2 weeks, or z lagged at a day. So you have to trade-off accuracy (correlation with z) with the forecast horizon.

It also doesn't allow you to use the whole curve z(t' ; t), you use only a fixed lag.

To do better I think will require some extra work to really be able to forecast z(t' ; t) given the observations of z so far, and then incorporate those forecasts into the forecast of y. I don't have any really specific ideas on how that might be done, but I'm not sure Prophet the package would be useful. (Thinking about it as a regression problem in a similar way may be).

 The other thing you could try would be to just incorporate the constraint `y(t) >= z(t' ; t) for all t' <= t`. The way you could do this would be:
* Draw posterior predictive samples for all future times.
* At each future time, compare the draw `y_hat(t)` to `z( . ; t)`, the current number of orders for that t.
* Throw out any posterior draws where `y_hat(t) < z( . ; t)`.
* Take the mean of the remaining samples. Use this as y_hat, and use the quantiles of the samples as y_hat_lower and y_hat_upper.

This will produce a forecast where the lower uncertainty bound is always `>= z( . ; t)`. I describe this approach in a similar context in #693 with a little more detail, and there is even an article that describes it in a lot of detail here: https://towardsdatascience.com/goal-based-forecasting-in-prophet-r-b79900c64ca6

Relative to the first approach I described (include a lagged z as an extra regressor), this has the benefit of allowing each forecast point to use the lastest z instead of being stuck at a fixed lag. But it has the downside of not being able to capture the fact that we expect `y_hat(t)` to be _even more_ larger than `z( . ; t)` as the lag increases.

You could actually use both of these strategies at the same time, and that might be the best you can do while still using the model in the package.
