### ISSUE TITLE
Description of fields(columns) in forecast data.frames? 

### ISSUE THREAD

**Issue by davidjayjackson** [facebook/prophet#1001]
I managed to find a definition of "yhat" on google? 
Is there a description of  remaining field some place? 
Last question, where is the actual daily observation number stores?
TIA, David

**Comment by bletham** [comment]
In the documentation here (https://facebook.github.io/prophet/docs/quick_start.html#python-api) it gives some description right before the call to `predict`:
```
The predict method will assign each row in future a predicted value which it names yhat. If you pass in historical dates, it will provide an in-sample fit. The forecast object here is a new dataframe that includes a column yhat with the forecast, as well as columns for components and uncertainty intervals.
```

So yhat is the forecast, and then there are columns for the components which depend on what seasonalities/regressors were used (but they will be things like `trend`, `weekly`, `yearly`), and then for each component there is a `_lower` and `_upper` that gives the uncertainty interval for that component.

The best place to get the actual observation is just on the history dataframe that was originally passed in to Prophet. You can combine it with the forecasts using pd.merge.

**Comment by davidjayjackson** [comment]
Ben ,
Thanks, that is very helpful.

David

**Comment by amw5g** [comment]
Further to this, what is the difference between "seasonal" and "seasonalities" the prediction dataframe?  It would seem that _seasonalities_ is the sum of weekly & yearly seasonal effects.  At least in my case, since I'm using an additive model with clearly yearly and intra-week seasonalities.  But I don't get what _seasonal_ represents in a real-valued additive model.

**Comment by bletham** [comment]
@amw5g are you by chance using an old version of Prophet? The use of 'seasonal' was stopped I believe in v0.3, because it was very confusing what it meant.

To give you a much longer answer then you probably want, in v0.1 'seasonal' meant sum of all seasonalities. In v0.2 extra regressors were added. To maintain a particular aspect of backwards compatibility, 'seasonal' then started to mean sum of all seasonalities _and_ extra regressors; and so 'seasonalities' was added to indicate just sum of all seasonalities. This was as you have noted very confusing and in v0.3 it was changed. Starting in v0.3 there is support for both additive or multiplicative seasonaltiies and extra regressors, so we have 'additive_terms', which is the sum of all seasonalities and extra regressors that are additive; and 'multiplicative_terms', which is the sum of all seasonalities and extra regressors that are multiplicative.

**Comment by amw5g** [comment]
@bletham I am indeed using an older version (v0.21, ugh).  This is due to a larger need to be consistent with other development environment nuances, and so I'm stuck using what's on conda-forge for windows 32-bit.  Not ideal :/.

I appreciate the history lesson, that's just as much info as I wanted, nothing more, nothing less :)

**Comment by bletham** [comment]
Mm, I see, I didn't realize win32 had an old version on conda forge. Unfortunately fixing that is beyond my conda forge knowledge.
