### ISSUE TITLE
Importing fbprophet sets root logger level to `INFO`

### ISSUE THREAD

**Issue by zachdj** [facebook/prophet#1006]
When using the Python version of the library, importing `fbprophet` can sometimes cause the  logging level of the root logger to become `logging.INFO`.

Reproducible example:
```python
import logging
import sys

# notice that the default logging level for the root logger is `WARNING`
assert logging.getLogger().getEffectiveLevel() == logging.WARNING

custom_logger = logging.getLogger('herp-e-derp')
custom_logger.addHandler(logging.StreamHandler(sys.stdout))
custom_logger.info('This message should not show up')

import fbprophet

# after importing fbprophet, the root logger will have level `INFO`
custom_logger.info('We would not expect this message to show up, but it does anyway')
```

This issue has caused some problems for [people using `fbprophet` on DataBricks](https://forums.databricks.com/questions/17799/-infopy4jjava-gatewayreceived-command-c-on-object.html).

I think this is caused by the following lines in [`python/fbprophet/forecaster.py](https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py):
```python
# lines 24-27 in python/fbprophet/forecaster.py
logger = logging.getLogger('fbprophet')
logger.addHandler(logging.NullHandler())
if len(logger.handlers) == 1:
    logging.basicConfig(level=logging.INFO)
```

Perhaps it would be better to set the logging level for the `fbprophet` logger instead of the root logger?
```python
logger = logging.getLogger('fbprophet')
logger.addHandler(logging.NullHandler())
if len(logger.handlers) == 1:
    logger.setLevel(logging.INFO)
```

**Comment by bletham** [comment]
Logging issues come up periodically and our current approach is probably not the best. Basically what we want is to get INFO level logging to stdout by default, while still making it possible to modify the logging as desired.

To achieve that, we just copied what pystan does with logging (https://github.com/stan-dev/pystan/blob/master/pystan/__init__.py).

PyStan has a description of how logging can be customized prior to package import: https://github.com/stan-dev/pystan/blob/develop/doc/logging.rst . My understanding of the logging package is pretty superficial, but I believe if you manually set up the fbprophet logger prior to import, then it will not change the root logger to INFO.

As for the solution presented: That seems reasonable to me so long as it does provide logging to stdout by default?. But I'm wondering if it will actually resolve the issue since PyStan has the same code and fbprophet imports pystan. So would it have to be changed there too?

**Comment by zachdj** [comment]
Thanks for the explanation!

> As for the solution presented: That seems reasonable to me so long as it does provide logging to stdout by default?

I actually don't think that the suggested solution will provide logging to stdout by default for fbprophet INFO messages.  The root logger (which is configured by `basicConfig`) has a default level of `WARNING`.  `WARNING`- and `ERROR`-level messages from fbprophet will still be logged to stdout, but the end user of fbprophet would need to configure the prophet logger with a stdout handler to see the `INFO` messages.

I think this is more desirable behavior.  If you _really_ need a user to see a message, shouldn't it be at the warning level anyway?

> But I'm wondering if it will actually resolve the issue since PyStan has the same code and fbprophet imports pystan. So would it have to be changed there too?

Yeah I guess so.  That's kind of annoying.  Maybe fbprophet should have some docs similar to pystan explaining how to customize logging prior to import

**Comment by zachdj** [comment]
>

**Comment by zachdj** [comment]
>

**Comment by bletham** [comment]
I think the difficulty is that "warning" makes it sound like something is going wrong and could cause users to be confused. I think this usage of logger.info is pretty typical of the info-level logging done in the package:
https://github.com/facebook/prophet/blob/7ff33137eb53fe9b1b743cc090fdad7872aabdca/python/fbprophet/diagnostics.py#L54

We want to print out the number of forecasts being made in cross validation, because sometimes it will make a lot of forecasts and will take a few minutes to run. It's good for users to have an idea of if it's going to be 5 forecasts or 25 to have some idea of when it will finish. But I feel like doing that as a "WARNING: ..." could make users think they chose bad settings and the cross validation isn't working as it's meant to.

I know that's a fairly minor thing to then add a bunch of work if you _do_ want to suppress info-level logging, but I think many users will not have a whole lot of familiarity with python logging and so the default experience is pretty important. Interfering with other packages is a big negative but I don't see a really great option. At the least, though, we should as you suggested link to the PyStan documentation about logging so people have that resource for figuring these things out.

**Comment by TristanJM** [comment]
After importing `fbprophet` you receive these logs for all other libraries too (which isn't ideal)

Example logs:
```
INFO:hyperopt.utils:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
2019-07-09 14:52:24,227 INFO [main] My nice formatted logs
2019-07-09 14:52:24,638 INFO [main] More logs
INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
```
hyperopt logs shouldn't be appearing after importing prophet, but I see that the final INFO log from prophet is useful. So how can we keep the prophet logs and prevent the activation of other library logs?


If we add this override for **both** prophet and pystan, we can suppress the logs for other libs.
```
logger2 = logging.getLogger("fbprophet")
logger2.addHandler(logging.NullHandler())
handler2 = logging.StreamHandler(sys.stdout)
handler2.setFormatter(my_formatter)
handler2.setLevel(logging.INFO)
logger2.addHandler(handler2)

logger3 = logging.getLogger("pystan")
logger3.addHandler(logging.NullHandler())
```

After the fix above, we still get unnecessary logs from prophet (straight to stdout with no level) and we lose the useful `INFO` log from prophet.
```
2019-07-09 14:52:24,227 INFO [main] My nice formatted logs
2019-07-09 15:06:09,630 INFO [preprocess] Data: 1210 (Train: 980, Val: 193, Test: 37)
2019-07-09 15:06:09,641 INFO [main] Training prophet model
Initial log joint probability = -13.1337
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      99       2072.16     0.0173682       1091.36      0.8031      0.8031      140   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     199       2177.94     0.0537723       3102.72      0.2882           1      303   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     383       2220.33   5.95938e-06       118.718   1.564e-08       0.001      669  LS failed, Hessian reset 
     399       2222.17    0.00895483       252.918      0.5761           1      693   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     411       2222.67   6.44379e-06       191.935   5.801e-08       0.001      752  LS failed, Hessian reset 
     499       2235.66     0.0191115       1179.73           1           1      892   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
     912       2260.82   3.94316e-06       77.4621   1.428e-08       0.001     1612  LS failed, Hessian reset 
     926       2261.14   2.23236e-06       78.5069   1.952e-08       0.001     1699  LS failed, Hessian reset 
     965       2261.29   2.48015e-06        71.358   1.632e-08       0.001     1794  LS failed, Hessian reset 
     999       2261.37   7.14797e-05       197.625      0.3532           1     1855   
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
    1301       2262.19    2.9104e-06       84.0956    1.62e-08       0.001     2451  LS failed, Hessian reset 
    1339        2262.2   3.50713e-08        47.029      0.1759      0.1759     2504  
2019-07-09 15:06:09,641 INFO [main] Finished
```

Any suggestion on how to format prophet INFO logs but not trigger all the other library logs?

**Comment by bletham** [comment]
For customizing fbprophet logging, I believe as long as you do it before package import it should work (as described in th prophet ). And yes, that class is still the best way to suppress the stan optimizer printing, which is coming from C++ and not python.

**Comment by TristanJM** [comment]
> For customizing fbprophet logging, I believe as long as you do it before package import it should work (as described in https://github.com/stan-dev/pystan/blob/master/pystan/__init__.py . And yes, that class is still the best way to suppress the stan optimizer printing, which is coming from C++ and not python.

Doing the logging customisation above won't show the `INFO` logs from prophet even if you do it before importing. It'll simply remove all logs to stdout, including the ones we care about.

Any idea how to get this code to show prophet `INFO` logs in a formatted way? (You have to add the `NullHandler` to prevent all the other libraries starting to log things to stdout)
```python
logger2 = logging.getLogger("fbprophet")
logger2.addHandler(logging.NullHandler())
handler2 = logging.StreamHandler(sys.stdout)
handler2.setFormatter(my_formatter)
handler2.setLevel(logging.INFO)
logger2.addHandler(handler2)

logger3 = logging.getLogger("pystan")
logger3.addHandler(logging.NullHandler())
```

**Comment by bletham** [comment]
I'm not quite getting that behavior, but I am getting some bad behavior when I do this:

```
import logging
import sys

logger = logging.getLogger("fbprophet")
handler2 = logging.StreamHandler(sys.stdout)
handler2.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s222222')
handler2.setFormatter(formatter)
logger.addHandler(handler2)

from fbprophet import Prophet
import pandas as pd

df = pd.DataFrame({'ds': ['2018-01-01', '2018-01-02', '2018-01-03'], 'y': [1., 3., 1.]})
m = Prophet().fit(df)
```
I get two outputs for every logging event: One with the default formatting, the other with the custom formatting that I specified.

I wonder if this is because we add the handler here before checking if a handler has already been specified:
https://github.com/facebook/prophet/blob/480b67b8fed05381b910bce6e7a64efba9f0d838/python/fbprophet/forecaster.py#L25

**Comment by TristanJM** [comment]
If you now import another library after pandas (eg. `hyperopt`) you'll get their INFO logs to stdout as well, which we really don't want. You also get the duplicate logs as you noticed.
Output:
```
INFO:hyperopt.utils:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
INFO:hyperopt.fmin:Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
2019-07-16 10:18:56,331 - fbprophet - INFO - Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.222222
INFO:fbprophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.

Initial log joint probability = -8.88016
Iteration  1. Log joint probability =   0.437246. Improved by 9.3174.
...
```


The duplicate unformatted logs **and** the activation of other library logs are because `pystan` also changes the root logger when you import `fbprophet`.

```python
import logging
import sys

logger = logging.getLogger("fbprophet")
handler2 = logging.StreamHandler(sys.stdout)
handler2.setLevel(logging.INFO)
formatter = logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(message)s222222"
)
handler2.setFormatter(formatter)
logger.addHandler(handler2)

# try to fix pystan's override too
logger2 = logging.getLogger("pystan")
logger2.addHandler(handler2)

from fbprophet import Prophet
import pandas as pd
import hyperopt

df = pd.DataFrame(
    {"ds": ["2018-01-01", "2018-01-02", "2018-01-03"], "y": [1.0, 3.0, 1.0]}
)
m = Prophet().fit(df)

"""
output:

Initial log joint probability = -8.88016
Iteration  1. Log joint probability =   0.437246. Improved by 9.3174.
...
"""
```

Now we get no logs at all:
* not from any other library (good)
* not formatted INFO from prophet (bad)

In both `fbprophet` and `pystan` we set `logging.baseConfig(level=logging.INFO)` to enable the libraries to override the root logger and allow their logs. Unfortunately this also opens the floodgates to all other libraries. I haven't been able to figure out how you allow this specific to one library

**Comment by bletham** [comment]
Ah, good call on pystan being the source of the duplication. I can't figure out why the logs are not printing when the handlers are set up as you do.

**Comment by Stuti14** [comment]
I am getting these log info which i don't want, how can I remove these logs in python?

logs:
INFO:fbprophet:Making 9 forecasts with cutoffs between 2019-12-26 23:00:00 and 2019-12-27 07:00:00
INFO:fbprophet:n_changepoints greater than number of observations.Using 9.
INFO:fbprophet:n_changepoints greater than number of observations.Using 10.
INFO:fbprophet:n_changepoints greater than number of observations.Using 11.
INFO:fbprophet:n_changepoints greater than number of observations.Using 11.
INFO:fbprophet:n_changepoints greater than number of observations.Using 12.
INFO:fbprophet:n_changepoints greater than number of observations.Using 13.
INFO:fbprophet:n_changepoints greater than number of observations.Using 14.

**Comment by tulbureandreit** [comment]
Hi. I want to remove all logging for Prophet and keep only ERRORS. Something like _set_log_level("ERROR"). But nothing here works. @cdeil any further ideas? I am using py 3.10 prophet 1.1.1
