### ISSUE TITLE
multiplicative model beta

### ISSUE THREAD

**Issue by germayneng** [facebook/prophet#1011]
Hi! I have some questions on the extra regressors interpretations:

From here : https://github.com/facebook/prophet/issues/928

Assuming that our regressor follows our seasonality mode, and assume we are modelling a multiplicative model: 

> additive:       y(t) = trend(t) + seasonality(t) + beta * regressor(t)
multiplicative: y(t) = (1 + seasonality(t) + beta * regressor(t)) * trend(t)

So you mentioned in the link that for multiplicative, increasing regressor by 1 unit leads to increase in y(t) by trend(t). **But shouldnt it be increasing regressor by 1 unit leads to increase in y(t) by trend(t) * beta??**

Another more complex thing would be if we define the seasonality to be multiplicative and the regressor to follow additive, how will this change our interpretation of the regressor's beta? Also what if we swipe seaonality to be additive and regressor to be multiplicative? There isnt a consensus that our regressor's mode should follow the seasonal or is it a best practice to ensure they are the same

**Comment by bletham** [comment]
That's correct, in the multiplicative case increasing regressor(t) by 1 unit will increase y by trend(t) * beta.
(Although it's actually a little more complicated since regressor(t) will be default be standardized, but we can imagine that the standardization factor is absorbed into beta).

As for additive vs. multiplicative - I think here it probably depends on the setting.

For seasonalities, we often get multiplicative seasonality because fluctuations represent a % change in people-driven outcomes. As the number of e.g. customers grows, the % changes stay the same, and so we get a seasonal effect that grows with the base rate. Additive seasonality assumes that the seasonal factor drives cyclic changes in the raw numbers, while multiplicative seasonality assumes that the seasonal factor drives a cyclic change in the %.

For extra regressor, it comes down to the same thing: is it driving a change in the raw numbers or in the %? If you took extra_regressor=5, would it have the same effect if the base rate (trend) were 100 as if it were 1000?

To make this a little concrete, consider this example (which I really love): https://nbviewer.jupyter.org/github/nicolasfauchereau/Auckland_Cycling/blob/master/notebooks/Auckland_cycling_and_weather.ipynb

Here he uses extra regressors for weather factors, like temperature, in a forecast of bike usage. We expect temp of 40F vs. 80F to have an effect on bike usage - but additive or multiplicative? If the temp drops from 80F to 40F, do we expect that to drop a constant _number_ of riders, or a constant _percent_? That's basically the question of additive vs. multiplicative seasonality. I'd expect it to drop a constant percent, and so would model this as multiplicative (which is what he does in that notebook).

I can't really think of any realistic settings where one would have some regressors with multiplicative effects but others with additive effects. They probably exist, and would be interested to hear if you think of any. But I think in most settings they would likely be the same since it would depend more on the nature of y and how external factors influence y.

**Comment by germayneng** [comment]
Thanks for the prompt reply! Also I do have a questjon. By default with standardising , how does it change the way we interpret beta? Will this change the way we interpret it? ( as mentioned by you above)

**Comment by bletham** [comment]
That's right for beta. Generally though I think the best way to understand the effect of a regressor is to look at the component in the forecast dataframe (equivalently, look at it in the components plot) which will show exactly what amount of y is being explained by the extra regressor.

**Comment by germayneng** [comment]
Hi @bletham  Sorry to bring this back. Standardizing can be disabled for the regressors. As for the y, it is scaled by its max value. This meant that even if i disable the regressor standarization, the beta value is with respect to scaled y values, which is not correct if we just take them as such. 

Doesnt seem like there is anyway to work with the beta values

**Comment by bletham** [comment]
This is true, that scaling is stored in `m.y_scale` so you could use it there to further adjust the beta, but like I said above I think the magnitude of the component in the forecast dataframe would probably be the most correct way of considering the relative importance.

**Comment by eromoe** [comment]
@bletham  About regressors I have a problem .
For example I have a timeseries (sale_count, price, ..., stock_count) of  a product. My goal is predict sale_count in future .

The problem is about `stock_count` . We can track how stock_count changing, it is handle by my man , more predictable . If a time point  `stock_count=0` , would easily infer that we can't sell this product any more.
I construct another model to make prediction of `stock_count` ,  maybe I have stock_count series  stock = [0,0,1,1,1,1....1, 0, 1...]  ,  I need to use multiply  stock * y(t) to get final result . 
Can fbprophet consider this too ?

**Comment by eromoe** [comment]
It looks like a varying cap .I just come up does logistic model support varying cap?  I think I need look into the code first ..

**Comment by bletham** [comment]
@eromoe I guess the right thing to do depends on how you want to model the relationship between sale_count and stock_count.
Setting stock_count as a capacity with logistic growth doesn't seem like the right model to me. The logistic growth model has the growth rate rise and fall with the capcity; more capacity means quicker growth, less capacity means less growth. Here, that would mean that if we double the stock count then we can double the sale count - probably not true.
A more typical model would be that there is some latent demand, and we observe a sale if stock_count is greater than demand, and we just don't observe sales otherwise. If data are aggregated by day or week or similar, then you could imagine doing something like the following:
* Remove all days from the data where there was a stockout (stock_count went to 0).
* Fit a model to the remaining days. If we assume that sales = demand whenever stock_count>0, this is now a model of demand.
* When predicting forward, we can use the model to forecast demand and then compute sales(t) = min(demand(t), stock_count(t)).

**Comment by eromoe** [comment]
Thank you very much. I tried to use min(demand(t), stock_count(t))  yesterday,  however I found the stock managment system was too complicated cound't not get a correct info of stock . We need some time to solve this problem at first .
