### ISSUE TITLE
Validation parameters

### ISSUE THREAD

**Issue by andrewng88** [facebook/prophet#1012]
I've been reading up examples for the past few days and I'm very happy that it's very simple to use up to the validation part.

I would like to do a prediction with daily data of 4 months , 1 week forecast. Of course I will not be predicting for the whole year since I do not have it. Do you suggest the following parameters?

cross_validate(m, horizon='7 days', period='7 days', initial='3*30')

Thanks

**Comment by bletham** [comment]
That seems reasonable to me, although I don't believe the '3*30' notation will work, pandas will want '90 days' or something like that.

This would give 4 error estimates for each day of the horizon. By default we usually set period to horizon/2, which would here give ~10 error estimates for each day of the horizon:
```
cross_validate(m, horizon='7 days', period='3 days', initial='90 days')
```
These error estimates are not entirely independent, but with only 1/2 overlap from each forecast horizon to the next you'll probably get some good variance reduction in the error estimates.

**Comment by andrewng88** [comment]
Ok thanks for your prompt reply. I'd try the settings that you've provided.

I think I do not have enough data for the initial period. Total 60
cross_validation(m, horizon='7 days', period='3 days', initial='50 days')

Side track, I've been reading up the diagnostic 
https://facebook.github.io/prophet/docs/diagnostics.html

I can't really visualize the initial, cutoff and the horizon parameters.

_Here we do cross-validation to assess prediction performance on a horizon of 365 days, starting with 730 days of training data in the first cutoff and then making predictions every 180 days. On this 8 year time series, this corresponds to 11 total forecasts._

`df_cv = cross_validation(m, initial='730 days', period='180 days', horizon = '365 days')`

What I understand is
i) initial = training days that we used for forecast
2) horizon = how many days you want to predict

Don't quite get the period and the cutoff.

May I trouble you to explain? Thank you

**Comment by bletham** [comment]
You take the first `initial` days of data, and use them to forecast out `horizon` days. `initial` is the cutoff, since we are using data before that as training data and data after that as test data.

Then, we advance the cutoff by `period` days. So, we now have `initial + period` days in the training, and we again forecast out `horizon` days. This gives us a 2nd set of error estimates.

And we repeat that, each time advancing cutoff by `period` days, to `initial + 2 * period`, `initial + 3 * period`, and so forth until we reach a point where we have less than `horizon` days left after the cutoff to be able to forecast.

Does that make more sense?

**Comment by andrewng88** [comment]
OK it's much clearer now. Thank you
Happy TGIF.
