### ISSUE TITLE
Very different behavior between 0.4.post2 and 0.5 fbprophet versions

### ISSUE THREAD

**Issue by rydevera3** [facebook/prophet#1019]
Hello,

Currently, I am building out different models with prophet. I was using the 0.5 version and then I switched to the 0.4.post2. 

```
model = Prophet(
    holidays_prior_scale=15.0,
)

model.add_country_holidays(country_name='US')
model.add_regressor('regressor_col_1')
```

My call to the model is very simple but for my holdout set the values are very different (with the exact same code). For `fbprophet==0.5` I get a validation `MAPE=0.12` but with `fbprophet==0.4.post2` I get a validation `MAPE=0.44`.

My question is:

1. Why might this be happening?
2. What were the significant changes made between the versions?
3. Were any default parameters changed?

**Comment by rydevera3** [comment]
A quick update on my end - I found this thread - https://github.com/facebook/prophet/issues/411 and when I switch `algorithm='Newton'` I get similar results now between the two versions. While, this is working would still love to know if this is the actually underlying difference between the two versions.

**Comment by bletham** [comment]
#978 describes the major changes with v0.5.

Related to Newton: There was a change where if you have less than 100 datapoints, it uses Newton by default instead of using L-BFGS by default (https://github.com/facebook/prophet/commit/e9c017ba017e8664593e6ed50707e83351ce3b3d). This change was because we found that Newton was much more robust for small datasets than L-BFGS, and in particular avoided a bunch of instances of system freezes that had been reported. If I understand correctly, then you have switched on v0.4 to use Newton and that has changed CV MAPE to be closer to that seen in v0.5? If your dataset has less than 100 points, then 0.5 will be using Newton and that could be part of it.

Another very important point for comparing CV results in v0.4 and v0.5 is that there was a significant change to the way cross validation metrics are computed for regularly spaced data (e.g., daily data, weekly data, ...). The change is described briefly in #978, which also links to the more detailed description of the change. So if you are using the built-in `performance_metrics` function and have regularly spaced data, you may see different results just because of how MAPE is being computed for each horizon. The change in v0.5 provides better (less biased by windowing) estimates of cross validation error.

Does one of those seem like the culprit?

**Comment by rydevera3** [comment]
Thank you @bletham. Yes, It is definitely the optimizer. When I switched it over to `Newton` everything started to be more inline.
