### ISSUE TITLE
Miss in capturing year end seasonality

### ISSUE THREAD

**Issue by chinmaytuw** [facebook/prophet#1021]
Hi,

My data is at a daily level for the years 2017, 2018. I am training the model till Nov' 18 and forecasting Dec'18 so I can compare the numbers with actuals. While laying down actuals and forecast on top of each other, there seems to be a big gap for the last week of December i.e. last week of my test period. 

<img width="1620" alt="Screen Shot 2019-06-18 at 2 36 05 PM" src="https://user-images.githubusercontent.com/18237649/59721563-7bf20c00-91d6-11e9-8546-87c9c50bd732.png">

The pattern for actuals in not very different from the previous December. It appears that the model is not capturing it despite a yearly seasonality component added. Could somebody please point out what I am doing wrong and how could I account for the dip observed?
Also, In general, if my time series follows a relatively similar yearly pattern, how can I make the model account for it? I thought the yearly seasonality component would suffice. It doesn't. Here's the plot component:

![image](https://user-images.githubusercontent.com/18237649/59794610-2f6a0780-928e-11e9-90c9-da4209623e46.png)

## Here's the code:
```
library(tidyverse)
library(prophet)
library(dygraphs)
library(xts)
library(lubridate)
````

```{r additional files}
holidays1 <- read.csv("Holidays1.csv")
df <- read.csv("df.csv")
```
```
# cleaning up the holiday file 
# and surrounding days for holidays on Tuesday and Thursday
holidays1$datecol <- as.Date(holidays1$datecol, format = "%m/%d/%y" )
holidays1$lower_window <- ifelse(holidays1$Weekday == "Tuesday",-1,0 )
holidays1$upper_window <- ifelse(holidays1$Weekday == "Thursday",1,0 )
holidays1 <- holidays1[c("Holiday_Desc","datecol","lower_window","upper_window")]
names(holidays1) <- c("holiday","ds","lower_window","upper_window" )
# adding a prior
holidays1$prior_scale <- 10

# converting ds to date 
df$ds <- as.Date(df$ds,format = "%m/%d/%y" )

# initializing prophet model
m <- prophet(holidays = holidays1, weekly.seasonality  = FALSE, yearly.seasonality = FALSE) 

# adding additional seasonality
m <- add_seasonality(m, name = "weekly", period = 7, fourier.order = 3)
m <- add_seasonality(m, name = "yearly", period = 365, fourier.order = 10) 

# fitting the model
m <- fit.prophet(m, df %>% filter(ds < '2018-12-01') )

# making future df
futureDF <- make_future_dataframe(m, periods =  31 ) #days_in_month(test_date1) 

# predicting
forecast1 <- predict(m, futureDF)

# converting ds to date type
forecast1$ds <- as.Date(forecast1$ds,format = "%m/%d/%y" )

# joining the actuals and forecast
combo <-  inner_join(forecast1[c("ds","yhat")],df, by = "ds") %>% rename( Actual = y, Forecast = yhat )
combo1 <- as.xts(combo, order.by = combo$ds ) 

# plotting forecast + Actuals
dygraph( combo1 ) %>% dyRangeSelector() %>% dyOptions(drawPoints = TRUE, pointSize = 2) %>% dyHighlight(highlightCircleSize = 3,highlightSeriesBackgroundAlpha = 0.6,hideOnMouseOut = TRUE)

```

[Files.zip](https://github.com/facebook/prophet/files/3303862/Files.zip)

**Comment by daikonradish** [comment]
Here's a suggestion for the yearly pattern - you could follow the suggestion [here](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html) for `nfl_sundays`. Basically what you want is to `add_regressor()` for a column that represents a `1` for December 24, 25, 26, 27, 28, 29, 30. Here's a snippet:

    yearly_occurrence <- function(ds) {
      dates <- as.Date(ds)
      month <- as.numeric(format(dates, '%m'))
      day <- as.numeric(format(dates, '%d'))
      as.numeric(day >= 24 & day <= 30 & month == 12)
    }
    df$yearly_occurrence <- yearly_occurrence(df$ds)
    m <- prophet()
    m <- add_regressor(m, 'yearly_occurrence')
    m <- fit.prophet(m, df)

but IMO for this to be useful you'll likely need to fit on more than just one year.

**Comment by vhpietil** [comment]
Please check and include the component plot. It might reveal where the problem is

**Comment by chinmaytuw** [comment]
> Here's a suggestion for the yearly pattern - you could follow the suggestion [here](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html) for `nfl_sundays`. Basically what you want is to `add_regressor()` for a column that represents a `1` for December 24, 25, 26, 27, 28, 29, 30. Here's a snippet:
> 
> ```
> yearly_occurrence <- function(ds) {
>   dates <- as.Date(ds)
>   month <- as.numeric(format(dates, '%m'))
>   day <- as.numeric(format(dates, '%d'))
>   as.numeric(day >= 24 & day <= 30 & month == 12)
> }
> df$yearly_occurrence <- yearly_occurrence(df$ds)
> m <- prophet()
> m <- add_regressor(m, 'yearly_occurrence')
> m <- fit.prophet(m, df)
> ```
> 
> but IMO for this to be useful you'll likely need to fit on more than just one year.

That makes sense and I tried incorporating this within the holiday list I am providing the model. Definitely, see an improvement. 
However, another issue is scalability. I have ~500 different time seriess' I want to forecast for and not every series has the same year-end effect. I am rather hoping that the model automatically captures this since 2 year's worth of data is provided.

**Comment by chinmaytuw** [comment]
> Please check and include the component plot. It might reveal where the problem is
> 
> You should also check if your model fits earlier year correctly or not.

Done! Could you please take a look. Also, the model doesn't fit the pattern for last year. I see a similar miss in the fitted values. What could I be doing wrong?

**Comment by bletham** [comment]
+1 for @daikonradish's suggestion. The issue here is that the model assumes smooth seasonality, and this large drop for 1 week is to sharp/fast of a change for the yearly seasonality (which spans 52 weeks) to capture well. It dips a little bit, but it can't change fast enough to be a full level the week before and full level again the week after while dipping all the way down.

The root of the issue is that in this time series, it seems there are significant holiday effects for the whole week  between Christmas and New Years. It looks like you've added a holiday for Christmas day itself, but not for the other days of that week. I would try adding a holiday for Dec24, Dec26, Dec27, Dec28, Dec29, Dec30, and Dec31. You could either do this with the "holidays" interface, or by creating a binary matrix like @daikonradish suggested.

As for not every time series having the same year-end effect: That's not a problem. You can still specify the holidays/regressors for all of the time series, and there is no effect for that time series, then they just will not be used by the model. (You can make sure of that by decreasing the prior scale a bit).


An alternative would be to increase the Fourier order of the yearly seasonality. I bring it up because it is given some description in the documentation (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#fourier-order-for-seasonalities) . This will allow the yearly seasonality to change more quickly and to be able to drop down and fit that week better. However, in this situation I would recommend the holidays/regressor approach over this approach, because we know that this week is special and we do not expect other weeks of the year to have this same time of drastic effect. Increasing the yearly seasonality Fourier order to cover this will make it much more likely to overfit the seasonality in other parts of the year and hurt the forecast. Especially for time series that don't have a strong effect in the end week this could be detrimental.

**Comment by sammourad** [comment]
Sounds like you have the best way to go about it from @bletham. I personally would choose to add the December 24 - December 31 holidays by setting lower_window to -1 and upper_window to 6 in the holidays' data frame for Christmas day while keeping them zero for other holidays.
