### ISSUE TITLE
Calculation of rate change / 'deltas' depending on seasonality

### ISSUE THREAD

**Issue by christophmeier** [facebook/prophet#1031]
Hi,

since turning on/off seasonality component(s) (e.g. weekly, yearly) directly influences the rate changes (the 'deltas') used to predict the trend component I am wondering how fbprophet exactly calculates the deltas and how seasonality affects that calculation. 

Many thanks for a response!

**Comment by bletham** [comment]
Basically the model is that
```
y(t) = trend(t; delta) + seasonality(t ; beta)
```
where `delta` are the trend parameters (rate changes, initial slope, initial offset) and `beta` are the seasonality parameters.

All of the parameters are jointly fit by maximizing the likelihood of the model. Removing a seasonal component completely changes the structure of the model, and so it will change the best-fit values for the trend. But it's hard to say exactly how removing a seasonality will affect the deltas, since it's all just a matter of maximizing likelihood.

For a more detailed (i.e., mathematical) description of the model and fitting, I would have to refer you to the paper: https://peerj.com/preprints/3190.pdf

**Comment by christophmeier** [comment]
Many thanks! I think the issue can be closed.
