### ISSUE TITLE
In cross_validation, STAN arguments aren't passed.

### ISSUE THREAD

**Issue by Alexsbuchanan** [facebook/prophet#1040]
For example, say I want to cross validate with 1000 mcmc samples, but only want it on a single process, the n_jobs=1 parameter for STAN is discarded (as far as I can tell) in the fit in the cross_validation function. Can we have a kwarg parameter in cross_validation that lets us pass arguments to STAN in this function?

**Comment by daikonradish** [comment]
do you have a code sample along with desired/undesired behavior?

**Comment by bletham** [comment]
This is a good suggestion. In cross validation, an unfit copy of the model is first made here:
https://github.com/facebook/prophet/blob/df8e39ae15a07ed7635a94a837247582225548fa/python/fbprophet/diagnostics.py#L108

And then it is fit here:
https://github.com/facebook/prophet/blob/df8e39ae15a07ed7635a94a837247582225548fa/python/fbprophet/diagnostics.py#L116

Any arguments to `Prophet()` are stored on the object and are appropriately copied over. However, as you note, kwargs to `fit` (which are passed along to Stan) are not being passed along.

Since `fit` can only be called once, as opposed to passing in the kwargs to cross_validation, I think my preferred solution would be to actually store the fit kwargs on the Prophet object. The copy utility can copy them over, and then in cross validation we would call
```
m.fit(history_c, **m.fit_kwargs)
```
Does that sound reasonable?

**Comment by Alexsbuchanan** [comment]
Hi @bletham 
Thanks for responding!
You're solution is certainly an improvement upon my initial request, I like it.

**Comment by daikonradish** [comment]
Took a stab at this. Seems reasonable, but *gotcha!* The `kwargs` allowed for `optimizing()` and `sampling()` are _not the same. Therefore this approach doesn't work: `Prophet.fit()` passes arguments merrily along into `sampling()`, `Prophet.cross_validation()` passes arguments merrily along into `optimizing()`.

https://pystan.readthedocs.io/en/latest/_modules/pystan/model.html#StanModel.optimizing

Actually I dunno why the two functions have different signatures 🤷‍♂

**Comment by bletham** [comment]
@daikonradish I don't think that should be an issue - cross_validation just calls `fit`, and whether or not `optimizing()` or `sampling()` is called will depend on `m.mcmc_samples`, as specified on model initialization. When the model is copied to make the new cross validation model, that attribute is copied as well:
https://github.com/facebook/prophet/blob/0d37a46593c7a1e0b8706be60a3d594ac3285c73/python/fbprophet/diagnostics.py#L181

So it should be the case that a model fit with MCMC (`sampling()`) will also use MCMC in cross validation. If you have found a situation where that isn't the case then it's definitely a bug.

**Comment by frederickayala** [comment]
Hi, I made a PR that adds the behavior described above. Please let me know if you would like me to make any changes. Thanks

**Comment by bletham** [comment]
This is done in https://github.com/facebook/prophet/commit/6e51130f28092099b4bc3b1c7c6349359c60be22

**Comment by bletham** [comment]
This is pushed to CRAN in v0.6
