### ISSUE TITLE
Modelling Sub-Daily Data

### ISSUE THREAD

**Issue by JainaProudmoore123** [facebook/prophet#1044]
Hello,

I have CPU metrics for every minute. Every data at two different times there is a peak load due to some batch processing. I have tried to account for this by adding 2 extra binary regressors as per https://github.com/facebook/prophet/issues/1013. I tried to fit Prophet model for last 5 months of train data versus just the last month of train data. The forecast is tested on 1 week worth of data.

CODE :
model = Prophet(changepoint_range=0.99)
train["floor"] = 0
train["cap"] = 100
model.add_regressor('reg_1', prior_scale = 0.9)
model.add_regressor('reg_2', prior_scale = 0.9)
model.fit(train)

DATA:

**This is how the data looks like for Training on last 5 months data.**

Usual Daily Usage :
![Day](https://user-images.githubusercontent.com/49508993/60205980-749ab600-9807-11e9-8b2d-19fde29f64a2.png)
Forecast :
![Forecast](https://user-images.githubusercontent.com/49508993/60205990-795f6a00-9807-11e9-9a88-829905516337.png)
Components :
![Components](https://user-images.githubusercontent.com/49508993/60205984-7795a680-9807-11e9-96b3-b9608108eacd.png)
In Sample (per month) :
![InSample1](https://user-images.githubusercontent.com/49508993/60206008-7f554b00-9807-11e9-9d11-ad08e8408583.png)
![InSample2](https://user-images.githubusercontent.com/49508993/60206014-811f0e80-9807-11e9-8e6b-ce15dec3d0cc.png)
![InSample3](https://user-images.githubusercontent.com/49508993/60206018-82503b80-9807-11e9-9314-62a5ffbef0ee.png)
![InSample4](https://user-images.githubusercontent.com/49508993/60206022-83816880-9807-11e9-8a78-cc09abed1d83.png)
![InSample5](https://user-images.githubusercontent.com/49508993/60206024-854b2c00-9807-11e9-8a4f-5ca3994377ff.png)
Out Of Sample :
![OutOfSample](https://user-images.githubusercontent.com/49508993/60206025-867c5900-9807-11e9-8f06-c20d8073eb95.png)

**This is how the data looks like for Training on past 1 month data.**

Usual Daily Usage :
![Day](https://user-images.githubusercontent.com/49508993/60206054-94ca7500-9807-11e9-8248-044d5fc1b210.png)
Forecast :
![Forecast](https://user-images.githubusercontent.com/49508993/60206068-9f850a00-9807-11e9-9bcd-c24db87242c8.png)
Components :
![Components](https://user-images.githubusercontent.com/49508993/60206087-a6138180-9807-11e9-9ac7-509cc77f532a.png)
In Sample :
![InSample](https://user-images.githubusercontent.com/49508993/60206090-a7dd4500-9807-11e9-8c56-863f2f2446d4.png)
Out of Sample :
![OutOfSample](https://user-images.githubusercontent.com/49508993/60206096-aa3f9f00-9807-11e9-9dfe-096b29f72190.png)

As you can see, the forecast is not able to effectively capture the peak while training on past 5 months data when compared to past 1 month data.

Any help on how to remedy this.

**Comment by bletham** [comment]
My personal experience with data generated by hardware systems, like CPU metrics, is that Prophet tends to not do a great job because they often do not have the same type of structure as data generated by humans doing things, like consistent seasonal effects.

The reason the model is fitting poorly with the 5 months of data is because of how the extra regressor effect is modeled. The model is basically
```
y(t) = trend(t) + seasonality(t) + beta * regressor(t)
```
where `regressor(t)` is the binary vector that you specified, and `beta` is the effect that will be fit to the data.

As you can see, Prophet assumes that the regressor has a constant effect that is added to the trend. With the 1 month of data, this is pretty much the case - the trend is fairly flat, and the peak is flat on top of that. For the 5 months of data, it is not the case. The peak level stays fairly flat, but the trend goes up and down quite a bit. In early months there is little difference between the trend level and the peak level, but then in later months there is a large difference. So the model isn't able to fit a constant regressor effect that does a good job of capturing the data.

I think in this particular case, the best thing that I could recommend would be to separate the peak time out from the rest of the data and forecast the two separately. If you remove the peak times from your data, then the forecast should be able to do a better job at non-peak times. And then you could just insert into the forecast the peak value at all of the peak times (assuming it stays constant all the time, which it appears to. Or you could forecast it by itself too).

**Comment by JainaProudmoore123** [comment]
Thanks for you reply Ben Letham, could you suggest other models I could use for analyzing CPU and Memory metrics? Should I use something like RNNs?

**Comment by bletham** [comment]
RNNs have been used for some pretty interesting time series but I personally don't have enough experience with them to guess how well they'd do here.
