### ISSUE TITLE
Big difference in prediction result in v0.4.post2 and v0.5.0

### ISSUE THREAD

**Issue by annaymj** [facebook/prophet#1049]
Dear developer,

        I had experienced big forecast differences by using the 0.4 version and 0.5 version using exactly same data and code.  Can you share what algorithm have been updated in the 0.5 version?Anyone experienced similar issue?

Thanks!

**Comment by daikonradish** [comment]
can u try this tho: #1019 and see if it helpz

**Comment by bletham** [comment]
+1 for @daikonradish's suggestion. Does your dataset have less than 100 points? If so then it is probably because it is using the Newton optimizer instead of L-BFGS, as described in #1019. You could verify this by using 
```
m.fit(df, algorithm='Newton')
```
in v0.4 and see if it matches the v0.5 results more closely. If that's not the case then we can look into it further.
