### ISSUE TITLE
How to improve end of month point forecasts

### ISSUE THREAD

**Issue by ryankarlos** [facebook/prophet#1051]
Hello, 
I am currently using `fbprophet version 0.3 post2`. I was wondering if it is possible to specifically tune the fbprophet model for just a specific day of every month (say the last day of every month). At the moment - the MAPE is worse than the MAPE for other days in the month. I specifically interested in improving this end of month forecast (i don't mind sacrificing RMSE, MAPE on the rest of the month).
The data has monthly seasonality (not multiplicative) with increasing trend.
I have tried adding in couple of holiday features for end of month (say 29th, 30th) with overlapping limits to increase the effect of these end of month days - I get some improvement (0.2%) but not much.
Im wondering if adjusting the holiday prior scale specifically for these end of month days relative to other holidays (currently default is 0.05, but thinking of increasing it to 10) would have much effect ?
Would be very grateful for any other suggestions ?  
Thanks
Ryan

**Comment by djrscally** [comment]
I did find that separate prior scales for holidays were valuable; in my data easter and new years needed to be tuned separately. The rest were pretty much fine with the defaults though.

**Comment by bletham** [comment]
This is sort of related to #282. There isn't really any direct way to specify that some datapoints are more important than others. I suppose you could try the old trick of just replicating those points in your dataset (so have a few duplicate rows in the history dataframe for each of the end-of-month points). Conceptually that should give those points extra weight but I haven't actually tried this and so I'm not sure if it will do much for you.

I'd be interested in trying to figure out why the points at the end of the month are being fit poorly and if there is anything to be done about that. Making holiday features would have been my first suggestion, but it sounds like those didn't work. I'm wondering if there may be something where the end-of-the-month effect is different from month to month. Maybe because of 30 vs. 31 days? If the monthly seasonality period is set to 30.5, then the last day of the month will have a different seasonal effect if it is 30 or 31 days in the month. Similarly, there would be a difference to having a holiday that was "30th" vs. "last_day_of_month". Another possibility would be that the end-of-month effect is different depending on if the last day of the month is a weekday or weekend. To try and figure out if there are consistent differences in the end-of-month effect that are causing the model to do poorly, I'd suggest looking at the residuals (y_hat - y) for the end-of-month days, and seeing if there are certain situations in which they are consistently negative or consistently positive. That would give some indication of what the model is missing, and what needs to be added in to make it perform better.

**Comment by ryankarlos** [comment]
@bletham Thanks for the suggestions. Yes, I have been using a monthly seasonality component with `period 30.5` and `fourier 5`.
The other thing i forgot to mention is that the data does not have weekends and instead of having these as nulls - I have forward filled the values from the last available day (Friday), so if the 30th/31st is on a weekend - it will be using the values from the 28th, 29th  etc. In some cases the model may fit 28th-31st well but not fit another day in the last week of the month (24th for example) very well
I have looked at (yhat -y) for the end of month days and there does not seem to be any consistent trend with being negative or positive (seems to be a mix) but in certain situations when it is negative it is even worse.  Here is a snapshot of what it looks like (this is a dummy version of the original data and dates but should hopefully get my point across) - the orange lines are the custom required thresholds below which I expect the differences to lie within. 

![Screenshot 2019-07-07 at 01 00 04](https://user-images.githubusercontent.com/16509490/60762198-9b03f100-a052-11e9-9e40-a6ecb2f54b89.png)

The peaks above the threshold points are not always on the last days of the month but sometimes on other days in the last week. 
I have added in holiday component to try and help the model fit these end of month points slightly better - i get some improvement (maybe a 0.5% improvement in MAPE compared to if i don't). 
Ive also tried different variation of holidays (again none of them make much different to those spikes):

**A) Just using all end of month (30/31st 0r 28th for Feb) and beginning month calendar days (1st) of every month**

I have used a lower limit window to account for the variation in these spikes at days other than last day of the month - i was hoping that having an overlapping lower window for the last day and first day of the month would have an additive effect on the last week on the month 
 
```
end_of_month = pd.DataFrame({
  'holiday': 'last_day',
  'ds': pd.to_datetime(['2016-04-30', '2016-05-31', '2016-06-30'..........'2018-05-31']),
  'lower_window': -6,
  'upper_window': 0,
})
first_day_month = pd.DataFrame({
  'holiday': 'first_day',
  'ds': pd.to_datetime(['2016-05-01', '2016-06-01', '2016-07-01'...........'2018-06-01']),
  'lower_window': -7,
  'upper_window': 3,
})
```

**B) Only using the points which are above the threshold for (yhat- y) as holidays and using  a smaller window**

```
special_events_end_beg_month = pd.DataFrame({
  'holiday': 'special_days',
  'ds': pd.to_datetime(['2016-05-31', '2016-06-01', '2016-06-25', '2016-07-02', '2016-07-29', '2016-08-01', '2016-08-23', '2016-08-26', '2016-08-29', '2016-08-31', '2016-09-15', '2016-09-22', '2016-10-01']),
  'lower_window': -2,
  'upper_window': 2,
})
```

**C) *Similar to A but creating two same dataframes for holidays***

```
end_of_month1 = pd.DataFrame({
  'holiday': 'last_day1',
  'ds': pd.to_datetime(['2016-04-30', '2016-05-31', '2016-06-30'..........'2018-05-31']),
  'lower_window': -6,
  'upper_window': 0,
})
end_of_month2 = pd.DataFrame({
  'holiday': 'last_day2',
  'ds': pd.to_datetime(['2016-04-30', '2016-05-31', '2016-06-30'..........'2018-05-31']),
  'lower_window': -6,
  'upper_window': 0,
})
```

**Comment by bletham** [comment]
Hm, it sounds like there isn't a very clear reason for why it over- or under-estimates on some weekend dates, which will make it hard for the model to do better than predict-the-mean (which seems to be close to what it's doing). If there's something special about those dates with the large downward spikes that you'd expect to happen in the future then that could be added as a feature (holiday), but otherwise it sounds like you've tried everything I could think of.

Is there a particular reason for imputing the weekend results? There should be no problem with just leaving them out, other than you won't be able to fit weekly seasonality for the weekend and so should limit future predictions to weekdays.

As for weights like in #282, like I mentioned above this could be effectively achieved just by duplicating the end-of-month data.

**Comment by ryankarlos** [comment]
Hello @bletham , yes the reason why i imputed the weekend results is because i need them in the future predictions. Thanks for the info, I shall close the issue now.
