### ISSUE TITLE
Cross validation of monthly (sampling frequency) series: aggregate "almost monthly" horizons

### ISSUE THREAD

**Issue by argku** [facebook/prophet#1073]
I have monthly data, fit the model and wanted to look at its cross validation performance. Here's a statement I tried to run:
df_cv = cross_validation(m, initial='5 Y', period = '1 M', horizon = '1 Y')

This produces a lot of horizons are about a month long but are reported separately, e.g.:
2 60 days 11:38:24  0.000066  0.008099  0.007855  0.130567      0.75
3 60 days 17:27:36  0.000055  0.007397  0.006247  0.107022      0.75
4 60 days 23:16:48  0.000077  0.008749  0.007522  0.122310      0.50

I understand that the library is not really built for monthly series analysis, that's the reason you report horizons in days. However, for monthly data analysis it doesn't make a sense to have three rows for almost 2 months horizon, when it's mean that these are two months steps

**Comment by bletham** [comment]
There shouldn't be any reason for the cross validation to not work with monthly data. First, can you check that you are using version 0.5? There were some improvements to the cross validation tool that make it work better for regularly spaced (daily/weekly/monthly) data.
```
import fbprophet
print(fbprophet.__version__)
```
But it looks like the issue here is the hours that are part of the horizon. Points that all have the same horizon will be grouped, but here these don't have exactly the same horizon - `60 days 11:38:24` vs. `60 days 17:27:36`. This suggests that the original data had various timestamps along with each date. For monthly data you should be able to drop the timestamp and then it would aggregate things as desired.
