### ISSUE TITLE
Lack of reproducibility of fit/predict result across different environment

### ISSUE THREAD

**Issue by wsuchy** [facebook/prophet#1077]
I've noticed that there is no unit test that checks end to end (fit to predict) workflow of the library.  The `TestProphet.test_fit_predict` just calls the `predict` but no result is being checked, therefore I've decided to create one: https://github.com/facebook/prophet/pull/1076
Unfortunately it looks like there must have been a reason for the missing test. After fixing seeds for numpy and stan the prediction seems to be deterministic only within one environment but not across them. 
For example, in my PR I used result obtained on my machine (osx) and they differ from that obtained on travis.
I am comparing an error metric (rmse) with some accuracy instead of comparing the raw predictions as I agree there might be some minor differences, yet the discrepancy seems too high (especially for mcmc sampling).
I've got a few ideas what might be going on here:
- Numerical accuracy problem (related to different OS)
- As above, but caused by different version of some python library
- Stan version issues - maybe there are additional calls to random and fixing the seed just won't help
-  A bug 

As an alternative, do you think it would make sense to check wider range of the result (e.g +- 10%)?

**Comment by bletham** [comment]
With MCMC, I think it would be very hard to get really low variance results. `yhat` will be computed using the posterior mean and it will require a lot of MCMC samples for that to be totally stable (especially given the number of parameters over which MCMC is being done).

Without MCMC, things are in principle deterministic but there still are cross-platform differences. There is some discussion of this in #253, and it basically comes down to the underlying optimization libraries used by Stan having slightly different behavior on different platforms. Perhaps due to different machine tolerances / different versions of the system libraries. Fitting by default uses L-BFGS and we have found that there can be small differences in the fitted parameters across different machines, and these small differences translate into small but noticeable differences in forecast outputs. The problem is more likely to be noticed in very short datasets (like those used in the unit tests) because the likelihood surface will be very flat, and so the optimizer will have more variance in where it terminates.

As discussed in #253, we have found that the Newton optimizer tends to be a bit more consistent in its termination across platforms, but even there there is some variance.

That would be a nice test (for MAP fit, not MCMC) if Newton had enough cross-platform reproducibility, we just need to be sure it won't be flaky.
