### ISSUE TITLE
Prophet().fit  no such as callback method

### ISSUE THREAD

**Issue by lilihongjava** [facebook/prophet#1079]
such as keras(https://keras.io/callbacks/) , provide callbacks parameters  as model.fit(callbacks=[history])
A callback is a set of functions to be applied at given stages of the training procedure.
Can you provide this parameter in the future?
Thanks!

**Comment by bletham** [comment]
The training procedure is very different for Prophet vs. typical keras models. What is the intended use of the callback?

**Comment by lilihongjava** [comment]
Hello @bletham 
I need to integrate Prophet into the AI training platform.Platform requires heartbeat data and training progress bar data.
So I need to do this through callbacks.
Thanks!

**Comment by bletham** [comment]
I don't see a very natural way to do this, in particular it isn't clear where in `fit` this callback would be called. The actual fitting is done in Stan, with `optimizing` (https://mc-stan.org/rstan/reference/stanmodel-method-optimizing.html), which has no callback. Since pretty much all of the fitting time happens there, there is not really a realistic way to return progress bar data; it would just go from 0% when `optimizing` is called to 100% when `optimizing` finishes.

**Comment by lilihongjava** [comment]
@bletham  
Thank you very much for taking the time to look at this problem for me. At present, I can only give up the function of progress bar.

**Comment by LeeDongGeon1996** [comment]
I got a same problem with this. I'm also implementing progress bar for Prophet. Is still there no way to make it?
