### ISSUE TITLE
model.predict_trend(df)

### ISSUE THREAD

**Issue by arnav31** [facebook/prophet#1089]
Hey,
Love the ease in prophet, just having a few issues.
 I've been using prophet and having an issue in calling the predict_trend() function. It throws an error "KeyError: 't'". I have also tried the predict_seasonal_components(df) method which returns the required result. 
I have made sure that the dataframe I'm giving the predict_trend method has the correct columns(ds ,y) and the correcet datatype(datetime, float). Even so, the code works for predict_seasonal_components and not for predict_trend. Is there any reason for this? 

And on the other hand, is there any way to extract the time series components (yearly/weekly/daily/trend) from the model once we have trained it? This is helpful for me because i have a training dataset with a lot of records(40000+) and once ive trained it, i want the seasonality components for the train set too, but i don't want to run the model.predict(train) as it would take a lot of time for prophet to predict. I assume since the model has already "seen" the training data, it would be able to give the seasonality components with with model not needing to predict on it. 

If there is something I'm missing, please forgive me as i am new to the coding scene. 
python - 3.6.7
fbprophet version - 0.5
running on windows 10.

**Comment by bletham** [comment]
The method `predict_trend` isn't meant to be called directly. We haven't documented in the Python code which methods are meant to be "external" vs. "internal", but if you look at the R reference manual (https://cran.r-project.org/web/packages/prophet/prophet.pdf), basically the functions there are all of the ones that are meant to be accessed directly.

For `predict_trend` in particular, internally the model does some data transformations prior to fitting/predicting, and it is during those data transformations that the `t` column is added.

There isn't going to be any way to get model components without doing `model.predict(train)`. All that is stored after `fit` is the coefficients of the linear regression used to estimate seasonality; the feature matrix X has to be re-constructed in order to compute the actual component, which is what is done when `predict` is called.

A big portion of the time in `predict` is spent estimating uncertainty intervals. If you just want the component prediction and don't need uncertainty you can speed things up a lot by reducing `uncertainty_samples` from the default of 1000 down to 1. (In the future with #1082 you will be able to disable it altogether which will even further speed things up).
