### ISSUE TITLE
should be print(df.head()) and not df.head() only

### ISSUE THREAD

**Issue by nganani** [facebook/prophet#1100]
should be `print(df.head())` to print the output and not as said in the doc `df.head()`

**Comment by bletham** [comment]
The documentation is generated from ipython notebooks (https://github.com/facebook/prophet/tree/master/notebooks), which always prints the output of the last item in the cell. Hence it is printed without needing to call print. Since that would be the behavior in both a notebook or the terminal, I'd imagine there probably isn't too much confusion on what is needed to print it and so I think it's probably fine left as-is.

**Comment by nganani** [comment]
I used code as simple Python in vs code and it did not work without it and I wanted to make it more clear for others who might do the same. Your call, of course :)
