### ISSUE TITLE
Increasing forecast horizon giving better results

### ISSUE THREAD

**Issue by ryankarlos** [facebook/prophet#1105]
@bletham Thanks for this great forecasting library which Ive enjoyed using and from a user perspective is a lot easier than traditional arima packages.

I have a query and hoping you could give some insight. 
I have 5 and a bit years worth of training data (with data available for each day of the month). What Im interested in checking the performance of the model for the last weeks of every month in the year. So I've carried out my own backtesting experiments (initially with a fixed forecasting horizon of around 15 days) for June, July, August months in 2018, 2017 with a view to understand the trend for these months going forward in 2019.  Note that Im not using the fbprophet cv function but my own similar implementation for my purpose.

I assumed that increasing the forecast period from 15 to 30 to 60 days  for example - should make the predictions worse. However, Im finding something opposite for some months where for example if I start forecasting from beginning of May instead of beginning of July and comparing the performance of the model for end of week July (compared to actual results), it actually improves. This is only the case for a few months but not sure if it is something related to the data (i.e. something happening in June) that is degrading performance for the model when including in training data (if using a shorter horizon to month end July) or if it is something technical related with the underlying model - im still using prophet 0.3.post2  ?

Im seeing the similar trend  for the given month in all the previous years when running previous backtests. 

Also, the confidence intervals (using 0.95 interval width) `yhat_upper- yhat`  and `yhat_lower- yhat` seem to be consistent when increasing horizon from the 1 to 3 to 6 months  - if comparing for the last days of the last month in the respective horizon setting. Shouldn't they be increasing ? 

Is there any tool/methods for generating explainability in fbprophet for why this is happening with the ? I guess I could run mcmc for yearly seasonality to see which months have the highest uncertainty (but not sure if this is related ?)  

Any insight would be greatly appreciated.

**Comment by bletham** [comment]
There aren't any technical aspects of the model that I'd expect to cause this, it seems to me that there must be something happening in the time series in June/July that is making the forecast worse.

I think there are two likely culprits: The most likely would be that there is some trend change happening in June that makes it so the trend in May is pretty good for forecasting end of July, but the end of June trend is not. I think you could diagnose that out by just plotting the two forecasts and seeing what the trend looks like in each of them. The other option would be that maybe including June/July is messing up the seasonality estimate. I'm assuming you have more than a year of history before May so that you have a decent yearly seasonality estimate. But maybe June has really different seasonality and that is making things different. Again I think the best way to diagnose would be to fit each model and compare the seasonalities in the component plot (`m.plot_components`).


As for the confidence intervals not widening: they will get wider as you move forward into the future, but the rate at which they get wider will depend on how much trend change there has been in the past (see https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend ). If the trend has been really stable in the history, then you may not see much widening across a few months. You can see for sure though by generating the components plot. All of the future widening comes from the trend, so just look at the confidence interval for the trend and you can see how quickly it is widening (like in the figure at the bottom of https://facebook.github.io/prophet/docs/quick_start.html#python-api).
