### ISSUE TITLE
How can I make multiple predictions simultaneously?

### ISSUE THREAD

**Issue by martisaju** [facebook/prophet#1121]
Hi, 

I want to build a retail predictor considering the historical purchases made by some different users. My purpose is taking into account all the products that a single user has bought in a period of time and predict which products this user will buy in the future (and when).

For this, I was thinking of creating as different **[ds || y]** tables as different products the studied user has bought and apply the Prophet model but, in order to make the predictive process cleaner and faster, I was wondering if Prophet supports any way to process multiple columns designing different variables simultaneously (i.e. **[ds || y1 | y2 | ... | yN]**, where **yn** designs each product the user has bought and its purchased amount in a datestamp).

Do you have any idea if it can be done and how?

Thank you very much :)

**Comment by Ace139** [comment]
Hi @martisaju,

What you need is to serve the fbprophet model as an API end-point so that you can asynchronously call the model with different datasets and get the desired output. It can be easily done with Flask. If you need it to scale in production scenario (100s of forecast request per second) then you can always containerize it and deploy it at scale using any Cloud Compute Platform like Azure, AWS, GCP, DigitalOcean etc. 

Hope this helps.

**Comment by martisaju** [comment]
Hi @Ace139 thanks for your answer. I will study in a deeper way your suggestion. :)
