### ISSUE TITLE
Adjusting model to respond quicker to higher and lower values 

### ISSUE THREAD

**Issue by vefae** [facebook/prophet#1125]
Hi guys, I am having difficulty to finetune the model to have a better fitting curve. Below is my forecast plot:
![image](https://user-images.githubusercontent.com/34002907/63940442-c232d980-ca69-11e9-8dab-3ea076b2a22a.png)

I would like my model to fit better to the spikes and drops. I can define these periods as holidays but I don't want to do that because these are just normal times, not specific time periods.

Is there a way to do that?

Thanks!

**Comment by sammourad** [comment]
Hi @vefae, here are a few things that should help:
- Use multiplicative mode.
- Set seasonality prior scale to 10.
- The time-series you have seem to have a 3-years seasonal cycle. Try a custom seasonality of 1095 periods.
See if any of this helps.

**Comment by bletham** [comment]
It is the yearly seasonality that would be capturing these spikes, and I think the reason it isn't being captured is because the size of the seasonal effect does not seem to be consistent across years. For instance there is a large spike around May 2015 (the first spike seen in the figure). There is a similar spike in May 2018, but it seems to be totally absent in 2016/17/ and 19. When fitting the model, the seasonality will essentially the average of the seasonal effect seen across years, so in this case with large spikes in 2 years but no spike in 3 years, it fits a smallish spike. Do you know why the size of the effect is different in 2015/18 vs. the other years? If so then you can add an extra regressor that explains the difference. Otherwise, the model will have no way in the future to predict if 2020 will be a large spike year or a no spike year (and so it will just predict smallish spike).

Like @sammourad suggests this could be because it is a 3-year cycle and not a 1-year cycle, so that's something you could check if it looks like that is the case. With only 5 years of data you won't be able to see 2 full cycles, but you can at least get an idea of if the first 2 years of the 3-year cycle match up well from the first 3 years to the next.
