### ISSUE TITLE
Different forecasts from different prophet versions (0.3.0.1 vs 0.5)

### ISSUE THREAD

**Issue by ruksarsultana** [facebook/prophet#1127]
Few users in my team had version 0.3.0.1 & others had the latest version 0.5. While comparing the forecasts from both the versions (for the same product, variables), we see minor differences in numbers. Could you please help understand the change/ update in the package from 0.3.0.1 to 0.5 which is affecting the numbers. Waiting to hear from you at the earliest

**Comment by bletham** [comment]
There was a change from 0.4 to 0.5 where for time series with less than 100 points, it uses a different optimizer by default (Newton instead of L-BFGS). Are the time series where you are seeing a difference less than 100 points? If so that is likely the source (see #1019 where this was the case). You could check by specifying the Newton optimizer and seeing if it makes the results consistent across the versions.
Py:
```
m.fit(df, algorithm='Newton')
```
R:
```
m <- prophet(df, algorithm = 'Newton')
```

If that's not it, then let me know and we can try a few other things to get to the bottom of this.
