### ISSUE TITLE
Wide range between yhat_lower and yhat_upper even on 1st predicted value

### ISSUE THREAD

**Issue by tomekziel** [facebook/prophet#1129]
I'm predicting time series with hourly resolution, for large data set (~18 months). Why the `yhat_lower` and `yhat_upper` values do not start from last known `y` value (last one in learning set) and grow over time from there, but instead starts with "full" width? 

Following graph covers last 24 hours of known values (left half) and first 24 hours of prediction (right half) with yhat lower/upper range as ribbon. Why don't the beginning of prediction look more like red dots? Is there a way to tighten the beginning?

![obraz](https://user-images.githubusercontent.com/1764747/64105858-4beaeb80-cd77-11e9-9cb5-55d823117c2d.png)

**Comment by bletham** [comment]
The model is essentially
```
y(t) = trend(t) + seasonality(t) + regressors(t) + noise
```
where `noise` is a Gaussian noise term that captures any variance not captured by the other components. Just like in a linear regression. The noise term is 0 mean, and has a variance that is fit to the data. If trend, seasonality, and regressors capture all of the movement of the time series, then the variance for the noise term will be very low. If there is a lot of movement in the time series that is not being well captured with trend/seasonality/regressors, then the variance will be high.

If you do the default fitting (not MCMC), then there are two sources of uncertainty: trend uncertainty, and the noise term. The trend uncertainty has the behavior that you describe: it starts off at 0 and then expands as you move forward into the future. The uncertainty from the noise term is constant. So that is what your'e seeing here: high uncertainty from the noise term.

You can see something like this in the example in the documentation: https://facebook.github.io/prophet/docs/quick_start.html#python-api . If you look at the uncertainty in the history, you can see from the shaded region that there's fairly wide shaded bands even in the history just to be able to fit the data. And so those wide shaded bands continue into the future.

 The only way to reduce this would be to get the model to fit the history better, so that the noise term is used to explain less of the variance. Are there seasonal effects that aren't being captured well that could be added into the model? Or other regressors that might be able to explain some of the variance around the trend? That's the sort of thing that would improve the short-term uncertainty.

**Comment by tomekziel** [comment]
Thanks for explanation!
