### ISSUE TITLE
Sunday Sales is low : It is not being captured by Prophet

### ISSUE THREAD

**Issue by rphaneendra** [facebook/prophet#1130]
1. We have high sales Monday - Friday. Decent sales on Saturday and  very low sales on Sunday.
2. We have increasing WoW sales in a month. i,e. Week 1 < Week 2 < Week 3 < Week 4

Both of these are not captured by Prophet. It gets the sunday sales completely wrong
For example: If sales on sunday is usually 5 units , the forecast for sunday is around 700

<img width="666" alt="Screen Shot 2019-09-02 at 6 19 26 AM" src="https://user-images.githubusercontent.com/33362243/64108026-c8ff6c00-cd49-11e9-913d-1d4add99b404.png">

Any suggestions?

**Comment by vhpietil** [comment]
Try increasing fourier order of the weekly seasonality. Increasing prior might also help

**Comment by rphaneendra** [comment]
m = Prophet(weekly_seasonality=False)
m.add_seasonality(name='Weekday', period=5, fourier_order=3, condition_name='Weekday')
m.add_seasonality(name='saturday', period=1, fourier_order=6, condition_name='saturday', prior_scale=1)
m.add_seasonality(name='sunday', period=1, fourier_order=6, condition_name='sunday', prior_scale=100)
I created separate columns for weekdays, saturday and sunday. Also, tried changing priors. However I'm still not anywhere close. The usual sunday sales are less than 10 , whereas prophet forecasts 500 -1000. Any way I can manually set the sunday values to less that 10?

**Comment by Shikhar2205** [comment]
Try making weekly seasonality multiplicative. Also could you share the trend chart to have a better understanding.

**Comment by bletham** [comment]
@rphaneendra if you could share the plot both of the forecast (`m.plot`) and the full components plot that'd be really helpful.

1. From the components plot it looks like the weekly seasonality is capturing much lower sales on Sunday relative to other days of the week. Basically the weekly seasonality is the additional sales due to being that day of the week, and in the weekly components plot there is +100-200 additional sales on M-F, and -700 additional sales on Sunday.

 2. For the increasing WoW sales, it sounds like you have multiplicative seasonality and would get better results with that (https://facebook.github.io/prophet/docs/multiplicative_seasonality.html)
