### ISSUE TITLE
R: custom seasonality with space in name is missing in prophet_plot_components graph

### ISSUE THREAD

**Issue by tomekziel** [facebook/prophet#1131]
When custom seasonality added with `add_seasonality` has space character in `name`, that custom seasonality section is missing from `prophet_plot_components` graph. Please check repro code and graphics below:

```R
m <- prophet(daily.seasonality = FALSE, yearly.seasonality = T)
# note the 'weekend' below
m <- add_seasonality(m, name='weekend', period=1, fourier.order=7, condition.name='weekend')
m <- fit.prophet(m, networkUsage)
future <- make_future_dataframe(m, freq=3600, include_history = F, periods = 24*10)
future$weekend <- as.POSIXlt(future$ds)$wday == 0 | as.POSIXlt(future$ds)$wday == 6
forecast <- predict(m, future)
prophet_plot_components(m, forecast)

m2 <- prophet(daily.seasonality = FALSE, yearly.seasonality = T)
# note the 'weekend day' below
m2 <- add_seasonality(m2, name='weekend day', period=1, fourier.order=7, condition.name='weekend')
m2 <- fit.prophet(m2, networkUsage)
future2 <- make_future_dataframe(m2, freq=3600, include_history = F, periods = 24*10)
future2$weekend <- as.POSIXlt(future2$ds)$wday == 0 | as.POSIXlt(future2$ds)$wday == 6
forecast2 <- predict(m2, future2)
prophet_plot_components(m2, forecast2)
```

![obraz](https://user-images.githubusercontent.com/1764747/64110128-82c5ff00-cd81-11e9-9081-3f88153aad20.png)

**Comment by bletham** [comment]
@tomekziel thanks for raising the issue. This is actually a bug that custom seasonalities whose names cannot be column names in R are actually dropped from the model entirely. So it's not just that it didn't show up in the plot, it was actually not used in the model at all.

The bug was identified and fixed shortly after the last version release (#996), but the fix hasn't been pushed to CRAN yet.

You can get the fix by installing from github:
```
devtools::install_github('facebookincubator/prophet', subdir='R')
```
Or of course you can also just make sure the name is a valid R column name.

**Comment by tomekziel** [comment]
Duplicate #996 #1033
