### ISSUE TITLE
prediction gone miserably wrong

### ISSUE THREAD

**Issue by kshitij002** [facebook/prophet#1139]
@bletham @seanjtaylor   I have been struggling with the prophet predictions lately, I have been assigned a task to find the error of the 2 given intervals. Prophet performed well on the first interval but on the second one it failed miserably. It'd be a great help if you could help me with this mess.
![download](https://user-images.githubusercontent.com/55188228/64693578-2ebfc680-d4b5-11e9-8da4-a3d6ff039107.png)
![download (2)](https://user-images.githubusercontent.com/55188228/64693579-2ebfc680-d4b5-11e9-8d40-d046bd396584.png)

**Comment by APramov** [comment]
@kshitij002 , could you maybe provide the data?

**Comment by vhpietil** [comment]
component_plot might also help.

It seems that your data does not have a regular weekly seasonality which leads to poor fit.

**Comment by kshitij002** [comment]
> @kshitij002 , could you maybe provide the data and details on the model that you ran?

![prophet2](https://user-images.githubusercontent.com/55188228/64720081-3a2be580-d4e7-11e9-817e-4b2227e024da.png)
@APramov  i really can't provide the whole dataset but you can have the gist of it, it's an hourly dataset from november to february.
![prophet2](https://user-images.githubusercontent.com/55188228/64720000-12d51880-d4e7-11e9-9053-2351544fff4f.png)

**Comment by APramov** [comment]
> 
> 
> @bletham @seanjtaylor I have been struggling with the prophet predictions lately, I have been assigned a task to find the error of the 2 given intervals. Prophet performed well on the first interval but on the second one it failed miserably. It'd be a great help if you could help me with this mess.
> ![download](https://user-images.githubusercontent.com/55188228/64693578-2ebfc680-d4b5-11e9-8da4-a3d6ff039107.png)
> ![download (2)](https://user-images.githubusercontent.com/55188228/64693579-2ebfc680-d4b5-11e9-8d40-d046bd396584.png)

OK, and what do you mean by saying that prophet performed well on the first interval but not on the second? Are these time intervals? how do you define them?

**Comment by bletham** [comment]
It looks like the model is doing a pretty good job of capturing the daily seasonality. There is a lot of fluctuation in this time series on top of the daily seasonality, like the sharp trend changes around 11/12, 11/16, and 11/24. These changes in direction don't seem to be seasonal to me (that is, it doesn't seem to be periodic with a fixed period) so they're being handled by the model with trend changes.

The model is doing a good job of capturing these up until the 1/1 trend shift. Then it is staying mostly flat and missing the trend shifts at the end.

The reason for this is because by default Prophet does not fit trend changes in the last 20% of the time series (see https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet). This is to avoid overfitting to trend changes at the very end. As described in the documentation there, you can change that threshold using the parameter `changepoint_range`, which could be increased to e.g. 0.95 to allow placing changepoints in the first 95% of the time series rather than the default 80%. This will allow the time series to fit the data at the end much better.

As a side note, this time series has frequent, significant trend shifts. This is reflected in the very wide uncertainty intervals for the prediction: in the history the time series has had frequent sharp changes, and so the model uncertainty assumes that there could be sharp trend changes at any point, and future trend uncertainty is high. Increasing `changepoint_range` will give you good fit through the end of the history and will change the forecast `yhat`, but the uncertainty intervals will remain wide because they come from the trend uncertainty.

**Comment by valeman** [comment]
Prophet is generally a mess, it is a ghastly model
