### ISSUE TITLE
Making sense of Prophet predictions  

### ISSUE THREAD

**Issue by paulaceccon** [facebook/prophet#1140]
So, I'm trying to model an hourly time series with Prophet to improve the current MAPE and RMSE, which are, respectively, 72 and 13, approximately. The current prediction is just performed based on medians of the day of the week, which should give a large margin for improvement. The series looks like [this](https://drive.google.com/open?id=12rRDWLga5NEXcYpvxjLbgw0PtTpYwxTf).

I did some EDA and noticed that there's a positive correlation between the weather temperature, weekday and hour of the day with the target variable. I created dummies for days of peak (Thursday, Friday, Saturday), and created as additional regressors these variables as well as the temperature, precipitation and day of the month. 

[Patterns](https://drive.google.com/open?id=1_NGRZpgWW7W4tz14oj5SvJZB4L3qYscQ)

As a result, I got a MAPE of 59 and RMSE of 12, which is not good.

[Prediction](https://drive.google.com/open?id=1vHx574by8ux4eF2SiioZme3D0vM7rHVq)

I have tried manually adding weekly and daily seasonalities, increasing the `fourier` value, with little improvement. 

```
model = Prophet(weekly_seasonality=False, 
                daily_seasonality=False)
model.add_seasonality(
    name='daily', period=1, fourier_order=4, mode='multiplicative')
model.add_seasonality(
    name='weekly', period=7, fourier_order=5, mode='multiplicative')

model.add_regressor('avg_temp')
model.add_regressor('avg_prec_val')
model.add_regressor('dayofmonth')
for d in days_of_peak:
    print(f'Adding regressor {d}...')
    model.add_regressor(d)
model.fit(train.rename(columns={'date':'ds', 'count':'y'}));
```

What seems really odd to me is that when displaying the model components, there's a peak on [Sundays](https://drive.google.com/open?id=1r6uUKj65bfVOcEcPkKRfWWpMzJ4vSWzh), which is not observed in the data. I'm not sure about what I'm missing. Any help would be appreciated.

**Comment by vhpietil** [comment]
I think it is problematic to think that there is a peak on Sunday after you have put regressors on Thursday, Friday and Saturdays. This way you take something away from the weekly seasonal pattern and put it in the regressors of those weekday. Does this make sense? 

In addition, I would like to see distribution of you MAPE and RMSE, because I think that those large values are mainly because of one weird day at about 2019-09-09. There are observations close to zero with prediction of about 80, which will lead to huge percentage error. This might make you MAPE way larger that it would otherwise be. Problem is the data, not the prediction. You could try median absolute percentage error. 

Looking at the data and the prediction, I am not sure if there is very great room for improvement. Unfortunately at the moment I can't recommend anything

**Comment by bletham** [comment]
Yeah, looking at the prediction vs. actual plot, things look pretty OK to me too. It's doing a good job of capturing the weekly drop on Sat and Sunday. There is a big mid-day drop on the last Sunday in the plot that is missed, but that drop isn't present on the first Sunday in the plot, so it doesn't seem to be anything periodic that could be captured by the seasonality.

The one thing that I do notice is that on M-F evenings, the model systematically overestimates the minimum value. This is probably because there is a slightly different shape to the seasonality on M-F vs. Sat/Sun. This can be corrected and I would expect would reduce your model error. Basically what you'll want to do is to define separate daily seasonalities for weekdays vs. weekends. The documentation descibes how to do this here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors

Basically what you'll do is add two binary indiciators to your dataframe, "is_weekday" and "is_weekend". Then you can do 
```
model.add_seasonality(name='weekday_daily', period=1, fourier_order=4, mode='multiplicative', condition_name='is_weekday')
model.add_seasonality(name='weekend_daily', period=1, fourier_order=4, mode='multiplicative', condition_name='is_weekend')
```
You would do this in the place of daily seasonality, so make sure to leave daily_seasonality=False.

That should give better fit for those weekday evenings. You could also consider making a daily seasonality for each day of the week (same as above, but 7 binary indicators), it looks like you may have enough weeks of data for it to do a decent job of fitting separate seasonality for each day. If you did this you would want to remove the days_of_peak regressors since they would be implicitly covered by the unique per-day daily seasonality.

I think that's the only thing I see in this forecast that could be improved. There is a lot of spikiness at the top of each day that isn't being captured by the model, but it doesn't seem to be repeated (for instance, the pattern at the top of the two Fridays in the plot look total different) so it isn't something that can be captured by seasonality. Individual seasonalities for each day of week may be able to grab some of that, but only if it is repeated across weeks.

---
As a sidenote, like @vhpietil says, the weekly seasonality is fitting an effect for each day, and when you had extra regressors for some days on top of that, it creates poor identifiability for weekday seasonality. This isn't an issue for prediction, but it means that the actual seasonality numbers aren't super meaningful, which is why the component plot can show an increase on Sunday when the actual forecast clearly does not have an increase on Sunday.
