### ISSUE TITLE
Train prophet on additional regressors, without using these in forecast

### ISSUE THREAD

**Issue by madjbb** [facebook/prophet#1141]
I was wondering if Prophet allows you to train the model on additional regressors to understand their impact on the target (i.e. by analysing the beta coefficients), but then excluding these regressors when performing predictions (as they are not known in the future).

Also how would you interpret the beta coefficients correctly to analyse their impact on the target? Do you have to transform them first to account for the fact the training data is normalised prior to model fitting? Would appreciate a steer on this please. 

Ideally, I'd like to use the coefficients to make statements such as: if the coefficient of x1 is B, then a unit increase in x1 implies an average increase of B in the target y.

**Comment by madjbb** [comment]
Just another quick thought on my initial request re excluding regressors at prediction time. Could this be achieved by simply setting the regressors to zero for future dates in the future dataframe used to make the prediction?

**Comment by bletham** [comment]
This isn't really possible. Suppose you fit a model with temperature as an external regressor, and it has a significant impact on the thing you are trying to forecast. The actual fitted model will be
```
y(t) = trend(t) + seasonality(t) + beta * temp(t)
```
where beta is the parameter fit to the data, which here is different than 0 because temp is being used in the model.

Now I don't know temp(t) in the future. Suppose I just set it to be 0. That's basically forecasting y under the assumption that temp will be 0. Unless it is a really cold place, that's probably a bad assumption and the forecast will not be reasonable. So you do have to assume something about temp(t) in order to forecast y(t). Using the forecast for temp(t) is one such assumption. You could also use easier assumptions. For instance, you could ask "What would y(t) be if temp(t) stayed constant at its current value". To do this you would use the latest value of temp(t) as the future value. Anyway, there are a bunch of things that could be done to plug in values for temp(t), and it all comes down to what assumption you want to make / what question you want to answer. But plugging in 0 is unlikely to be the assumption you want.

As for interpreting the beta coefficients: Yes, there is normalization by default of both `y` and the extra regressor that does make it a bit tricky to directly interpret beta. There is discussion of this in #928. I think the best way to understand the impact of the regressor on y is to look at the regressor in the component plot, or equivalently look at the column of the regressor in the forecast dataframe. The numbers here e.g. `beta * temp(t)`, and so is directly how much of `y` is being attributed to the extra regressor.

**Comment by madjbb** [comment]
@bletham this makes sense, thanks a lot for taking the time to respond, much appreciated!
