### ISSUE TITLE
How to augment changepoints

### ISSUE THREAD

**Issue by nescobar** [facebook/prophet#1146]
Thanks for making this library available, it's very simple to use, yet powerful.

I have a couple of questions regarding the changepoint definition and usage. In the documentation it is mentioned that  
> One could, for instance, create a grid of points as is done automatically, but then **augment that grid with some specific dates that are known to be likely to have changes**

1. However, it is not clear to me _how to augment the grid_. My understanding is that if I specify the changepoints to the Prophet constructor then it will replace the auto-detected changepoints with the values passed as arguments.

2. Regarding the changepoints usage, if I know that a campaign will run on specific dates, would it be recommended to add these dates as changepoints? How will the model identify if these affect the trend upward or downward?

**Comment by bletham** [comment]
1. That is correct, and the documentation should probably be made a bit more clear on that matter. The auto-generated changepoints from Prophet is just a simple grid on the time series history (see the vertical lines on the figure in https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet ). What the documentation is suggesting is that you could create your own grid of dates across the history, with `pd.date_range` in Py or `seq.Date` in R, and then augment that list with some custom dates and submit the whole thing to the `changepoints` argument on model creation.

2. If I understand the question correctly, this campaign is in the future? And the question is how the model would know if this future campaign will increase or decrease trend? Changepoints can only be set in the history, not the future, precisely because there would be no way for the model if it would cause an increase or decrease. If you've had past campaigns, then the better thing to do would be to create an extra regressor for the campaign which the model could then learn its effect, and project it into the future if there are future dates with that extra regressor active.
