### ISSUE TITLE
Accounting for New holidays in Regressor

### ISSUE THREAD

**Issue by trevor-pope** [facebook/prophet#1147]
Hi,

I have a daily time series that has an upcoming holiday which isn't present in the historical data (at least, it would be cumbersome to pull a year of data since I am forecasting several thousand time series). I have a regressor whose future values are known, and they reflect the upcoming holiday. I want my data to be extremely overfit to the regressor on outlier days, i.e. have my predicted values mirror the effects of the holiday in the regressor. Currently I have the following, where a holiday occurs on 2019-08-27 (the regressor drops to zero). 
![Example](https://user-images.githubusercontent.com/39242775/65270777-dd818980-dae9-11e9-848c-69fc3b9e6595.png)

I get a slight reaction from my model using a high `prior_scale`, but the model doesn't drop to zero as I intend. 

As a solution, instead of having a regressor, I simply placed the regressor into the dataset as "last months" data, and fitted a monthly seasonality with a very high fourier_order. Of course, the accuracy is atrocious due to overfitting the past data instead of looking at the current trend, but it does handle the holiday situation. Not only this, but I have to pull in unnecessary data that isn't so useful to the forecast so that I can have enough for two cycles for my monthly period.

Is there a better approach, or will I just have to manually adjust the forecast for that day?
Can I add a single fake datapoint from last year that is the regressor's value on the holiday and fit the model without messing up any other seasonalities?

**Comment by eromoe** [comment]
I am in same situation , the different is I am predicting 200 thousand products . Because the trainning is too slow, I only use 90days data, which means model can't learn the yearly holiday effection .
The general way is  train a model with 2 or 3 year data at first , then pull out the reggressor parameters,  feed to 90days model .  

The parameters are in `m.params` .  I haven't looked into this because there are many other important features need focus first .

**Comment by bletham** [comment]
@trevor-pope an extra regressor (call it `z`) going to 0 will only take `yhat` down to 0 if the extra regressor is being used to explain all of `yhat`, which basically means `y = beta * z`. So this won't happen unless `y` and `z` are perfectly correlated. In this case you have some knowledge of how the value of `z` should affect `yhat`. Would it be reasonable to just have an extra wrapper on the Prophet forecast that has a rule something like `if z(t) < 10, set yhat(t) = 0`? I'm just wondering if that might be easier than trying to wrangle this into the model, if you do have knowledge of what the right effect will be.

@eromoe that's a really interesting problem - to be sure I totally understand the setting, there is a time series with a few years of data. You want to fit that time series once to learn yearly seasonality, but then after that only fit the last 90 days but apply that same yearly seasonality. Is this because you are constantly updating the time series and re-fitting the model to the latest 90 days, which is why you are willing to do the slow fit once but need it to be fast after that?

You wouldn't want to do this directly by modifying `m.params` because all of the other components would have been fit without the yearly seasonality, so adding it in could be a real mess. What I would recommend would be to store the model fit to all of the data (let's call it `m0`). Now, at some future point we want to fit a model just to the last 90 days, and then make a prediction for h days into the future. What you could do is take `m0` and make a prediction on that whole time period (last 90 days and h future days). The forecast dataframe (`forecast`) will have  column `yearly` that provides the `m0` estimate for yearly seasonality for the whole time period. Construct a new dataframe for the last 90 days that has `y` with the yearly seasonality from `forecast` subtracted out. Fit a Prophet model to that without yearly seasonality, and predict out h days. Add the yearly seasonality from `forecast` into the prediction of `yhat` for those h days. Now yearly seasonality will be incorporated into the forecast.

**Comment by eromoe** [comment]
@bletham It is a little different . Because my holidays only happened yearly ,under this situation, holidays can count as yearly seasonality. But I don't tend to learn yearly seasonality,   just add holiday effection. Do you mean holiday effection is contained in `yearly seasonality` , so only need add `yearly seasonality` to last 90 days model's `yhat` ?  
I was affraid yearly seasonality would add bad affaction to yhat, because the two years data may have some continuous zero in different time range.  Only consider holidays would be more proper for me.

@trevor-pope said he had historical data 
> an upcoming holiday which isn't present in the historical data ... it would be cumbersome to pull a year of data since I am forecasting several thousand time series

So I think he also can use this way to get a better model.

---

I come up another question:  Each learned regressor parameter looks like a constant which is independent and doesn't change by seasonality as I saw. 
Didn't learn the seasonality of each regressor is because cost too much ?

**Comment by trevor-pope** [comment]
@bletham Yes, a feature like that could work. Where's the best place to implement that at? 

And @eromoe is correct as well, I have plenty of data available, but fitting years of data would be too slow. I plan on refitting every day, hopefully in under an hour.

@eromoe is also right in thinking that all I need is holidays. For a large majority of time series I am predicting, last year's values are rather poorly correlated, so having a yearly seasonality isn't a good idea, but I do know that holidays are consistent across years.

**Comment by bletham** [comment]
I see, for just holiday effects I think things can be done a bit easier. You could fit the model once to all of the data and call `predict` on the history to get a forecast dataframe. Each holiday will be a column in the forecast dataframe, and the non-zero entries in that column are the fitted holiday effect. Call it `h`. Then in the future when the model is fit to the shorter dataframe, when a holiday comes up you can just add in the fitted holiday effect, so the actual forecast on holiday date `t` becomes `yhat(t) + h`.

That's assuming additive holiday effect, if it is multiplicative then it would be `yhat(t) + trend(t) * (1 + h)`.

**Comment by SandeepaDevin** [comment]
I have a similar model where my holiday(matchday) data has a much higher value than an average day. prophet consider this as an anomaly and does not fit the model really well.

**Comment by caphychan** [comment]
@bletham HI. I am recently taking up Prophet and trying to figure out the explanation of additive effect and multiplicative effect. It's confusing here the multiplicative effect is calculated as $yhat(t) + trend(t) * (1+h)$ rather than $yhat(t) + trend(t) * h$. I thought yhat(t) has alreday included the effect of trend here.
