### ISSUE TITLE
values of regressor changes after passing it to forecast.

### ISSUE THREAD

**Issue by p9anand** [facebook/prophet#1188]
@bletham 

Hi,

i added a regressor to the model in the future dataframe (it's present in training dataframe as well).  But when i forecasted using fitted instance. The values of regressor of the future dataframe changes in the forecasted value of the future dataframe. I have attached the screen shot for the same.
<img width="785" alt="Screenshot 2019-10-21 at 6 50 31 PM" src="https://user-images.githubusercontent.com/7848315/67208746-b1805d80-f433-11e9-8130-e6956ee546ff.png">

I just want to know why values in this column forecast2['reg_1'] have changed?

Thanks.

**Comment by Igevorse** [comment]
Hi @p9anand,
extra regressors are [standardized by default](https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L330), that's why the data is different. This is briefly mentioned in [the docs](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html).

You may forbid standardization explicitly for each extra regressor:
```
m2.add_regressor('reg_1', standardize=False)
```

**Comment by janethompson** [comment]
Hi there, I am running a prophet model with some additional regressors. I am scaling the data prior to fitting the model, so for this reason I am setting standardize = False as such:
`model.add_regressor('DEMAND_60', prior_scale=0.5, mode='additive', standardize = False)`
But I noticed in the model output that I seem to be getting two different values for my regressor (demand in the prior 60 days). In this screenshot you can see there is DEMAND_60_x and Demand_60_y. Are you familiar at all with why this might be happening?
![image](https://user-images.githubusercontent.com/54864102/67419688-2a4df980-f59b-11e9-936f-208e1fac1a44.png)

**Comment by bletham** [comment]
@p9anand What you put in to predict in the `future` dataframe is the value of reg_1.
What comes out of predict, in the `forecast2` dataframe, is not the value of reg_1, rather it is the magnitude of the reg_1 component of the model. You'll notice in `forecast2` that there is a column for every component of the model, like weekly seasonality, yearly seasonality, etc. Each of these is in essence the amount of `y` that is being modeled by that component. The model is basically
```
y(t) = trend(t) + seasonality(t) + beta * reg_1(t)
```
The column in `forecast2` will be essentially the `beta * reg_1(t)` part of the model; so it is the model output, not the input.
(It is not exactly that because of standardization that is happening both in `y` and in `reg_1`, but that's the essence of it).

Does that clarify things?

**Comment by bletham** [comment]
@janethompson this looks like it could be a bug, could you post the code you used to get this result? Perhaps in a new issue?

**Comment by p9anand** [comment]
@bletham : Yeah got it. Really appreciate your clarification. Thanks.

**Comment by janethompson** [comment]
@bletham I posted the new issue here: https://github.com/facebook/prophet/issues/1190
Let me know if there's any additional info I can provide

**Comment by bletham** [comment]
@p9anand Yeah that makes sense to me, basically the country forecast would be an extra regressor for each of the state forecasts. If you do try this, I'd be very interested to hear if it improves your forecasts relative to doing each state independently. I don't personally have an example to share, I just heard from a friend who uses Prophet at a small company that he had a lot of success with this strategy, and it seems to me conceptually that it could work in some situations. I'd love to hear more people's experiences with this approach.

**Comment by p9anand** [comment]
@bletham : Thanks. will try and keep you posted.
