### ISSUE TITLE
*_lower & *_upper not correctly filled in predict() output from R?

### ISSUE THREAD

**Issue by harlecin** [facebook/prophet#1192]
Hey,

I was just debugging a model when I wanted to check the lower and upper boundaries for the trend, but there might be a copy error in prophet (in the R version at least):

When I look at the generated output from this code:

```
test <- read.csv('../examples/example_wp_log_peyton_manning.csv')
m <- prophet(test)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
data.table::setDT(forecast)
View(forecast[,.(yhat_lower, yhat, yhat_upper, trend_lower, trend, trend_upper)])
```
using the Peyton Manning sample data, I get:
![grafik](https://user-images.githubusercontent.com/11078385/67569945-84cc8e80-f730-11e9-87d0-14089c037bb7.png)

Prophet correctly includes uncertainty in yhat_lower and yhat_upper, but trend_lower = trend = trend_upper.

I think that might be a bug or is this to get a nice plot output?

Best
Christoph

PS: Thx a lot for all your work on this package! It's amazing:)

**Comment by benmwhite** [comment]
It looks like you can't get trend component uncertainty over the time period in your training set unless you have the model do full MCMC sampling rather than MAP estimation. [You can get it for future predictions, however](https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend). 

See the [code here](https://github.com/facebook/prophet/blob/c7a150312ad26db5a8ea81d8cd32dd5fd6ce1eda/R/R/prophet.R#L1552), trend upper and lower bounds are computed by looking at the quantiles of a simulated sample.

**Comment by benmwhite** [comment]
The sample generation looks like it's here [in this line](https://github.com/facebook/prophet/blob/a3ae4715bbc0a18cde35f7b199a671f53df80168/R/R/prophet.R#L1583). The yhat samples also include a random noise term, so I believe that's why you still get an interval estimate. 

This is what I've been able to gather from a quick look over the source code at least, hopefully someone who's dug deeper can correct me if I'm wrong.

**Comment by harlecin** [comment]
Ah, thx. Did not catch that one.

I was under the impression that yhat_lower/upper = trend_lower/upper + additive_terms + multiplicative_terms

**Comment by skannan-maf** [comment]
I had the same observation and this thread cleared it up! Thanks! Enabling MCMC takes a very large amount of time. Keeps on running for hours even for a simple model. So not going to use that.
