### ISSUE TITLE
fbprophet fails in mac os 10.9.5.

### ISSUE THREAD

**Issue by gg4u** [facebook/prophet#1194]
I cannot make run fbprophet,

```
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib
```
I reference also issue:

https://github.com/facebook/prophet/issues/715

@bletham could you please help, maybe your solution is close to the one I am looking for.

I think this issue is related to compiler:

```
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbprophet
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
````

I am running mac os 1.9.5

tried to install gcc compiler via conda:
`conda -c conda-forge gcc -n myenv``
then 
`conda -c conda-forge fbprophet -n myenv``

still same error with :
`/usr/lib/libSystem.B.dylib`

pystan indeed failed , same error:
```
dyld: lazy symbol binding failed: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _fdopendir$INODE64
  Referenced from: /Users/me/Sites/miniconda3/envs/meteo/bin/python
  Expected in: /usr/lib/libSystem.B.dylib
````

_Originally posted by @gg4u in https://github.com/facebook/prophet/issues/715#issuecomment-546492343_

**Comment by xiaoyaoyang** [comment]
I use `pip install pystan` and got error when tried this

`import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0`

" distutils.errors.DistutilsExecError: command 'clang' failed with exit status 1"

I think it is compiling error... what gcc/clang set up should I use?

**Comment by bletham** [comment]
It looks like the Clang version is 4.0.1. Stan tests with clang 6 (https://github.com/stan-dev/stan/wiki/Supported-C---Compilers-and-Language-Features) so I'm not sure what the support for that old of a version is.

Because Anaconda has a separate build toolchain, I have found the best success in installing via conda forge. If you try uninstalling everything and then install just pystan, do you get the same error that you got when running the code you tried with pip?

I don't think I'm going to be very helpful in figuring out how to get things working (or if they will with Clang 4.0.1), so I'll have to refer you to the pystan issue tracker (https://github.com/stan-dev/pystan)
