### ISSUE TITLE
Model format conversion

### ISSUE THREAD

**Issue by eannam** [facebook/prophet#1198]
Hi, 

Are there any existing methods for converting trained Prophet models to universal model formats (e.g. ONNX, PMML) for porting to other languages? What are current Prophet productionisation best practices?

Thanks,
Éanna

**Comment by bletham** [comment]
There isn't any capability for this now (see also #811).

In our productionization, we don't typically store models. We usually are interested in predictions on some known set of dates, so we fit a model, make predictions on those dates, and then store just the predictions (which can easily be done in a SQL-style table). We typically are only interested in updating predictions when we have new data, in which case the model has to be re-fit anyway. The models do pickle and so I have seen other services where people store pickled models that can be re-loaded when new forecasts are requested, so that's another possibility.

**Comment by gabrielfior** [comment]
Are there any updates on this? I'm also looking for a way to store the Prophet model as an ONNX file for easier downstream compatibility.

**Comment by phoenixClairvoyant** [comment]
Are there any updates on this? I am also looking for methods to convert prophet model to onnx.
