### ISSUE TITLE
R: Missing holidays for BG, BY, JP, RS, and UA

### ISSUE THREAD

**Issue by jdumas-fastly** [facebook/prophet#1202]
Greetings! 

After taking a peak at the [generated_holidays.csv](https://github.com/facebook/prophet/blob/master/R/data-raw/generated_holidays.csv) file I noticed that all the historic and future holidays for Japan are NA, which cause this error:

Screenshot of missing holiday names for Japan:

<img width="326" alt="Screen Shot 2019-10-31 at 1 33 12 PM" src="https://user-images.githubusercontent.com/42421548/67971580-66104100-fbe3-11e9-9ef4-9f64c601d789.png">

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in dimension declared and found in context; processing stage=data initialization; variable name=sigmas; position=0; dims declared=(29); dims found=(28)  (in 'model166a03c929512_prophet' at line 82)

failed to create the optimizer; optimization not done

```

**Comment by bletham** [comment]
Thanks for pointing this out - I know there were some ascii conversion issues in the past, and it seems like they have not been correctly resolved for Japan. This CSV is generated from the Python holidays package using this script:
https://github.com/facebook/prophet/blob/master/python/scripts/generate_holidays_file.py
so the issue will have to be fixed there.

**Comment by bletham** [comment]
OK the issue here is that the holiday names are all in utf-8. We can't include utf-8 data in the R package (CRAN is very strict about certain things) and so we convert them to ascii:
https://github.com/facebook/prophet/blob/64d54e774865c8913d0f80a589af1cfa2340a05f/python/scripts/generate_holidays_file.py#L22-L37

The characters for the Japanese holidays do not have an ascii decoding.

I "fixed" the issue for now by removing these holidays from the csv file that is used by R. This unfortunately means R will not have access to holidays from: JP, BG, BY, RS, and UA. To get these back in we'd have to somehow get ascii versions of the holiday names.

**Comment by somum** [comment]
@bletham 
I am unable to add the Japan holiday here ->

**m.add_country_holidays(country_name='JP')** 

Can you help?

**Comment by AlFontal** [comment]
I can't get the Japanese holidays either now (in Python 3.10, `prophet==1.1.2`)
