### ISSUE TITLE
Combine Prophet model with mathematical optimization

### ISSUE THREAD

**Issue by nba2020gr** [facebook/prophet#1210]
I want to use Prophet to build a forecast model of **Y** with 10 regressor variables (x1, x2, x3 etc.)
My **Y** time-series has daily observations with trend, weekly and annual seasonality.
After constructing the model, l want to find the optimal values of [x1, x2, x3..]  that will maximize Y in the future. How may I approach this in R?

**Comment by Momboosa** [comment]
I've been trying to do something similar. Did you find an easy alternative?

**Comment by nba2020gr** [comment]
No not yet :(

**Comment by bletham** [comment]
Unfortunately I think the answer will be somewhat trivial because regressors in Prophet are always modeled as linear.
The model is basically
```
y(t) = trend(t) + seasonality(t) + \sum_{i=1}^n beta_i * regressor_i(t)
```
where `n` is the number of regressor. So, each regressor is taken to have a linear effect on the final `y(t)`, with coefficient `beta_i`. So for some future t, what is the value of `regressor_i(t)` that maximizes `y(t)`? Well, if `beta_i` is positive, then it will be whatever the largest possible value of `regressor_i(t)` is. If `beta_i` is negative, it will be the smallest possible value.

Does that make sense? Is that the question you were asking?

**Comment by nba2020** [comment]
OK since the regressors are modeled linear then the answer makes sense.
It would be interesting if somehow we can get Prophet to model nonlinearities and interactions.
`y(t) = trend(t) + seasonality(t) + beta1 * regressor_1(t)* regressor_2(t)+beta1 * regressor_1(t)^3`

**Comment by benmwhite** [comment]
@nba2020 You can compute the nonlinear and polynomial terms manually and feed them into the model as additional regressors, something like the [recipes](https://tidymodels.github.io/recipes/) package can help here.
