### ISSUE TITLE
How to model repeated truncation of annual (daily) data?

### ISSUE THREAD

**Issue by hilikus44** [facebook/prophet#1211]
I have daily data for the past 10 years, but the bulk of my business volume (95%) falls between about January 28th (varies each year) and April 15th (varies each year).

I mainly just need forecasts within this timeframe of Jan-Apr, and do not really need the forecasts in the months of May-December, as the volume is low as a % of my total volume. 

I suppose I have two options in forecasting my daily volume: 
(1) use each cycle entire year of daily data, and create a custom holiday or regressor to indicate the "heavy period" of the year of Jan-Apr
(2) or, truncate each year of my data, and only use days in January-April for each year cycle of my annual data

So, my questions are: 
- which of these (1)-(2) would be better?
- from what I understand, Prophet could handle the truncated data in (2) fine, as long as my future timeframe data also does not include May-December?
- is there any benefit to using the entire year of the data (1), as this seems to complicate the forecast, by including such a low volume and highly variable timeframe May-Dec, which would have seasonalities and trends different from my heavy period that I am interested in of Jan-Apr?
- Also wondering how to test optimal # of years of history to use? I assume that if one is going to include custom holidays or extra regressors, then more data is generally better....

**Comment by bletham** [comment]
My recommendation would be (2) (give the model only the data that you are interested in forecast, here the Jan-April data). That way if the trend/weekly seasonality are totally different in the May-Dec period, they won't be interfering with that of the Jan-April period that you care about. As you note, doing this means that the yearly seasonality will be totally unconstrained in the May-Dec period, which means it will probably be poorly fit and so you'd want to be sure to only make predictions in the Jan-Apr period (since predictions in May-Dec would probably be very bad).

There really is no benefit to including the entire year data if you only want to forecast Jan-Apr. As you note, the seasonalities are very different and so it would only make your Jan-Apr forecast worse.

How many years - I guess however many you think the seasonal and holiday effects are reasonably stable over. For instance, Prophet assumes constant weekly seasonality across the entire time series. So if the weekly seasonality was really different in the distance past, then maybe using only more recent data would make sense and give estimates that are better for the near future. But if things are relatively stable, then the more years the better.

**Comment by hilikus44** [comment]
Thank you for the response, makes sense!
