### ISSUE TITLE
Support reggessor prediction when a reggresor doesn't contain future data

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#1216]
provide a `price ` reggressor for  salecount forecast .
I have the history price , but I don't know the future price , so I have to assume future price is the guide price .
However, this product never sold in guide price , there is always some retail workers who set the price on  that day .

The problem is , there are 3  point 4980( $49.80)  salecount less than the other points which price is 4990( $49.90)  . This make model think higher price have higher salecount . So when I set future price as guide price 6590( $65.90)  , model predict a huge salecount .

![image](https://user-images.githubusercontent.com/3938751/68659245-e171db00-0571-11ea-80a8-1daf2f7f0322.png)

prediction component:

![image](https://user-images.githubusercontent.com/3938751/68986981-baf8bc00-085f-11ea-99b6-1f682a8a8902.png)

Because guide price is the max price a retail worker can set.
. I don't have any have the maximum and minimum price reference any more.  

Even if I set 150% of the guide price as maximum price, 50% of the observed price as minimun price to do minmax scale , still occur such problem, juts prediction value decrease .

The solutions 
1. drop price reggressor .
1. make price prediction , conbime history price and set to reggressor .

If I have many such reggresor which is important but only have history data .
I should make prediction to all of them , this would cause many redundant codes .

So how about support reggessor prediction when a reggresor doesn't contain future data ?

**Comment by bletham** [comment]
Generally, you will need to give something for the value of each extra regressor for the future. The model doesn't have a good way of assuming what a "good" future value of the regressor is, since it doesn't have any context for what a particular value of the regressor means (see my comment here for more detail: https://github.com/facebook/prophet/issues/1141#issuecomment-536218940 ).

For the particular issue here: If I understand correctly, the history has only 2 price points, 4980 and 4990. 4990 was used every day except for 3 days that used 4980. Predictions are then being made by setting price to 6590. In this setting the model really has no way to learn what the effect of price is on y, and almost certainly will not generalize well to 6590 (as observed). I think there are two options for what could be done. The first would be, as you note, to drop the price regressor. In this case with so little change in price it probably isn't going to be able to learn anything useful anyway.

The other option is just to set the future value to something that is consistent with past values, and so for which the model should be better able to generalize. For instance, instead of using the (never observed) guide price as the future price, you could you use the mean or median price in the history. The model will be able to do a much better job at predicting price levels similar to those seen in the history.
