### ISSUE TITLE
Yearly seasonality and Regressors offsetting each other with weekly data

### ISSUE THREAD

**Issue by sammo** [facebook/prophet#1226]
Hey Ben and all,
I came across a weird behavior when modeling with less than 2 years of weekly data with yearly seasonality and holidays processed as regressors.

Here is what the forecast results look like:
![image](https://user-images.githubusercontent.com/47832587/69459369-74ef9c80-0d26-11ea-9817-66e08c17d630.png)

The holiday features indicate whether a holiday exists in the specific week, with calculated holidays for two weeks before and one week after. This is trying to replicate what Prophet does with daily holidays but at the weekly level.

Do you have an explanation for why the annual seasonality and holiday regressors' effects are offsetting each other in this way? Any help or insight would be appreciated.

Here is the data and code to replicate it.
```
import numpy as np
import pandas as pd
from fbprophet import Prophet  #fbprophet==0.5
import matplotlib.pyplot as plt

df = pd.read_csv("df.txt", index_col=[0])
future = pd.read_csv("future.txt", index_col=[0])

hyper_params = dict(
    growth="linear",
    changepoints=None,
    n_changepoints=25,
    changepoint_range=0.95,
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False,
    holidays=None,
    seasonality_mode="additive",
    seasonality_prior_scale=0.5,
    holidays_prior_scale=5.0,
    changepoint_prior_scale=0.05,
    uncertainty_samples=1000,
)

m = Prophet(**hyper_params)
_ = [m.add_regressor(feature) for feature in df.columns if feature not in ["ds", "y"]]
_ = m.fit(df)
forecast = m.predict(future)

# Displays automatically in a jupyter environment
_ = m.plot_components(forecast)

# Displays automatically in a jupyter environment
_ = m.plot(fcst=forecast)

# Displays automatically in a jupyter environment
fig, ax = plt.subplots(figsize=(18, 8))
_ = ax.plot(forecast.set_index("ds")[["yhat"]], label="yhat")
_ = ax.plot(forecast.set_index("ds")[["trend"]], label="Trend")
_ = ax.plot(forecast.set_index("ds")[["yearly"]], label="Yearly")
_ = ax.plot(forecast.set_index("ds")[["extra_regressors_additive"]], label="Holiday regressors")
_ = ax.legend()
```

[df.txt](https://github.com/facebook/prophet/files/3881406/df.txt)

[future.txt](https://github.com/facebook/prophet/files/3881408/future.txt)

**Comment by bletham** [comment]
Thanks for the clear repro code! Yes, the yearly seasonality is being badly overfit here.

I think the issue is that while there is nearly 2 years of data, it isn't fully daily data so there aren't actually that many data points. There are only 93 data points. There are 8 holidays defined, but some of them also have a +1, -1, or -2 defined, which add up to a total of 32 holidays (the number of columns in df besides y and ds).

Of the 93 data points, 47 of them fall on a defined holiday (so, more than half of them). Since holidays are themselves seasonal, this means that the holidays have the chance to capture nearly all of the yearly seasonality, in a way that they wouldn't if there were more non-holiday days. (With full daily data, there would be 32 holiday days per year and thus 333 non-holiday days). I think that is what is ultimately causing the seasonality to be badly fit (what's leftover after grabbing most of it with holidays is a bit of a mess).

You can always reduce overfitting in the seasonality by really clamping down on the prior scale; you already did that (you took it from the default of 10, which is basically no regularization, down to 0.5), but taking it even further down eventually flattens it out. This is with 0.01:

![Screenshot-20200128163235-1820x889](https://user-images.githubusercontent.com/6339760/73317729-f0b90a00-41eb-11ea-9faf-05d83ffe0d59.png)

The holiday effect is probably overfit too:
![Screenshot-20200128163302-1020x689](https://user-images.githubusercontent.com/6339760/73317741-fc0c3580-41eb-11ea-8575-67a45cf40684.png)

but with so few non-holiday days, the model is going to have a really hard time identifying what the holiday effects are vs. the noise level.
