### ISSUE TITLE
Conditional Regressors (Similar to Conditional Seasonalities)

### ISSUE THREAD

**Issue by trevor-pope** [facebook/prophet#1233]
Is it currently possible to implement conditional regressors? I have several continuous time series with strong correlation to the variable I am predicting, except on specific holiday events. Is it possible to have regressors fit only to a certain section of data like holidays are?

**Comment by sammo** [comment]
@trevor-pope you can take the regressor you want to make conditional and set it to zero on the "off-season" dates. This is what the `make_seasonality_features` method does. Did you try that?

**Comment by bletham** [comment]
Yeah I think that since the relationship between `y` and regressors is assumed linear, specifying "this regressor as no effect at t" would just amount to setting `regressor(t) = 0`.

However there is one complication, which is that Prophet will automatically standardize non-binary regressors. So specifying it as 0 in the input would then produce something that, after standardization, would probably not be 0. So you'd need to either specify no standardization (https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/forecaster.py#L589-L591) or you'd want to actually set them to the _mean_ value (excluding them) so that they'd be 0 after standardization.
