### ISSUE TITLE
When we use prophet for fault prediction, negative numbers appear, but negative numbers are not reasonable.

### ISSUE THREAD

**Issue by lizhaodong** [facebook/prophet#1234]
The great Prophet team:
       When we made a fault prediction, a negative number appeared, but in fact, it should not appear, because a negative number of faults is meaningless. I have looked at previous issues and they have asked the same question. When can the great Prophet team solve this problem?

![image](https://user-images.githubusercontent.com/1129767/69855051-98d25580-12c5-11ea-9849-278dac351b70.png)

        We also tried setting a value less than 0 to 0, which didn't seem to be a good approach. As shown below:
![image](https://user-images.githubusercontent.com/1129767/69855307-388fe380-12c6-11ea-882a-4f65e7582d42.png)
Feeling awkward!

**Comment by lizhaodong** [comment]
The great Prophet team:
  &emsp; &emsp; After I performed the boxcox transformation on the original data, the prediction did not show negative numbers, but compared to the before, the curve of trend seems to fit more precisely, and the predicted data as a whole seems to be reduced. The two pictures below are shown without changes and after the boxcox transformation. The figsize of both pictures is the same --- (10, 6). 
 &emsp; &emsp; Before boxcox transformation：
![image](https://user-images.githubusercontent.com/1129767/69861712-e0f87480-12d3-11ea-90a8-0a67febdfb7c.png)

After boxcox transformation：
Restored these data: 
ytrue =  special.inv_boxcox1p(new_df['y'], lam_best)
size = len(ytrue)
yhat =  special.inv_boxcox1p(forecast['yhat'], lam_best)
trend =  special.inv_boxcox1p(forecast['trend'], lam_best)
yhat_lower =  special.inv_boxcox1p(forecast['yhat_lower'], lam_best)
yhat_upper =  special.inv_boxcox1p(forecast['yhat_upper'], lam_best)

![image](https://user-images.githubusercontent.com/1129767/69861770-fec5d980-12d3-11ea-8279-1d3f8f2ba6d2.png)
Drawing source code:
fig = plt.figure(facecolor='w', figsize=(10, 6))
ax = fig.add_subplot(111)

ytrue =  special.inv_boxcox1p(new_df['y'], lam_best)
size = len(ytrue)
yhat =  special.inv_boxcox1p(forecast['yhat'], lam_best)
trend =  special.inv_boxcox1p(forecast['trend'], lam_best)
yhat_lower =  special.inv_boxcox1p(forecast['yhat_lower'], lam_best)
yhat_upper =  special.inv_boxcox1p(forecast['yhat_upper'], lam_best)
ds = forecast['ds'].dt.to_pydatetime()


ax.plot(ds[0:size], ytrue, 'k.')
ax.plot(ds, yhat, ls='-', c='#0072B2')
ax.fill_between(ds, yhat_lower, yhat_upper, color='#0072B2', alpha=0.2)

ax.plot(ds, trend, color="red")
ax.fill_between(ds[size:], yhat_lower[size:], yhat_upper[size:], color="red", alpha=.75)

ax.grid(True, which='major', c='gray', ls='-', lw=1, alpha=0.2)
ax.set_xlabel('ds')
ax.set_ylabel('y')
fig.tight_layout()

My question is: Is this reasonable? If it is not reasonable, can you tell me the reason?  Thank you very much!

**Comment by lizhaodong** [comment]
The process of boxcox transformation:

from scipy import stats,special

lam_range = np.linspace(-2,5,100)  # default nums=50
llf = np.zeros(lam_range.shape, dtype=float)
# lambda estimate:
for i,lam in enumerate(lam_range):
    llf[i] = stats.boxcox_llf(lam, new_df['y'])	
	
# get best lambda :
lam_best = lam_range[llf.argmax()]

# boxcox convert:
new_df['y'] = special.boxcox1p(new_df['y'], lam_best)

**Comment by bletham** [comment]
This certainly seems to be giving you a reasonable forecast. I'll just give a few comments on using the boxcox transformation, and on alternative things you might try.

Using boxcox: It is definitely reasonable to Box-Cox transform the data y, and then apply the inverse transform to yhat. Because the Box-Cox transformation is monotonic, it is also appropriate to apply to yhat_lower and yhat_upper without it affecting the percentile. The only thing to be careful about is looking at the components (seasonality, holidays, etc.). If you apply an inverse Box-Cox transform to the components, you will find that they do not sum up to yhat as expected;  I give some description of that here: https://github.com/facebook/prophet/issues/647#issuecomment-413027578

I think Box-Cox did the job well here, but the only other thing I would suggest as a possibility would be to use the logistic trend with a floor of 0 (https://facebook.github.io/prophet/docs/saturating_forecasts.html#saturating-minimum), and then use multiplicative seasonality. That will keep things mostly positive (though possibly not entirely, in which case you would just clamp any leftover negative values to 0).
