### ISSUE TITLE
.add_country_holidays() with weekly data

### ISSUE THREAD

**Issue by maralbertomar** [facebook/prophet#1239]
Hi Everyone,
I have **weekly data** and I was trying to figure out how to properly use the **.add_country_holidays()** function. The built-in function doesn't seems to work as it identifies only some of the given holidays. Does the built-in function works only with daily data or it has some walk around for more aggregated data?   

Thank you

**Comment by bletham** [comment]
That's correct, the built-in function will only work with daily data since it assigns the holiday effect to that particular day, and thus will miss it if it has been aggregated into a single day for the week. Basically you'd need to create your own holiday and give it the dates that that holiday will be rolled up into; I give some more detail here: https://github.com/facebook/prophet/issues/985#issuecomment-496627352
