### ISSUE TITLE
Prediction for AUPH Stock Not Including Recent Uptick in Value 

### ISSUE THREAD

**Issue by basillatif** [facebook/prophet#1246]
I have a data frame which shows the price of AUPH stock going up to 18.45 at EOD today. 
<img width="473" alt="Screen Shot 2019-12-11 at 4 18 46 PM" src="https://user-images.githubusercontent.com/9244621/70671771-066d7280-1c32-11ea-894f-fa65f2d05b4f.png">

Yet the predictive model doesn't even include the recent points where the stock has gone up in value...

![AUPH_predict](https://user-images.githubusercontent.com/9244621/70671829-39b00180-1c32-11ea-95d0-9a20ce2f4a79.png)

FB Prophet is not useful if it can't capture very recent upswings in price...

**Comment by reidwil** [comment]
Do you have reprex of your model? Furthermore, an uptick in the last two days shouldn't completely change the trajectory of a model that has 2+ years of data

**Comment by basillatif** [comment]
Here's the code I'm using to make the forecast:
```
auph_model = AUPH[['ds', 'y']]
#Instantiating a new prophet object
my_model = Prophet(interval_width=0.95)
my_model.fit(auph_model)
future_dates = my_model.make_future_dataframe(periods=365)
forecast = my_model.predict(future_dates)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
```
I think the Prediction should be more accurate. The stock has already gone up to $18, so it doesn't make sense to project it to hover around $8.

**Comment by reidwil** [comment]
Because prophet is using a Fourier Order for seasonalities, making a model to reflect the sudden spike in the past few days, would cause the model to continually to predict that at some level when historically, that hasn't been the case. I would adjust maybe a few parts of the Prophet call but error more on the side that this instance is an outlier

**Potential Solutions**

From the docs:
>  You can adjust the strength of the sparse prior using the input argument changepoint_prior_scale. By default, this parameter is set to 0.05. Increasing it will make the trend more flexible 

[https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet](url)

I would also consider changing the seasonality scales for monthly and yearly scales with something like:
`Prophet(yearly_seasonality=20, monthly_seasonality=20)`

**Comment by bletham** [comment]
I think the answer is in the last paragraph here https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet :

> By default changepoints are only inferred for the first 80% of the time series in order to have plenty of runway for projecting the trend forward and to avoid overfitting fluctuations at the end of the time series. This default works in many situations but not all, and can be change using the changepoint_range argument. For example, m = Prophet(changepoint_range=0.9) in Python or m <- prophet(changepoint.range = 0.9) in R will place potential changepoints in the first 90% of the time series.

In this time series, there is a very sharp change at the very end. Prophet is not putting any changepoints there, since they are only in the first 80%. If you want the model to fit that trend change, then you need to increase that number; maybe has high as 0.95 since the change is at the very end.

That will get the model to fit the change, but I don't think it will give a good forecast. What it's going to do is then fit a linear trend to that end segment with an extremely high slope, and that extremely high slope will be projected forward into the entire future. We know that this is a bad forecast and that (since this is a stock price) this uptick will not last forever, but the model doesn't know that. So you would definitely need to add to the model to avoid that, for example with https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth .
