### ISSUE TITLE
Is there a way to run cross validation in parallel (multiprocessing)?

### ISSUE THREAD

**Issue by covrig** [facebook/prophet#1250]
I have quite a few loops to run and running the cross validation in parallel would help quite a bit.
Thanks.

**Comment by bletham** [comment]
This isn't possible now, but probably wouldn't be too difficult. This is the loop that would be distributed: https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/diagnostics.py#L110

**Comment by ryankarlos** [comment]
@bletham We have been doing something similar for our project using dask delayed - not sure if your preference is to use `multiprocessing` library in python or `dask` - guess the latter would require an update to `requirements.txt` file.

**Comment by bletham** [comment]
My preference would be to try and do it with vanilla multiprocessing in order to not have to add a new dependency. And I was also thinking about doing it just with a Pool across cutoffs as you describe. I think the only important detail would be to have a way of doing it without multiprocessing (for the purposes of debugging especially), but that should just be a couple lines. A PR would be great!

**Comment by ryankarlos** [comment]
Ok thanks, having an option to switch it on and off is a good idea - just made a PR.

**Comment by mat178** [comment]
@ryankarlos Nice! Thank you so much for this feature!

**Comment by ryankarlos** [comment]
@mat178 no worries - theres more enhancements that could be added in once the PR is approved.

**Comment by bletham** [comment]
I'll leave this open til it's pushed

**Comment by bletham** [comment]
Pushed in v0.7!
