### ISSUE TITLE
cross validation with monthly data - workaround solution not working

### ISSUE THREAD

**Issue by vivi11130704** [facebook/prophet#1253]
system: win10

prophet version: 0.5

I'm referencing [this workaround](https://github.com/facebook/prophet/issues/949#issuecomment-487994184) solution for dealing with monthly data using cross validation. #949 

The goal is to use past monthly revenue data to predict future revenue. You can find the data [use with link](https://drive.google.com/file/d/11-JZVZtnYNur0frnEPPzFsZM2peewPRK/view?usp=sharing)

my code looks like this: I'm using the first 2 months as initial training period. Then predict the next month, then iterating for every month. 

`m = Prophet()`
`m.fit(df)`
`df_cv1 = cross_validation(m, initial=pd.to_timedelta(2,unit='M'), period=pd.to_timedelta(1,unit='M'), horizon=pd.to_timedelta(1,unit='M'))`

The output df_cv1 can be found [here](https://drive.google.com/open?id=1VJT9TXtP--kpJrngCmKB7aNodfM5cJT8). Here is a screenshot: The yellow part where I highlighted is obviously wrong.

![image](https://user-images.githubusercontent.com/7614915/71039487-3d3ffe80-20f2-11ea-99bf-92bb21b748ac.png)

Can someone please explain why this happen? Thanks in advance!

**Comment by bletham** [comment]
The challenge here is that a month is not a fixed amount of time. If you check what `pd.to_timedelta(1,unit='M')` gives you, it is: `Timedelta('30 days 10:29:06')`. This means that in some months (lke Jan) it will be slightly less than a month; in other months (like Feb) it will be a couple days more than a month.

The way cross_validation computes cutoffs is to start from the end of the time series minus horizon, and then walk backwards, taking steps of size `period`.The logic for this is here (most of the logic is handling the situation where the horizon at a particular cutoff has no data):
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/diagnostics.py#L37-L47

So now for this time series, consider row with 12 (with ds 4/1/2019). The cutoff here was 3/1/2019 19:34. To get the next cutoff, we subtract 1 "pandas" month, which is `30 days 10:29:06` and we end up with `2019-01-30 09:04:54`. So in this case the entire month of February was skipped because the pd time delta of "1 Month" was actually longer than the month of February.`2019-01-30 09:04:54`

Once the cutoff has been established as `2019-01-30 09:04:54`, it will make predictions for any datapoints that fall within `horizon` of that point. `horizon` is again a _pandas_ month, which is longer than the month of February, so both 2/1/2019 and 3/1/2019 lie within the horizon. And so predictions are made for both of these (and are rows 10 and 11 highlighted in the spreadsheet).

So I hope that makes sense for why this is happening. Basically the data in the time series have uneven spacing (since the length of a month is not constant) so sometimes we end up with 2 datapoints within a single period. 

What can you do about this. The short fix would be to just pass through `df_cv1` and remove any rows where `cutoff` and `ds` are very close to eachother, to get rid of these instances where it is predicting 1 day into the future. For instance,
```
df_cv1['ds'] - df_cv1['cutoff'] > pd.Timedelta('15 days')
```
would probably work as a filter condition.

Longer-term, it would probably be useful to be able to directly specify the cutoffs used. Basically there could be an input to cross_validate that would allow passing a list of cutoffs directly instead of calling `generate_cutoffs` , here:
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/python/fbprophet/diagnostics.py#L108-L110

In the meantime, you could also always copy out that function and replace `cutoffs` with whatever you want (here, a list of month start dates).
