### ISSUE TITLE
Can we decouple fits around changepoints?

### ISSUE THREAD

**Issue by dhitals** [facebook/prophet#1255]
Hi, 

I am trying to change how `fbprophet`/`stan` fits to data around changepoints.

Consider data where there are catastrophic changes where `y` increases by 2-5x at a given changepoint, `t`. The current behavior is to ramp up/down smoothly, which makes sense in most cases. In this particular case, if changepoints are recalculated or known, I would prefer a catastrophic ramp up/down as dictated by the data (akin to a step function); otherwise the predictions are way off. In other words, a model that treats data on either side of a changepoint independently is what I am looking for.

Thanks, in advance for your help.

**Comment by bletham** [comment]
There isn't a good way to do this automatically. This would imply a different trend function, and there isn't yet support for customizing the trend function (see #705). The best that could be done for now is if you know when those dates are, you could add a binary extra regressor that is value 1 for those dates and 0 otherwise that would fit the large shift.
