### ISSUE TITLE
The impact of the holiday is the hour level

### ISSUE THREAD

**Issue by 404nala** [facebook/prophet#1256]
I want the given holiday date to be not days but hours when I tried to model hourly data. 
Frankly, I am not giving holiday dates, but some unexpected events that we know in advance but are irregular.The impact of an emergency is only a few hours.

Which part of the program should I modify in this case.
Any help would be greatly appreciated.

**Comment by bletham** [comment]
If I understand correctly, you want to specify a special event that maybe only lasts a few hours rather than an entire day (as when using the holidays). You can get this by adding an extra regressor: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

Basically you would add a binary regressor that would have value 1 for the rows that have the effect, and 0 otherwise. That gives you complete flexibility in how long the effect will last, since you will directly specify (both in the history and future dataframes) where it should be active.
