### ISSUE TITLE
Unable to get 'p value' of additional regressors used in Prophet

### ISSUE THREAD

**Issue by venkatraman29** [facebook/prophet#1264]
Hi,

In addition to historical data of my target variable, I am using a few regressors in my model.
I want to understand the significance (p value) of each of those features in my Prophet model, so that I can perform backward elimination of features, iterate and train a robust model.

Couldn't find any direct way of getting this by using the Python API for Prophet.

**Comment by benmwhite** [comment]
The models aren't built around a hypothesis testing framework so you don't technically have traditional p-values to compute (and in any case stepwise feature selection based on p-values will give you misleading results if you intend to report the final p-values after the selection process).

If you use MCMC to estimate the model parameters instead of the default MAP then it should be possible to get the estimated posterior distributions of the regressor coefficients and use these distributions for inference (e.g. where does zero fall in this distribution, what percent of the samples are positive/negative, etc.), however I'm not sure if these samples are available to end users or just purely internal to the Stan backend at this point. I'd love to get some clarification on this one, and it might be worth a feature request if it's not already available.

That said, If your goal is robust prediction then a safe approach is to use the built-in regularization with prior scale parameters on the additional regressors. This is meant to ensure that you don't overfit to small or noisy effects in your regressors when the forecast is produced.

If it turns out that the coefficient MCMC samples are only internal and also you *really really need* to get *some* way to assess *some sort* of "significance" then a super dirty brute force approach would be to take your response and regressor time series, randomly permute their values, run the Prophet models on the new permuted samples (which should not have any time relationship now since you've decoupled that through permutation), save the coefficient values, and repeat this process a whole bunch of times . These sets of coefficient samples for each regressor from this process can be used as an approximate null distribution for setting sort of "p-value-esque" thresholds with empirical quantiles. 

Again this is a really hacky approach and you should take results from this with a grain of salt.

**Comment by bletham** [comment]
The parameters for a fitted model `m` are stored in `m.params` in Python or `m$params` in R. This is a dictionary (list in R) from parameter name to values. `m.params['beta']` will contain the values of the regressor coefficients (for both seasonalities and extra regressors), and if you do MCMC it will also contain the MCMC samples. If there are `n_param` total regressors and you have `n_samp` total MCMC samples, then `m.params['beta']` will be a `n_samp x n_param` array, so each column has all the MCMC samples for a particular coefficient. To figure out which column corresponds to which coefficient, you can look at `m.train_component_cols` as I describe here: https://github.com/facebook/prophet/issues/848#issuecomment-465800085

So you could look at the distribution of betas in that column and determine the posterior probability that it is > or < 0. I have some additional comments on this here: https://github.com/facebook/prophet/issues/1145#issuecomment-537746564

However, if you just want to know if the effect of a regressor as used in the model is significantly different than 0, there is a much easier way. The forecast dataframe (output of `m.predict`) will have a column for that regressor, let's call it `regressor`. That column is the model-estimated effect of `regressor` on `y`, and in particular is the amount of the estimate `yhat` that is coming from that particular regressor. If you look at `regressor_lower` and `regressor_upper`, it will give you an uncertainty interval for that effect (by default 80%, but you can set it as described in https://facebook.github.io/prophet/docs/uncertainty_intervals.html). Whenever the interval `[regressor_lower, regressor_upper]` does not contain 0, that indicates a significant effect.

**Comment by benmwhite** [comment]
@bletham the `regressor_lower`/`regressor_upper` check with the raw prediction output is also for MCMC rather than MAP, is that right?

**Comment by bletham** [comment]
Yes that's right, with MAP estimation only trend uncertainty is estimated, not regressors.
