### ISSUE TITLE
Any good way to transfer seasonality from parent to children ?

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#1269]
For example, 
I want to predict a new kind of apple named `a1`, this apple didn't sell in my store before .
I have a  category named `A` to stand for all kinds of apples .

I can predict salecount seasonality of `A` , but due to lack of data , can't predict  `a1` .

Now I am plan to hack fbprophet to add trained seanonality of `A` to `a1` . 
Is there an official/ recomanded way to do this ?

**Comment by eromoe** [comment]
The holidays effects also can inherit from parents to solve below problem
https://github.com/facebook/prophet/issues/1200
https://github.com/facebook/prophet/issues/1157

**Comment by leslieclemence** [comment]
Hi ,

In the first month of sells of a1, where you don't know how many a1 sells
you will have,  i think you only can use the same projection curve of A.
In the subsequents months i would try to proportionately decrease or
increase A's previous months according to a1's actual sales data, coupling
with a1's actual sales months, and use this data to generate the projection.
I think this is more controllable
Hope this helps.

Leslie Clemence


Em seg., 6 de jan. de 2020 às 01:04, eromoe <notifications@github.com>
escreveu:

**Comment by eromoe** [comment]
@leslieclemence 
Yes the simple way is
1. only use A model to do prediction
2. use scale( A/a1 )  to adjust the prediction .

But I need predict by hour/day, products may have 1~12 months data when the parent category have been sold for 2 years . I think use real feature is much more precise : 

1. use `a1` data to train a `model a1`
1. extract seasonality parameters from `trained A model`  ( mainly use yearly seasonality and  summer/winter reggresor ) , replace the parameters trained in model a1
1. extract replace holidays effect  from  `trained A model` ,  overwrite in a1 too .
1. use new a1 model to make prediction.
1. use scale( A/a1 )to adjust the prediction 

I know the parameters are store in trained model, but not sure replacement would work as my thought , or I would make some imperceptible mistakes due to lack of understanding of fbprohet . So I ask for the official/ recomanded guide .

**Comment by benmwhite** [comment]
I think using multiplicative seasonality effects makes the most sense in this case/example (model fit on all apples -> model for single new type of apple). The estimates are basically percentage increases or decreases from the estimated trend at that point, so it won't require any manual parameter rescaling.

**Comment by bletham** [comment]
I think this could work using extra regressors.

The challenge is that when the model for a1 is fit, the trend and the seasonality are jointly fit. What you would ideally want to do to directly transfer seasonality from A to a1 would be to fit the trend for a1, while fixing the seasonality to be that of A (or more likely, some scaled version of that of A). To do this would require pretty significant changes both to the Stan model and to the fit function in R/Py. On the other hand if a1 is first fit and then the seasonality for A is swapped in (perhaps after some scaling), then this might give bad results because the trend for a1 was fit while taking into account the a1 seasonality; so after plugging in the A seasonality, the trend might not be what we really would have wanted given the A seasonality. 

So what you could try instead is to take the seasonality for A and add it as an extra regressor to the model for a1. Basically then the model for a1 is going to be
```
y_a1(t) = trend_a1(t) + seasonality_a1(t) + beta * seasonality_A(t)
```
where the amount of `seasonality_A` used in the model would be the fitted parameter beta. (it'd be the same idea with multiplicative seasonality / a multiplicative extra regressor). You could then entirely disable seasonality when fitting a1, in which case `seasonality_a1(t)` will be 0 and all of the seasonality will be coming directly from a scaled version of seasonality_A, where the amount of scaling is fit by the model to be whatever is most appropriate for the data. I think that should give pretty close to what you're looking for. You could even add weekly and yearly seasonalities from A as separate extra regressors so that they each get their own fitted scale coefficient.

You could also leave `seasonality_a1` in the model but just give it a very tight prior scale (like 0.1 or 0.01 instead of the default 10). This would encourage the model to use `seasonality_A` whenever possible, but if e.g. we have a few weeks of data and the weekly seasonality in A is doing a bad job at fitting the data, then the model would be able to instead use its own weekly seasonality.

If you try this I'd be very interested to hear how it works.

**Comment by cockroachzl** [comment]
I encountered the similar(if not exactly the same) problem. We are attempting to switch from current business metric to a new one to better reflect our business value. The old and new metrics are very relevant but have quite a few differences. The old metric has 2.5+ years of data, whereas we are only able to backfill the new metric for a few months. We would like to know how the metric would perform at the end of H1 of 2021.

Tried both multiplicative seasonal effect suggested by @benmwhite and the extra regressor approach suggested by @bletham. The latter approach is also explained in the doc [Additional regressors](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors) 

> For instance, if r(t) is included as a regressor for y(t), Prophet can be used to forecast r(t) and then that forecast can be plugged in as the future values when forecasting y(t).

What works best for us is to combine both suggested approach, adding an extra regressor and switch the seasonality mode to multiplicative.
