### ISSUE TITLE
Problem with installation on RHEL

### ISSUE THREAD

**Issue by miamartin8** [facebook/prophet#1272]
I am trying to install fbprophet on RHEL virtual machine.  The latest error I have received is:

```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/tmp29t0arch/stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_891399227597298623.cpython-36m-x86_64-linux-gnu.so)
```

I am using:
- Python version = 3.6.9 

- PyStan version = 2.14, 2.17, 2.18, 2.19 
(I have tried all four versions of PyStan)

- GCC version = 4.8.5 

When I try to update GCC:
```
sudo yum install gcc-c++
```
I receive the output:
```
Package gcc-c++-4.8.5-39.el7.x86_64 already installed and latest version
Nothing to do
```

I have tried uninstalling everything and reinstalling several times, and I have tried different versions of the packages needed. 

---

Update: 

I was able to install GCC version 5.4 using the code in this link:
https://gist.github.com/jdhao/e3fd77d51f3a95684d2b3354fc61b2ab#file-gcc-5-4-0-install-sh

Using this, I was able to install fbprophet with PyStan version 2.19.

However, when I tried to run my python script, I received the following warnings:
```
WARNING:pystan:/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/tmp5qn86dx1/stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_2825722041206227630.cpython-36m-x86_64-linux-gnu.so)
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
```

And then I get the error:
```
AttributeError: 'StanModel' object has no attribute 'fit_class'
```

I ran this code to test PyStan and it did work:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

I also tried to uninstall PyStan and fbprophet and reinstall with:
```
pip install pystan --no-cache
```
```
pip install fbprophet --no-cache
```

Both packages installed with no warnings or errors; however, I am still getting the error when I try to run my model:
```
AttributeError: 'StanModel' object has no attribute 'fit_class'
```

**Comment by bletham** [comment]
hm OK so the first GCC issue was probably, as you noted, that PyStan 2.19 requires gcc >= 5.4.0.

Though it seems that after the upgrade you are still getting a warning about this? Was this only before you re-installed pystan or do you still get it? I'm guessing that message has gone away since you do say that PyStan is now working and that the test code runs.

The message `Something went wrong while unpickling the StanModel. Consider recompiling.` can happen when pystan is upgraded, so the fbprophet model was compiled using an older version of pystan than the one currently in the system. So in this case, if fbprophet was installed with pystan 2.14 or 2.18 and is now being run with pystan 2.19, I'd expect this error. So for that re-installing pystan and fbprophet is the right thing to do, which it seems that you did.

So I'm not totally sure what is happening here. Based on the symptoms it sounds like the fbprophet is using a model built with an old version of pystan, so I wonder if something went wrong in the re-install. Could you try that once again with first a pip uninstall, and then load python and make sure that `import fbprophet` fails (that it's really fully uninstalled, and that there aren't multiple copies installed), and then re-install? Could you also post the full stack trace of the error that you're seeing after that? (I'm not totally clear on if you're still seeing the GLIBCXX error). Thanks!
