### ISSUE TITLE
Logistic growth with MCMC gives yhat outside PI

### ISSUE THREAD

**Issue by rsangole** [facebook/prophet#1276]
**Situation**

Running a logistic growth model with MCMC Sampling results in `yhat` outside the prediction intervals.

Sample data at https://www.dropbox.com/s/i7nes81378zd4im/to_share.csv?dl=0

Code snippets at https://gist.github.com/rsangole/ef794826a9039aaffaef392b0c29cb1f

**Sample Output**

_Linear growth model_

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6344050/72192719-726f0200-33bb-11ea-95e6-27c419604109.png">

_Logistic growth model_

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6344050/72192724-76028900-33bb-11ea-821b-0252e5763c6b.png">

_Logistic growth model with MCMC Sampling_

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6344050/72192735-7ef35a80-33bb-11ea-862e-9f23b1450c43.png">

Any idea what's going on?

**Version Info**

```
prophet version 0.5
```

```               
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes        
```

**Comment by bletham** [comment]
Thanks for the clean repro code!

Yeah this is giving really bad results with MCMC.

Generally it is possible for this to happen because `yhat` produced in the forecast dataframe (and shown in the plot) uses the _posterior mean point estimate_. This is different from the mean of the posterior predictive distribution. For example here it computes the posterior mean of the parameters, and then uses that point estimate when computing the trend:
https://github.com/facebook/prophet/blob/0a270b4a19cafb084e5ed6ee0cf942198d4c913b/R/R/prophet.R#L1433-L1435

The uncertainty intervals, on the other hand, are the intervals of the full posterior predictive distribution (so, no point estimates involved). In this case the posterior mean point estimate is very poor, although the posterior predictive distribution is reasonable. I'm not sure what it is about this problem that causes the point estimate to be so poor. I did the sampling with 1000 samples and that didn't improve things.

What can be done about it: You can pretty easily compute the mean of the posterior predictive distribution and use that for yhat rather than the posterior-mean-point estimate returned from `predict`. This will do that:

```
fcst <- predict(m, future)  # Make the prediction as usual
# This returns samples from the posterior predictive distribution:
samps <- predictive_samples(m, future)  
yhat_post_mean <- rowMeans(samps$yhat)
fcst$yhat <- yhat_post_mean  # Replace point estimate with this
plot(m, fcst)  # Plot with the new value
```

That produces a good forecast here.

One caveat with using the mean of the posterior predictive distribution is that with the logistic trend, yhat is no longer necessarily monotonic. With a point estimate it will monotonically saturate at either floor or cap. The posterior mean will likely not because once some of the posterior samples saturate, the distribution will be asymmetric and that will pull the mean down away from the cap. So if you have a time series that is close to saturating at the cap, you will likely see yhat actually decrease away from the cap; but that won't be an issue for this time series.

**Comment by rsangole** [comment]
Thanks for the work around. That'll do nicely. Very weird that this happens with this time series though, none of my other series seem to have any issues.

Thanks for looking into this.
