### ISSUE TITLE
Can Y be a time-of-day?

### ISSUE THREAD

**Issue by stoltzmr** [facebook/prophet#1285]
Hi There,

I want to plot seasonality of observed car license plates from an ALPR camera. For a given plate, I want to plot the seasonality and forecast the expected times, for any given weekday, when the car is next to be expected. In building the CSV file, DS will be date-and-timestamp. Can I make Y the time HH:MM of the car being seen? But Y must be numeric, so how should i handle this situation? Thanks so much!

**Comment by benmwhite** [comment]
This doesn't sound like an appropriate problem for time-series modeling, since the timestamps are the response variable, and not something associated with a continuously-tracked measurement. 

Without knowing any other details, I would start with a regression approach with the days of the week encoded as dummy variables and the timestamp as a numeric response (with the minutes going from 0 at midnight to 1439 at 11:59 pm), and run these regression models separately for each car under the assumption that their timestamps are independent.

**Comment by stoltzmr** [comment]
Thank so much Benjamin - this makes sense yes.

Regards
 Markus
