### ISSUE TITLE
Predicting with new data

### ISSUE THREAD

**Issue by tqdo** [facebook/prophet#1290]
I am curious about how to use the model to predict if I have new data. Say I train a model and get the predictions for the next 7 timepoints using the code below

````
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=7)
forecast = m.predict(future)
forecast
````

Say now I have 1 more timepoints (df has 1 more row), is there any way to use the same model to make predictions for the new `df` without retraining the model?

**Comment by bletham** [comment]
There really isn't a way to update a model with incremental data; it will have to be re-fit. There is an issue for this in #46 with discussion describing some of the challenges.

**Comment by tqdo** [comment]
@bletham Thanks for your reply. The link you commented is very helpful. But it mainly discusses about incremental training and training with warm start. I am curious whether I can use the exact same model (no incremental training) to predict new data (original data + 1 more timepoint)?

**Comment by bletham** [comment]
I see, in that case, once the model is fitted, you can make predictions for any points that you want. So
```
future1 = pd.DataFrame({'ds': '2020-02-04'})
fcst1 = m.predict(future1)
```
will make a prediction for 2020-02-04. If tomorrow you wanted to make a prediction for 2020-02-05, you would just change the date to that. Of course since the model has not be re-fit, any data that came in since the last time the model was fit would not be used for the new predictions.
