### ISSUE TITLE
how to show all month name in prophet_plot_components in R

### ISSUE THREAD

**Issue by rajnishrajput12** [facebook/prophet#1312]
I am currently seeing only January, April, July, October on x axis of prophet_plot_components in R
is there any way to show all the month name on x-axis.

**Comment by benmwhite** [comment]
The plots are [ggplot2](https://ggplot2.tidyverse.org/) objects in R, so you can use that package's layering system to make adjustments. In this case you can use `scale_x_continuous()` to [adjust the breakpoints and labels along the x axis](https://ggplot2.tidyverse.org/reference/scale_continuous.html).

**Comment by rajnishrajput12** [comment]
Hi Benjamin,

I am trying to use ggplot2 scale_x_continious. here are my steps:-

1. p <- prophet_plot_components(m, fd) ## this is the ggplot object.
2.p1 + scale_x_continuous(breaks = c('january', 'february', 'march','april','may','june','july',                              'august','september','october','november','december'))

I am getting NULL as result..
I am new to R. if you could please help me.
my prophet_plot_components(m,fd) gives me plot having 3 subplots.. so not sure how to use
scale_x_continious.
sample plot is the one which is there on https://facebook.github.io/prophet/docs/quick_start.html.

**Comment by benmwhite** [comment]
`breaks` tells it where to actually put the ticks/gridlines in the plot, so it needs to be in the exact format as the input data (in this case dates like "2019-01-01", "2019-02-01", etc). `labels` is the character vector with the actual labels ("Jan", "Feb", etc).

**Comment by rajnishrajput12** [comment]
Thanks, but still giving me NULL when i do:-

data_wiki <- read.csv("https://github.com/facebook/prophet/blob/master/examples/example_wp_log_peyton_manning.csv") ## or read this csv file.. this is same csv used by facebook to explain Prophet
m <- prophet(data_wiki,daily.seasonality = TRUE)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
plot_list <- prophet_plot_components(m, forecast)
plot_list[3] + scale_x_continuous('x-axis name change')

Actual:- i am able to extract graph using plot_list[3], but when i add scale_x_continuous.
it is returning NULL.

if you could reproduce this in you  machine with R and try changing the month name .

**Comment by benmwhite** [comment]
I made a mistake in my first post, you should be using [`scale_x_datetime()`](https://ggplot2.tidyverse.org/reference/scale_date.html) instead of `scale_x_continuous()`.

The issue with your snippet is that you should be using `[[` to extract the plot instead of `[`, with R lists the way to think of it is that `[` gives you the train car and `[[` gives you the passengers. In this case `plot_list[3]` returns a list of length one that happens to contain a ggplot object, and `plot_list[[3]]` give you the ggplot object (use the structure function `str()` to see the difference between the two). 

I was able to run this code to produce the plot with the name change in the x-axis:
```
library(prophet)
data_wiki <- read.csv("https://raw.githubusercontent.com/facebook/prophet/master/examples/example_wp_log_peyton_manning.csv")
m <- prophet(data_wiki, daily.seasonality = TRUE)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
plot_list <- prophet_plot_components(m, forecast)
p <- plot_list[[3]] 
p + scale_x_datetime(name = "x-axis name change")
```

**Comment by rajnishrajput12** [comment]
Thanks Benjamin,
thats cool,

at last i got..
library(prophet)
data_wiki <- read.csv("https://raw.githubusercontent.com/facebook/prophet/master/examples/example_wp_log_peyton_manning.csv")
m <- prophet(data_wiki, daily.seasonality = TRUE)
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
plot_list <- prophet_plot_components(m, forecast)
p <- plot_list[[3]] 
p + scale_x_datetime(breaks = (as.POSIXct(c("2017-01-01","2017-02-01","2017-03-01",
                                "2017-04-01","2017-05-01","2017-06-01",
                                "2017-07-01","2017-08-01","2017-09-01",
                                "2017-10-01","2017-11-01","2017-12-01"))),date_labels = "%b")

would give you Dec,Jan,Feb....... as x axis labesl
 the only thing is Forecast dataframe has values only till 2017-01-19. so why my plot is showing
Yearly-seasonality till 2017-12-31. but thats another question

**Comment by benmwhite** [comment]
The seasonality plot shows you estimates of the added effects across any given year, it just happens to use POSIX dates from the last year in the background data layer for the plot.

**Comment by rajnishrajput12** [comment]
Oh so that means the trend in yearly plot is for future timeframe also (say for 2019)

**Comment by benmwhite** [comment]
You can look through the original paper [(pdf)](https://peerj.com/preprints/3190.pdf) for more details, but the way it works with the default settings is that a baseline "trend" is estimated, then all the seasonal and holiday effects are added to it to produce the final fitted estimate or prediction.

So if you were predicting some time series for today, you'd start with the trend value for today, then add in the Thursday effect, then add the February 13 effect, and then any additional holiday effect that may be specified (like day before Valentines Day). After adding all these together you get your final prediction or estimate for today, Feb 13 2020.

The seasonal plots show you these effects separately from the year, since they're estimated across the entire training period (ideally multiple years).

**Comment by rajnishrajput12** [comment]
Ok Thanks a lot Benjamin
