### ISSUE TITLE
Daily Seasonality peaks makes no sense

### ISSUE THREAD

**Issue by Bartbeckers** [facebook/prophet#1316]
After modelling Facebook Prophet (with both an additive and a multiplicative seasonality mode) I get daily seasonality with a peak at 06:00 hour.

However,  since my dataset doesn't contain observations < 9:00 hour and > 22:00 hour, this seasonality doesn't make sense to me.

Does anyone has an explanation or solution for this issue?

Many thanks in advance!

**Comment by bletham** [comment]
The issue here is that when there is a period with no data (in this case, between 22:00 and 9:00) the seasonality is unconstrained in that period and it can do wonky things (because it is being fit with Fourier series, and regularization is happening in the frequency domain). There's some discussion of this in the documentation here: https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps

Generally, you'll want to remove any such points from the `future` dataframe. As long as you aren't trying to make predictions within this time period, you can safely ignore this.  There is much more discussion of this in #749, which is also an open issue to detect these sorts of regular gaps and handle them in a nicer way.
