### ISSUE TITLE
confidence intervals for constant time series

### ISSUE THREAD

**Issue by tt7533** [facebook/prophet#1321]
Consider a constant time series as below.  We can still use Prophet and forecast based on the green data points.  As expected the prediction is also constant.  But **how is the confidence interval (orange) determined** considering that there is no variation at all in the data?

![image](https://user-images.githubusercontent.com/26541376/74177398-4f49a380-4c42-11ea-81fd-bec79558c57d.png)

**Comment by bletham** [comment]
The unit for the y-axis is clipped. This is what I get:
```
from fbprophet import Prophet
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

df = pd.DataFrame({'ds': pd.date_range(start='2015-01-01', end='2017-02-01', freq='D'), 'y': np.zeros(763)})

m = Prophet().fit(df)
fcst = m.predict()
m.plot(fcst)
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/6339760/74882849-af1c0a80-5324-11ea-8d09-a594aa505a50.png)

Notice the y-axis ranges from -1.5e-9 to +1.5e-9.

The reason it isn't exactly 0 is because it comes from the Normal observation noise term, which technically must have positive variance (so it ends up being positive,  but very small).
