### ISSUE TITLE
Taking fluctuation from several years but growth trend only from last year

### ISSUE THREAD

**Issue by Ivanwang516** [facebook/prophet#1324]
Hi guys,

I have a set of data that was declining for couple of years but growing from last year, just wondering if it's possible that I take the growth trend from last year only but still make the model to fit the seasonality from previous years. Thanks guys!

**Comment by bletham** [comment]
This will sort-of happen by default. The trend is a piecewise function (piecewise linear unless using the logistic growth trend, in which case it is piecewise logistic) in which the trend changes at certain points in the history (see the illustration in https://facebook.github.io/prophet/docs/trend_changepoints.html ). The trend that is projected forward is just whatever the trend value is of the last segment. So if the trend in the model has correctly captured the trend change you've seen in the data, then the trend projected forward will be exactly the new trend from the last year. The seasonality will be fit from all years. The fact that the trend was previously decreasing will only impact the uncertainty intervals, yhat_lower and yhat_upper. Since there has been a large trend change in the past (from decreasing to increasing), the model assumes the possibility of similar trend changes in the future and so the uncertainty intervals will be wide. But the main yhat estimate uses only the most recent trend.

If what you're seeing doesn't look what you're expecting based on that description, go ahead and post the output of `m.plot` and I could give more suggestions.
