### ISSUE TITLE
Creating Optimal Capacity Ceiling for Multiple SKUs

### ISSUE THREAD

**Issue by aesler13** [facebook/prophet#1328]
High everyone,

I am new to fbprophet and python coding, so please bear with me. I am working on a project for a client where I am trying to create an optimal growth ceiling for each SKU. I currently have the code written so forecasts are made for each SKU by month. The business is very seasonal and there is high volatility among different SKUs (newly introduced items with high growth, drop off in sales due to supplier issues the year before, etc). After looking at rolled up sales by item and year, it looks as if some forecasts are off and are trying to hard to fit the linear trend. So I figured I would try logistic growth instead. The data is monthly, but they only care about total sales by the year so I have put a cap ceiling of 2019 sales multiplied by 2. But since that is at a yearly level, I am worried my monthly forecasts will over-predict. Sales can vary from July-December so some years an item will have high sales in August, and the next year it could have high sales in July and low sales in August. What is the optimal way to determine the capacity ceiling? I'm leaning towards multiplying the prior year month (t-12) by 2 because I feel as if 2019 total sales by SKU multiplied by 2 would create too high of a ceiling.

For reference of the issue I am seeing with a growing SKU trying to fit the linear trend, please see image below.

[https://github.com/aesler13/SKu-Forecasting/blob/master/Example.PNG](url)

I have also referenced my code below. If there are parameters that need to be adjusted that might improve my predictions, please let me know. I am open to any advice as I am relatively new to python, fbprophet, and git!

[https://github.com/aesler13/SKu-Forecasting/blob/master/Loop%20Forecasting%20Example%20Code](url)

**Comment by bletham** [comment]
Generally you probably don't want the cap to be changing month to month. The month-to-month fluctuations could be coming from yearly seasonality, whereas the cap applies to the trend.

The cap is the highest trend value that you think reasonable / where you think the trend for the forecast should naturally saturate. The actual forecast will be `trend + seasonality`, so the forecast can be larger than cap in places where the seasonal fluctuations are very large. You can see some of this in the example in https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth ; the uncertainty interval extends above the cap at some points due to yearly seasonality.

I'm not really sure what more concrete advice I could give; if you are able to make a post of the figure produced by `m.plot` then I could perhaps give more suggestions on how to address any issues.
