### ISSUE TITLE
plot_components Seasonality results do not match 

### ISSUE THREAD

**Issue by shoaibkhanz** [facebook/prophet#1334]
Please find the code I am experimenting with to extract seasonality manually from the data frame for plotting purposes. To my surprise, I am unable to understand the `yearly` seasonality that I get from the `plot_components` method. i.e. the yearly seasonality I observe in the data and the one I get from `plot_components` do not match.

fbprophet v 0.5
running on google collab

GitHub gist: https://gist.github.com/shoaibkhanz/4e45cae1f5f6090a7c5ec8d82eb87141

```

import numpy as np
import pandas as pd
from fbprophet import Prophet
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

df = pd.read_csv('https://assets.digitalocean.com/articles/eng_python/prophet/AirPassengers.csv')
df.columns = ['ds','y']
df['ds'] = pd.to_datetime(df['ds'],format = '%Y-%m')

#fitting the model
mod1 = Prophet(interval_width=0.95,seasonality_mode = 'multiplicative')
mod1.fit(df)

future = mod1.make_future_dataframe(periods = 36,freq='MS')
future.tail()

forecast = mod1.predict(future)

#manually extracting yearly seasonality
year = (pd.date_range(start='1951-01-01', periods=365) + pd.Timedelta(days=0))
yearly_ = forecast.loc[(forecast['ds'] >= min(year)) & (forecast['ds'] <= max(year)) ,['ds','yearly']]

#plotting figure
fig, ax = plt.subplots(figsize = (10,4))
ax.plot(yearly_["ds"],yearly_["yearly"])
plt.show()

#inbuilt plotting function
_ = mod1.plot_components(forecast)

```

**Comment by bletham** [comment]
I think the difference you're seeing is because the forecast dataframe has monthly data frequency, whereas the seasonality plot is using daily frequency:
https://github.com/facebook/prophet/blob/101dd50e3195c1875ee856cdf49ee9fcd6a87fa3/python/fbprophet/plot.py#L334

When yearly seasonality is fit to monthly data, it can behave badly for the periods in the middle of the months where there is no data. There is some discussion of this in https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data . You can see in the plot with MCMC that the seasonality is pinned down at the month starts, but then has really high variance and fluctuations mid month. There's an issue for detecting this and limiting the seasonality plots accordingly, but in the meantime (as described in that monthly data page) the yearly seasonality plot is a bit wacky with monthly data.

In the example that you give, if you take the yearly seasonality plot and extract the values just at the start of each month, it will match what you are pulling from the forecast dataframe. Similarly, if you make a forecast with daily data (replace `'MS'` with `'D'` in make_future_dataframe, and construct `yearly_` with a future year) then the yearly column forecast dataframe will look like the seasonality plot.

**Comment by shoaibkhanz** [comment]
@bletham thanks for the explanation this makes sense. Following your explanation, if we consider the yearly seasonality for monthly data which is present in the forecast dataframe, how correct are we then for this wacky behaviour? do you think it represents the right way to look at seasonality?  Are there methods that could be implemented to correct this behaviour.

**Comment by bletham** [comment]
I think the documentation here gives a fairly general description of the issue: https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps

The core of the issue is that when generating this figure, we are asking the model to make predictions for points where it had no data (mid-month for monthly data).  It can do a really bad job at predicting mid-month for monthly data. But that does not affect its ability to predict where we do have data (at the start of the month). Those predictions will be good and are reliable (as you can see in the MCMC posterior variance in the yearly seasonality plot in the documentation). The seasonality has a lot of flexibility and is only being pinned down at the start of each month, but if you only make predictions where it is being pinned down that's fine. In that case this is really just a visualization issue and you don't need to worry about it.

The alternate approach would be to use extra regressors to handle yearly seasonality. You could create 12 extra regressors (is_jan, is_feb, ....) that are 1 if it is that month and 0 otherwise. The model would then learn an effect for each month, and add it only on those days that you specify with the regressor. In this case you would disable yearly seasonality. This would allow you to see just the discrete effect of the yearly seasonality in the components plot, and I'd expect little change in the forecasted values.
