### ISSUE TITLE
Which metric should I use to choose the best model?

### ISSUE THREAD

**Issue by nescobar** [facebook/prophet#1341]
I'm using Prophet with MLflow on Spark to run hundreds of models. I've found in many cases there are models with the lowest RMSE but not the lowest MAPE. There also cases when MAPE at one day is the best but not MAPE at 30 days.  Then, there is the MAPE average across all days where the best could also be different from others.

Here is an example from three runs:
![image](https://user-images.githubusercontent.com/1939865/74851414-7cc9d780-533b-11ea-86fd-9c94081e6ca0.png)

The question is, is there any criteria to select the best metric to choose the best model?

**Comment by bletham** [comment]
I don't know that there's a "right" answer, and it probably depends on what the metrics are ultimately used for.

MAPE has an advantage in being interpretable (people have a general idea of what 5% error means). But it does have an issue that it doesn't work well for time series with values close to 0, where a very small difference can turn into a huge % error.

RMSE is nice because it doesn't have that problem (it is translation invariant, and it doesn't matter if values are close to 0). But it has downsides too; I think the interpretability is lower (if you tell someone the forecast has RMSE of 3.5, do they have a sense for what that means?). Also, unlike MAPE, it isn't scale invariant. So time series that take values in different ranges might have very different RMSEs just because of the differences in scale, which makes it more difficult to understand performance across time series.

Every metric has some issue like that. There are many posts online comparing performance metrics and ultimately it will depend on the properties of your time series and how you want to use the metric.

**Comment by nescobar** [comment]
Thanks @bletham, I was aware of some of these differences and like to use MAPE most of the time, if possible.

However, my confusion is in relation to the difference in performance across metrics. I'm expecting the best models for the same dataset to be the best across all metrics. For example, the best model using RMSE, shouldn't it be the best using MAPE as well?

**Comment by benmwhite** [comment]
@nescobar Since MAPE scales the error difference terms by the actual values then averages them all up you can get results like this if your actual values in the time series have high variability compared to the predicted error (i.e. the individual residuals are fairly cosistent . 

Ex: Your actual values are 0.5 and 1.5. If you predict 1 for both then RMSE = sqrt(1/4) and your MAPE = 2/3.  if you predict 0.75 for both then RMSE = sqrt(5/16) and MAPE = 1/2. Using RMSE the first prediction has lower error but using MAPE the second prediction has lower error.
