### ISSUE TITLE
evaluate launch effect for a couple of months

### ISSUE THREAD

**Issue by MiraLS** [facebook/prophet#1342]
Hello,
Thanks for creating the package and I really like it.
I am trying to use Holidays option to test my product launch effect with aggregated monthly data. My launch effect may last 4-12 months depending on the product. The effect size is different in each month. I am currently trying modeling the data distribution of those launch month to calculate the index for each month. I will add the estimated index as a regressor. This is pretty complicated. Is there a better way to do this? 
Thanks.
Mira

**Comment by bletham** [comment]
I think the challenge here is going to be that different products have different launch effects.

The other thing you could consider would be using binary regressors for the launch effect; have a "launch_month" that is 1 if it is the month of a launch and 0 otherwise; "launch_month+1" that is 1 in the following month, 0 otherwise; and so forth for however many months you expect there to be an effect. But this would fit a monthly launch effect that is the same for all products, which it sounds like is not the case. If you extended that to be a separate set of regressors for each product ("launch_month_p1", etc.) then it would fit separate launch effects for each product, but you'd have no way of predicting the launch effect for a future product (because they're assumed to all be totally independent). With this approach it would also be very challenging to separate out product launch effects and yearly seasonality, unless you have a couple years with no product launches.

So I don't see a clear easier way to do this under the assumptions you describe.

**Comment by MiraLS** [comment]
Thanks Ben. They are all very good points. 
Yes my goal is to predict the future outcome with a launch effect. Can you elaborate a bit more on "If you extended that to be a separate set of regressors for each product ("launch_month_p1", etc.) ..."? I may not make my launch effect clear enough. Here is an example, I have one product in market for around 2 years. We had an initiative after 2 years but we still sell it as the same product. We do see a spike which lasted around 6 months in product performance due to that initiative. Now we'd like to evaluate that initiative effect and also make prediction. If our performance data goes by day, I think we can just add an holiday effect at the starting date and then put an upper window, right? I think I didn't get what you mean by "each product"? I only have one product. Thanks. Mira

**Comment by bletham** [comment]
Thanks, I better understand what is happening now. So there is a particular initiative that you want to see the effect of. In that case, yes, making a holiday with an upper window for how long you think the effect lasted would definitely be the best approach.

My worry was that there would be many different initiatives/launches all overlapping with eachother, which would make it hard to estimate the effect of any one. But here it sounds like there is already 2 years of data prior to the initiative, so I think the model should be able to do a fine job of separating out the initiative effect vs. the pre-initiative behavior.

The alternative that I'd consider would be to make a forecast using data just up to the initiative, and then compare that forecast to the actual and the difference is an estimate of the initiative effect. If you look at the amount of error in cross validation prior to the initiative, that would be the baseline for determining how significant the effect is.

**Comment by MiraLS** [comment]
Thanks Ben. 

Mine is monthly aggregated data. Let’s say the initiative effect lasts for 8 months, how shall I set up my upper window? If I put 8, it means 8 more days from the starting point, right? 

Thanks.
Mira

**Comment by bletham** [comment]
That's right. You could set it at 8 * 30, to get the number of days.
Basically each of those will be modeled as a separate holiday effect, which is a lot of extra parameters being added to the model. You'll want to really clamp down the holiday prior scale parameter (it's default is 10, which applies very little regularization; I'd look at what 1 or 0.1 produce) to be sure that the holiday effects are being used only for what cannot be captured with the seasonalities from the prior years. The success of this would definitely rely on having a significant amount of data outside this effect.

**Comment by MiraLS** [comment]
Thanks a lot Ben. I will try to do it with 8 binary regressors  as you suggested.
