### ISSUE TITLE
Validation of added regressors

### ISSUE THREAD

**Issue by crinix16** [facebook/prophet#1345]
During linear regression classes in academia, it is taught that including trivial/irrelevant features to the model decreases its ability to predict more accurately.

For add_regressor() function, I want to know:
- Is there a way to check whether added parameter/feature actually improves the model or it's actually trivial? 
- What should I look for during the process of adding regressors to fbprophet?

Of course I prefer a more intuitive, smart way rather than simply checking the evaluation metric with and without the added regressor, since the improvement can simply be noise and cause overfitting, decreasing the ability to generalize on unseen data.

**Comment by benmwhite** [comment]
If you use MCMC estimation instead of the default then you get uncertainty interval estimates for the additional regressor coefficients. These can be used as sort of a rough "significance" check for the regressor: see whether or not the estimated uncertainty interval contains zero. See @bletham's [comment in this thead here](https://github.com/facebook/prophet/issues/1264#issuecomment-580400794).

**Comment by bletham** [comment]
I would also just note that regularization makes it much more possible to include irrelevant features without degrading the model (the model learns to ignore them). The amount of regularization on extra regressors isn't particularly strong, but if you were concerned with this you could set a prior scale for the extra regressors and then tune it using cross validation:
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/forecaster.py#L583
