### ISSUE TITLE
Weeky seasonality repeated during holidays (should minimize its effect)

### ISSUE THREAD

**Issue by iRoneyMathew** [facebook/prophet#1348]
I am trying to forecast the energy consumption for a building (a production plant). I have historical data of the past 4 years which are aggregated to have one data point for each day. So I am forecasting on a daily basis. I have tried out a lot of parameters for the model to match my case based on the documentation of Prophet.  The model performs pretty well to my needs. However I am facing problems with the forecasts during periods of holidays.I have historical data of the holidays and also for the period I'm forecasting.I'm feeding the holidays to the model as a dataframe. There are 2 major breaks in our calendar year( Summer break which is of 3 weeks and Christmas break which is of 2 weeks). In terms of adjusting the yearly trend to accommodate these two breaks, the model does well by reducing the consumption during this period. But the problem is, it also tries to fit the weekly seasonality during the holidays. So there is a huge fluctuation in the forecasts during these holidays and this makes the forecasts wrong during the holidays. I will place screenshots of the forecasts to illustrate the problem. 

yhat is the prediction and y is the actual data. 

![image](https://user-images.githubusercontent.com/45064528/75025859-36d85500-549c-11ea-8c77-ecb74c0e22a6.png)

![image](https://user-images.githubusercontent.com/45064528/75026017-799a2d00-549c-11ea-883e-727bbdeac22e.png)

![image](https://user-images.githubusercontent.com/45064528/75026050-8fa7ed80-549c-11ea-97de-813f792ba917.png)

![image](https://user-images.githubusercontent.com/45064528/75026330-152b9d80-549d-11ea-872c-bcb0318afee5.png)

![image](https://user-images.githubusercontent.com/45064528/75026374-25dc1380-549d-11ea-97d2-27fad1a35117.png)

![image](https://user-images.githubusercontent.com/45064528/75026487-591ea280-549d-11ea-8d73-23c5bcf70299.png)

![image](https://user-images.githubusercontent.com/45064528/75026527-6c317280-549d-11ea-97e1-1301008ec516.png)

An example of how the dataframe Holidays looks like 
![image](https://user-images.githubusercontent.com/45064528/75026606-8a976e00-549d-11ea-84a9-84a885aa75b3.png)

I tried removing the weekly seasonality, it still gives me decent results. But the forecast is underfitting. 
So I wanted to know if I can somehow solve this problem without getting rid of the weekly seasonality. Basically, I want the weekly seasonality to not have so much effect during the holidays.
Any suggestions would be welcome!
Thanks

**Comment by benmwhite** [comment]
Have you tried using multiplicative seasonality effects instead of additive? This way instead of e.g. "Wednesdays are always worth an extra 5k widgets above trend" it estimates something like "Wednesdays are always worth an extra 10% more widgets above trend". If your trend and holiday effects are already capturing the reduced output during your breaks then your weekly effects will be dampened over those periods as well.

**Comment by bletham** [comment]
+1 for trying multiplicative seasonality.

Otherwise, this is a situation where the shape of the weekly seasonality is different on holidays vs. not holidays, and would be a good use case for conditional seasonalities as described here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors . Basically you would disable the built-in weekly seasonality and create two new weekly seasonalities, one for is-holiday and one for is-not-holiday the same way as is done in the documentation example.

**Comment by iRoneyMathew** [comment]
Thank you very much for the suggestions.

I had tried the Multiplicative Seasonality. But it didn't make much of a difference.
@bletham  ...Conditional seasonality was exactly what I was looking for. I tried it and it works like a charm in solving the problem. I'm not sure how I missed reading that in the documentation. 
Anyway thanks again. :)
