### ISSUE TITLE
Using prior knowledge about regressors

### ISSUE THREAD

**Issue by nirvs44** [facebook/prophet#1349]
Hello! 

I have some issues with intepretation of models.
The fitted model is used as sales forecasting tool. 
Trend, holidays, seasonalities are specified well, the problems are mainly connected with additional regressors.

We know some prior business facts about additional regressors in model, at least, we can determine the sign of the regressor before the run.

For, example, **promotion periods** (encoded as binary variable) make always **positive effect** on sales, in contrast **low competitors price** **decreases our volume**.  At moment, we use grid search of two parameters: trend's prior scale and seasonality's fourier term, to maximamize the number of correctly interpreted additional regressors (about 20 regressors), after mcmc sampling.
 
It would be great if all the users have an opportunity to define sign of regressors or even prior coeffitients distributions based on prior knowledge, before fitting the model.

Or may be it is possible in current version?

Thank you for your attention!

**Comment by bletham** [comment]
I can't think of any way to do this right now. It'd be a bit challenging - this is the prior in the Stan code:
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/stan/unix/prophet.stan#L113
The challenge is that `beta` here is both the regressor coefficients and also the coefficients for the seasonality Fourier features. So you'd have to track down which column of X is being used for the regressor and change the prior just for that corresponding element of beta. I think it's going to be a real challenge.

It sounds like in your case you're finding that under some model fits, you are finding that not all extra regressors have their expected sign. I wonder how much of this might be noise. Clamping down the prior scales for the extra regressors might reduce that (see below). You could also try doing MCMC to get uncertainty estimates for the regressor effect. I suspect that for some of these instances the regressor effect will not be significantly different than 0, and that what you're seeing as the wrong sign is really just that the correct sign cannot be inferred from the data. If with MCMC you see significant regressors with the wrong sign, then it may be that the nature of the correlation is not the linear relationship assumed in the model, and in that case I'd be interested to see the output of `m.plot` and `m.plot_components` if possible.


If you are tuning parameters for extra regressors, you might consider tuning the prior scale for the extra regressors themselves, which default to the holiday prior scale:
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/forecaster.py#L583

**Comment by nirvs44** [comment]
Thank you for your answer and your attention!

1. About STAN and possibility to define sign of regressors.
In most cases, while additing new regressors, users have a prior knowledge about the sign of regressor, because people usually taking into accout some business insights on regressors used in a forecasting model (promotions, discout provided, information about competitors, weather, gross margin) and certainly know the possible effect of it. At the worst, considered regressor could be not be significantly different than 0. 
So, it would be very useful if users have such opportunity.

**Comment by nirvs44** [comment]
3. Good district (all regressors are interpreted correctly) 
![good_district x1](https://user-images.githubusercontent.com/7073039/75234729-25f54f80-57cc-11ea-8486-e53f855d6de4.png)
![good_district x2](https://user-images.githubusercontent.com/7073039/75234736-2857a980-57cc-11ea-8e41-f094dcd5a7d2.png)

**Comment by woozyandpupsy** [comment]
` beta ~ normal(0, sigmas);`
@nirvs44 
Hello! How a priori distribution will help change a posteriori? Indeed, the choice of betta can only affect the rate of convergence of the MCMC method, and not on the posterior distribution.

**Comment by bletham** [comment]
@nirvs44 Thanks for the plots, I think I have a better idea now of what is happening.

This issue isn't that the total sign is wrong (that is, the sign on beta is wrong and so positive changes in the regressor are being turned into negative changes in y), rather it's just that the regressor takes on negative values when you expect it to always be positive. Is that correct?

If so, you can't really directly interpret the magnitude of the outputs in that way. When trying to determine the effect of regressor(t) on y(t), what we care about is the sign of beta. If beta is positive, then increasing regessor(t) will increase y(t); if negative, then increasing regressor(t) will decrease beta(t).

The actual values of the regressor are actually standardized under the hood:
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/forecaster.py#L360-L364
https://github.com/facebook/prophet/blob/46e56119835f851714d22b285d2e4081853b9fb1/python/fbprophet/forecaster.py#L324-L325

So the extra regressor column isn't actually `beta * regressor(t)`, it's `beta * standardized_regressor(t)`. If beta is positive, then this will be negative any time regressor(t) is less than its mean. When it is negative, it doesn't mean that the regressor is having a negative effect on y - that's determined by the sign(beta). All it means is that the effect of the regressor is lower than its baseline, where the baseline is its mean effect. That baseline mean effect is basically what the trend is representing.

In this case did you disable standardization of the extra regressor? I'd actually expect _more_ negative values than what we're seeing here (I'd expect it to be approximately centered around 0%).

Is that accurate that the issue is just that there are parts where the component is negative when it is expected to be positive, and not that the direction of the relationship is incorrect (e.g. the peaks in the winter should really be down instead of up).

**Comment by nirvs44** [comment]
Thank you for your guess! We have already set standartization to **False** for external regressors like percent of discout, for example.

We have negative effect and it is significantly different than 0 for **binary promo regressors**, 1 or 0 for every date in dataset. The negative effect should be distributed between other regressors, trend, or residuals, not promo period regressor.

**Comment by bletham** [comment]
I don't know that I have any other ideas. One possibility is that if there is a large number of extra regressors there could be an issue of multicollinearity, where some of the regressors may be correlated with eachother (there does seem to be yearly seasonality in the regressors). This isn't a significant issue for prediction (quality of the forecast), but it can make it difficult to interpret the regression coefficients. For instance, maybe the yearly seasonality is capturing some of the positive regressor effect. In some years, maybe the actual effect of the regressor is positive but less than in other years, and so the model ends up fitting a _negative_ coefficient to the regressor to counteract the positive effect that is already baked into the yearly seasonality. That's just an example of how correlated regressors can produce coefficients with the wrong sign. For a more artificial example, suppose we have two regressors x1(t) and x2(t) that are actually equal to eachother, and the true coefficients are each +1. The model can fit `+3 * x1(t) - 1 * x2(t)` and this is equivalent to the true values, but potentially confusing because x2(t) has a negative sign when we may know that it should be positive; but what is happening is that its effect is also being captured by x1(t). Normally with MCMC I'd expect that the posteriors should reflect this and should cover 0, which it sounds is not the case for all of the effects. It could just be that the MCMC isn't fully converged / mixing well, but there could also just be model misspecification. In terms of what to do to get the desired coefficient signs here, I don't think I have any good suggestions.

Enforcing the sign of the coefficient in model fitting would require identifying the desired positive or negative columns and passing that up into the Stan model, where they'd have a HalfNormal prior instead of Normal, which is going to be a bit complex.
