### ISSUE TITLE
Install error "SyntaxError: invalid syntax" (Python2 no longer supported)

### ISSUE THREAD

**Issue by springster** [facebook/prophet#1350]
Hi,
I am trying to install fbprophet on MacOS Catalina 10.15.3, but I am getting an error as below:

_ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-S11Lcd/fbprophet/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-S11Lcd/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-install-S11Lcd/fbprophet/pip-egg-info
     cwd: /private/tmp/pip-install-S11Lcd/fbprophet/
  Complete output (6 lines):
  Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/private/tmp/pip-install-S11Lcd/fbprophet/setup.py", line 30
    def get_backends_from_env() -> List[str]:
                  ^
  SyntaxError: invalid syntax_

I already installed cython and pystan, but I am still unable to resolve this. Any suggestions?

**Comment by bletham** [comment]
The issue is that it is installing in python2.

We just pushed a new version of fbprophet to PyPI, and it is Py3 only. This was part of enabling cmdstanpy as a backend, but Python2 is deprecated as of Jan 1 and should not be used anymore: https://www.python.org/doc/sunset-python-2/

So switching to py3 is ideal. If you need to use fbprophet with py2 software that has not yet been updated to py3, then use version 0.5, which is the last that will support py2

```
pip install fbprophet==0.5
```

**Comment by springster** [comment]
Thanks beltham.. I eventually ended up using v0.5 of fbprophet. Will soon move to Py3 for this project and update.
