### ISSUE TITLE
Uncertainty interval does not grow with missing data

### ISSUE THREAD

**Issue by tt7533** [facebook/prophet#1354]
This toy example consists of two parts separated by a long interval without data.  Basic usage of Prophet generates the following predictions.   
```
df1 = pd.DataFrame({'ds': pd.date_range(start='2015-01-01', end='2015-03-01', freq='D'), 'y': np.random.rand(60)})
df2 = pd.DataFrame({'ds': pd.date_range(start='2015-06-01', end='2015-08-01', freq='D'), 'y': np.random.rand(62)})
df = pd.concat([df1, df2])
m = Prophet(mcmc_samples=1000).fit(df)
fcst = m.predict()
m.plot(fcst)
plt.show()
```
![tt](https://user-images.githubusercontent.com/26541376/75094870-b3039300-5597-11ea-8a44-f82850a0e09a.jpg)

There are 2 aspects that seem to come out strange:
1. the uncertainty interval does not grow symmetrically during the time period without data as would be expected...  Note that this happens also with MCMC sampling.  In picture, we would expect something more like the plot below:  when there are less data points on the right side, the uncertainty grows in both directions up/down

![ex](https://user-images.githubusercontent.com/26541376/75094968-a7fd3280-5598-11ea-85e7-1d4df5018276.jpg)

2. in the parts where there is data, the uncertainty interval jumps around when we would have expected smooth behavior...

**Comment by bletham** [comment]
In this model, the primary source of uncertainty growing into the future is future trend uncertainty. This is described in the documentation here (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend) but in short, trend changes in the future are simulated with the same frequency/magnitude seen in the history, and the uncertainty interval is the distribution of trends across those simulated trend changes.

This simulation is only done looking into the future. If you're interested, the simulation happens in this function:
https://github.com/facebook/prophet/blob/8c48f5b0429d127f6243110ff13f61a322cbf227/python/fbprophet/forecaster.py#L1429
and you can see in there that these new, simulated changepoints are only placed after the last date in the history (which is t=1 in the way the model scales time).

In principle this same process could also be done looking backwards in time but since forecasting is pretty much always into the future, we didn't worry about handling cases other than looking forward in time.

Doing this type of simulation for a gap like in this example would be quite a bit more complicated. When simulating into the future, we can draw all of the future rate changes as being i.i.d. But if we have to simulate trend changes within a gap, the trend would need to match on _both_ ends, and so the trend change magnitudes would no longer be independent. I suspect this simulation would have to be folded into the MCMC somehow; unfortunately I don't think there will be an easy way to do this.

As a minor side note, you may know this already but in case not, when you call `predict()` like that it evaluates the model on the training data points, which means it actually isn't evaluating the model at any point between 2015-03 and 2015-06. The line being plotted there is just matplotlib connecting the forecast values between those two dates. If you instead call predict on a dataframe that you construct that contains all days between 2015-01 and 2015-08, you will see the model predictions for the dates in the gap. The uncertainty will still not grow in the center of the gap, so this is not the source of your issue here, but what you will see change is that the model will predict the weekly seasonality on the dates in the gap. So the forecast is not actually be constant in the gap.
