### ISSUE TITLE
Can't install R Package - "Malformed" error

### ISSUE THREAD

**Issue by ctn9** [facebook/prophet#1355]
When I try and install the R package, this error appears:

```
> install.packages('prophet', type="source")
Error in install.packages : Line starting '<!DOCTYPE HTML PUBLI ...' is malformed!
```

I have tried different CRAN mirrors, and it is always the same error.

**Comment by bletham** [comment]
I'm not exactly sure what is happening but my guess is that there is either a redirect (repo list is stale?) or a proxy that is returning HTML instead of the package.

Could you specify the repo in the command like this?
```
install.packages("prophet", repos="https://cloud.r-project.org")
```
Alternatively maybe try installing from github?
```
devtools::install_github('facebook/prophet', subdir='R')
```

Otherwise I think you'll have to see what that HTML that it is downloading says.
