### ISSUE TITLE
Using future known values to adjust forecast

### ISSUE THREAD

**Issue by jwang-gtech** [facebook/prophet#1358]
Hi there, 

I am trying to forecast customer cancellation $ amounts and would like to use future known values to adjust my forecast. 

For example, if today is 2/1 and a large customer has given notice that they will cancel on 3/1, how would I adjust the forecast to show a higher forecasted cancellation amount for 3/1?  

I did read through this post that discussed a similar issue where @bletham gave a great answer (https://github.com/facebook/prophet/issues/1000) but was wondering if there were other options besides adding a regressor for "cancellations booked at least 1 month ago" for each day. Would I be able to add this in as a custom holiday effect and adjust the magnitude of the effect? 

Thanks

**Comment by bletham** [comment]
To be sure I understand clearly the problem, there is a time series y(t) that is how much cancellation happens on day t. Sometimes cancellation will be scheduled in advance, and we want to improve our forecast for t using the fact that we already know some lower bound for y(t). If a large cancellation is scheduled for day t, then that lower bound would be much higher than usual (maybe even higher than y_hat(t)) and so we'd want to adjust y(t) accordingly.

This does seem pretty similar to #1000. Could this be handled with a holiday effect - I think the challenge here is that the forecast y_hat(t) has baked into it the possibility for large cancellations. Suppose as in your example it is currently 2/1 and we know that there will be a cancellation of amount z on 3/1. If I take the forecast y_hat(t=3/1) and just add z to it, that might over-estimate the actual effect, because some of that z cancellation was probably already being expected by the model. The setting here is that z is bigger than usual, but we'd need to know how much bigger than "usual" in order to know the correct amount to add to y_hat(t=3/1). This could become challenging especially if there is some yearly seasonality in these large cancellations, then the model would forecast would already be expecting some large cancellation from that, and so directly adding the amount of cancellation would overestimate.

If you do know the incremental increase, then sure, you could just directly add it to the effect on y_hat(t=3/1); that would be equivalent to creating a holiday with specified magnitude. But that seems unlikely to me.

You could try to estimate the incremental effect of these "bigger than usual" cancellation orders using a holiday (Or, equivalently, a binary extra regressor, which under the hood is handled in the same way as a holiday). You could try creating a regressor that was "scheduled_cancellation_more_than_X_amount" where X is some big enough number that this isn't happening all the time (where it would be impossible to disambiguate from seasonalities). It would be 1 on days that had these pre-scheduled large cancellations, and 0 otherwise. The model would then learn some positive effect for these dates, and that effect would be the incremental increase on t from having a large scheduled cancellation at some point in advance.

So for 3/1, when I was making a forecast in Jan it would be set to 0 for 3/1, but then on 2/1 when the large cancellation order came in, the regressor value for 3/1 would be changed to 1, and it would now have the positive effect.

Whether or not this will work will really depend on how often these large cancellation events occur, and how consistent the incremental effect of them is. If you had one of these every week, then I'd expect that a lot of the weekly seasonality will start to be captured by this cancellation regressor Does that make sense why that would be the case? Basically this is the true underlying source of the weekly seasonality, and so if we give it to the model, it will use it instead of just tracking the week-to-week patterns. This would be bad because it would hurt the farther-out forecasts where right now weekly seasonality is able to capture some expected effect, which now we wouldn't be able to get until the large cancellations started coming in. On the other hand, if they don't happen very often or if the incremental effect is very heterogeneous, then it might not be able to learn a consistent effect of the scheduled cancellation on y_hat.

The next step above this would be instead of a binary extra regressor, have it still be 0 if there is no pre-order less than X, but allow it to be the actual value of the pre-order if it is greater than X. This might help a bit if there is a lot of heterogeneity in the incremental effect due to the actual amount of the cancellation.

If you do try this, I'd be interested to hear how it goes, but otherwise I think that's the best I can come up with!
