### ISSUE TITLE
Error pickling Prophet objects in Python 3.6.

### ISSUE THREAD

**Issue by arnaudvl** [facebook/prophet#1361]
Attempting to pickle a Prophet object in Python 3.6 (3.6.10 to be precise) results in the following error:

`TypeError: can't pickle _thread.RLock objects`

Snippet to reproduce the error:
```python
from fbprophet import Prophet
import pickle

with open('test.pickle', 'wb') as f:
   pickle.dump(Prophet(), f)
```
Trying to save with dill also does not help. The error does not occur in Python 3.7.

**Comment by Gcav66** [comment]
I'm seeing the same behavior

**Comment by bletham** [comment]
I was able to reproduce this. It happens in fbprophet==0.6 but not fbprophet==0.5. v0.6 changed the Stan interface to enable using cmdstanpy, and this refactoring seems to be the source of the issue. There is now a class PyStanBackend:
https://github.com/facebook/prophet/blob/952b5449285abbd1ecf655dd8ef3bb782609b077/python/fbprophet/models.py#L198
an instance of which is attached to the Prophet object:
https://github.com/facebook/prophet/blob/952b5449285abbd1ecf655dd8ef3bb782609b077/python/fbprophet/forecaster.py#L152

That is the object that cannot be pickled:
```
import logging
from fbprophet.models import PyStanBackend

logger = logging.getLogger('fbprophet')
b = PyStanBackend(logger=logger)

with open('test.pickle', 'wb') as f:
   pickle.dump(b, f)  # FAILS with error
```
The issue is that the stan backends are storing the logger as an attribute:
https://github.com/facebook/prophet/blob/952b5449285abbd1ecf655dd8ef3bb782609b077/python/fbprophet/models.py#L21

and you can't pickle loggers. So this works to pickle the  backend.
```
b.logger = None
with open('test.pickle', 'wb') as f:
   pickle.dump(b, f)  # WORKS
```

**Workaround:**
Wipe the stan backend logger object prior to pickling.

```
m = Prophet()
m.stan_backend.logger = None

with open('test.pickle', 'wb') as f:
   pickle.dump(m, f)
```

(Or, of course, upgrading to Py 3.7 is a workaround, for those for whom this is possible).

**The fix:**
I can't think of any reason why the logger would need to be stored on the backend, so we can just remove that and instead use a logger defined in that file, something like `fbprophet.models` as is done for plotting here:
https://github.com/facebook/prophet/blob/952b5449285abbd1ecf655dd8ef3bb782609b077/python/fbprophet/plot.py#L16

**Comment by JArturoHReyes** [comment]
I got the same error before `TypeError: can't pickle _thread.RLock objects` after putting `m.stan_backend.logger = None` I get this error `AttributeError: 'NoneType' object has no attribute 'warning'`

**Comment by bletham** [comment]
Built-in json serialization is now pushed out in v0.7 and should be used instead of pickle as described here: https://facebook.github.io/prophet/docs/additional_topics.html#saving-models
