### ISSUE TITLE
Recommended approach for interpreting a log model with additive seasonality

### ISSUE THREAD

**Issue by seanyboi** [facebook/prophet#1363]
We want to be able to interpret the impact of each component on the final output of the model. 
We are finding this less intuitive since log transforming our data and were hoping you could offer some guidance please.

We understand the math to be the following:
``` 
ln(y) = trend + weekly + yearly + weather
y = exp(trend + weekly + yearly + weather)
y = exp(trend) * exp(weekly) * exp(yearly) * exp(weather)
```

In a regular additive model we can easily see the impact of each component on the output but with the above equation it is a bit less clear. 

With an additive model we interpret the output as:
```
trend = 2000
weekly = 1000
yearly = 1000
weather = 250
y = 2000 + 1000 + 1000 + 250 = 4250
```

With a log model we interpret the output as: 
```
trend = 85
weekly = 25
yearly = 2
weather = 1
y = 85 * 25 * 2 * 1 = 4250
```

From the above additive model it is clear to see the absolute effect of each component but more tricky to work out the absolute effect of each component in the log model. Is this a limitation of the log transformation or is there a way we can still maintain the interpretability?

**Comment by bletham** [comment]
I think the best way to interpret this is as being a % change.
 
Let's say it's just trend and yearly seasonality. trend=90 and yearly=1.5 would mean that yearly seasonality has pushed y to be 50% higher relative to the baseline (which is trend=90 and yearly=1). similarly, yearly=0.3 would mean that the seasonality is pushing things to be 70% lower.

Adding in additional factors the interpretation is mostly the same, except the factors all combine on top of eachother. So if we have

y = trend * weekly * yearly * weather , and
trend = 100
weekly = 1.05
yearly = 0.95
weather = 1.20

we have that (on a baseline of 100), weekly has a +5% effect, yearly has a -5% effect, and weather has a +20% effect; all of which combine multiplicatively. So you can't establish an absolute effect of each component, but you can express the relative effect like this.

Does that seem reasonable / answer the question?

As a sidenote, why are you using a log transform? Is it because of lognormal noise?

**Comment by seanyboi** [comment]
I completely agree that expressing the relative effect may be the way we have to move to. But the problem we feel we will have with interpreting it as being a percentage change is that clients may believe weather is responsible for 50% of y for that day where in fact is it responsible for less. Also as we are already displaying the absolute effect of our additive or multiplicative models we feel it could be a step back in terms of interpretability.

We have some math that follows ratios and proportion rules but would love some clarification on it please.

```
If we predict y = 6375 using log transforming where:

trend = 85
weekly = 25
seasonality = 3

Adding those together = 113

Then we divide the predicted y value by 113 to show the weighting of each component = 56.42

Then multiplying each component by 56.42 to show their absolute value? (This is what we are not too sure on)

trend = 4795.35
weekly = 1410.5
seasonality = 169.26

y = 4795.35 + 1410.5 + 169 = **6374**

```

The reason for log transforming is because some of our data is quite skewed and noisy as you stated. With some models when we compare our results with and without log transform we see better results with the log transforming.

**Comment by bletham** [comment]
I see, so that is basically computing an additive component for e.g. weekly as being
```
weekly_add_comp = weekly * ( y / (trend + weekly + seasonality))
```
That does definitely convert things to being additive, though I'm not really sure how to interpret what that is doing. Thinking about just 2 components, if I have trend=1000 and seas=1.1 and they are multiplicative, then my normal intepretation would be that seasonality is giving a 10% boost (albeit relative to the baseline of "seas=1.0", which may be an arbitrary / not-intuitive baseline), which amounts to 100 units. In any case, y = 1100. If I compute
```
trend_add_comp = trend * (y / (trend + seas)) = 1000 * (1100 / (1000 + 1.1)) = 1098.8
seas_add_comp = seas * (y / (trend + seas)) = 1.1 * (1100 / (1000 + 1.1)) = 1.2
```
which pretty substantially shrinks the relative importance of the seasonality.

**Comment by seanyboi** [comment]
That's a very valid point I had not considered.

From the above, do you know what the best approach is to calculating the absolute effect of our log model?

**Comment by bletham** [comment]
I'm not sure I have any great ideas. I think what I would try would be to set a "baseline" value for each component (for instance, if weather is temp in deg F and typical temp is 70, then I'd set that as my baseline), and then for each component measure what the current y_hat is, vs. the y_hat if that component were set to its baseline. So if temp is 80, then I'd measure the difference in y_hat when temp is 70 vs. 80 while other components are fixed, and then say that is the estimated change in y due to weather being 80 instead of baseline of 70. Similarly, for yearly seasonality maybe baseline is April, and we can say this is the change in y_hat from it being Aug instead of April. Now all of these deltas are not going to add up to the total y, but I think that they do individually represent what we're trying to identify.
