### ISSUE TITLE
Extra regressors: should they be made stationary before adding to the linear part

### ISSUE THREAD

**Issue by NikkiDakota86** [facebook/prophet#1375]
Thank you very much for the wonderful Prophet package. I find it very useful for my research. 
I had a couple of questions on adding additional regressors in Prophet and I would be very thankful if you could please give me some pointers: 
Lets say my data has 4 columns: [ds(date), y(some demand), temperature, wind]

Question:
If I were to consider temperature and wind as my extra regressors, both of which exhibit different kind of behavior: (a) temperate has nice yearly seasonality similar to my y (some demand) column while (b) wind might be random data. 

For example, imagine the demand is "like" a sinusoidal function and the temperature is also "like" a sinusoidal function where as wind is like a random component. 

What kind of pre-processing should be done to these regressor columns before adding to Prophet model. Should I explicitly de-trend and de-seasonalize them? Should I some how construct a composite weather variable and de-trend and then use that as a regressor?

They both exhibit different kind of behavior and adding them to the linear part of the model does not seem right. Any insights on this are appreciated.

**Comment by bletham** [comment]
De-seasonalizing and de-trending regressors should not be necessary. Temperature will clearly have some yearly seasonality in it; but if that is a driver of the yearly seasonality in the time series, then leaving it in the extra regressor allows the model to learn that, and then the yearly seasonality component in the model will just have to capture whatever is left over. De-trending could be bad because suppose the average temperature in a year is higher than in another year and that affects demand for the entire year; de-trending will break that relationship.

This question came up in #1144, and on that particular time series de-trending and de-seasonalizing the regressor increased the predictive error (as measured with cross validation). You could try that here too to see for this time series what the effect is, and if you do please report back the results :-)

**Comment by DivJ** [comment]
I am using box-cox transformation on my regressors as well as target variable. Does it makes sense?

**Comment by bletham** [comment]
Box-cox can make sense if you have a lot of skew in the noise distribution; but if your noise distribution is fairly symmetric it probably isn't necessary. Boxcox does make it more difficult to interpret the components, as I described here https://github.com/facebook/prophet/issues/647#issuecomment-413027578
