### ISSUE TITLE
Prior distribution for holidays

### ISSUE THREAD

**Issue by dhkim125** [facebook/prophet#1377]
Can someone provide more information on how exactly does the prior distribution, κ ~ Normal(0, ν^2), changes the forecast. From reading the paper, I understand that κ is the corresponding change in the forecast (positive or negative change) for the holiday that is determined by the indicator function. However, how does prophet know if that change is positive or negative for a given holiday? For example, when talking about business transaction volume, Black Friday would indicate a large positive κ as sales are increased but New Years Day would indicate a large negative κ as everyone is home enjoying the holiday and not shopping. Any details regarding how the model is able to distinguish between these two changes would be appreciated!

For further clarification: since κ (the change in forecast due to holiday) is centered around 0, how does Prophet ensure certain holidays always have positive change and other certain holidays always have negative change?

**Comment by bletham** [comment]
There isn't any place that specifies whether the fitted effect should be positive or negative (see #1144 which is on that question). So what will happen is just whatever provides the best fit for the model (minimize mean squared error, with some regularization). If on Black Friday there is a positive spike in the time series relative to what was predicted by the model without the holiday, then a holiday effect will reduce mean squared error. So it's just all about what provides the best model fit. Does that answer your question?

**Comment by dhkim125** [comment]
Thank you @bletham for the reply! I am still unsure of how the minimizing MSE process works with the holiday effects. My main point of confusion is that since κ is normal with mean 0 and variance defined by holiday_prior_scale, at each holiday (as defined by the indicator function), κ can be a positive value or negative as sampled from the normal. How does the minimizing MSE affect that selection of κ? Would it be through adjusting the prior scale?

**Comment by bletham** [comment]
The normal distribution is the prior for kappa. During model fitting kappa is set to the value that maximizes the log posterior, which means maximizing log likelihood plus log prior.

The log likelihood for this model is the squared error (this is because of the assumption of Gaussian noise). The log prior will penalize values of kappa that are far from the prior mean (0). How large kappa can get before it is penalized depends on the variance of the prior (holiday_prior_scale). If that is very large, then kappa will be unrestricted and kappa will effectively be chosen as whatever minimizes squared error. If that is very small (let's say, 0.1), then a large value of kappa (let's say +/-10) would have 0 probability under that prior, and so it will force the model to choose a smaller value for kappa.

The default value for holiday_prior_scale is 10. Because the data are normalized in model fitting, 10 means basically any value of kappa is reasonable, and it will be chosen just as whatever minimizes squared error. If you were to change that to 0.1, then it would force the fitted holiday effects to be smaller, even if it comes at the cost of a small increase in squared error.

MAP estimation with this model (Gaussian likelihood plus log prior) is mathematically equivalent to "ridge regression" (regression with an L2 regularization term), where the holiday_prior_scale is the inverse of the regularization coefficient.

If you're interested in a mathematical description of this, I actually wrote up some notes on this a while back (Section 2.3 in http://lethalletham.com/Letham_bayesian_analysis.pdf), or I'm sure there are many other posts online describing priors in the context of regression.

I hope that makes things more clear?

**Comment by dhkim125** [comment]
That clarifies things a lot! Thank you.
