### ISSUE TITLE
Addictive or Multiplicative?

### ISSUE THREAD

**Issue by andrewng88** [facebook/prophet#1382]
![image](https://user-images.githubusercontent.com/44232530/76157527-e1ab6d00-6144-11ea-9601-fc9c155ded97.png)

I ran with additive and managed to obtained around 0.3 MAPE.
parameters used

'additive'
initial = '270 days' 
period = '30 days'
horizon = '90 days'
changepoint = 0.1

![image](https://user-images.githubusercontent.com/44232530/76158430-a878fa00-6150-11ea-8272-9db70e40e408.png)

It's the sample dataset. Addictive most of time but post September there is some slight multiplicative component. 

Questions:
1) would it be ok to use addictive? Thanks
2) MAPE of 0.3 is it normal for daily forecasting?
3) Perhaps doing weekly would be better since higher chance it has lesser noise. and in order to look ahead for 3 months, i'd use 3 x 4 = 12 weeks?

Thanks

**Comment by bletham** [comment]
1. I suppose you could try them both and see which is working better, and if additive is giving a better forecast then going with that makes sense. The only thing I'd consider is that if the seasonality seems more multiplicative later in the history, then the later part of the history might be more indicative of the future and so it'd be better to use multiplicative if it fits that later part better.

2. It really depends entirely on the time series, and how much natural variation there is. In this case the model seems to be doing an OK job. There are two things that might improve it. The first is that it seems to be missing that sharp trend change early on. If you loosened up the changepoint prior scale then that would allow the trend to be a bit more flexible and would probably capture that better. The default is 0.05, and it looks like you tried with 0.1; maybe try 0.5 too. The second thing is that it looks like the noise is positively skewed; the model is overestimating on lower values but underestimating on higher values. When you have positive skew like this, you might be able to improve the forecast with a log transform. So, take the log of your `y`, fit a model to that, make a prediction, and then take the exp() of that prediction to return it back to the original values. If you do this then you would definitely want to use additive, because additive on log transformed data is equivalent to multiplicative in the original space. You could try and see if that improves your forecast error.

3. If you only care about making predictions at the weekly level, then yes, aggregating the history at a weekly level would likely reduce the variance and allow for more accurate predictions. But if you need to predict at the daily level, then this is the way to do it.

**Comment by andrewng88** [comment]
Hi Ben, 

Thanks for your reply.

Apologies for the late response.

As per your suggestion, I did a np.log. I assume if the scenario is negatively skewed. We can still apply np.log ? 

![image](https://user-images.githubusercontent.com/44232530/77138194-02ac8000-6aac-11ea-84bf-c013dd7d3fd5.png)

![image](https://user-images.githubusercontent.com/44232530/77138365-c9c0db00-6aac-11ea-98f6-c15c444dad3e.png)

I understand that I can reverse the log but how do I compare the validation MAPE as they are of different scale with the ones that I didn't log?

1) Sidetrack, will box-cox transformation help too as it helps to fit TS better?
2) I did try no log with removing outliers outside of 2 s.d and impute with None. And the MAPE improved from 30% to 20% .
3) I did try re-sampling it to weekly ( no log ) but the MAPE is the same as daily hence, might as well just use daily.

Thank you and have a nice weekend.

**Comment by bletham** [comment]
Computing MAPE with log transform: What you'll want to do is take the cross validation dataframe that is returned by `cross_validation`, and then apply the reverse transform (`np.exp`) to the columns `yhat`, `yhat_lower`, `yhat_upper`, and `y`. Then when you pass that into performance_metrics it will be computing it on the correct (original) scale.

Box-Cox could also help with the skewed noise, and I think would be along a similar line as the log transform. The cross validation would happen the same as with the log transform.
