### ISSUE TITLE
How to deal with different timeframe in a time series

### ISSUE THREAD

**Issue by ruben-rosa** [facebook/prophet#1393]
Hi All,

I got time series from 2016 through 2019.  The time series from 2016 through mid 2017 is monthly and from there is daily.  How can I deal with this time series in fbprophet?  Should I ignore the monthly data and predict the daily ones or resample it to monthly.  The business wants weekly.

Thanks for the valuable feedback.

Ruben

**Comment by bletham** [comment]
I assume the monthly data means that each point is an aggregate for that entire month? In that case you should not mix the monthly and daily data, since they are describing different quantities. Given that hte business wants weekly forecasts,  I think there are basically two things you could do.

(1) Take only the daily data, use them to make a daily forecast. Then aggregate that forecast into a weekly forecast.

(2) Take only the daily data, aggregate them to weekly, fit a model to the weekly data and then directly make a weekly forecast.

Option (2) will likely reduce the variance in the history (by aggregating across days) and so I would expect would give you a better forecast with lower uncertainty.

The benefit of Option (1) is that if you have holidays that are in different weeks from one year to the next, this will be directly handled (since the forecasting is being done at a daily level) whereas with (2) you would have to manually add holiday effects to the point in the history that represents the week containing the holiday. So I'd probably try them both, and see if (2) is doing a lot better than (1) other than around holidays, you can easily fix that.

**Comment by ruben-rosa** [comment]
Thanks a million Ben.  I will try your suggestions!! Really appreciate it

Ruben,
