### ISSUE TITLE
Quadratic growth?

### ISSUE THREAD

**Issue by TomKealy** [facebook/prophet#1406]
Is it possible to add quadratic growth to a prophet model?

We are trying to forecast a new regime where, after a changepoint, the growth rate rapidly chagnes from linear to something looking like a quadratic/sigmoid growth regime.

Is it possible to add this in prophet?

**Comment by bletham** [comment]
If you use the logistic growth trend and set a cap that is something like twice the maximum value in your data, you should see a sigmoidal growth (the early state is sigmoidal, https://en.wikipedia.org/wiki/Logistic_function). But that's the best you could do for now.

There is an issue for using custom trend models in #705, but the plan was to do that after moving the prediction code into Stan (#865), which we have since decided not to do after all. The challenge is that the code for the trend is in both the Stan and the Py code, so modifying the trend means making changes in both places. And in the Py, it's handled in a few different places (`if trend=='logistic'...`). To make it reasonable to add custom trends we'll want to do some refactoring in the Py to make a single point where trends can be specified. It's on the todo list, but it's likely going to be some time.
