### ISSUE TITLE
Why do we need to fit the model before doing cross validation ?

### ISSUE THREAD

**Issue by c3-VincentBrisse** [facebook/prophet#1409]
If I understand correctly, when doing cross validation, Here's how the cross-validation works:
- the model is first trained on the first `initial` data points in the Time Series
- the model predicts the next `horizon` data points
- the model is trained on the first `initial + period` data points.
- the model predicts the next `horizon` data points

If that's how the model behaves, why does it need to be `.fit()` first ?

**Comment by bletham** [comment]
Good question. It's because during cross-validation, attributes of the model that are automatically set are all fixed at what their values are for the full time series. As a concrete example, consider yearly seasonality. If that is left to its default setting of 'auto', then the behavior is to turn it on if there is >= 2 years of data, and off otherwise. Suppose I have 2.5 years of data and I'm doing cross validation. The way it currently works is that all of the CV predictions will have yearly seasonality enabled. If we did not copy that over from the final model, then yearly seasonality would be set differently for some cutoffs (cutoffs before 2 years would have it off, those after 2 years would have it on). The general idea is to cross validate the particular set of model components that will be used in the final prediction, rather than what would have been used if the only data I had were up to cutoff. Similarly, stan fitting parameters can be passed along to `fit`, and the CV will make sure that each fold gets the same fit kwargs as the full model fit.

An example of where this could matter a lot would be if you had exactly 2 years of data. When you fit all the data, you make a forecast that includes yearly seasonality. But if cross validation just fit with the usual auto behavior, none of the CV estimates would include yearly seasonality. So the CV estimates wouldn't well reflect the actual model that we're trying to cross validate.
