### ISSUE TITLE
Quarterly data reported in Quarters

### ISSUE THREAD

**Issue by AlanORB** [facebook/prophet#1413]
Hello, i have data which is something like

2018-1st Quarter
2018-2nd Quarter
2018-3rd Quarter
2018-4th Quarter
2019-1st Quarter

and im trying to fit a model for that. Already done month and yearly data! 
How should i proceed? i dont know how to do a "Date" column which could be read with periods and freq

**Comment by bletham** [comment]
Like with monthly or weekly data, you could just give each point a date that is the first day of the quarter, like
```
    ds       |   y
'2018-01-01' |  20.1
'2018-04-01' |  25.2
'2018-07-01' |  19.8
```

Though with quarterly data, I'd expect that you'll need quite a few years worth of data for the model to do anything interesting; If only since 2018 that will be a total of 9 datapoints, and Prophet is just going to fit a simple line. You would also want to disable yearly seasonality and instead model seasonality with a binary extra regressor for each quarter ("is_Q1", "is_Q2", ...) as described here for monthly data: https://github.com/facebook/prophet/issues/1168#issuecomment-542859810

**Comment by AlanORB** [comment]
That makes sense! actually i got only 24 points of data (20131-20184) and i coded something that gave me results, so now im waiting to see how that goes.
Also, i will have some readings on seasonality because i was ignoring their effect so, time to work.
Thanks!!
