### ISSUE TITLE
Threshold in linear model

### ISSUE THREAD

**Issue by aasi24** [facebook/prophet#1417]
I want to apply a threshold like upper and lower limits (prediction values outside of these limits should map within them). Logistic models have the opportunity to use cap and floor values but in the case of linear I am not getting any suitable parameters. So does fbprophet provide this functionality to apply upper and lower threshold in case of linear models?

**Comment by bletham** [comment]
No, the linear model doesn't have any sort of saturation in it. Have you tried the logistic model for your particular application and is there some aspect of it that doesn't work for you?

The alternative would be to just manually threshold the `y_hat` predictions in the forecast dataframe.

**Comment by aasi24** [comment]
Thanks ben,

I am forecasting the data of sensors that come in continuous values, applying logistic on continuous data doesn't make any sense to me. So I will try the alternate way btw thanks for the help.

**Comment by bletham** [comment]
Just to make sure there isn't a misunderstanding here - the use of the logistic function here is entirely different from the logistic function used for binary classification in ML. It is not used to squash data into binary classes, rather everything is still continuous but just saturates on each end. See the plots in the documentation here for examples: https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth

**Comment by aasi24** [comment]
Thanks Ben,

I have used logistic regression and it shows very great results but there is a problem that "cap" and "floor" values in some cases are not being respected, I am using per 10 minutes data for prediction but some values are coming out from the floor and cap values.

As reference I am sharing a screenshot.

![C2](https://user-images.githubusercontent.com/37794664/80474007-65712100-8960-11ea-8f0c-d667c8d63918.JPG)
![C1](https://user-images.githubusercontent.com/37794664/80474030-6c982f00-8960-11ea-9d4a-3f5ccbf396b1.JPG)

Please tell me what I am doing wrong over here?

**Comment by bletham** [comment]
Thanks, I see better now what is happening. The cap and floor for the logistic model are all about the trend; it forces the trend to saturate. The seasonal fluctuations on top of the trend can still go above/below those thresholds. These time series are basically all seasonality, and the trend is flat. The top 1 got a really bad it; I'm not exactly sure what happened here, but I'd expect that using the linear trend would probably work better there. The fit for the 2nd is overall OK, and the fluctuations below 0 are due to seasonality; you could just clamp those to 0. So, for a time series like this, I would try using default linear trend, and then just clamp the forecast to 0 and whatever the max value is, and that's probably about the best that Prophet will be able to do here.
