### ISSUE TITLE
Interpolation in predictors' values

### ISSUE THREAD

**Issue by aasi24** [facebook/prophet#1418]
Some of my predictors contain None value and these are other than timestamp, how can I interpolate it by using FBProphet?

**Comment by bletham** [comment]
If I understand correctly, there are rows in your history dataframe that have a `ds` but have None for their `y`. And you want to get a prediction for the `y` value at these missing points in the past. Is that correct?

If so, you should leave those rows in the dataframe when you pass it into the model for fitting. Then, do
```
future = m.make_future_dataframe()  # With no args will makes predictions for the history
fcst = m.predict(future)
```
`fcst` will contain an estimate `yhat` for all of the rows in the history dataframe, including those that didn't have any data. So just lookup those dates in `fcst` and you'll see the estimate.

**Comment by aasi24** [comment]
Thanks for your ben, actually I am using the term predictor in a sense of independent variable, that we use to predict the dependent variable.

Let's take an example of linear regression, we have the equation for it 
                    y = mx +c
where x is an independent variable and y is dependent, in my case x contain some none values and when I am trying to add it through 

 **add_regressor()** 

it shows an error message that appears in " parameter contain none value"

I hope you understand my query

**Comment by bletham** [comment]
Ah, I see, so there are missing values in an extra regressor. Yes, that is not allowed because there is no way for the model to make a prediction without knowing the value for the extra regressor. You basically have two options:
- You can drop those rows from your dataframe. If it's just a few dates with missing data, this probably won't affect things too much. But if it's a lot, then you're losing alot of information about `y` that you otherwise would have.
- You can impute the missing regressor values. Whether or not this can be done in a reasonable way will really depend on regressor. There are many ways to try and impute values for missing data.
- If a lot of values are missing, you may be better off just not using the regressor. Because any errors in imputation will basically be adding noise to your model, and if there are many values being imputed (or alternatively many rows of `y` being dropped) then you may be better off not using it at all. You could check with cross validation if using the regressor is improving your prediction quality.

**Comment by aasi24** [comment]
Thanks a lot Ben, is there any method or function that can generate future data for extra regressor that we can use for forecasting of our objective?

**Comment by benmwhite** [comment]
@aasi24 You can use another univariate time series forecast using the regressor values themselves to predict their future values and use those predicted regressor values in your main time series forecast.

**Comment by dharani-aws** [comment]
HI @aasi24  could you please advise me over an urgent problem in using add_regressor() ?

https://github.com/facebook/prophet/issues/1619
