### ISSUE TITLE
The correct specification for add_seasonality when working with weekly series?

### ISSUE THREAD

**Issue by amurguiag** [facebook/prophet#1419]
When specifying weekly seasonality manually with add_seasonality, should period = 52.18 or 7? Similarly, if I were to add monthly seasonality, should the period = 4.34 or 30? I guess my confusion stems because I have seen in some documentation that period should be in terms of days. But my data is weekly.

**Comment by bletham** [comment]
The period is always in days. The underlying Prophet model is in continuous time, so it doesn't have any notion for the frequency of the data. Weekly data just means there is only one datapoint per week; internally time is measured the same as with daily or irregular data.

Weekly seasonality here means a seasonal cycle within a week. The period for that is 7 days, but if you have weekly data you should disable weekly seasonality since you cannot measure seasonal cycles within the week with only 1 datapoint for the week. If you leave weekly seasonality at its default value of `'auto'` it will be automatically disabled when you have weekly data.

Monthly seasonality would have a period of about 30.4375 (which is 365.25 / 12).

**Comment by amurguiag** [comment]
Thanks for your help, Ben! This is very useful.
