### ISSUE TITLE
make_future_dataframe with Saturday weekly data

### ISSUE THREAD

**Issue by rjsbhatia** [facebook/prophet#1424]
I am calling the make_future_dataframe function and asking for 52 weeks to forecast for a year out from my end date. The input data is weekly.

`make_future_dataframe(periods=52,` freq='w')

I noticed in the middle of the frame it does a weird one day jump and it throws off my data completely, as i use the ds field to match and plot information. 

I have added an index to the future dataframe to make it easy to read the error:- 

![fb_error](https://user-images.githubusercontent.com/2141214/78675897-b20e9280-78b3-11ea-9603-6d2a432c8799.png)

**Comment by bletham** [comment]
The `make_future_dataframe` function uses `pd.date_range` to generate the dates starting from the last date in the history:
https://github.com/facebook/prophet/blob/6cd14438c61a7518ae3cfd6b8d91788fab80cd6f/python/fbprophet/forecaster.py#L1509-L1513
The dates in the history are then pre-pended:
https://github.com/facebook/prophet/blob/6cd14438c61a7518ae3cfd6b8d91788fab80cd6f/python/fbprophet/forecaster.py#L1517-L1518

If you do
```
pd.date_range(start='2018-12-29', periods=4, freq='W')
```
you get
```
DatetimeIndex(['2018-12-30', '2019-01-06', '2019-01-13', '2019-01-20'], dtype='datetime64[ns]', freq='W-SUN')
```
So you see that it started with '2018-12-30' even though we specified to start on '2018-12-29'. This is because in pandas `W` means weekly _starting on Sunday_.

I'm guessing here that Dec 29, 2018 was the last day in your history. All of the days in your history are Saturdays. But then when asking pandas to generate the future, it is generating dates on Sundays. To fix this you need to use `W-SAT` instead of `W` (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#anchored-offsets):
```
pd.date_range(start='2018-12-29', periods=4, freq='W-SAT')
# Produces DatetimeIndex(['2018-12-29', '2019-01-05', '2019-01-12', '2019-01-19'], dtype='datetime64[ns]', freq='W-SAT')
```

**Comment by rjsbhatia** [comment]
Thanks a lot! that explains the discrepancy.

**Comment by ernestocharry** [comment]
Thank you very much for your assistance!
