### ISSUE TITLE
I set column named 'cap' for logisticmodel,but it did't work.how do i fix it?

### ISSUE THREAD

**Issue by BigFishDreamWater** [facebook/prophet#1427]
![debug1](https://user-images.githubusercontent.com/61278937/78976885-b81da100-7b49-11ea-8a92-863891bdd227.jpg)

**Comment by bletham** [comment]
The issue here is that it has to also be supplied for the future dates , in the dataframe named `future`. so you would do something like
```
future = m.make_future_dataframe(periods=10, freq='W')
future['cap'] = 100.  # or whatever it is
```
(That's assuming cap is constant, if it is not constant then it will be a vector of values. In either case it will be very important that what you put in the `future` dataframe matches what you have for past dates in `dfw`.)

**Comment by BigFishDreamWater** [comment]
> The issue here is that it has to also be supplied for the future dates , in the dataframe named `future`. so you would do something like
> 
> ```
> future = m.make_future_dataframe(periods=10, freq='W')
> future['cap'] = 100.  # or whatever it is
> ```
> 
> (That's assuming cap is constant, if it is not constant then it will be a vector of values. In either case it will be very important that what you put in the `future` dataframe matches what you have for past dates in `dfw`.)

Wow,it's worked with follow your concise code. Thanks a bunch！

**Comment by puneet29** [comment]
@BigFishDreamWater You should close this issue as it is resolved.
