### ISSUE TITLE
How does cross validation work if my data only has weekdays and excludes holidays?

### ISSUE THREAD

**Issue by pypinkfloydfan** [facebook/prophet#1431]
Hi there

I am using a dataset with approximately 4 years of weekday data excluding US holidays. Whilst I understand that for accurate forecasting I need to remove the weekends after running "make_future_dataframe", if I want to use the cross-validation function on this dataset will it work out-of-the-box accurately?

Assuming I want to make cross-validation predictions every 180 calendar days (~126 business days), can you offer any advice for the correct inputs to the function?

Thanks very much

**Comment by bletham** [comment]
Yes, the cross validation should work just fine. Cross validation only makes predictions for days in the history, since those are the dates for which we have a true `y` to compare the forecast to.

With 4 years of data, I'd recommend using 1 year as the minimum amount of data, so that you will be able to estimate yearly seasonality. So your cross validation would look something like
```
df_cv = cross_validation(m, initial='365 days', period='180 days', horizon = '180 days')
```
where you might be interested in changing `horizon`, which would be however far you're interested in forecasting into the future. So if you want to assess your ability to make 1 year predictions it should be 365 days, but if you're primarily interested in  3 month predictions, then it could be 90 days. Does that make sense?

**Comment by pypinkfloydfan** [comment]
That's super clear, thanks very much 👍
