### ISSUE TITLE
Using Prophet to forecast on sparse data

### ISSUE THREAD

**Issue by ishan42d** [facebook/prophet#1432]
Hi, I have a situation where I am trying to use Prophet but on a sparse data. For example my data starts from 2019-01-03 which is 3rd Jan then the next issue came in on 8th jan then next on 13th Jan and so on. 
Now my data has the following credentials:
1. It shows spikes around every quarter 1 and quarter 3 of each year
2. It is US based, so I need to use the US holidaying effect
3. Also there is some monthly seasonality as well

Now my question is that I have used the Prophet with additional seasonality for monthly as well as quarterly and disabled the yearly and weekly seasonalities and have used US holidays. I still see some negative values for yhat_lower. Why is it so? 

Also, considering I am  forecasting after Apr 5th until 30th May, how do I incorporate the current coronavirus situation? is it required at all?

and my last question is around CV. I am using this :
**df_cv = cross_validation(model2, initial='104 days', period='15 days', horizon = '130 days')**
which shows me this : 

**INFO:fbprophet:Making 15 forecasts with cutoffs between 2019-04-27 00:00:00 and 2019-11-23 00:00:00** 

whereas I want my first date to be the first date when the case was rasied which is 2019-01-02 00:00:00 and should run until 2019-11-23 which makes a total of 104 cases out of 130 cases that I have. How do I solve for this one?

**Comment by bletham** [comment]
Let me try to address each of the questions here. If the data are very spiky, Prophet might not be a great model for the data; if you're able to post a plot of the forecast (with `m.plot`) I might be able to give some more comments on that, and things you could try to get better model fits.

Negative values for yhat_lower: The model assumes Gausisian noise, and a big part of the uncertainty will be this noise component. If the model is fitting a lot of noise, then it can give you uncertainty intervals that span 0. It's a case of model misspecification; in a situation like this where you know it must be positive, the best thing to do would be to just clamp forecast estimates at 0.

Coronavirus: Prophet assumes stationary seasonalities, e.g. weekly seasonality is the same throughout the whole history. This is not going to be true for many time series in the last couple months. The effect this will have on your forecast will really depend on the time series. I don't have a very good answer to give right now for what to do about it (#1416 is a place to discuss this), but I think there's so much exogenous factors affecting time series right now that I suspect you will probably have to rely a lot on your domain expertise for now to plot the forecasts and identify if it is reasonable / how it needs to be adjusted. #1416 does have some discussion in at least handling changing seasonalities.

cross validation dates: The way it works is it fits multiple models (in this case 15) that use increasing windows of data. What the printout means is that the first model will use data up through 2019-04-27. This is because initial is set to '104 days', which means the first cutoff will use at least 104 days of data (in this case it is 114 days from the start of the time series). So it uses those 114 days of data to make a 130 day forecast. That's the first forecast. Then, it adds 15 days to the time series (since that's the period), and now uses all of the data up through 2019-5-12, and makes a forecast for the next 130 days. That's the 2nd forecast. This continues, adding 15 days at a time until you reach 130 days til the end of the time series (since that's the horizon). So the final cutoff is at 2019-11-23, which is 130 days before the end of the time series. It sounds like you want a cutoff that uses all data up to 2019-11-23? Here's it's doing that, but only as the last of 15 cutoffs. If you wanted a single cutoff, you could just increase your `initial` to require it to use all data up to 2019-11-23. Does that make sense?

**Comment by ishan42d** [comment]
Thank you so much! Apologies for responding a little late. But all of your points seems reasonable and answer my questions.
