### ISSUE TITLE
install failed on macos mojave by python and r

### ISSUE THREAD

**Issue by wyfSunflower** [facebook/prophet#1456]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q5/txy9q4p90mb46cxgw85l5yfrwqbqs6/T/pip-install-MvkARt/fbprophet/setup.py'"'"'; __file__='"'"'/private/var/folders/q5/txy9q4p90mb46cxgw85l5yfrwqbqs6/T/pip-install-MvkARt/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/q5/txy9q4p90mb46cxgw85l5yfrwqbqs6/T/pip-install-MvkARt/fbprophet/pip-egg-info
         cwd: /private/var/folders/q5/txy9q4p90mb46cxgw85l5yfrwqbqs6/T/pip-install-MvkARt/fbprophet/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q5/txy9q4p90mb46cxgw85l5yfrwqbqs6/T/pip-install-MvkARt/fbprophet/setup.py", line 30
        def get_backends_from_env() -> List[str]:
                                    ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

package 'prophet' is not available (for R version 3.6.3)

**Comment by bletham** [comment]
For Python: it looks like you are installing with python2. Since 0.6, fbprophet is python3 only (python2 has been deprecated since the start of the year and shouldn't be used anymore). If you do have to use python2, then you'll have to install fbprophet==0.5.

For R: This is related to #1448 which is that we're having some issues with CRAN right now, but in the meantime you can install the package devtools, and then install prophet with:
```
devtools::install_github("facebook/prophet", subdir='R', ref="8306ae3")
```

**Comment by wyfSunflower** [comment]
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbprophet
ERROR:fbprophet:Importing plotly failed. Interactive plots will not work.
>>>

**Comment by wyfSunflower** [comment]
fbprophet is not on pypi, it can not installed by pip.
conda install -c conda-forge fbprophet .this command can install fbprophet, but you can not use it,after fbprophet installed, it will throw error if you import it into your project.
import fbprophet
print(fbprophet.__version__)

Traceback (most recent call last):
  File "/Users/evan/Movies/e/Users/evan/PycharmProjects/untitled/sarima/prophet.py", line 1, in <module>
    import fbprophet
  File "/Users/evan/miniconda/lib/python3.7/site-packages/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/Users/evan/miniconda/lib/python3.7/site-packages/fbprophet/forecaster.py", line 20, in <module>
    from fbprophet.make_holidays import get_holiday_names, make_holidays_df
  File "/Users/evan/miniconda/lib/python3.7/site-packages/fbprophet/make_holidays.py", line 16, in <module>
    import fbprophet.hdays as hdays_part2
  File "/Users/evan/miniconda/lib/python3.7/site-packages/fbprophet/hdays.py", line 16, in <module>
    from holidays import WEEKEND, HolidayBase, easter, rd
ImportError: cannot import name 'easter' from 'holidays' (/Users/evan/miniconda/lib/python3.7/site-packages/holidays/__init__.py)

**Comment by bletham** [comment]
For your first post with `ERROR:fbprophet:Importing plotly failed. Interactive plots will not work.`, that looks like the installation actually worked. The message there is as it says, that plotly is not installed so plotly plotting will not work, but the rest of the package will. If you install plotly, then that message will go away.

For your 2nd, fbprophet is on pypi here: https://pypi.org/project/fbprophet/
The error that you report `ImportError: cannot import name 'easter' from 'holidays'` is because of an incompatibility with fbprophet==0.5 and holidays>0.1. Since you are using python3 now, you can install fbprophet==0.6 and then it will work.

**Comment by wyfSunflower** [comment]
conda install -c conda-forge fbprophet==0.6
conda install plotly
solve my problem,thanks @bletham
