### ISSUE TITLE
no previously-included directories found matching 'fbprophet\stan_model'

### ISSUE THREAD

**Issue by lboxum** [facebook/prophet#1467]
I'm trying to build a wheel file after changing the source code a little bit, but I get the error 'no previously-included directories found matching 'fbprophet\stan_model''. Pystan is installed as 
in the installation instructions. I have tried updating and reinstalling pystan but nothing seems to work. Any ideas what could help? Thanks in advance!

![fbprophet](https://user-images.githubusercontent.com/47666711/80795734-a7d37180-8b9d-11ea-9f39-6840c0e0e427.PNG)

**Comment by bletham** [comment]
I don't really know what's happening here, I don't get this when building a wheel with the current version.

The directory `fbprophet/stan_model` is created during build here:
https://github.com/facebook/prophet/blob/a3bf6c4cdc315cec9cbac8417742a0c513280091/python/setup.py#L47

Did you by chance change the build code related to that? If you look in the build directory, do you see this directory? I.e. at `prophet/python/build/lib/fbprophet/stan_model`.

**Comment by lboxum** [comment]
Thanks for your response @bletham ! I tried building the wheel file from the original python files (so without having changed anything) and I still get the same error. I do see this directory prophet/python/build/lib/fbprophet/stan_model with the prophet_model.pkl file in it. 

It seems as if it goes wrong in this step (line 38 setup.py): 
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)

I'm trying to break it down step by step to find the issue, but no success so far.

**Comment by bletham** [comment]
Actually I just noticed that I do see this message when I run `python3 setup.py install`. Specifically, I see:
```
running install
running bdist_egg
running egg_info
writing fbprophet.egg-info/PKG-INFO
writing dependency_links to fbprophet.egg-info/dependency_links.txt
writing requirements to fbprophet.egg-info/requires.txt
writing top-level names to fbprophet.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'fbprophet/stan_model'
writing manifest file 'fbprophet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_888a84912910fa0a45b9d614b75bb8a8 NOW.
Adding fbprophet 0.6.1.dev0 to easy-install.pth file
```

I think that message is coming from here when it is parsing the MANIFEST.in:
https://github.com/facebook/prophet/blob/a3bf6c4cdc315cec9cbac8417742a0c513280091/python/MANIFEST.in#L7

I think that what is happening is if there isn't already a model there, then there's nothing to prune and so it prints that message.

On my machine it is printing prior to running build_py, so it may not be exactly the same thing, but I do suspect now that this message may be benign and unrelated to the failure.

Is there any additional error message after that? The most common reason compiling the model fails is because PyStan isn't configured with the C++ compiler correctly. Could you try running this code in pystan and see if it works?

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

**Comment by batmax2015** [comment]
Try _python setup.py sdist bdist_wheel_  instead of _python setup.py bdist_wheel_

**Comment by lboxum** [comment]
That works, great thanks!
