### ISSUE TITLE
Negative Forcasting for Fb prophet 

### ISSUE THREAD

**Issue by amymyr** [facebook/prophet#1468]
### I'm trying to forecast an hourly Count Cx I have 2 year and a half data , and using Prophet generate negative prediction.
I have tried : 1. doint log(y+1) and change after yhat to exp (yhat)-1 and 2. using logistic Growth with cap and floor.
For 1. I no longer get the negative value but the model under estimate the highs count between (10 am and 6pm).

![image](https://user-images.githubusercontent.com/64642190/80805453-0ee52c00-8b86-11ea-8c5c-6f67ab708c73.png)

for 2.  I have use floor= 0 but it dont respect it for the training. and I have use also add. seasonality multiplicative dont work too. 
this the code : 
from fbprophet import Prophet
df_test=df_test.reset_index(drop=True)
df_train['cap'] = 700
df_train['floor'] = 0

m = Prophet(growth='logistic',daily_seasonality = False, yearly_seasonality =False,weekly_seasonality =False,changepoint_prior_scale=0.5, interval_width=0.9)
#m.add_seasonality(name='weekly', period=5,fourier_order=20,mode ='multiplicative') have tried this seasonality
m.add_seasonality(name='daily', period=1,fourier_order=10,mode= 'multiplicative')
#m.add_seasonality(name='Hourly', period=24,fourier_order=20,mode ='multiplicative') also this
m.add_seasonality(name='Yearly', period=365.5,fourier_order=20,mode ='multiplicative')

m.fit(df_train)

it give 35% SMAPE
this is the plot 
![image](https://user-images.githubusercontent.com/64642190/80820311-a48fb400-8ba4-11ea-99c5-ca9491c65472.png)

![image](https://user-images.githubusercontent.com/64642190/80820347-b1aca300-8ba4-11ea-9821-89770035e034.png)

![image](https://user-images.githubusercontent.com/64642190/80820419-d30d8f00-8ba4-11ea-8b17-7549b06bc9ea.png)

Can some one help me to improve the forecasting please

**Comment by bletham** [comment]
A few comments on this forecast:

- With the logistic trend, the floor and cap apply only to the trend component - seasonal fluctuations can push the total forecast `yhat` outside those bounds. And the noise term will also push uncertainty intervals outside those bounds. There isn't a clear saturating growth trend, so I think you'd be better off here just using the default linear trend, and clamping the forecast to be >0 (so, replace negative values with 0).

- Most of what is happening in this forecast has to do with the daily seasonality. In the bottom forecast there is a clear weekly seasonality in the amount of daily seasonality: the daily seasonality has higher magnitude on weekdays than weekends. Since weekly seasonality was disabled and isn't being modeled in any way, the daily seasonality is an average of both the weekday and weekend effects. This means that on weekdays the daily seasonality is too small, while on weekends it's too large. You'll definitely want to include weekly seasonality. In this particular case where the weekly seasonality is effecting the magnitude of the daily seasonality, the best way to include it is to have separate daily seasonalities for weekdays and weekends. You can do that as described in the documentation here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors (here you would create binary indicators for "is_weekend" and "is_weekday").

- for the `m.plot()` forecast shown, it does look like a lot of the variation in the forecast is variation in the magnitude of the daily seasonality. It looks like the model is doing a pretty reasonable job of catching this with the multiplicative seasonality, and I think the adjustments above will help with a lot of the underforecasting that is seen. I'd be interested to see the plots after accounting for the weekend effect on daily seasonality.

**Comment by amymyr** [comment]
Thanks for your answer, It helped me a lot understanding prophet . I did your 3 advice: 1. changing from logistic to linear, 2. clamping the forecast to be >0 (so, replace negative values with 0 and 3. adding the daily seasonalities for weekdays and weekends, But my SMAPE still high 22%
the code :
df_test=df_test.reset_index(drop=True)
df_train['nfl_weekend'] = df_train['ds'].apply(nfl_weekend)
df_train['nfl_weekday'] = df_train['ds'].apply(nfl_weekday)
m = Prophet(daily_seasonality = False, yearly_seasonality =False,weekly_seasonality =False,changepoint_prior_scale=0.5,  interval_width=0.9)
m.add_seasonality(name='weekly', period=7,fourier_order=25,mode ='multiplicative')
m.add_seasonality(name='weekend', period=1, fourier_order=50,condition_name='nfl_weekend',mode ='multiplicative') 
m.add_seasonality(name='weekday', period=1, fourier_order=50, condition_name='nfl_weekday',mode ='multiplicative')


m.fit(df_train)
future = m.make_future_dataframe(freq='h',periods=24)

future['nfl_weekend'] = future['ds'].apply(nfl_weekend)
future['nfl_weekday'] = future['ds'].apply(nfl_weekday)
df_test_d_fcst = m.predict(future)
fig = m.plot(df_test_d_fcst)

df_test_fc= df_test_d_fcst.loc[df_test_d_fcst.ds > split_date].copy()
df_test_fc['yhat']= np.where(df_test_fc['yhat']<0,0,df_test_fc['yhat'])
df_test_fc=df_test_fc.reset_index(drop=True)
calc_smape(df_test['y'],df_test_fc['yhat'])

How can improved the model ? should I change something else ?

![image](https://user-images.githubusercontent.com/64642190/81319908-5ecc6300-905e-11ea-98f8-aee2b4343d30.png)

**Comment by bletham** [comment]
That looks a lot better. The fit for the 2nd week (4/6) looks pretty good and what is left looks like it would just be noise variance. The subsequent weeks it looks like it's under-predicting the peak a bit.

Like I mentioned above, most of what is happening in this time series is that the magnitude of daily seasonality is fluctuating over time. Prophet assumes stationary daily seasonality (meaning, it's the same every day). It's able to capture some of this by having multiplicative seasonality, and increase the trend in order to increase the magnitude of daily seasonality, but it isn't a perfect fit for what is actually happening so there's some model misspecification. I think what you have here is about as good as Prophet will get for this time series.

If you only cared about the total for the day, then you could aggregate your data up to a daily total and then I think Prophet would work much better on that time series. But if you need forecast at the hourly level this about it.

**Comment by bletham** [comment]
(If you were to aggregate, then you could just use the default built-in yearly seasonality / weekly seasonality and don't need to worry about the multiple daily seasonalities).

**Comment by bletham** [comment]
One final note: SMAPE probably isn't a great choice for evaluation metric for this time series since it has values very close to 0. SMAPE will treat an error like forecasting 1 instead of 0.1 as a huge error, while forecasting 401 instead of 400.1 will be a very small error. MAE or RMSE might make more sense for a time series with values close to 0.

**Comment by amymyr** [comment]
Perfect!!! thanks so much for you response and advice. I did both daily and hourly. Yes the daily are good, I trying just to improve the hourly forecasting. Ok for MAE and RMSE.
