### ISSUE TITLE
conda install success on py3.7 but cannot import name 'easter' from 'holidays'

### ISSUE THREAD

**Issue by wyfSunflower** [facebook/prophet#1471]
macos 10.14.6
conda install -c conda-forge fbprophet
fbprophet installed successfully.
but when I import fbporphet, it throw error:
from holidays import WEEKEND, HolidayBase, easter, rd
ImportError: cannot import name 'easter' from 'holidays'
fbprophet:Importing plotly failed. Interactive plots will not work.

**Comment by ryankarlos** [comment]
What prophet version are you using ? This should not be an issue with latest prophet v  0.6. If you are using 0.5 or earlier you may need to downgrade holidays <=0.912.
The issue was that "easter" was being imported directly from holidays library rather than dateutil library (where that function is actually defined)  in the prophet source code. Until the previous version of holidays (0.9.12) this was working as it was being imported in holidays.py. 
So you can do one of two things : 
* Upgrade to latest prophet version 0.6 
* Downgrade holidays library to version 0.9.12 or below.

**Comment by ChatsHD** [comment]
When I try to install the version 0.6 it says it cannot find that verison

**Comment by ChatsHD** [comment]
The fix was to download the prophet 0.6 files manually and then use pip install prophet==0.6 after adding the directory of downloaded files.
