### ISSUE TITLE
Adding Regressors

### ISSUE THREAD

**Issue by carlose2108** [facebook/prophet#1473]
@bletham 
I was wondering if you can help me to clarify a doubt of Prophet, so my question is Can I use Prophet to predict a value with multiple inputs?

For example, I can use DL (LSTM) to predict a value in this case "Pollution Level" with other inputs (dew, temp, press, wnd_dir, wnd_spd, snow, rain) but Prophet has "ds" and "y", I just read adding regressor but I don't understand well.

Hope you can help with this.

Regards,
![pollution](https://user-images.githubusercontent.com/4132472/80869491-bf2e5f80-8c6e-11ea-9721-9a598972a374.png)

**Comment by mat178** [comment]
Yes it is possible to add these inputs as additional regressors with prophet. 
Here is the documentation on how to do it: 
[Additional regressors](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors)

Basically if you have a column "temp" in your data that you want to use as additional regressor you create your model and then call the add_regressor function providing the name of the column you want to add. But keep in mind that you have to add this column to your future dataframe in order to make a forecast. So if you want to forecast the air pollution for tomorrow, you have to add the temperature for tomorrow in the "temp" column.

**Comment by csetzkorn** [comment]
downside. you have to predict regressors separately ... what does everyone else use to do this? VAR implementation in R does this OOTB but very interested in hearing from others.

**Comment by carlose2108** [comment]
Thanks a lot for your answer @mat178 
I had some doubt because a person told me when I add those inputs in my model, they were calculated aside and result is a models of each input inside in my model, I mean, those inputs does not relation with the target (Pollution).

If someone join to this conversation it would be perfect and expose his experience.

**Comment by bletham** [comment]
This is a nice example of extra regressors that actually includes temperature specifically https://nbviewer.jupyter.org/github/nicolasfauchereau/Auckland_Cycling/blob/master/notebooks/Auckland_cycling_and_weather.ipynb

But yes as @csetzkorn notes you do have to then be able to forecast your extra regressors. You then ideally want to also include uncertainty in your future extra regressors into your estimate of uncertainty of `y` (there's discussion of how to do this in #1392). Generally, I think that if you do have an extra regressor that isn't known in the future (and so must be forecasted), then you will only get value from including it in the model if it is somehow easier to forecast than `y` alone. Otherwise, having the forecast of `y` depend on an equally uncertainty quantity isn't really going to buy you much.

In the particular case of weather, I think there are some reasonable applications. Weather can account for a lot of the yearly seasonality in some time series, and temperature forecasts based on yearly averages can be known years out and be a good baseline estimate. Then as you get closer in time, the weather prediction will become more accurate, and the forecast of `y` can thus also become more accurate. So in this case we would be depending on something that long-term we probably can't predict any better than `y` alone, but short-term we can, and so we if we care primarily about e.g. 1-7 day forecasting ability it makes sense to include it.

**Comment by carlose2108** [comment]
Thanks a lot @bletham for your comment and share the example.

**Comment by Abdulwasiv** [comment]
>Yes it is possible to add these inputs as additional regressors with prophet. Here is the documentation on how to do it: [Additional regressors](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors) 
> Basically if you have a column "temp" in your data that you want to use as additional regressor you create your model and then call the add_regressor function providing the name of the column you want to add. But keep in mind that you have to add this column to your future dataframe in order to make a forecast. So if you want to forecast the air pollution for tomorrow, you have to add the temperature for tomorrow in the "temp" column.

@mat178  How can we incorporate categorical variables(String) as regressors so that the model can accurately interpret the data and predict outcomes?
