### ISSUE TITLE
Known impact of an upcoming trend change

### ISSUE THREAD

**Issue by kaspersgit** [facebook/prophet#1478]
In our data we have quite some seasonality of which the magnitude is growing as can seen in the graph. Now putting the seasonality mode on multiplicative give the best fit visually, the problem however is around end of 2018 where it drop and then the trend continues again from a lower level. This causes an especially big error when running cross validation with `seasonality_mode='multiplicative'` compared to `seasonality_mode='additive'`, yet we knew this change was coming and we actually new the impact of the change. 
Now is there a way to include that kind of prior knowledge into the model to make it handle these changes more smoothly?
![image](https://user-images.githubusercontent.com/30573156/81226344-fdb77780-8fea-11ea-88c4-bae5306b9b7b.png)

**Comment by svjack** [comment]
Try add regressor as an indicator of the time before 2018 end and after.

**Comment by bletham** [comment]
So you knew there would be a drop in trend at a particular date in the future. Simply subtracting out that known decrease from `yhat` isn't sufficient because of the impact it also has on the multiplicative seasonality.

Unfortunately I can't think of a totally straightforward way of doing this. If you look in the forecast dataframe returned by `predict`, you will see the columns `yhat`, `trend`, `multiplicative_terms`, and `additive_terms`. The forecast `yhat` is computed as:
https://github.com/facebook/prophet/blob/16e632a6958bc1fbfcc67ed8628ba8c972df15db/python/fbprophet/forecaster.py#L1216-L1219
(where `df2` there is the result returned by `predict`). So what you could do would be something like
```py
forecast = m.predict(future)
forecast['trend_adjusted'] = forecast['trend'] - XXX  # make adjustment here
forecast['yhat_adjusted'] = forecast['trend_adjusted'] * (1 + forecast['multiplicative_terms']) + forecast['additive_terms']
```
(in your case it seems that everything is multiplicative so `forecast['additive_terms']` will be 0).

For cross validation, you'd have to code up a loop yourself to insert this into the middle of it.

**Comment by kaspersgit** [comment]
Thanks @bletham , the seasonality impact makes sense I didn't think about that. But I will give your suggestion a try and see how it works out!
