### ISSUE TITLE
Multivariate time series  adding regressors

### ISSUE THREAD

**Issue by AshikTalupula** [facebook/prophet#1511]
Hello, I am trying to forecast multiple time series using prophet in a loop by adding the external regressors but when I compare the outputs by summing up its not matching to the actual.

example: for simplicity lets consider a daily data of two time series A and B which is dependent on C , I am using C as external regressor to forecast both A and B separately that is sum of A and B is equal to C , when I add the forecasts generated by these two series by providing  C value as an external I am not getting the equal split of A and B. Please let me know If I am modeling the problem in a wrong way .

**Comment by bletham** [comment]
To be sure I understand: A + B = C. You forecast C, and then include the forecast of C as an extra regressor for A and B. The sum of the forecast of A and B does not equal the forecast of C. Is that correct?

There's nothing in the model to force the relationship A+B=C. I think the best you could do in this situation is to normalize each forecast at the daily level to sum to C. So, forecast A(t) and B(t) would be multiplied by C(t) / (A(t) + B(t)).

In order to ensure all of the component forecasts sum up to the aggregate, you'd have to use a model that specifically incorporates the hierarchical structure, something like https://arxiv.org/pdf/1711.04738.pdf .
