### ISSUE TITLE
Facebook prophet Anomaly detection : Issues with seasonality 

### ISSUE THREAD

**Issue by engineeryashsaxena** [facebook/prophet#1518]
We are trying to make a generic anomaly detection prescribe using Prophet. 
We can have multiple time series ( this is basically session-level information such as number of users in a day, number of users in a day from web-only, etc. ) having different types of seasonalities. Seasonality can be at weekly, yearly, daily, quarterly and monthly levels.

Explanation of how do we say something as anomalous? : 

Based on y and yhat we calculate in terms of percentage how far is the actual value from the predicted value and then provides the user an interface to set up a threshold. Say 90%, so only the instances where the difference was more than  90% will be termed as an anomaly .

The doubts we are having are these :

1. Since we want to make a generic version, there can be 10000 time series in a day so how do we generalize the seasonality. What I mean is which all types of seasonality I should give my default and what should be corresponding Fourier orders? How do they impact the model? 
2. Does the order of seasonality also matter? 
3. Should adding extra regressors in this a  better approach apart from using seasonalities 
4. Is there any other recommended method for doing Anomaly Detection using Prophet in a generic way?

**Comment by bletham** [comment]
1. You'll definitely want to exclude seasonalities that don't have enough data (like less than a year for yearly seasonality, perhaps even less than 2 depending on how conservative you want to be) or that have period <= the data frequency (so, turn of daily seasonality if it is daily data, no weekly seasonality if it is monthly data, etc.). Besides that, you might want to just test with a few typical time series what set of seasonalities works best. My feeling is that quarterly seasonality would possibly be picked up by the yearly seasonality and unnecessary, but it could depend on the time series. You can include a number of seasonalities in the model but will probably want to decrease the `seasonality_prior_scale` parameter to better regularize them (it defaults to 10; something more like 1 or 0.5 might be what you'd want if you are adding a few custom seasonalities). The effect of Fourier order is described here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#fourier-order-for-seasonalities . You most likely will be fine with the default values for weekly and yearly seasonality.
2. The order in which you add them does not matter, they all just become columns in the linear regression portion of the model.
3. If you have extra regressors that you expect the time series to be correlated with then adding them makes a lot of sense, but probably wouldn't be a good substitute for seasonality modeling in entirety.
4. I think the uncertainty intervals given in `yhat_upper` and `yhat_lower` should be useful to you, and note that you can set the width of them (default is an 80% interval, https://facebook.github.io/prophet/docs/uncertainty_intervals.html ). That should do a good job of capturing the un-modeled variance of the time series and not producing false positives in settings where the model just doesn't have a clear fit for what's happening.

**Comment by engineeryashsaxena** [comment]
Thanks a lot for detailed answers @bletham  
However, just a few follow-up questions, would be great to have your views . 

1. On the question number 3 in the original question what I want to understand is which is a better approach with FB Prophet? 

   A. Using add_seasonality to give more seasonalities as mentioned here: 
![image](https://user-images.githubusercontent.com/12986911/83752575-0a220500-a669-11ea-84b6-5eab944a160e.png)
( assuming I am adding a month of day and not a quarter of the day ) 

  B. Providing different seasonalities we want as one-hot encoded variables as mentioned here : 
![image](https://user-images.githubusercontent.com/12986911/83752639-2625a680-a669-11ea-8821-93022e93fee1.png)


2. As a follow-up experiment, we have done the following experiment to get SD (  standard deviation )  from Prophet using yhat_upper and yhat_lower values.The details are as follows : 

Assuming the distribution which computes yhat_upper and yhat_lower is normally distributed we try to find SD  by providing a confidence_interval of 0.95 percent and calculating SD as : 

SD=(yhat_upper-yhat_lower)/4
( as we have 95% of the data within mean+2 SD and mean-2 SD in a normal distribution )

Once we get SD we compute our 3 zones as :  ( yhat-1*SD to yhat-1*SD ) , ( yhat-2*SD to yhat-2*SD )  and ( yhat-3*SD to yhat-3*SD ) respectively . Anything outside  3rd zone we term anomalous. 
We need zone for different business use cases , but can you confirm whether the calculation part of the SD is the right approach

**Comment by bletham** [comment]
Seasonalities using `add_seasonality` vs. one-hot encoded extra regressors:
For both settings we are constructing a matrix of regressors X, and then the model is
```
y(t) = trend(t) + X(t) * beta
```
With dummy variables, you will have an entry in X for every day in the period. Weekly seasonality would have 7 binary entries in X(t), with 7 corresponding parameters in beta to be fit. These parameters would represent the seasonal effect on each day. If you wanted to do this with yearly seasonality, it would take 365 parameters, and the value of each would be the seasonal effect on that day of year.

With `add_seasonality`, the regressors X are not binary, they're sinusoids of varying frequency representing a truncated Fourier series. The math is given in Section 3.2 of the paper (https://peerj.com/preprints/3190/). The number of parameters for the seasonality depends on how many of these sinusoid components are included in the model, which is twice the Fourier order (the parameters are a_n and b_n in the eqn in the paper). For weekly seasonality, the default is to use 3, which means there are 6 parameters to fit. For yearly seasonality it is 10, which produces 20 parameters.

The advantage of using the Fourier series seasonality over one-hot encoded regressors is that for longer seasonalities it will have a lot less parameters. It's able to use less parameters because it assumes smoothness of the seasonality (which we expect to be true in most business time series). For weekly seasonality with daily data, there's really no difference between using the Fourier seasonality vs. using dummy variables. However for something like weekly or yearly seasonality it can be a big difference. I don't think the model will do a good job at inferring 365 independent parameters for one-hot encoded yearly seasonality. Fourier seasonalities require inferring only 20 parameters which is much more doable. If the seasonalities actually are smooth, then you'll get very beneficial regularization.

For the SD calculation: If you set the interval to 95%, then that's a reasonable calculation. Basically what you're doing is approximating the posterior with a normal distribution and moment matching. The posterior distribution isn't actually normal because of the future trend uncertainty (Sec. 3.1.4 of the paper), so the calculation you give won't be exactly the posterior standard deviation but it will probably be close. If you want to compute the actual posterior standard deviation, then you would use `m.predictive_samples(future)` to draw posterior samples of `yhat`:
https://github.com/facebook/prophet/blob/f16d9df33337be93d34f0f69904e9fa25e1b6a10/python/fbprophet/forecaster.py#L1401
and then take the standard deviation of those samples.

**Comment by engineeryashsaxena** [comment]
Thanks a lot, @bletham for the clarification, this really helps a lot 👍

**Comment by engineeryashsaxena** [comment]
One last question before I close this thread: Is there any difference in terms of CPU cycles if we do a predict for the complete dataset or I predict just for say last date? 
What I want to understand is that whether predict takes the same amount of time irrespective of the period for which we are predicting ( not forecasting for future, but predicting till the last day of the train data ) 
@bletham Please if you can let me know this
