### ISSUE TITLE
Fill missing data datestamps (days) with 0?

### ISSUE THREAD

**Issue by ivangvi** [facebook/prophet#1522]
Hi! First let me say, Prophet is awesome. I'm glad I stumbled upon it, thank you for it.

I'm building a sales (units) forecasting system for restaurants, building one model per location per sku using aggregated daily data. Some of these combinations have very sparse data, for instance, take a look at the following fit:

![download](https://user-images.githubusercontent.com/30244899/83462598-f779b700-a441-11ea-93b2-39ad16b3d4b8.png)

I'm afraid in most cases, the following appearance of that location>sku combination will probably be in the low values. And this is a small case, imagine if for one combination I had first 1, then 5 and then gone. The trendline would be insane!

I suspect I can fix this by adding the 'missing' days with the actual data, which is actually 0. What do you think about this approach? Furthermore, is the only way to do it manually while preparing data, or is there a parameter somewhere in fit() I can use to specify this treatment?

Thanks in advance.

**Comment by bletham** [comment]
Prophet isn't going to do very well on time series like this one. Yes, the correct thing to do would be to fill in 0s for the days where the sales were 0. But Prophet will still do poorly on such a time series; it generaly does poorly on time series that are mostly 0 with occasional non-zero points because it violates the Gaussian likelihood assumption. We are actively working towards a model that will work better for "small count" data such as this (a negative binomial likelihood). I plan to get it out this summer, but in the meantime there aren't really any good options for very sparse data like this.

That said - even if we did have the appropriate likelihood for small-count data, it would still not do anything really great on this time series because there just isn't much to learn. There's not going to be a chance for the model to learn a trend or seasonality when there's so little data, so the best you'd be able to hope for is that it would predict the average sales frequency. And that's something you can just do on your own without having to fit models.

Something you might consider for a setting like this would be to try and aggregate data further, either across locations or SKUs, so that you can fit a model to a time series that actually has some structure to it (seasonality in particular). Let's say you aggregated across locations and that allowed you to get good forecasts at the level of SKU (e.g. fit seasonality). Then, you could try to forecast just the proportion of that total at each location, for instance you could see if the simple approach of a piecewise linear function with no seasonality would work for that. That might give you a way to propagate the seasonality from the aggregate down into the individual level forecasts, where the data are too sparse to estimate it independently.

**Comment by ivangvi** [comment]
Amazing bletham, thank you for your reply. I'm glad you are always working towards improving the algorithm! Take a look at this other problematic series, with and without 0-count filling:

![git1](https://user-images.githubusercontent.com/30244899/83765774-f919c980-a651-11ea-9894-d4e14023cbee.JPG)

As you can see, the last forecast goes skyrocket. I explored this particular SKU because I was testing performance for log(y) model variation, and performance was much worse. This happens because on these kind of SKU series, the log/exp transform even goes further up and MAE gets absolutely trashed. See same series with log(y), image applying exp(y) after prediction and you get the idea of what's happening:

![git1b](https://user-images.githubusercontent.com/30244899/83766104-5a419d00-a652-11ea-99ee-5ceb0b8f1a9b.JPG)

So then I proceeded to fill 0s and this is what you get:

![git2](https://user-images.githubusercontent.com/30244899/83766438-d1773100-a652-11ea-8d4b-9ee807643d3a.JPG)

Forecast for last date looks actually below 1. I suspect a good solution could be to do the 0 filling at training and coercing to 1 or 0 as a minimum yhat after forecast. Maybe from a business standpoint a 1 would be better. Another solution, as you said, would be to at some threshold determine that the series doesn't have enough data and just go for the average. 

Interesting idea regarding aggregations, yes that could work as well. I have my doubts though on how to build the second proportion model, since that second model itself will now be the one with little data to work with. Maybe averaging proportion over time.. I'm unsure. To be honest I don't really know what you mean with a simple piecewise linear function approach.

Thank you for your thoughts, I hope the little data I shared can help further development of the project. Let me know if there's more I can share that would be useful.

**Comment by bletham** [comment]
Those first two forecasts surprise me a bit. Have you by chance forced on yearly seasonality? That's the sort of thing I've seen when seasonality is overfitting badly because there's less than a year of data.

**Comment by ivangvi** [comment]
No, I haven't touched a single parameter actually, and as you can see there's no yearly component:

![git1](https://user-images.githubusercontent.com/30244899/83931797-f5329800-a774-11ea-85cd-7556d00ed7ee.JPG)

![git2](https://user-images.githubusercontent.com/30244899/83931799-f663c500-a774-11ea-8e80-099f3467b6de.JPG)

**Comment by ivangvi** [comment]
Thank you @bletham! I will try that.

On the other hand, just to comment on the thread's subject, filling with 0's every series didn't improve my results. Maybe I can improve by looking more closely at what kind of series I have, how they perform with different processing schemes and setting certain thresholds such as disabling weekly seasonality for low data points, and even do fill some kind of series with 0's.

**Comment by gmverdon** [comment]
> Prophet isn't going to do very well on time series like this one. Yes, the correct thing to do would be to fill in 0s for the days where the sales were 0. But Prophet will still do poorly on such a time series; it generaly does poorly on time series that are mostly 0 with occasional non-zero points because it violates the Gaussian likelihood assumption. We are actively working towards a model that will work better for "small count" data such as this (a negative binomial likelihood). I plan to get it out this summer, but in the meantime there aren't really any good options for very sparse data like this.

Is this already implemented? I am having exact this use case.

**Comment by swati536** [comment]
I have ecommerce sales would like to use FB Prophet for Forecast have channel Shopee and total 60 product category are there have missing dates haven;'t filled missing dates with 0 my MAPE is 46% what more can I do to improve accuracy
