### ISSUE TITLE
Yearly seasonality disappearing

### ISSUE THREAD

**Issue by Barbusse** [facebook/prophet#1535]
Hi

I am using prophet to forecast on my data and I found that yearly seasonality is not respected and disappears from my forecast when I add a single point on my data. I only have yearly seasonality with no others seasonality. My aim is to forecast 2020 (with the missing values) with that single point in December 2020.

I have data going for each Monday starting from 2010 with a gap between june 2020 and December 2020 and then a single point then nothing.

The shape of the forecast doesn’t fit the yearly seasonality with the addition of this single point.

How could I fix that strange behavior ?

Here is the output without the point :
![graph1](https://user-images.githubusercontent.com/49550766/84166297-016c6d00-aa75-11ea-887d-1872e5c5e845.png)

And the output with the point :
![graph2](https://user-images.githubusercontent.com/49550766/84166303-029d9a00-aa75-11ea-8d70-77beeb7ac561.png)

Thank you for your help

**Comment by bletham** [comment]
I'm pretty sure what's happening here is just a matter of the plotting. When you call
```
fcst = m.predict(future)
```
it will make predictions only for the dates in `future`. It looks like here there are some missing dates between the the last date in the first figure and the new point added in the second. The model thus is not making any predictions for those points.

When you call `m.plot(fcst)`, it plots the forecast for whatever points were forecasted for. But matplotlib will connect the points with straight lines. So that's what's happening here. If you want to see the actual forecasts for those dates, you need to pass in the full set of dates to `predict`. For instance, something like
```
future = pd.DataFrame({'ds': pd.date_range(start='2011-01-01', end='2021-06-01')})
```
with whatever the right dates are.

**Comment by Barbusse** [comment]
I also thought I didnt specify the right dates but they truely are in the future dataframe.

Here is a picture of the dataframe below.

In red, there is the single date I added in the training set.

As you can see, all the dates are specified.

![image1](https://user-images.githubusercontent.com/49550766/84471998-c80b4b80-ac86-11ea-9290-69de1a293822.png)

**Comment by bletham** [comment]
hm can you look at the dates in the forecast dataframe (the output of `predict` that is being passed to `plot`)?
```
forecast['ds'].tail(100).values
```
and also
```
m.history.tail(3)
```
