### ISSUE TITLE
Different Forecast Outputs

### ISSUE THREAD

**Issue by ahash52** [facebook/prophet#1536]
Hi @bletham,

I am getting different prophet outputs on mac vs pc. Any reason why?

I already took a look at this link: [here](https://github.com/facebook/prophet/issues/253)

We tried algorithm = 'Newton' and it doesn't seem to change our outputs. Any way we can get the outputs to match?

Thank you.

**Comment by bletham** [comment]
As described there, this comes down to differences in the Stan optimization due to the underlying libraries. There's more description of this here:
https://discourse.mc-stan.org/t/under-what-conditions-should-i-expect-stans-optimization-to-be-deterministic/12496

As discussed there, there probably isn't a way to get things to be exactly the same on different platforms.
They also note that cross-platform differences will be larger for ill-conditioned problems. Prophet fitting can easily be ill-conditioned on very small datasets. You can improve the conditioning and thus possibly reduce the cross-platform differences by removing parameters from the model. Reducing the number of changepoints, removing seasonalities, and removing holidays are things that would potentially improve model conditioning by removing parameters. Reducing the seasonality and changepoint prior scales would also add some shape to the likelihood surface and potentially improve optimization.

**Comment by ahash52** [comment]
Thank you Ben for getting back to me so quickly. This was helpful. Please
keep up the good work. Loving the package!
