### ISSUE TITLE
Holiday regressor, Extra regressor - specify values/parameters

### ISSUE THREAD

**Issue by sipro1** [facebook/prophet#1543]
Hello there,

I have a dataset of 10minute frequency over nearly 5 months. I have weekly and daily seasonality and no noteworthy trend. 
I used holiday effects because the values of the data are much lower on holidays than on non-holidays. In the plot_components function the holidays are shown. I used a train/test data split to verify my model. The original data has a range of 0 to 100 (%) and on those specific holidays-dates the value is close to 0/or 0. The original data shows that. But the modeled data (train and test) on those holiday-dates is not 0/close to 0. 

How can I specify that for those holiday dates the values are usually around 0? 

I tried to use an extra regressor. So I created an additional column in my dataframe (and also future dataframe) that will have the value -1 if the data is on a date, which is a holiday-date. 
Otherwise the value is 0. It has little to no effect on the modelled data. I tried setting the value to -20 or -100 instead because I was hoping it would put more weight on it if I use more negative values. Still little to no effect.
I then tried to add a prior scale weight equal to holiday weight (by default 10)
`model.add_regressor('regressor', prior_scale=10)`
But still no to little effect.

Does anyone have any idea how I can solve my problem, so that the values on those holiday-dates are put to small values?

Thanks a lot! Any advice is much appreciated.

**Comment by bletham** [comment]
To be sure I understand correctly: In the data (both training and test) the `y` on the holiday is close to 0. You added a holiday in the model for that date, but the model is not predicting values close to 0 (in both the training and test sets). Is that right?

The normal usage for holidays would be to fit the effect of a particular holiday each time it occurs. So for instance, I add "Christmas" as a holiday to the model. Under the hood, this is equivalent to adding a binary regressor for "is_Christmas" that is 1 if it is Christmas and 0 otherwise. Then, the model will fit the effect of Christmas. The fitted holiday effect is an offset on top of whatever the seasonality effect is, and the model assumes that this is constant for every instance of the holiday.

Since you have only 5 months of data, it sounds like you are merging all of the holidays into a single regressor. The model will then have to fit a single, fixed holiday effect for all holidays. This probably won't work because not all holidays will have the same effect size, and so the model will end up fitting something like the average effect size. Even if the end result is the same for all holidays (y=0), the holiday effect size is the difference between 0 and what it would have been normally (trend + seasonality), and that will be different at different holidays that may have different seasonal effects.

That's one thing that may be happening. The other is that if you have strong daily seasonality, the fitted holiday effect will be a constant offset to that daily seasonality. If you need it to be flat on the holiday, then you'll need to fit a separate daily seasonality for the holiday days (along the lines of what is done here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors ).

If you share some plots I might be able to provide some more tips. But generally, I'd say that if you know that the prediction should be 0 on holidays, you might be best off just specifying that explicitly by removing holidays from the training data, making predictions, and then replacing the holiday predictions with 0.

**Comment by sipro1** [comment]
Hello @bletham 
Thanks a lot for your answer!
Yes you are right I defined a few holidays like this:
`Holidays1 = pd.DataFrame({
  'holiday': 'Holidays1',
  'ds': pd.to_datetime(['2020-01-03', '2020-01-08', '2020-04-20']),
  'lower_window': 0,
  'upper_window': 0,
})`
--> Holidays defined like this are for example Christmas Day. 
And also a few holidays with upper_window (because it's a longer vacation, one or two weeks in most cases; for example Christmas Vacation) --> during the whole vacation period the values do not get to 0, but it definitely influences the graph (with lower values than usual). During the single Day holidays the values are close to 0 or 0 though.

After defining those holidays separately I combined them with `holidays=pd.concat((......))`

> Since you have only 5 months of data, it sounds like you are merging all of the holidays into a single regressor. The model will then have to fit a single, fixed holiday effect for all holidays. This probably won't work because not all holidays will have the same effect size, and so the model will end up fitting something like the average effect size. Even if the end result is the same for all holidays (y=0), the holiday effect size is the difference between 0 and what it would have been normally (trend + seasonality), and that will be different at different holidays that may have different seasonal effects.

So you are saying that by merging all different kind of holidays (those that are only one day and therefore have values close to zero and those that are a few days/or weeks and therefore have values lower than usual but not equal or close to 0) all of the single holiday effects get averaged right?

> That's one thing that may be happening. The other is that if you have strong daily seasonality, the fitted holiday effect will be a constant offset to that daily seasonality. If you need it to be flat on the holiday, then you'll need to fit a separate daily seasonality for the holiday days (along the lines of what is done here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors ).

That would make a lot of sense! Thanks! I do have a strong daily seasonality. I will have a look into what you sent me. Do I have to disable the "normal" daily seasonality for the holidays then, or is it enough to add a new seasonality for my holiday dates?

> If you share some plots I might be able to provide some more tips. But generally, I'd say that if you know that the prediction should be 0 on holidays, you might be best off just specifying that explicitly by removing holidays from the training data, making predictions, and then replacing the holiday predictions with 0.

One question regarding the above: If I replace the holiday predictions with 0, why would I remove the holidays from the training data then? What I mean is it wont make a difference if I do not remove the holidays, because I am replacing it in the modeled data anyways - right?
I will share some plots after I tried the methods you suggested.

Thanks again!

**Comment by sipro1** [comment]
Hello @bletham 

I tried to use your advice to change my model. 
I did the following:
- I defined the days that were holiday-dates and created a separate daily seasonality for working days and another one for holidays.
`model = Prophet(weekly_seasonality=40,daily_seasonality=False,changepoint_prior_scale=0.5) 
model.add_seasonality(name='Working_Day', period=1, fourier_order=40, condition_name='Working_Day')
model.add_seasonality(name='Free_Day', period=1, fourier_order=40, condition_name='Free_Day')
model.fit(train)`
This would be the plot:
<img width="956" alt="Bildschirmfoto 2020-06-18 um 16 29 04" src="https://user-images.githubusercontent.com/67048567/85033114-de327380-b180-11ea-8535-4e3d05bd5e69.png">

--> I marked the holidays red, so as you can see the model does a good job detecting them and assigning them low values. Do you know how I can get those values even lower (as I said: Close to zero or zero)? 

And this would be the components:
<img width="544" alt="Bildschirmfoto 2020-06-18 um 16 33 23" src="https://user-images.githubusercontent.com/67048567/85033649-7c263e00-b181-11ea-818f-4ab6782d68d3.png">
--> What surprises me is, that the Working Days and Free Days seem to have a similar shape, only inverse. What I would want to achieve is that the curve for the Free Days (Holidays) is flat, so it won't have those big values and stay close to zero. 
--> Also I marked some of the Weekends and what also surprises me, that the weekends are not exactly zero, even if the training data mostly shows zero on Weekends. 

Also: As the model also shows negative value, I am wondering if some kind of overfitting is maybe happening? I could not find a way to remove those negative values, wo I just did a simple code saying: if there are negative yhat values I put them to 0. Is there another way?

Also: As you can see, some of the higher datapoints are completly missed out by the model (this was also the case before using the alternative seasonality). Is there any way to change that?

I was thinking about adding more separate seasonalities to the Holiday-Workingday-Daily-Seasonality. Out of your experience would it make sense to add the following:
- A seperate daily seasonality for Weekdays and Weekends
- As I said in my comment before, parts of the data is from vacation-weeks (like Christmas Holidays or Easter Holidays etc.). The Duration of those holidays is not the same for every holiday. But there in the holidays the values are a bit smaller than during non-holidays weeks. Would it make sense to do a seperate weekly seasonality for the vacation-weeks and non-vacation-weeks?
- Considering I am using all of the above: What happens in the model, if one date for example is a single free day but also lies in one of the holiday-weeks. The date is influenced double in this case, right? Could that be a problem?

And last question: In the plot above I used only the seperate seasonality and not holiday effects.
Did I get it right, that by defining a holiday for the model, you are basically telling it to treat those dates differently than the rest of the data? So I am basically doing the same with the specifying the different seasonalities, right? Therefore I would not need the holiday effects.

Sorry for those many questions! Thank you so much in advance!

**Comment by bletham** [comment]
Sorry for the slow reply, let me try to unpack some of your questions here.

But first - is there any chance you could upload a CSV of the data for this time series? It would be a very useful test case for the new model that we are developing in #1500 , and I'd love to try that out on this time series and see if it works better.

OK, so first a couple general comments.
- This type of time series where the data are relatively small integer counts is an area where the model can struggle because the assumption of additive Gaussian noise isn't very accurate. The new model we're working on in #1500 will hopefully do better, but in the meantime there are some things that I think will help.
- Looking at the trend, it's fitting a flat trend value of about 10. You'll notice that the trend line is a bit wiggly, and the uncertainty grows really wide really quickly into the future. This is because the changepoint prior scale was set to 0.5, a relatively large value that gives the trend a lot of flexibility. More flexibility than is needed here, it seems to me. I'd crank that down a bunch (probably back down to the default value) since we don't need to be capturing those types of small fluctuations with the trend.

- Can the model capture those higher peaks that are currently missed: The model assumes that the seasonalities are stable over time, here that `y(t) = trend(t) + daily_seasonality(t) + weekly_seasonality(t)`. In this time series, the magnitude of the daily seasonality is not constant rather it's different in different weeks. You might be able to capture this better by using multiplicative seasonality (both for daily and weekly), which would make the model `y(t) = trend(t) * (1 + daily_seasonality(t) + weekly_seasonality(t))`. Then the model might be able to increase the trend a little bit in order to increase the effective magnitude of the seasonality. I think that's the best you could do here to capture that effect; otherwise, the model has no way of knowing why daily seasonality was higher in the 5th week than it was in the 2nd week, and so won't be able to capture that. That said, multiplicative seasonality may not be enough to capture this well since the trend really does appear flat. There's a banding in the data, where values tend to be 0, ~10, or ~16, and that banding is really stable across the entire time series.

- Weekends not totally pushed to 0: This is probably because of the additive nature of the model. Basically it will be fitting `weekly_seasonality` and `daily_seasonality` to try and offset `trend`, but since `trend` is itself fluctuating, it will not be able to do that perfectly consistently. Multiplicative seasonality would probably help with this. Setting up a separate weekend daily seasonality could also help as you suggested. But if you know they're always 0, just replacing them with 0 would probably make the most sense.

- Handling negative values: This is something that the new likelihood in #1500 should do much better (it will not predict negative values), but in the meantime, just replacing them with 0 is totally acceptable.

- Free_Day shape: That is a bit surprising. I wonder if it might be interacting with another seasonality in an unexpected way. Just to be sure, are the Free_Day and Working_Day indicators in the history dataframe totally disjoint? As in, there aren't any datapoints for which they're both 1? Assuming they are disjoint, I wonder if there is something weird going on in the weekly seasonality. I noticed that the Fourier order for weekly seasonality was set at 40. This is a _very_ large number; it means that 80 parameters are being used to estimate weekly seasonality. The weekly seasonality shown in the components plot shows just the point for each day, but it is in reality a continuous function. You can plot the full weekly seasonality like this:
```
from fbprophet.plot import plot_seasonality

plot_seasonality(m, 'weekly')
```
With order=40 and 80 parameters, the weekly seasonality has enough flexibility to start capturing daily seasonal trends, which is what I suspect is happening here. I'd recommend turning that number down substantially, to something more like 10 or less.

- The nature of the holiday effect is a little odd to me also though; for the first holiday that you marked the time series doesn't drop all the way down to 0, but for the next 2 it does. I don't know if this is just because of missing data, in which case it isn't an issue, but if it is because the shape of the holiday effect is different every time, then the model won't really be able to capture that well.
