### ISSUE TITLE
Extra regressor- How to change the direction of influence on data

### ISSUE THREAD

**Issue by Bombadilll** [facebook/prophet#1545]
Hello.
First of all, I want to thank you for the wonderful Prophet that you made for everyone.
I also want to ask you for help. I have been working with the prophet for half a year and have experienced all possible and impossible options for working with him. I came to the conclusion that to successfully predict my data model, I need a regressor that changes the direction of influence on the forecast.
In fact, the regressor is a temperature value, the whole year except for the summer, the regressor works correctly (increasing the temperature reduces the forecast). But only in the summer it is necessary on the contrary, an increase in temperature should increase the forecast.
I tried a lot, but without this I can’t get it.
This is very important to me and you are my last hope. Thank you in any case for all that you have already done.

**Comment by Bombadilll** [comment]
model = Prophet(growth="logistic", daily_seasonality=False,  
                weekly_seasonality=False,
                yearly_seasonality=False,
                seasonality_mode='multiplicative',
                seasonality_prior_scale=0.01,  
                mcmc_samples=0,  
                interval_width=0.8,  
                changepoint_prior_scale=0.03,  
                changepoint_range=1.0, 
                n_changepoints=64, 
                holidays_prior_scale=0.008,
                holidays=specialDays)  
model.add_seasonality(name='yearly', period=365.25, fourier_order=12,prior_scale=0.001)
for i in range(1, 13):
   model.add_seasonality(name=str(i)+'monthly', period=30.5, 
           fourier_order=2,condition_name=str(i)+'m',prior_scale=0.005)
for i in range(1, 13):
    model.add_seasonality(name=str(i)+'weekly', period=7, 
               fourier_order=4,condition_name=str(i)+'m', prior_scale=0.013)
for i in range(1, 13):
    model.add_seasonality(name=str(i)+'day', period=1, fourier_order=22,condition_name=str(i)+'m', prior_scale=0.01)
model.add_country_holidays(country_name="UA")
model.add_regressor(name="temperature", prior_scale=0.002, mode='multiplicative',
                    standardize=True)
Its my model.)

**Comment by bletham** [comment]
Sorry for the slow reply! To be sure I understand, in your time series temperature is an extra regressor. In Fall/Winter/Spring, an increase in temperature corresponds to a decrease in y. In Summer, an increase in temperature corresponds to an increase in y.

As you have discovered, this behavior will not be directly captured by the model. All regressors in Prophet are linear regressors, meaning the model is something like:
```
y(t) = trend(t) + seasonality(t) + beta * temperature(t)
```
where beta is a coefficient fit to the data, and is constant. You want beta to be positive in the Summer, and negative the rest the year, but in Prophet it has to be constant. Basically, y does not depend linearly on temperature.

How to get around this: you'll have to do a bit of manual effort to get this behavior into the model, basically some feature engineering. Instead of using temperature directly as the regressor, you'll want to replace it with something that you think would be correctly modeled with `y(t) ~ beta * regressor(t)`, meaning, y is linearly related to the regressor. For instance, something like `regressor(t) = abs(temperature(t) - 70)` would have the property that for temperatures below 70 (F of course) y would decrease as temperature increases, but for temperatures over 70 y would increase as temperature increases. You'd have to figure out the correct threshold, of course.

If the switch in behavior is a function just of time and not of temperature, then you could do something like creating two separate regressors "temperature_winter" and "temperature_summer", and letting the model learn the correct sign for each of them. You'll have to be a bit careful with this. To construct temperature_winter, you'd want to do is take the temperatures just for non-summer dates, standardize them (subtract mean divide by std), and then in your history dataframe include that as the regressor value for all of the winter dates and set it to 0 for all of the summer dates. For temperature_summer you'd do the opposite: take all of the summer dates, standardize them, use that as the regressor value for all of the summer dates and then fill in with 0 all of the winter dates. The standardizing part is important because temperature_winter will have to have a value for the summer dates, and 0 would only be a sensible choice if you had standardized the others. It'll possibly take a bit of fiddling to avoid a discontinuity with this method.

So those are two possible approaches, but generally you'll have to replace "temperature" with a new feature that you've engineered to be linearly correlated with y.

**Comment by Bombadilll** [comment]
Thank you so much. It helped a lot. I thought so. I chose the second option - according to the season. I just wanted to clarify about temperature standardization. You mean to standardize separately or with a regressor option, like this:
model.add_regressor (name = "temperature", prior_scale = 0.002, mode = 'multiplicative', standardize = True)
You can write a short example with data and temperature standardization. Thanks in advance.

**Comment by bletham** [comment]
No, I meant that you would need to manually standardize rather than using the built-in standardization, though thinking more about this, I'm not exactly sure what the right scaling will be. The challenge will be that if you split temp out into winter vs. summer, you have to have a default value for when it isn't that season. Basically, the model would be
```
y(t) = trend(t) + seasonality(t) + beta1 * winter_temp(t) + beta2 * summer_temp(t)
```
winter_temp(t) would be the temperature in the winter, but then some constant in the summer (so that it won't be changing the prediction value). My original thought was that if you standardized the temps just of the winter months then you could set it to 0 during summer months, but I'm no longer sure that would work. Maybe what you'd want to do instead would be to use the temp at the change in season as the value when that season isn't active. Like this, if 5/1 is the switch from winter to summer and 70 is the typical temp then:
```
ds                   winter_temp   summer_temp
2020-04-28    60                   70
2020-04-29    64                   70
2020-04-30    62                   70
2020-05-01    70                   68
2020-05-02    70                   72
2020-05-03    70                   71
```
The first option might be easier, but in either case it's going to take some manual feature engineering to figure out something that works, I think it would depend alot on the data and I'm really not sure.

**Comment by Bombadilll** [comment]
Thank you very much for your prompt reply.) I agree with you.  The built-in standardization did not give good results, I had to turn off the "winter regressor" as it affected the value in the summer.  I think manual standardization will be the same.  You know, if you saw my model, you would laugh, it looks like a big monster which is better not to touch.) There is a lot of everything in it and sometimes I myself begin to get lost.  I will try to implement the first option, since zero is always zero, but not in this case))).  I will write on the result if you are interested.

**Comment by bletham** [comment]
Yeah, I'd be interested to hear if you end up finding something that works! Good luck.

**Comment by hansukyang** [comment]
Hi @Bombadilll - are you working with electricity data by chance? I work with this type of data quite frequently where decrease in temperature in winter leads to an increase in power consumption for heating and obviously in summer, increase in temperature also leads to higher electricity consumption due to air-conditioning. 

What @bletham explained in [this comment](https://github.com/facebook/prophet/issues/1545#issuecomment-657911208) (Option 1) works very well as it emulates what we call [heating degree days and cooling degree days](https://en.wikipedia.org/wiki/Heating_degree_day). You'd want to add a slight change though, where you set something like:

`cooling_regressor(t) = min(temperature(t) - 70,0)` and
`heating_regressor(t) = min(70 - temperature(t),0)`

This way, both regressors have values throughout the year and zeroed when they shouldn't be affecting the load. As mentioned, the threshold would have to be tweaked.

**Comment by Bombadilll** [comment]
Thanks a lot for your help.  It helped a lot in understanding.  You are wonderful and helpful professionals.  I was pleased to communicate with you.  And again I thank you for sharing your work and experience with the world.

**Comment by hansukyang** [comment]
You're very welcome! I just noticed I had the min/max mixed up so have updated my comment above.

**Comment by Bombadilll** [comment]
Joseph excuse me for my insolence. Yes, I also do electricity forecasting. I would like to ask you to share your experience with me. I have a few questions for you:
1. How do you implement the maximum dependence of pronoz on the latest data. For example: in recent days, the consumption of electricity has increased, but this does not significantly affect the prophet's forecast. In reality, the forecast is very different from the fact (bad forecast).
2. How do you implement a dramatic increase in consumption (surge). For example: it is a very hot day in summer, or very cold in winter.
I have a lot of such days, I realized this through the holidays (in the "prophet").
3. How to implement a previously known decrease in consumption in the forecast. For example: last year we had 1000 consumers and 10 million kW of electricity per day, and this year we have 900 consumers and 9 million kW of electricity per day. How to reflect in the forecast that the initial value has changed by a known number of kW, percentage.
Moreover, could you send a piece of code with an example on temperature regression. I'm afraid I will be mistaken if I do not understand you correctly, it will take me a lot of time.
Thank you in advance, here is my mail if it is convenient for you: [bombadilium@gmail.com](url)

**Comment by hansukyang** [comment]
Hi - so that I can understand your forecasting case better, what is your forecasting horizon? If you're making day-ahead to about 2~3 days in advance, is the prediction still very far off? What is the error range?

Peak summers and peak winters are in general somewhat tricky but this should be handled by Prophet just fine and the quality of your extra regressors will come into play here (perhaps relevant to your Q1 & 2) so do ensure that the temperature values are valid. Another trick to help with peaks is to use less data (i.e. only the past 3 months), and this is actually another way of isolating winter vs. summer temperature influences.

For the known decrease in consumption, I believe this should be what Prophet trends were designed for. Even though logistic growth seems to make sense for electricity grid load, I find that simple 'linear' growth works better and this should have captured the long term reduction in usage.

The way you have set up regression is not too different from mine:

 `m.add_regressor(ext_regressor, mode = 'multiplicative')`

**Comment by Bombadilll** [comment]
Hello, thank you for not forgetting about me and answering me.
In general, I'll start to tell:
1. I make an hourly forecast 4 days ahead, sometimes 6 days. (24 hours for 4-6 days)
2. basic data - 1 year with periodicity of 1 hour.
3. Range of errors:
      - hourly - from 0.3% to 5%, rarely 6-8%, in the worst case up to 10%
      - per day - from 0.3% to 3%, rarely up to 5%, very rarely 8-10%
      - per month - 0.4% - up to 1.5%, once it was about 3%
                           Good forecast:
![image](https://user-images.githubusercontent.com/18697755/92309257-a8956d80-efac-11ea-9b75-b41d9251aed6.png)
                       It got very hot:
![image](https://user-images.githubusercontent.com/18697755/92309445-42a9e580-efae-11ea-9957-97651d9a53a9.png)
                     It 'linear' growth not an accurate forecast at all:
![image](https://user-images.githubusercontent.com/18697755/92309879-cfa26e00-efb1-11ea-9fac-1214382ce088.png)
Initially I worked with 'linear' growth, but after 3 months of testing I tried logistic growth and it gave a much better result. According to my observations, "linear growth" averages and fits the model to all the initial data (in my case for 1 year).
These graphs and percentages are based on the model without regression. He realized temperature influences in the form of "holiday days" of the prophet. Regresor on your advice so far I can not understand how to implement. All I understood is that instead of the real temperature in the data frame for the "prophet", you need to insert "your formula" about which you wrote about (and also insert the threshold temperature value when the regressor should not work, as Ben wrote). And then create a regressor based on this reworked temperature frame.
If it's not difficult, please send me an example with the code, otherwise the words do not really work out for me.
I implemented what Ben wrote according to the season, but this did not give positive results - with an increase in temperature, the forecast increased but not significantly (did not correspond to the actual growth), and when the priority scale of the temperature regressor was increased, there was too much growth, which also did not correspond to the fact. Here is the code and data:
`model.add_regressor(name="temp_winter", prior_scale=0.003, mode='multiplicative',
                                    standardize=True) 
model.add_regressor(name="temp_summer", prior_scale=0.003, mode='multiplicative',
                                   standardize=True) `

ds | y | temp_summer | temp_winter | floor | cap
-- | -- | -- | -- | -- | --
29.05.2019   21:00 | 513839 | 0 | 18,8 | 467833 | 603276
30.05.2019   22:00 | 531841 | 0 | 18,8 | 487680 | 627907
31.05.2019   23:00 | 534758 | 0 | 18,8 | 490086 | 652319
01.06.2019   0:00 | 416979 | 19,2 | 0 | 376518 | 449420
01.06.2019   1:00 | 350931 | 19,2 | 0 | 323555 | 390255
01.06.2019   2:00 | 315802 | 19,2 | 0 | 291636 | 357458

If I understood you correctly, do you offer such an option?

ds | y | temp_summer, C   (fact) | temp_winter, C   (fact) | heating_regressor | cooling_regressor | floor | cap
-- | -- | -- | -- | -- | -- | -- | --
29.05.2019   21:00 | 513839 | 15 | 18,8 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 467833 | 603276
30.05.2019   22:00 | 531841 | 15 | 18,8 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 487680 | 627907
31.05.2019   23:00 | 534758 | 15 | 18,8 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 490086 | 652319
01.06.2019   0:00 | 416979 | 19,2 | 15 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 376518 | 449420
01.06.2019   1:00 | 350931 | 19,2 | 15 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 323555 | 390255
01.06.2019   2:00 | 315802 | 19,2 | 15 | =   max(15 - temp_summer,0) | =max(temp_winter   - 15,0) | 291636 | 357458

and such a regressor code:
`model.add_regressor(name="heating_regressor", prior_scale=0.003, mode='multiplicative',
                                    standardize=True) 
model.add_regressor(name="cooling_regressor", prior_scale=0.003, mode='multiplicative',
                                   standardize=True) `

I am waiting for your opinion on all this, thanks in advance.

**Comment by hansukyang** [comment]
Hi - thanks for sharing. It seems like heating and cooling electricity usage make up a relatively small percentage of your total consumption and the accuracy that you're getting would be considered quite good in North American cities where cooling energy consumption can make up more than 50% of total electricity consumption. 

For comparison, what I have looks somewhat like this, probably even simpler than what you have:

```
df['HDD'] = df.apply(lambda row: max(15-row['temperature (degC)'],0),axis=1)  # Heating degree day
df['CDD'] = df.apply(lambda row: max(row['temperature (degC)'-15],0),axis=1)  # Cooling degree day

m.add_regressor('HDD',  mode = 'multiplicative')
m.add_regressor('CDD',  mode = 'multiplicative')
```
One thing I have noticed is that your temperature data seems somewhat inconsistent, with the value staying constant during each of the three hour periods you showed - can I ask how you're getting the temperature data? The thing with extra regressor is that the quality of the regressor can affect your forecast quite substantially. I can help you look up temperature data if you let me know the approximate location or the city.

**Comment by Bombadilll** [comment]
Thank you Ben and Joseph. You helped a lot. Today I implemented your advice, everything worked out. It remains only to conduct experiments and set the correct coefficients. Everything works as you said. I am very very glad, this is exactly what I have been missing for many months. Thanks a lot.
