### ISSUE TITLE
Step function trend with known historical states

### ISSUE THREAD

**Issue by yavalvas** [facebook/prophet#1547]
I try to model power demand signal as hourly consumption in real power units to forecast next days.
It looks that logistic trend with floor and cap is the most applicable for it, or new flat trend that is still not in a release.
Still, some constantly working device turned on/turned off transitions can be described more precisely by step function with known states from history, so that whenever there is a process of transition, it'll be more probable that it goes to one of previous known states.
Is there a way to describe it with a custom trend or are there any implementations that can be used for it with Facebook Prophet for a custom trend?

**Comment by bletham** [comment]
I think with a bit of modeling effort you could capture this behavior.

To be sure I understand, the trend is piecewise constant, and the value will be one of some small set of known values.

You can fit such a model pretty easily using the flat trend that is in the current github version and will be in the next release. What you would do is use a flat trend, and then add the known historical state values as an extra regressor. An additive regressor will give you a model like
```
y(t) = flat_trend(t) + beta * regressor(t) + seasonality(t)
```
where beta is a coefficient fit to data. So, if you give the known piecewise historic trend as a regressor, you will have the correct trend. The only challenge would be if you need multiplicative seasonality, because the seasonality would be multiplying only the flat_trend and not flat_trend+regressor as you'd want. But if additive seasonality is OK, then this would work.

In the future, you could make predictions for what the forecast will be under different future state values by plugging in different future values for the regressor when calling `predict`. You could manually compute the distribution of state values in the history, and then from that simulate the likely future forecasts and get a distribution of yhat estimates.

Let me know if that makes sense! (and sorry for the slow reply)

**Comment by yavalvas** [comment]
@bletham 
As it looks It makes sense for additive model, I tried "flat" trend when it wasn't in the release but was in the master branch. It looked fine, but the state transfer has to be modeled separately by keeping it in memory. The intuition behind state transfers is that I can have the limited number of states of power in a system for a flat trend and it can be used to predict the next "step" of piecewise constant step function if the prediction is done somewhere during the transition.
Could you please clarify what do you mean by "in the future", will it be implemented in FbProphet, are there any plans for it?

**Comment by bletham** [comment]
Sorry, by "in the future" I meant "for future values".

The procedure I suggested above would allow you to forecast counterfactuals for what forecast you'd expect given the next step.  If you have some distribution for what the next step might be (e.g. it is one of 5 values with equal probability), then you could simulate under each of those and take the average to get an expected outcome. It sounds from your last post like you might be trying to also learn that state transition distribution, which is something that would have to be done externally and not something that Prophet would be able to do itself.
