### ISSUE TITLE
Holidays seasonality without same days measured in the past

### ISSUE THREAD

**Issue by yavalvas** [facebook/prophet#1548]
I have a problem in prediction for the days when there is a holiday, it looks that by default fbprophet fits holidays in way that it needs already existing signal for that day from the same previous holiday from last years.
I have a situation that I don't have that much signal to have repeated holiday yet.
Is there a possibility to use something as averaging seasonality between all other holidays to forecast until the moment when the holiday was measured from the last year?
In my case the signal behaves similar during different holidays.

**Comment by benmwhite** [comment]
Maybe you can try assigning the same name to all the low-sample holidays in your holiday data frame? This way the model will handle them all with the same dummy regressor and will estimate a single effect parameter for all of them. This seems like a decent workaround if it's reasonable to assume a similar signal across the holidays like you mentioned.

**Comment by yavalvas** [comment]
@benmwhite 
Could you please clarify what you mean by "name" in this case with some example?
Let's assume I use holidays in the UK, I have some data at the end of a year, so holidays seasonality in December can be computed and in the data frame I have some columns like:
`..., "Christmas Day 25 December", "Boxing Day: 26 December", "New Year's Day: 1 January", "holidays", ...`

where "holidays" is the column with extracted seasonality from the signal. I have 25 and 26 December holidays passed, I don't have samples for "New Year's Day". What can I try to do in this case to forecast that on "New Year's Day" I'll have a holiday seasonal component value similar to the existing two holidays?

I thought to be able to compute holiday seasonal component for some days ahead that are presented on the horizon which I use to make a prediction as some sort of imputer from historical holidays, calculating mean/median between several last holidays and "extrapolating" holidays component this way.
Is it possible to do it this way?

**Comment by benmwhite** [comment]
@yavalvas By "name" I meant the labels for the holidays in the holiday data frame. For every different holiday label the model actually creates a new regressor variable along your input timestamps that has a value of 1 on that specific holiday and a value of 0 everywhere else. So if you have several different holidays ("Christmas", "New Years", etc.) it will create a new variable for each different holiday and estimate a different effect for each of them. 

To get the model to treat all your holidays as the same effect you can just have a holiday data frame where one column is the dates and the other column just labels them all the same, this way there's only one additional regressor instead of one for each separate holiday. This should give you a similar result to aggregating the separate holiday effects, but it'll be easier since it lets the model backend estimate the effect for you instead of doing manual work after the fitting.
