### ISSUE TITLE
How to install Prophet Python 0.7 tag version?

### ISSUE THREAD

**Issue by ajangus** [facebook/prophet#1549]
I want to install a version newer than the GA 0.6 version in order to test the `parallel` feature within `cross_validation` https://github.com/facebook/prophet/blob/30bcfed91872015ed6b864b29b7886e03e7a87f6/python/fbprophet/diagnostics.py#L61

What's the secret to doing so in Python effectively? I am using Python 3.7.7. Using Anaconda or PIP, I get errors that point to problems for `setup.py`. 

I get the same problem if I run things try to install the entire package for 0.7 at https://github.com/facebook/prophet/releases or even if I zip up the `python` folder within that root directory. 

```
ERROR: Command errored out with exit status 1:
     command: /Users/ayrtonangus/opt/anaconda3/envs/ga-tech-prophet-7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/0w6dbn690b1fqjzyz37tqdb00000gn/T/pip-req-build-asyn7_mg/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/0w6dbn690b1fqjzyz37tqdb00000gn/T/pip-req-build-asyn7_mg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/tg/0w6dbn690b1fqjzyz37tqdb00000gn/T/pip-req-build-asyn7_mg/pip-egg-info
         cwd: /private/var/folders/tg/0w6dbn690b1fqjzyz37tqdb00000gn/T/pip-req-build-asyn7_mg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ayrtonangus/opt/anaconda3/envs/ga-tech-prophet-7/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/tg/0w6dbn690b1fqjzyz37tqdb00000gn/T/pip-req-build-asyn7_mg/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm sure it's something basic... 😸

**Comment by eracle** [comment]
Software version is not even updated on the setup.py file. Check it out [here](https://github.com/facebook/prophet/blob/master/python/setup.py#L122).

**Comment by ajangus** [comment]
@bletham Hopefully this is appropriate, but any ideas on this one? I'm working to submit a paper in the next two weeks and hoping to be able to use the CV improvements checked into master to speed up my parameter tuning 😅 . Thanks in advance.

**Comment by bletham** [comment]
Sorry for the slow reply. The v0.7 tag there is an error, there hasn't been an 0.7 release and that tag was actually just pointing to the same code state at the 0.6 release. I deleted the tag to hopefully not cause more confusion on that matter.

You'll want to just install the latest master branch, which you can get as a zip from https://github.com/facebook/prophet/archive/master.zip or by git cloning this repo.

I can't really figure out what's happening here. I think the first thing to do is be sure that the new package has been installed correctly. In case it isn't clear, what you'll want to do after downloading master branch (and unzipping if you downloaded the zip instead of git clone) is cd into the python directory and run
```
python3 setup.py install
``` 
and that will install the new version. I'd recommend first uninstalling any existing versions just to be sure they don't get installed in parallel and cause confusion. Make sure they're uninstalled by running `import fbprophet`, which should produce an error if it isn't installed. Then after installing the new version, run
```
import fbprophet
print(fbprophet.__version__)
```
and you'll see `'0.6.1.dev0'`. At that point you'll know the new version is installed and working, and I'd expect cross validation to work after that. If it doesn't, then please post some code and we can dig deeper.

**Comment by ajangus** [comment]
That worked like magic @bletham 🧙. 

Could I open a PR to add those instructions to https://github.com/facebook/prophet/blob/master/README.md?

**Comment by bletham** [comment]
Glad that settled it! As for adding this to the documentation, sure, it could be a section after the current sections of installation instruction named something like 'Installing latest development branch".

**Comment by eracle** [comment]
Hey @bletham thanks for this nice library. 
What blocks to release version 0.7?
