### ISSUE TITLE
Plot continuous weekly seasonality with sub-daily data

### ISSUE THREAD

**Issue by anqus** [facebook/prophet#1557]
I have been recreating the plot_component daily and weekly graphs using the forecast dataframe.

```
forecast = m.predict(future)
fig = m.plot_components(forecast)
```

Recreating the daily component is straight forward, as it is repeated for every day in the dataset. So can be plotted as:

```
forecast['daily][:n].plot() 
# Where n = number of readings in 24hr period
```

However, the weekly component is less intuitive. It appears to match that created by plot_components when you choose the component value at 00:00 for each day. So can be plotted as (provided your data starts on Sunday):

```
forecast['weekly'][:n*7:n].plot()
# Where n = number of readings in 24hr period
```

This feels as though the plot is missing out on (n-1)*7 points of data for the weekly component. Would the weekly component be better displayed as:

```
# Plotting the whole component series for 1 week
# Where n = number of readings in 24hr period
forecast['weekly'][:n*7].plot()
```

or

```
# Taking an average for each day of the week
# Where n = number of readings in 24hr period
a = forecast['weekly'][:n*7]
groups = [a[x:x+n] for x in range(0, len(a), n)]
means = pd.Series([sum(group)/len(group) for group in groups])
means.plot()
```

**Comment by bletham** [comment]
You raise a good point. As you note, the weekly seasonality plot shows the seasonal effect at just one point for each day. That happens here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/plot.py#L287-L291

The reason this is done is really historical reasons: When Prophet was first released, it assumed daily data, so it makes sense to consider the seasonality as it will be applied to each day. As you note for sub-daily data, the plot is potentially missing important aspects of the seasonality. What we'd really want in that case is along the lines of the first thing that you suggested, `forecast['weekly'][:n*7].plot()`.

It should be straightforward to change the behavior here to do better. What we'd ideally want is for `plot_weekly` to:
- Identify frequency of the time series dates, as is done here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/forecaster.py#L942-L943
- If frequency is daily, we can generate the plot exactly as is (evaluate weekly seasonality with daily frequency). If not, then use a finer grid, as is done for instance here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/plot.py#L381-L384

That should give us the best of both worlds: With daily data it will continue to show clearly the daily effect, with sub-daily data it will show the accurate weekly seasonality.

**Comment by bletham** [comment]
As a workaround for this for now, you can plot the full (not-daily) weekly seasonality using `plot_seasonality` like this:
```
from fbprophet.plot import plot_seasonality

plot_seasonality(m, name='weekly')
```

In fact, the cleanest solution to this issue would probably be in `plot.plot_components` we could check the data frequency, and then just include frequency >=1 day as a condition in L160 here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/plot.py#L160-L171
so that we just use `plot_seasonality` in that case instead of `plot_weekly`.

**Comment by anqus** [comment]
Sure, I'd like to have a go at fixing this!

**Comment by bletham** [comment]
This is done in #1615 for Py, we'll want to port the same change to R.

**Comment by raffg** [comment]
While investigating https://github.com/facebook/prophet/issues/1693, I came across a slight problem with the fix implemented in this issue here. The `plot_weekly` function sets the x-axis label to `Day of week` here: https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L308
but the `plot_seasonality` function sets it to `ds` here: https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L412
So with sub-daily data, the weekly plot will have an x-axis label "ds":
![image](https://user-images.githubusercontent.com/20135094/94374527-c0e73c80-00c1-11eb-8b51-bfa02d4c2b9e.png)

instead of "Day of week":
![image](https://user-images.githubusercontent.com/20135094/94374532-c93f7780-00c1-11eb-8be8-2b6849ad048a.png)

The easiest fix would probably be to add some conditional statements here https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L412

```
if name == 'yearly':
    ax.set_xlabel('Day of year')
elif name == 'weekly':
    ax.set_xlabel('Day of week')
elif name == 'daily':  # see comment below regarding these two lines
    ax.set_xlabel('Hour of day')
else:
    ax.set_xlabel('ds')
```

There's no `plot_daily` function, but for consistency's sake perhaps there should be one so that the daily plot would have an x-axis label "Hour of day" instead of the current "ds".

**Comment by bletham** [comment]
I agree that'd be nice. Right now there is a switch here that determines for formatting for the labels, which is why it produces weekday labels for weekly data:
https://github.com/facebook/prophet/blob/77da5b8c06d05d478af510198c685d454342db1f/python/fbprophet/plot.py#L402-L409

We can just set the correct label in that same statement, including an "hour of day" label for daily data.

**Comment by bletham** [comment]
58a0b96 adds this in R

**Comment by bletham** [comment]
Pushed to CRAN and pypi in the latest v1.0 release.
