### ISSUE TITLE
valueerror lam value too large

### ISSUE THREAD

**Issue by sammathewc** [facebook/prophet#1559]
-------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-72-dca9fb349a7c> in <module>
----> 1 forecast=prophet_basic.predict(future)

C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py in predict(self, df)
   1177         seasonal_components = self.predict_seasonal_components(df)
   1178         if self.uncertainty_samples:
-> 1179             intervals = self.predict_uncertainty(df)
   1180         else:
   1181             intervals = None

C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py in predict_uncertainty(self, df)
   1383         Dataframe with uncertainty intervals.
   1384         """
-> 1385         sim_values = self.sample_posterior_predictive(df)
   1386 
   1387         lower_p = 100 * (1.0 - self.interval_width) / 2

C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py in sample_posterior_predictive(self, df)
   1347                     iteration=i,
   1348                     s_a=component_cols['additive_terms'],
-> 1349                     s_m=component_cols['multiplicative_terms'],
   1350                 )
   1351                 for key in sim_values:

C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py in sample_model(self, df, seasonal_features, iteration, s_a, s_m)
   1412         Dataframe with trend and yhat, each like df['t'].
   1413         """
-> 1414         trend = self.sample_predictive_trend(df, iteration)
   1415 
   1416         beta = self.params['beta'][iteration]

C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py in sample_predictive_trend(self, df, iteration)
   1449         if T > 1:
   1450             S = len(self.changepoints_t)
-> 1451             n_changes = np.random.poisson(S * (T - 1))
   1452         else:
   1453             n_changes = 0

mtrand.pyx in numpy.random.mtrand.RandomState.poisson()

_common.pyx in numpy.random._common.disc()

_common.pyx in numpy.random._common.check_constraint()

ValueError: lam value too large

how can you fix this error?

**Comment by bletham** [comment]
It is erroring out while estimating future trend uncertainty. This can happen when the time period for future predictions is way longer than the history; like 1e20 times longer. Here is how you get the error:
```
>>> import numpy as np
>>> np.random.poisson(1e20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 3262, in numpy.random.mtrand.RandomState.poisson
  File "common.pyx", line 814, in numpy.random.common.disc
  File "common.pyx", line 378, in numpy.random.common.check_constraint
ValueError: lam value too large
```

You should obviously never be making forecasts for a future window that is 1e20 times longer than the history, so I expect there is an error in how either the future dates or history dates were represented.

In particular, take your history dataframe (which I'll call `history`) and convert the `ds` column to dates, and see what they look like:
```
history['ds'] = pd.to_datetime(history['ds'])
print(history.head())
print(history.tail())
```
I'm guess that those are not being converted into valid datetimes. You'll need to change the formatting of `history['ds']` so that it converts correctly to datetimes.

You can do the same thing for `future`:
```
print(future.head())
print(future.tail())
```

If you don't see what the issue is after looking at the `ds` column in those dataframes, please post here the output of those print statements and I could help further. Also, sorry for the slow reply.
