### ISSUE TITLE
Some puzzles of Prophet in mathematics.

### ISSUE THREAD

**Issue by ZaVang** [facebook/prophet#1563]
Hi, I'm a college student who is now using Prophet to work on my intern program. I've met some problems while using the package. Then I read the paper and come up with some problems. Here're my questions:

1. I think the change point in fitting linear trend is a really good idea, which allows the logistic growth model to fit any trend of the data. But I can't see how it influence the future prediction since we can not set the future change point. In my personal view, I think maybe setting change points can help fit other items (holidays and seasonality) better?  But sometimes if the data don't show obvious periodicity, so why don't we just fit them piecewisely?

2. In prophet model, we adjust the growth k on change points and then we can calculate the offset parameter m by setting the right and left limits equal. We can do that because we set the carrying capacity C fixed. But what if we don't set it fixed? We then have two variables m and C. We can calculate m and C by setting both right and left limits and derivatives equal.  It will make the fit curve smooth and let the trend change slowly.  Do you think it is an appropriate idea?

3. Every time when I try to add some holiday items by myself, the program just refuses to respond for a long time without printing error. But if I don't use the holiday item, it will soon output a result. I am wondering if the holiday items really effect a lot.

By the way, I came up with question 2 for the following reason:
I try to use the historical DAU (daily active users) data to predict the future DAU. The curve of DAU is just like the density function of chi-square distribution (first increase rapidly and then decrease slowly). So I fit the data with function a+b(x+1)*exp(-cx). Absolutely, the curve is smooth everywhere. But the result of prophet is not. After comparing the two results, I find the prophet curve decreases faster than the chi-square curve, which means the result of prophet tends to underestimate the future DAU. One of the reasons I think, is that the prophet model is not smooth. So the derivative changes faster on those points (local maximum or minimum), while smooth function's derivatives on these points is always 0.

Hope to get response as soon as possible.

Thank you!

**Comment by bletham** [comment]
Let me try to answer these as best I can, and sorry for the slow reply.

1. Trend changes model non-seasonal changes in the time series. These are changes that have happened but (unlike something like yearly seasonality) we don't know if or when they might happen again in the future. So the model prediction will project forward just whatever the current trend is. Past trend changes affect the prediction in two ways. First, it will affect the prediction uncertainty. If we saw many large trend changes in the past, we will assume that there may be many large trend changes in the future. We don't know what they might be so yhat is not changed, but it means that we have higher uncertainty for future values. This is calculated by simulating future trend changes, and the uncertainty interval is the distribution over future simulated trends. This is described in the documentation here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend . The other way that trend changes affect the future prediction is by enabling better seasonality estimates. If we assume a constant trend on a time series that does not have a constant trend (like the one in the quickstart, https://facebook.github.io/prophet/docs/quick_start.html#python-api) then the seasonality estimate will be poor. Having flexibility in the trend allows us to separate out the changes that are repeatable and can be useful for predicting the future (seasonality) from those that aren't (trend changes).
2. We assume C is known and not estimated. If it is fixed, then the calculation of m ensures continuity. If it is not fixed, so it is C(t), then the trend will be continuous if and only if C(t) is continuous. Even without changepoints, if C(t) is discontinuous then the trend will be discontinuous. If C(t) varies smoothly then you should find that the trend varies smoothly. For your comment at the bottom, increasing C would cause the trend to increase more quickly prior to saturation, I wonder if perhaps it was too low in the problem you were trying.
3. Holidays are modeled with binary regressors, that are 1 on the holiday date at 0 otherwise. If you add a very large number of holidays then I suppose it could cause performance issues, but this isn't something I've seen be an issue in the past so if you could post some code that produces the issue we could debug further!

Hope that helps, let me know if there are other questions!

**Comment by ZaVang** [comment]
Thanks for your reply! It's really helpful for me to understand. 

1. I think it's a good interpretation. The confidence interval is significantly effected by the change points. When I use it in my program, I don't show the interval in the plot at first because it's too wide. But now I think that's OK because I use the past half of year's data to predict the future half of year's. It should be so wide. 

2. I don't think I set C too low because I set it as the global maximum.  By the way, how do you think if I make the C not fixed, and change it at every change point?

3. I've set a large number of holidays so it didn't work. By your suggestion, I fix my code and it works.

Hope to get your reply! Thanks a lot!

**Comment by ZaVang** [comment]
> Let me try to answer these as best I can, and sorry for the slow reply.
> 
> 1. Trend changes model non-seasonal changes in the time series. These are changes that have happened but (unlike something like yearly seasonality) we don't know if or when they might happen again in the future. So the model prediction will project forward just whatever the current trend is. Past trend changes affect the prediction in two ways. First, it will affect the prediction uncertainty. If we saw many large trend changes in the past, we will assume that there may be many large trend changes in the future. We don't know what they might be so yhat is not changed, but it means that we have higher uncertainty for future values. This is calculated by simulating future trend changes, and the uncertainty interval is the distribution over future simulated trends. This is described in the documentation here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend . The other way that trend changes affect the future prediction is by enabling better seasonality estimates. If we assume a constant trend on a time series that does not have a constant trend (like the one in the quickstart, https://facebook.github.io/prophet/docs/quick_start.html#python-api) then the seasonality estimate will be poor. Having flexibility in the trend allows us to separate out the changes that are repeatable and can be useful for predicting the future (seasonality) from those that aren't (trend changes).
> 2. We assume C is known and not estimated. If it is fixed, then the calculation of m ensures continuity. If it is not fixed, so it is C(t), then the trend will be continuous if and only if C(t) is continuous. Even without changepoints, if C(t) is discontinuous then the trend will be discontinuous. If C(t) varies smoothly then you should find that the trend varies smoothly. For your comment at the bottom, increasing C would cause the trend to increase more quickly prior to saturation, I wonder if perhaps it was too low in the problem you were trying.
> 3. Holidays are modeled with binary regressors, that are 1 on the holiday date at 0 otherwise. If you add a very large number of holidays then I suppose it could cause performance issues, but this isn't something I've seen be an issue in the past so if you could post some code that produces the issue we could debug further!
> 
> Hope that helps, let me know if there are other questions!

**Comment by bletham** [comment]
I've definitely used a not-fixed-C before, for instance if you think about C as being a market size (as is described in https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth ) then if the market is growing, C will be growing. You'll want this to be smooth changes though; when I did this myself, C was increasingly linearly, and this meant that the trend will saturate at C, but then track it upwards. You can experiment around with linear Cs and see what effect it has.

**Comment by ZaVang** [comment]
Ok, I think you're right. Thanks for replying.
