### ISSUE TITLE
Reducing trend growth?

### ISSUE THREAD

**Issue by phamtony93** [facebook/prophet#1566]
I am trying to use Facebook Prophet to predict a company's hosted expenses for a particular software. After making the model, I determine that the trend growth is too aggressive. From a business perspective, it is not possible for the hosted expenses to grow as fast as prophet is predicting. How can I scale back the trend growth?

I understand that I can use the 'cap' to to specify a carrying capacity but I am not trying to specify a maximum but more so throttle/scale back the trend.

I am not a Github veteran so please let me know if this is posted in the wrong place.

**Comment by bletham** [comment]
Sorry for the slow reply, and yes this is the right place to post questions like this.

There's not a whole lot of direct control over this. As you know the trend is piecewise linear, and the trend that is projected forward will just be that of the last segment. So the growth rate projected forward is one that has been seen in the history, but it sounds from your description that you know that, although this rate was seen at the very end of the history, you know it is not feasible for it to continue at that rate for so long and so you want to be able to scale it back.

The model doesn't give you very direct control over this. If the reason the trend slope is too high is because it is overfitting to a high slope at the end of the time series, then you can force it to use a longer section of history for that last piecewise chunk by decreasing the parameter `changepoint_range`. This is 0.8 by default, which means trend changes are allowed in the first 80% of the time series and the last 20% is used to compute the slope for the future. If you reduce that to 0.7, then it will use 30% of the history to compute the future slope, which may shrink things down if it is too high because it is overfitting the end of the history. There's some discussion of this in the documentation here: https://facebook.github.io/prophet/docs/trend_changepoints.html

Otherwise, I think the only other option that would make sense would be to use a sampling-based approach to apply your prior on top of the model posterior. If you call
```
m.predictive_samples(future)
```
it will return a dictionary with samples of both the `trend` and the estimate `yhat`. You could use the `trend` samples to identify which are consistent with your expertise as to what is possible (so, throw out any that are too high). Keep track of the sample indicies that are being thrown out for having too high of a trend. Then, throw out the same samples in the `yhat` samples, and what you'll be left with is the distribution of `yhat` subject to your constraint on what is possible. You can take the mean over those remaining samples to get a new estimate for `yhat`. Let me know if that makes sense!
