### ISSUE TITLE
fit.prophet ignoring last value

### ISSUE THREAD

**Issue by Paulgbullard** [facebook/prophet#1567]
I have an hourly dataframe `dfWal.In` that when I fit to a prophet model it is ignoring the last record.

`> tail(dfWal.In)
                       ds  y
22771 2019-08-07 18:00:00 14
22772 2019-08-07 19:00:00 18
22773 2019-08-07 20:00:00 20
22774 2019-08-07 21:00:00  7
22775 2019-08-07 22:00:00 10
22776 2019-08-07 23:00:00  9
> test_fit <- fit.prophet(m, dfWal.In)
> tail(test_fit$history.dates)
[1] "2019-08-07 17:00:00 GMT" "2019-08-07 18:00:00 GMT" "2019-08-07 19:00:00 GMT" "2019-08-07 20:00:00 GMT" "2019-08-07 21:00:00 GMT"
[6] "2019-08-07 22:00:00 GMT"`

For testing purposes, I have left `m` as the default from prophet(). Why is history.dates missing 2019-08-07 23:00:00?

**Comment by bletham** [comment]
Sorry for the slow reply. You've run into a bug that recently came up in #1501. 

The problem is that your input data, `dfWal.In$ds`, has a timezone associated with it. Prophet is converting this into GMT, as you can see in `test_fit$history.dates`: the first row was converted from `2019-08-07 18:00:00` to `2019-08-07 17:00:00 GMT`. The last row wasn't dropped, but was converted from `2019-08-07 23:00:00` to `2019-08-07 22:00:00 GMT`. You'll be able to see this clearly if you look at `m$history`, which will have the `y` values for each of these.

The workaround for now is to either (1) set the timezone on your data as GMT (instead of letting it use the system timezone) and then you don't have to think about timezones at all. Or, (2) after making predictions, convert the GMT times in the forecast dataframe back to your system timezone.
