### ISSUE TITLE
How to get cross_validation on monthly data for say 6 months?

### ISSUE THREAD

**Issue by pratikchhapolika** [facebook/prophet#1569]
I am trying to model time series using Prophet. I have two columns in my data-frame: monthlydate and sells. This is the only data that I have to build model.

time         sell
1/31/2014   273033
2/29/2014   203019
3/31/2014   225844
4/30/2014   236374
5/31/2014   189666
6/30/2014   242742
7/31/2014   191682
8/31/2014   208270
9/30/2014   236533
10/31/2014  188010
11/30/2014  245185
12/31/2014  224990
1/31/2015   186733
2/28/2015   296641
3/31/2015   234317
4/30/2015   160818
5/31/2015   214937
6/30/2015   226710
7/31/2015   176030
8/31/2015   160991
9/30/2015   205668
10/31/2015  183680
11/30/2015  194428
12/31/2015  643302
1/31/2016   1306566
2/28/2016   2031110
3/31/2016   1756328
4/30/2016   1703885
5/31/2016   1620547
6/30/2016   1862650
7/31/2016   1742188
8/31/2016   1441375
9/30/2016   1666798
10/31/2016  1992165
11/30/2016  1965643
12/31/2016  1315753
1/31/2017   1676141
2/28/2017   1572417
3/31/2017   1442843
4/30/2017   1337359
5/31/2017   1350256
6/30/2017   1090291
7/31/2017   1329138
8/31/2017   1245024
9/30/2017   1246177
10/31/2017  1361814
11/30/2017  1574517
12/31/2017  1035892
1/31/2018   1358912
2/29/2018   1408371
3/31/2018   1239371
4/30/2018   874519
5/31/2018   1025873

What I want is cross validation for 6 months. I want to see forecasted result every month for say 6 months in my cross_validation.
How to incorporate that in code?

df_cv = cross_validation(m, initial='1095 days', period='30.4 days', horizon = '30.4 days')
 df_p = performance_metrics(df_cv)

**Comment by bletham** [comment]
`cross_validation(m, initial='1095 days', period='30.4 days', horizon = '30.4 days') will basically do:

0. Set cutoff to `initial` days into history (1095 days after start, so 1/30/2017)
1. Fit a model using all data up to cutoff. Make a forecast of `horizon` (30.4) days.
2. Advance cutoff by one month and GOTO 1. Repeat until reach the end of the time series.

So to get that down to only 6 predictions, you'd want to bump up your `initial` so that the first cutoff is around Jan 2018.

That said... the CV doesn't always work great for monthly data, because the spacing between the data points is not regular (sometimes it's more than 30.4 days, sometimes it's less). There's some discussion of this in #1253. To fix this, we recently added a new feature that allows you to directly specify the cutoffs (so here you could set them to the last 6 months). This was added in #1351. We haven't shipped the new version that has this functionality yet, but if you install the latest code from github then you'll be able to use it. Or you can wait a few weeks and it'll be on PyPI.

**Comment by pratikchhapolika** [comment]
thanks
