### ISSUE TITLE
How to interpret the plots of univariate and multivariate time series using prophet. ? << Strange  Results >>

### ISSUE THREAD

**Issue by pratikchhapolika** [facebook/prophet#1570]
I am trying to model time series using Prophet. I have three columns in my data-frame: monthlydate ,sells and another is quantity. This is the only data that I have to build model. << 52 data points >> The data is at month level.

ds | y | quantity
-- | -- | --
1/31/2016 | 273,033 | 254,361
2/29/2016 | 203,019 | 226,407
3/31/2016 | 225,844 | 203,314
4/30/2016 | 236,374 | 213,600
5/31/2016 | 189,666 | 277,953
6/30/2016 | 242,742 | 286,846
7/31/2016 | 191,682 | 204,144
8/31/2016 | 208,270 | 338,484
9/30/2016 | 236,533 | 236,944
10/31/2016 | 188,010 | 194,817
11/30/2016 | 245,185 | 247,757
12/31/2016 | 224,990 | 206,078
1/31/2017 | 186,733 | 206,161
2/28/2017 | 296,641 | 291,983
3/31/2017 | 234,317 | 268,169
4/30/2017 | 160,818 | 198,757
5/31/2017 | 214,937 | 286,911
6/30/2017 | 226,710 | 295,733
7/31/2017 | 176,030 | 234,974
8/31/2017 | 160,991 | 304,740
9/30/2017 | 205,668 | 267,798
10/31/2017 | 183,680 | 222,700
11/30/2017 | 194,428 | 411,732
12/31/2017 | 643,302 | 1,246,364
1/31/2018 | 1,306,566 | 3,357,298
2/28/2018 | 2,031,110 | 2,761,750
3/31/2018 | 1,756,328 | 2,953,104
4/30/2018 | 1,703,885 | 2,519,665
5/31/2018 | 1,620,547 | 2,440,144
6/30/2018 | 1,862,650 | 2,397,619
7/31/2018 | 1,742,188 | 2,832,808
8/31/2018 | 1,441,375 | 2,664,235
9/30/2018 | 1,666,798 | 2,070,212
10/31/2018 | 1,992,165 | 1,918,050
11/30/2018 | 1,965,643 | 1,581,767
12/31/2018 | 1,315,753 | 1,775,745
1/31/2019 | 1,676,141 | 1,444,562
2/28/2019 | 1,572,417 | 1,431,246
3/31/2019 | 1,442,843 | 1,787,914
4/30/2019 | 1,337,359 | 1,468,870
5/31/2019 | 1,350,256 | 1,232,917
6/30/2019 | 1,090,291 | 1,318,053
7/31/2019 | 1,329,138 | 909,751
8/31/2019 | 1,245,024 | 1,130,612
9/30/2019 | 1,246,177 | 813,441
10/31/2019 | 1,361,814 | 618,372
11/30/2019 | 1,574,517 | 939,767
12/31/2019 | 1,035,892 | 1,012,354
1/31/2020 | 1,358,912 | 734,281
2/29/2020 | 1,408,371 | 1,022,904
3/31/2020 | 1,239,371 | 1,041,731
4/30/2020 | 874,519 | 799,478
5/31/2020 | 1,025,873 | 1,046,195

First I do univarite model with ds and y.

**There is a sudden change (spike) in 1/31/2016 and it doesn't happen every year.**

I am using python to fit the facebook's prophet model. Here is the code:

data_forecast = df.tail(6)
df.drop(df.tail(6).index,inplace=True) # drop last n rows
m = Prophet(interval_width=0.95,changepoints=['2016-01-31'],changepoint_prior_scale=0.25,
        yearly_seasonality = True,weekly_seasonality = False,
        daily_seasonality = False)

 m.add_seasonality(period=30.4,  name='monthly',fourier_order=5)
m.fit(df)
forecast = m.predict(data_forecast)
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']])

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(forecast['yhat'], data_forecast['y']))
print(" RMSE ")
print("THE RMSE IS : ", rmse)

def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("THE MAPE IS :", mean_absolute_percentage_error(data_forecast['y'], forecast['yhat']))

**RMSE 
THE RMSE IS :  231248.68324126405
THE MAPE IS : 18.083864176875686**

Plots:

![univariate1](https://user-images.githubusercontent.com/11159549/87119910-e58aff80-c29c-11ea-890c-1e54262dfa05.png)

![univariate2](https://user-images.githubusercontent.com/11159549/87119925-ecb20d80-c29c-11ea-8138-7dc358e1b1ee.png)

**Question 1**: What is the significance of interval_width=0.95 and changepoint_prior_scale=0.25. When I keep default value of changepoint_prior_scale I don't see a red line in plot components. When I keep it 0.25 I see a one changepoint in plot. Why?

**Question 2** Why I see a straight line in trend? How to interpret it?

**Question3:** From the above data that I have what can I do more to improve my RMSE or MAPE? If we see clearly the predicted curve doesn't fit the black dots nicely. Any other parammeters to include?

If I have to interpret Yearly trend. Then by looking at the plot can I say << At every year Feb month has **4000000** more sells then usual??

                   **Similary I do Multivariate Forecasting: and here is the plot:**

![multivariate1](https://user-images.githubusercontent.com/11159549/87120329-c6d93880-c29d-11ea-8eb0-9fe68abf314a.png)

![multivariate2](https://user-images.githubusercontent.com/11159549/87120335-c9d42900-c29d-11ea-87e6-bfac74f17e77.png)

**Qusetion4:** Why I don't see blue forecasted line??
**Question5:** What does **extra_regressor_additive** plot indicates? Can you please help me to understand it?

Code:

cols = list(df.columns)
cols.remove('ds')
cols.remove('y')

data_forecast = df.tail(6)
df.drop(df.tail(6).index,inplace=True) # drop last n rows

m = Prophet(interval_width=0.95,changepoints=['2018-01-31'],
            yearly_seasonality = True,weekly_seasonality = False,
            daily_seasonality = False,changepoint_prior_scale=0.3)

for c in cols:
    m.add_regressor(c)

m.fit(df)

print(data_forecast);

forecast = m.predict(data_forecast)
print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(18))

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(forecast['yhat_lower'], data_forecast['y']))
print(" RMSE ")
print("THE RMSE IS : ", rmse)

def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("THE MAPE IS :", mean_absolute_percentage_error(data_forecast['y'], forecast['yhat_lower']))

**Question7:** How can I do **cross_validation**  on the same monthly data where I see results for 6 months with RMSE and MAPE.

Thanks

**Comment by pratikchhapolika** [comment]
Any help on the above questions?

**Comment by bletham** [comment]
A couple general comments before diving into your specific questions.

First, changepoints: The trend is piecewise linear. This means that it will not make discontinuous jumps. See the figure here for an example: https://facebook.github.io/prophet/static/trend_changepoints_files/trend_changepoints_9_0.png

When you set there to be a single changepoint (`changepoints=['2016-01-31']`) this means that the trend will be a line that is allowed an elbow at a single point. However, you want something with a jump that looks close to a step function, and this requires _2_ trend changes; One to change from flat to increasing (at 2018-01-01), and  a second to change from increasing back to flat (or actually slightly decreasing); that one would be around 2018-03-01. With only one changepoint, the trend is able to change from flat to increasing, but can't change back to flat so you get the terrible fit in your figure.

Second, monthly seasonality: Monthly seasonality means seasonality within a month; so a cycle that repeats every 30 days. With monthly data, you will not be able to fit monthly seasonality (there is only one observation per month) so you should remove it. Seasonality across months (like Jan is always a bit higher than Feb) is yearly seasonality and so is being fit.

Now for your questions:
1. interval_width=0.95: width of the uncertainty intervals; see documentation here: https://facebook.github.io/prophet/docs/uncertainty_intervals.html . `changepoint_prior_scale=0.25`: This is how flexible the trend is allowed to be. So far you've seen strange behavior with the trend because of forcing it to a single changepoint, which produces bad model fit as described above. If you give it two changepoints, the trend will be able to fit much better. That value should be fine.
2. The trend will always be piecewise linear, and in this case it wasn't able to fit well because of the single changepoint as described above.
3. The two things I suggested above (add two changepoints, remove monthly seasonality) should make things much nicer.
4. It looks like in the `future` dataframe you included the extra regressor only for the future dates. You'll need to add its values for all of the past dates as well.
5. That's the amount of `y` that is being attributed to the extra regressor. The model is basically (after some scaling and standardization):
```
y(t) = trend(t) + seasonality(t) + beta * regressor(t)
```
so `y` is modeled as a combination of those three factors. The regressor component in the plot is showing `beta * regressor(t)`, so it is the effect of the regressor on `y`. So, on 2020-05-01, `y` is forecasted as 140,000 lower due to the regressor than it would have been if the regressor were at the same value in 2020-04-01 (when the regressor has ~0 contribution to y).

I hope that helps, but definitely fixing the changepoint and seasonality issues should make things much nicer.

**Comment by pratikchhapolika** [comment]
Thank you. Perfectly explained.  Cheers!! Closing it,
