### ISSUE TITLE
Incorrect future gaps

### ISSUE THREAD

**Issue by cr151691995** [facebook/prophet#1575]
Hey Guys,

First post! Below is my code

#Model 1 Chemicals - Prophet Modelling
chemicals = chemicals[["ds","y"]]
m_chem = Prophet(changepoint_prior_scale=0.1,holidays = hols)
m_chem.fit(chemicals)

future = m_chem.make_future_dataframe(periods=100, freq = "H")

forecast = m_chem.predict(future)
fig = m_chem.plot_components(forecast)
fig = m_chem.plot(forecast)
a = add_changepoints_to_plot(fig.gca(), m_chem, forecast)

I have 2 issues:

![image](https://user-images.githubusercontent.com/68229409/87302465-c052f700-c511-11ea-8849-75cbb4348692.png)

The above is result, 
1) What are all the black dots?? I thought at first this was observed historic values, this is not the case as you can see from the plot in tableau! The true historic plot has much less vaiance and is similar to blue line.

![image](https://user-images.githubusercontent.com/68229409/87302597-f55f4980-c511-11ea-9664-905d7c088d48.png)

2) historically my data is hourly, but the forecast seems to only plot at end of month?

![image](https://user-images.githubusercontent.com/68229409/87302703-2e97b980-c512-11ea-84f4-78a4057ac81f.png)

TIA

C

**Comment by bletham** [comment]
Sorry for the slow reply.

It's possible that something is getting messed up when parsing the dates, that's the first thing that I'd check:
```
chemicals['ds'] = pd.to_datetime(chemicals['ds'])
```
That's what Prophet is doing internally to parse dates, so you could then check over that column and make sure that the dates are what you expect them to be.

But yes, the black dots on the figure are the historical data points. They will be exactly what is in `chemicals` (subject to the date parsing being done correctly). If you want to see more directly, `m_chem.history` is the model-processed copy of the history, and the dots are `m_chem.history['ds']` vs. `m_chem.history['y']`. You should be able to verify that the `y`s being passed in are exactly those being plotted. As for comparing it to the tableau plot, is there any chance the tableau plot is doing some extra smoothing? There are definitely some differences between the datasets because `chemicals[y'].max()` seems to be about 620, while the tableau plot shows a max around 760.

I'm not sure what's happening at the end where the dates are clumped, but that's an area where I wonder if the dates are not parsing correctly. If you look at `chemicals['ds'].tail(100)` what do you see? Given that these are all future dates, is it possible that their data is being somehow formatted differently?
