### ISSUE TITLE
Dates for predictions are uneven

### ISSUE THREAD

**Issue by mohnish7** [facebook/prophet#1578]
I have daily timeseries data that I am first grouping by using df.groupby to get the result below - these are basically the sum totals for that month (I have data until 6/30/20 in that dataframe).

<img width="180" alt="Screen Shot 2020-07-14 at 9 28 50 PM" src="https://user-images.githubusercontent.com/7302380/87492649-0777df80-c619-11ea-997e-2d7e6dae34b4.png">

However, once I predict, the results are like this: 

<img width="303" alt="Screen Shot 2020-07-14 at 9 31 23 PM" src="https://user-images.githubusercontent.com/7302380/87492800-5f164b00-c619-11ea-9956-33117a7468ca.png">

Why is there a discrepancy in how the monthly predictions are being made? This is the line of code that I am using:

`df_cost_forecast = df_cost_prophet.make_future_dataframe(periods = 7, freq='M')`

How do I interpret the results of 06-30-20 and so on? What is that supposed to represent and how does that affect the result for 06-01-20?

**Comment by bletham** [comment]
Sorry for the slow reply. The `freq` uses pandas `date_range`, and for Pandas `freq='M'` means month-end frequency. That's why it's producing the last day of each month. If you change it to `freq='MS'` you will get month-start frequency which is what you'd want here (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases).
