### ISSUE TITLE
How to tackle with the yearly data?

### ISSUE THREAD

**Issue by LucyChen0228** [facebook/prophet#1593]

**Comment by LucyChen0228** [comment]
My original time series is from 2014-2018. I want to make predictions for the next 20 years( 2019-2038).

<img width="478" alt="屏幕快照 2020-07-24 下午3 09 59" src="https://user-images.githubusercontent.com/42339395/88368053-ca9dac80-cdbf-11ea-9a84-1438c0796822.png">


So I wrote the code like that:

future = m.make_future_dataframe(periods=20,freq='Y')


However， the predicted time series is in the past, not in the future. 


How could I tackle this?

<img width="553" alt="屏幕快照 2020-07-24 下午3 08 46" src="https://user-images.githubusercontent.com/42339395/88367988-a8a42a00-cdbf-11ea-9dee-6d5316d6acce.png">

**Comment by bletham** [comment]
It looks like the dates in your history dataframe were not parsed correctly. If `df` is the dataframe that you pass in to `m.fit`, then it will have columns `ds` and `y`. Do this:
```
df['ds'] = pd.to_datetime(df['ds'])
print(df.head())
```
and see what dates are in the `ds` column. I'm guessing they aren't what you want them to be. You'll need to adjust the date format that you're using so that `pd.to_datetime` parses them correctly. I'd recommend YYYY-MM-DD, like `2018-01-01`, `2019-01-01`, etc.

I will however note that for yearly data, Prophet will just be a piecewise linear function. A lot of the value from Prophet comes with modeling yearly/weekly seasonalities, which won't be present here.
