### ISSUE TITLE
How to improve forecast of high values

### ISSUE THREAD

**Issue by NathanRDN** [facebook/prophet#1594]
Hi,

I'm struggling to make forecast using prophet and python. My main goal was to predict and detect some patterns in the electricity's consumption of an house like the start of a hot water tank. Actually the forecast works pretty fine but it seems that he can't handle the high values of the dataset. Is there a way to fix that with an external regressor or something like that ?

![image](https://user-images.githubusercontent.com/68427027/88388881-afc63a80-cdb5-11ea-9ce2-9dac095edfd8.png)

**Comment by avinashmatani** [comment]
FB prophet is an additive model by default. You should consider using Multiplicative seasonality mode for your model.

**Comment by NathanRDN** [comment]
Ok thanks I'm going to check that now !

**Comment by NathanRDN** [comment]
> FB prophet is an additive model by default. You should consider using Multiplicative seasonality mode for your model and try seeing the effects. It should capture those high values.

So I just checked. It's better, I can see a little gain but I'm very far away from the reality. Is there a way to add a multiplier coefficient to be closer to my high values ?

**Comment by bletham** [comment]
The Prophet model basically assumes
```
y(t) = trend(t) + seasonality(t) + noise
```
(with multiplicative seasonality it's obviously a little different, but the same basic idea). Seasonality is assumed to be smooth, and stationary.

The low values of this time series (everything below 1000) look like the kind of thing Prophet would do a good job at learning - there's a stable trend and clear daily seasonality that it would be able to pick up. But the high values are not consistent with the model assumptions. It looks like there is some stationarity (there are clumps of high values occurring at the same time each day) but the timing of the streaks in between 1000 and 3000 does not seem consistent across days. The seasonality for the high values also doesn't look smooth: for instance, the cluster of high values at the start of each day looks like it's interleaved with low values. What is happening now is that because of the non-smoothness the daily seasonality in the a.m. is being forced to be an average of the low and high values, and the noise term is being inflated to compensate for the bad fit to the high values.

I think the model would do a good job at a smoothed version of this time series. Do you need to be able to forecast at the full time resolution of the history? For instance if you were able to bucket your data by hour and fit (and forecast) the hourly total/average, that would greatly smooth things out and I think the daily seasonality fit would be good.

**Comment by NathanRDN** [comment]
Firstly, thank you for your answer ! My objective was to predict some patterns in my house consumption. For example, my hot water tank starts every night at 2am, 3am et 4am and i was hoping that fbprophet was able to detect it to include this trend in an algorithm that will decide the start hour of my wash machine for example.

> The Prophet model basically assumes
> 
> ```
> y(t) = trend(t) + seasonality(t) + noise
> ```
> 
> (with multiplicative seasonality it's obviously a little different, but the same basic idea). Seasonality is assumed to be smooth, and stationary.
> 
> The low values of this time series (everything below 1000) look like the kind of thing Prophet would do a good job at learning - there's a stable trend and clear daily seasonality that it would be able to pick up. But the high values are not consistent with the model assumptions. It looks like there is some stationarity (there are clumps of high values occurring at the same time each day) but the timing of the streaks in between 1000 and 3000 does not seem consistent across days. The seasonality for the high values also doesn't look smooth: for instance, the cluster of high values at the start of each day looks like it's interleaved with low values. What is happening now is that because of the non-smoothness the daily seasonality in the a.m. is being forced to be an average of the low and high values, and the noise term is being inflated to compensate for the bad fit to the high values.
> 
> I think the model would do a good job at a smoothed version of this time series. Do you need to be able to forecast at the full time resolution of the history? For instance if you were able to bucket your data by hour and fit (and forecast) the hourly total/average, that would greatly smooth things out and I think the daily seasonality fit would be good.
