### ISSUE TITLE
Can anyone please explain holiday effects of FB Prophet? 

### ISSUE THREAD

**Issue by avinashmatani** [facebook/prophet#1596]
From what I understand is you provide a data frame of holiday effects. Is it like it takes care of those dates in a special way and models them in a special way. Further, what if we are providing holiday dates only for the future, in that case, how does the model will know whether to rise or fall or stay flat for that holiday events.

Thanks!!

**Comment by bletham** [comment]
The model will fit a holiday effect for that day, which will be a constant amount that is either added or subtracted from the forecast for that day. This is described in Section 3.3 of the paper here: https://peerj.com/preprints/3190.pdf . It is equivalent to having a binary extra regressor that is 1 whenever it is the holiday and 0 otherwise.

If holiday dates show up only in the future, they will be ignored since (as you note) there is no way to estimate their effect. This happens here:
https://github.com/facebook/prophet/blob/0d260699e4776c449703a957f08eca8013461a47/python/fbprophet/forecaster.py#L491-L493

**Comment by brochuJP** [comment]
> Hello, I observed that even if the same holiday is present in training set as well as forecast period, prophet tends to ignore the forecast holiday. please suggest how to treat such cases ?

I have the same problem
