### ISSUE TITLE
Prophet and time series basics

### ISSUE THREAD

**Issue by mukundkalani** [facebook/prophet#1606]
Hi all,

I am new to time series forecasting and I am trying to figure out the fundamentals of how to conduct a forecast using Prophet. I have gone through the documentation and I've also been reading up on time series forecasting generally. I have some general questions about prophet that I was hoping I could get help with - 

1. Does the data need to be stationary for prophet to work accurately? Or is that not a requirement when using prophet?
2. How does training and testing data work in prophet? I understand that prophet has an internal cross-validation mechanism. Is that different from splitting the data into train and test? If so, how, and is one method better than the other? Can you also generally explain how the cross validation in prophet works and what it does?
3. I am thinking of adding external regressors (e.g. - weather data) for a project on forecasting sales. Any things I should keep in mind when adding regressors?
4. How do you measure forecast accuracy? what are the best ways?

Any help with these questions (even parts of it) would be appreciated. Thank you!

**Comment by benmwhite** [comment]
1. No, the prophet model handles baseline trend changes.

2. Since we're working with time series you can't just randomly split into training and testing. Instead, you use timestamp cutoffs where you train the model using observations before the cutoff and test the model using observations after the cutoff. [Prophet's built in cross validation routine does this over a range of timestamp cutoffs](https://facebook.github.io/prophet/docs/diagnostics.html).

3. If you're using additional regressors probably the most important thing to keep in mind that you need to have future predicted values for the regressors themselves if you want to use them for forecasting future observations. If you need to run a separate forecasting model for the future regressor values as well then this will add extra uncertainty to the prediction that won't be entirely captured in the main model output alone.

4. Usual error metrics still apply (MSE, MAPE, etc.), just for future data points past the initial training window. 

3.

**Comment by mukundkalani** [comment]
Thanks for the reply, Ben. This is very helpful. 
Question about point 2 - So cross validation in prophet takes place after the model is fit and the prediction is done, right? And then the model can be adjusted based on the cross validation results?
Also, what are some other forecasting methods that I can look into if I want to predict daily sales for a period into the future and account for other variables like weather? I have been reading up on exponential smoothing, SARIMAX etc. but it seems like these methods do not work as well with daily data and are also more difficult to implement without a background in time series forecasting. I also came across the XGB method but haven't read about it too closely. What do you think? Is it better to just stick to Prophet? Thanks.

**Comment by benmwhite** [comment]
During cross validation it fits a separate model for every timestamp cutoff, similar to how you'd fit separate models for each split when cross validating a model with independent observations.

For general time series resources it's tough to top [Rob Hyndman's "Forecasting: Principles and Practices"](https://otexts.com/fpp2/). It uses R and the `forecast` package for the examples and exercises, and it's extremely comprehensive for an applied introductory text.

**Comment by mukundkalani** [comment]
Awesome, I'll look into this. Would you recommend the forecast package over prophet?

**Comment by benmwhite** [comment]
It depends on the application, your goals, and your assumptions about the data generating process. The forecast package has a wide variety of time series models implemented, so it's probably better for learning about general models and assumptions since prophet is basically just one family of models in this fairly broad category.
