### ISSUE TITLE
how to process non-daily periodic spike ?

### ISSUE THREAD

**Issue by rollmark** [facebook/prophet#1613]
![150110](https://user-images.githubusercontent.com/2113894/89501458-f5432880-d7f5-11ea-9196-8a6bf12c197c.png)
As you can see, every daily from 10:30 AM to 11:15 AM, there will be a quick grow spike happen, it happen during about 45 minutes, we can't fitting those kind of spikes very well, could any body help me, BTW, i using prophet（py） and minutes data unit.
Any help or suggestions will be thnk you.

**Comment by benmwhite** [comment]
Maybe try increasing the prior scale for the time-of-day seasonality?

**Comment by bletham** [comment]
I think you'd actually in this case need to increase the Fourier order for the daily seasonality to grab the spike; the default of 4 is going to be pretty smooth. There's some discussion of this in https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#fourier-order-for-seasonalities . Something like
```
Prophet(daily_seasonality=20)
```
would be able to grab it.

But it also would add a lot of flexibility to the entire day's seasonality, which may not be totally desirable if you know this spike is only between 10:30a and 11:15a. The other thing you could consider in this case would be to keep the default smooth daily seasonality, and add a separate seasonality on top of that just for the spike, that would only be active during the window of 10:30a to 11:15a. You would do this by making a conditional seasonality, as described here: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors . So, have a binary indicator that is 1 between 10:30a and 11:15a and 0 otherwise. Let's call it "is_spike_time". Then you could add a seasonality like:
```
m = Prophet(daily_seasonality=True)
m.add_seasonality(name='spike_seasonality', period=1, fourier_order=20, condition_name='is_spike_time')
```

In either case, if you post the output of `m.plot` and `m.plot_components` that would be helpful for any further discussion on improving model fit.
