### ISSUE TITLE
holidays - observed vs actual date

### ISSUE THREAD

**Issue by rquintino** [facebook/prophet#1618]
hi there!

is there any info on how prophet handles observed vs actual holiday dates? (ex: 4th july 2020 is observed on 3rd july)

docs seem to mention observed dates but I was seeing effects on the other ones.

thanks!

https://support.predicthq.com/what-is-the-difference-between-an-observed-holiday-and-an-observance
"For example, if July 4th (Independence Day) falls on a Saturday, it is "observed" on the Friday before as a holiday (and is usually a day off work). When a federal holiday falls on a weekend, the holiday is usually observed the Friday before or the Monday after. Below is a list of the federal holidays:"

**Comment by rquintino** [comment]
ok closing this one as further checking allowed to confirm that:
-both official and observed dates are accounted for
-both effects are visible and inspectable on the results coefficients

thanks
(amazing package!)

**Comment by bletham** [comment]
Thanks for pointing this out. To see it cleary inside fbprophet,
```
>>> from fbprophet.make_holidays import make_holidays_df
>>> make_holidays_df(year_list=[2019, 2020], country='US')
           ds                      holiday
0  2019-01-01               New Year's Day
1  2019-01-21   Martin Luther King Jr. Day
2  2019-02-18        Washington's Birthday
3  2019-05-27                 Memorial Day
4  2019-07-04             Independence Day
5  2019-09-02                    Labor Day
6  2019-10-14                 Columbus Day
7  2019-11-11                 Veterans Day
8  2019-11-28                 Thanksgiving
9  2019-12-25                Christmas Day
10 2020-01-01               New Year's Day
11 2020-01-20   Martin Luther King Jr. Day
12 2020-02-17        Washington's Birthday
13 2020-05-25                 Memorial Day
14 2020-07-04             Independence Day
15 2020-07-03  Independence Day (Observed)
16 2020-09-07                    Labor Day
17 2020-10-12                 Columbus Day
18 2020-11-11                 Veterans Day
19 2020-11-26                 Thanksgiving
20 2020-12-25                Christmas Day
```

As you note, 2020 has both "Independence Day" and "Independence Day (Observed)", but 2019 has only "Independence Day" (because it was on a weekday).

As you also note, this is not ideal for the modeling because these will be treated as separate holidays.

I think it's a bit of a challenge to know what the "right" thing to do is. Merging "Independence Day" and "Independence Day (Observed)" might not be right because the effect of "Independence Day (Observed)" might not be the same as that of "Independence Day"  in a year with no "Independence Day (Observed)". For example, in 2019 people had Jul 4 off and had their BBQs and parades etc. then. In 2020, both the 3rd and 4th were off. The 3rd was the "Observed" day, but most BBQing and parading was probably still happening on the 4th, which just happened to be a weekend. I think depending on the time series, the impact of having an "observed" day on the regular holiday could be different. I'm not sure there is a single correct way to handle this, but would love to hear if anyone has any ideas.

**Comment by rquintino** [comment]
thanks for the feedback @bletham! 
yes, agree, depending on the time series behavior can switch. In this scenario we were seeing makes sense main effect goes to observed (also because weekend weight is residual), but others might differ. So it's a kind of hyper param.

Prob a first thing could help would be just to add a note on this to the respective holidays doc page. Probably can save a few hours debugging or avoiding this to creep in quietly without anyone noticing (may not be noticed on historic eval).

Prob, a single correct way is asking too much, but what about multiple correct ways guidance? like, if you think your time series behave similarly on actual vs observed  do this, if not do this instead? Or some additional parameters on prophet make holidays (remove unobserved, add observed as actual also, change observed to actual,...)

We made that hack as a test but actually unsure of how that could break other prophet assumptions and bias results (ex: affect training coefficients due to collinearity).

**Comment by bletham** [comment]
I definitely agree on describing this in the documentation! And maybe we can there reference this issue as a place to discuss possible strategies of handling this.
