### ISSUE TITLE
ERROR: "The kernel appears to have died. It will restart automatically"

### ISSUE THREAD

**Issue by KathyGCY** [facebook/prophet#1624]
Dear Sir / Madam,

I’m writing to report an error when running Facebook Prophet in python Jupiter notebook, and ask for help on fixing this error.
It keeps shutting down my kernel resulting in an error message “The kernel appears to have died. It will restart automatically.”
<img width="1440" alt="Screen Shot 2020-08-12 at 10 45 17 AM" src="https://user-images.githubusercontent.com/14912791/90050035-a7219f80-dca3-11ea-9f11-459d2d47751a.png">

Attached to the email I have presented an example of the error:
`import pandas as pd
from fbprophet import Prophet
df = pd.read_csv('test.csv')
df.head()
m = Prophet()
m.fit(df, algorithm='Newton')
`
 
Here are some fixes that I’ve tried but failed:

- In this issue [[857](https://github.com/facebook/prophet/issues/857)] in github, it mentioned the kernel meltdown can be fixed with specifying algorithm='Newton'  but that did not work.
- Removed all packages and restart in a new empty environment, that didn’t work
- Tried “conda install gcc” but reported error that “Error: gcc 8.2.0 is already installed”
- Tried “brew upgrade gcc” to 10.2.0, didn’t work.
- In Stackoverflow issue [[47022997](https://stackoverflow.com/questions/47022997/jupyter-the-kernel-appears-to-have-died-it-will-restart-automatically)] it mentioned reinstalling numpy. But that didn’t work either.
- It is worth mentioning that at one point the code worked in an very very old version 0.3.post2. After downgrading everything to older version, a different error occurs : “ValueError: Wrong number of items passed 270, placement implies 20”. So it didn’t really fixed anything, but just switched from one error to another…

<img width="1186" alt="Screen Shot 2020-08-12 at 11 47 30 AM" src="https://user-images.githubusercontent.com/14912791/90050096-b99bd900-dca3-11ea-9d39-9143fadaa317.png">

After running the following code:

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.samp
[pip freeze files.txt](https://github.com/facebook/prophet/files/5064720/pip.freeze.files.txt)
ling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

An error is returned "CompileError: command 'gcc' failed with exit status 1"

Here's a google drive link with a demo to replicate this error:

- The code in notebook (in .ipynb and .py format)
- The csv data file used to replicate the error. This is from a is public dataset.
- The txt file of pip freeze package versions in the virtual environment
- A screen recording of how the error occurs.

https://drive.google.com/file/d/1Z9ZHn4TDgvzUWKUNScgkVdrNQsvg_2uy/view?usp=sharing

[demo.zip](https://github.com/facebook/prophet/files/5064750/demo.zip)

Thanks!
All the best,
Kathy Chenying Gao
cg2908@columbia.edu 
chenyinggao@kpmg.com

**Comment by bletham** [comment]
The issue seems to be with the C++ toolchain, which is causing the CompileError in pystan. That error in pystan is certainly what is crashing the kernel.

The error (exit status 1) is pretty generic and can be caused by any piece of the C++ toolchain being missing or misconfigured. For instance, if you're in Linux, make sure you have python dev packages installed (though it sounds like you're on OSX). Usually in Anaconda this works out-of-the-box since it maintains its own C++ toolchain, but you can check the pytsan documentation here for some detailed instructions (for instance, on using Clang in OSX): https://pystan.readthedocs.io/en/latest/installation_beginner.html .  You could also try re-installing pystan, in case it needs to be re-built after upgrading gcc.

Once pystan is working, you'll want to re-install fbprophet (to recompile the model), and then I expect the kernel to stop crashing.
