### ISSUE TITLE
Cannot Unpickle Models When Switching Python Versions

### ISSUE THREAD

**Issue by Yubel124** [facebook/prophet#1625]
I know this is similar to issues that have been posted in the past but none of the solutions that I found answered my problem specifically so I thought I'd give it a go here. 

So when trying to unpickle models built in python 3.7 in either python 3.6 or 3.8 I get : 
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
WARNING:pystan:No module named 'stanfit4anon_model_ad32c37d592cdbc572cbc332ac6d2ee2_4431954053790800620'

Does fbprophet not support loading models built in other versions of python or is this an installation problem with conda virtual environments?  
I read through #775 and the issues referenced in it.

**Comment by bletham** [comment]
This is pretty fundamental to pickle, which typically is not compatible across different versions of packages.

We just added json serialization in #1415 , which will be pushed to pypi soon in v0.7. So at that point you will want to use json instead of pickle, but until then there really isn't a good workaround because pickle is not cross-platform.

**Comment by bletham** [comment]
Json serialization is pushed now and should be used instead of pickle, as described in https://facebook.github.io/prophet/docs/additional_topics.html#saving-models
