### ISSUE TITLE
components in fbprophet vs arima

### ISSUE THREAD

**Issue by svenaoki** [facebook/prophet#1631]
Hello,

I have a quick question regarding the components in fbprophet. I forecasted the same dataset (passenger airlines) in fbprophet and arima and plotted the components. Yet the components in fbprophet are very different from what I would expect when I look at the predictions (not plotted here). In comparison I also plotted the ARIMA model components which looks more likely. I actually encountered it when I looked at a personal sales dataset, where we knew sales peak around december/january and are small in summer, yet the fbprophet component plots did not indicate such seasonality, although predictions were fine.

Arima
![Arima](https://user-images.githubusercontent.com/12186842/90603601-cec0bc80-e1fb-11ea-8401-da37e481a3c0.png)

FBProphet
![fbprophet](https://user-images.githubusercontent.com/12186842/90603571-c6688180-e1fb-11ea-8c4b-719eb7b8078e.png)

**Comment by mdancho84** [comment]
FB Prophet is showing you that there is a yearly seasonality that repeats. The main difference with the structure of the ARIMA plot is that the scale of the x-axis follows the overall time series, whereas the Prophet plot just includes one cycle. 

## Yearly Seasonality (Year-Over-Year) - Prophet
![image](https://user-images.githubusercontent.com/13734662/90646480-3f200b80-e205-11ea-91ac-cecb4e7259ea.png)

Arima
![image](https://user-images.githubusercontent.com/13734662/90646166-e3ee1900-e204-11ea-987a-b17fa04f8076.png)

## What does this mean? 
If you repetitively stacked the prophet yearly seasonality plot side-by-side, you'd get something that looks similar to the ARIMA plot. 

Now keep in mind that ARIMA uses a seasonal lag to compute seasonality whereas the prophet uses a fourier series, which is why you see the smooth transition from month to month. But I digress. 

The main point is that the look of the plots are different, but they are showing the same seasonal component information in different ways.
