### ISSUE TITLE
Trend changepoint detection with vs. without mcmc_samples option

### ISSUE THREAD

**Issue by daydreamersjp** [facebook/prophet#1634]
Hello!

I was playing with the package using Peyton Manning data. I noticed there are much more changepoints automatically detected when using mcmc_samples option than when not using mcmc_samples option. 
Is this something expected?

![image](https://user-images.githubusercontent.com/42426597/90924705-3ccdd500-e3f0-11ea-8317-6762a194a884.png)

![image](https://user-images.githubusercontent.com/42426597/90924743-4d7e4b00-e3f0-11ea-87f8-34437495e5fc.png)

**Comment by bletham** [comment]
I think the default threshold for flagging the changepoint as "significant" may be a little too tight, but generally this isn't too surprising to see. The changepoints are shrunk towards 0 with a lasso-style L1 regularization. With MCMC, it is in Bayesian analysis a well-known phenomenon that the Laplace prior does not shrink parameters all the way to zero. So instead of the trend change being 0, it will just be a small number. If you look at the trends in the figures, they look the same, so the difference really is just a small difference in how close to 0 things were pushed.

You can see what the trend change magnitudes are by computing
```
np.nanmean(m.params['delta'], axis=0)
```
This is a plot of the trend change magnitudes with and without MCMC (basically what is used to produce the plots above) (I used `m0` for the model fit without MCMC, and `m` for the model fit with):
```Python
fig = plt.figure(figsize=(15, 5))

ax = fig.add_subplot(121)
ax.bar(np.arange(25), np.nanmean(m0.params['delta'], axis=0))
ax.set_title('Without MCMC')
ax.set_xlabel('Changepoint')
ax.set_ylabel('Trend change (delta)')
ax.axhline(y=0.01, color='r', ls='--')
ax.axhline(y=-0.01, color='r', ls='--')
ax.axhline(y=0.1, color='g', ls='--')
ax.axhline(y=-0.1, color='g', ls='--')

ax = fig.add_subplot(122)
ax.bar(np.arange(25), np.nanmean(m.params['delta'], axis=0))
ax.set_xlabel('Changepoint')
ax.axhline(y=0.01, color='r', ls='--')
ax.axhline(y=-0.01, color='r', ls='--')
ax.axhline(y=0.1, color='g', ls='--')
ax.axhline(y=-0.1, color='g', ls='--')
ax.set_title('With MCMC');
```
![bars](https://user-images.githubusercontent.com/6339760/91093770-b8a56880-e60e-11ea-977a-0558b870981f.png)

You can see that they are qualitatively very similar, but with MCMC things are not shrunk quite all the way to zeros. As mentioned above, this is expected. The red dashed line is the default threshold used by `add_changepoints_to_plot` to identify it as being significant (default is 0.01). This is obviously really tight. With MCMC, you'll probably want to ease it off for the visualization. If you change it to 0.1 (the green dashed lines), you get:
```Python
fig1 = m.plot(forecast)
a = add_changepoints_to_plot(fig1.gca(), m, forecast, threshold=0.1)
```
![p2](https://user-images.githubusercontent.com/6339760/91094058-1fc31d00-e60f-11ea-99d5-db844c3a2e49.png)

This seems much more reasonable, and the points being marked as having trend changes are those where you can visually see that the trend has changed.
