### ISSUE TITLE
Support different regressor with different interval_width.

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#1653]
I'd like to use yhat_upper to keep a good stock level .
But different regressor should have different interval_width .

For example, I have an event `A` hold on  1-3 times  per  two week ， and I have  event `B` hold 1-3 times  per year .
So I want event `A` at 80% interval_width  , and  event `B` at 50% interval_width  .

fbprophet doesn't support it now .

**Comment by bletham** [comment]
I'm not exactly sure what you mean. Are A and B time series that are being forecast separately? In that case they could each have separate interval_width's specified. If these are extra regressors on the model for a different `y`, I'm not sure what you mean by setting interval_widths on the regressors.

**Comment by eromoe** [comment]
I mean:

- A and B are all regressors to target y 
- A is more frequent than B , so I want A has a larger confident interval  . 


fbprophet would calculate  `*_upper` and  `*_lower`  when `uncertainty_samples=True`  , and the `interval_width` is fixed for yhat and other regressors . Would it be nicer to set custom `interval_width` for different regressors so that `yhat_upper` and  `yhat_lower` would be more adequate.

**Comment by bletham** [comment]
I think there is a misunderstanding here on how the *_upper and *_lower are computed.
If MCMC is done (by setting `mcmc_samples` to the number of samples, e.g. 500.) then there will be uncertainty estimates for the regressor effects, `A_upper` and `B_upper` (and *_lower of course). These are the quantiles of the posterior for each regressors component. Basically, the model is
```
yhat = trend + seasonality + beta1 * A + beta2 * B
```
and MCMC produces a posterior for beta1, and `A_upper` is the upper quantile of the posterior for `beta1 * A`.
It is _not_ the case that
```
yhat_upper = trend_upper + seasonality_upper + A_upper + B_upper
```
Rather, the posterior for yhat is computed through the following procedure:
for i = 1 to uncertainty_samples:
* Sample beta_i, seasonality_i, and trend_i from their posteriors.
* Compute yhat_i = trend_i + seasonality_i + beta1_i * A + beta2_i * B

Then, yhat_upper is the quantile of those yhat_i samples. So there isn't really a meaning to setting separate intervals for separate regressors. Does that clarify things?


As a note, you wrote `uncertainty_samples=True`, which I think was a typo. `uncertainty_samples` should be the _number_ of samples, not a boolean. It defaults to 1000. I suspect that True may somewhere be cast to 1, so it could be really bad to use True instead of a number like 1000. Same for `mcmc_samples`, which should be 0 to not do MCMC and should otherwise be the number of samples, like 500 or 1000.

**Comment by eromoe** [comment]
Oh sorry, I disabled mcmc to speed up trainning by `uncertainty_samples=False`  , then forgot it is a numeric parameter . 
----
I mainly suggest to make `interval_width` be able to setting by per indivisual parameter( through `add_regressor` )
Now it is integrated over all model parameters : 
>     interval_width: Float, width of the uncertainty intervals provided
        for the forecast. If mcmc_samples=0, this will be only the uncertainty
        in the trend using the MAP estimate of the extrapolated generative
        model. If mcmc.samples>0, this will be integrated over all model
        parameters, which will include uncertainty in seasonality.

**Comment by bletham** [comment]
Right, but to be clear it is integrated over the full posterior of all parameters. `interval_width` isn't applied before that integration, it's applied only after (to the posterior of `y_hat`). So there's nowhere that an interval width on regressors would impact the interval of y_hat. There's a misunderstanding here and I'm not sure if it's around how the integration is done, or if I'm misunderstanding what you're trying to accomplish here.

**Comment by eromoe** [comment]
> So there's nowhere that an interval width on regressors would impact the interval of y_hat.
I see .
It is hard to reflect `interval_width` of `y_hat` from the `interval_width ` of  all components(trend,seasonal, regressors) , that's why use mcmc to sample it. 

I come up this idea because I am not sure set what `scale` to a regressor  since there is half million series I can't look them all .

**Comment by bletham** [comment]
Meaning the `prior_scale` when adding it? I think for that your best best would be to use cross validation to test a range of values and select the best one. Values in the range [0.01, 10] would probably be around the range of interest (see also https://facebook.github.io/prophet/docs/diagnostics.html#hyperparameter-tuning)

**Comment by eromoe** [comment]
Thank you , it is really a big task. 
Since the amount of products is too huge, very cost human resources .
