### ISSUE TITLE
quarterly predictions with FBProphet

### ISSUE THREAD

**Issue by wasifmasood** [facebook/prophet#1660]
is it possible to do quarterly predictions with FBProphet? I want to do the prediction for the following case

>     ds             y  
>  07:30:00  152.456966 
>   07:45:00  104.716333 

I dont want to go for 'min' granularity. Just checking if quarterly predictions are possible.

**Comment by bletham** [comment]
Sure, as described in the quick start documentation (https://facebook.github.io/prophet/docs/quick_start.html) you can pass in a dataframe with any set of timestamps at which you want predictions to `predict` and it will predict at those timestamps. For 15min intervals you will have to generate the sequence of timestamps yourself since that isn't a built-in functionality in either R or pandas date sequences (the valid frequencies in pandas are here: https://facebook.github.io/prophet/docs/quick_start.html), but once you construct it you can pass it directly to `predict`.

**Comment by wasifmasood** [comment]
unfortunately, my question is sitll open, its not about the data its about the freq parameter in the predict function. 

df_prophet.make_future_dataframe(periods= fcast_time, freq='D', include_history=True)

here freq cannot be defined as '15min' or 'quarterly' right?

**Comment by bletham** [comment]
@wasifmasood you can pass any pandas time frequency specifier; see here for a list: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases . As described there, `Q`, `BQ`, `QS`, or `BQS` will provide quarterly frequency for different definitions of quarterly. `15min` will provide 15 minute frequency.

**Comment by wasifmasood** [comment]
thanks a lot.
