### ISSUE TITLE
updated r and r studio in Catalina 10.15.6

### ISSUE THREAD

**Issue by sbaumbaugh** [facebook/prophet#1661]
Hey all,

Small problem, update R to 4.0.2 and R Studio to 1.3.1073 and now getting this error.

Any ideas on how I might get prophet working again?

![Screen Shot 2020-09-11 at 9 18 55 AM](https://user-images.githubusercontent.com/60758737/92936966-5de27e00-f410-11ea-9eee-4763628b5e12.png)

**Comment by bletham** [comment]
There have recently been some issues with prophet when upgrading R versions, including this particular "image not found". See #1639 for some links to other issues. I'm not exactly sure what the issue is, but as described there, one of these might help:
* Run `devtools::clean_dll()` and then re-install prophet
* Uninstall prophet and re-install from source, like `install.packages("prophet", type = "source")`
Let me know if either of those works!

**Comment by sbaumbaugh** [comment]
I have tried both of these steps with no luck.

Uninstalled Prophet numerous times and reinstalled.

Any thoughts?


![Screen Shot 2020-10-08 at 11 51 10 AM](https://user-images.githubusercontent.com/60758737/95489663-c9126800-095c-11eb-9de8-3e579a19daca.png)

**Comment by bletham** [comment]
Redirect to #1703
