### ISSUE TITLE
Holidays in forecast period not being considered 

### ISSUE THREAD

**Issue by pg1912** [facebook/prophet#1665]
Hi all,

I am facing an issue with the right way to treat 'future' holidays. I have included holidays in the holidays data frame but these are not being considered in the forecast result. Could anyone please elaborate how to resolve this ?

I can share the dummy code I have used, if needed. 

Thanks in advance.

**Comment by bletham** [comment]
If you could share code that'd be great, you should be able to see holiday effects in the components plot from `m.plot_components(fcst)`.

The only thing to check first is that if you are using Python,  this may be the bug in #1617, which was that a pandas change broke holidays in fbprophet. So if you are using pandas 1.1.0 and fbprophet 0.6, holidays will not work. The issue was fixed in fbprophet version 0.7.1, so just upgrade to that and it should work.
