### ISSUE TITLE
One-step prediction CV using all previous data

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebook/prophet#1666]
I have daily data from 2017,2018 (`X_train`) and 2019 (`X_test`).

I want to do a one-step ahead CV prediction for each day in 2019 trained on all the data op to the day before i.e
first use all traning data (2017,2018) to predict 01-01/2019, then use all training-data + 01-01/2019 to predict 02-01/2019 etc. etc.

As far as I understand, the parameter `initial` that is the traning-window i.e setting `initial="365 days"`  and `horizon="1 day"` it would use the last 365 days to predict the next day i.e a rolling window of 365 days.

The problem is, I want to use all the data in the past, and not just the last 365 days thus `initial` would first be 730, then 731, then 732 etc.
According to the doc-string for `initial`; "The first training period will include at least this much data. If not provided, 3 * horizon is used." which seems like it would then use 3 days for forecasting if `initial` is not set?

The question is; would the following code

``` python 

model = Prophet()
#X_train= data from 2017 and 2018
#X_test = data from 2019
model.fit(pd.concat((X_train,X_test)))

cutoffs = [p for p in pd.to_datetime(X_test["ds"].values)]
df_cv = cross_validation(model,cutoffs=cutoffs[:-1],horizon = '1 day')
```

provide `df_cv` with:

1) One-step prediction for 2019 using all data in the past?
2) One-step prediction for 2019 using just the last 3 days?
3) Something else

Thanks a bunch for an awesome package!

**Comment by bletham** [comment]
The `cross_validation` function actually does exactly what you're looking for. `initial` is the size of the history for the _first_ cutoff, but then every cutoff after that will use all data up to it. So, it isn't a rolling window. If you do
```Python
df_cv = cross_validation(model, horizon="1 day", period="1 day", initial="730 days"),
```
then the first cutoff will be placed at day 730; it will use all data up to that, and will then make a forecast for day 731.
The next cutoff will be placed `period` days later, and so will be at day 731; it will again use all data up to that point, and will then make a forecast for day 732.

This needs to be clarified in the documentation, because this misunderstanding about the initial being a rolling window has come up at least once before.

**Comment by Jakobhenningjensen** [comment]
So, say I have 800 days training data and 100 days of validation.
If I set `initial=730` it would use the last 730 days for the first cutoff (ignoring the very first 30 days) but for the second cutoff it would use all 801 data points or only the 731 (since we ignored the 30 first days for the first cutoff)?

My question is, if we have a dataset which is being incremented each day, do we then just set `initial=X_train.shape[0]`, such that we always use all data available to make a one-step-prediction?

Get Outlook for Android

________________________________

**Comment by bletham** [comment]
I'm not quite understanding what you mean by training data vs. validation data. In the `cross_validation` utility, everything happens on the training data given to the model. If you specify `initial=730` and `horizon=100` but have only 800 data points, it will raise an error because there isn't enough data to fit a model to 730 days and predict for 100 and compare to true values (730 + 100 > 800).

If you set `initial=730`, `period=1`, and `horizon=1`, it will not ignore the first 70 days of data. It will set cutoffs beginning at day 730 for every `period=1` day, up until there isn't enough data left to predict `horizon`. So, cutoffs will be set at [730, 731, 732, ..., 799]. At each cutoff, it will use all data up to that cutoff. So it is like:
* Use days 1-730 to predict day 731
* Use days 1-731 to predict day 732
...
* Use days 1-799 to predict day 800

This will give you 70 estimates of your 1-day forecast error, which you can then use to compute metrics like MAPE.

If you set `initial=X_train.shape[0]`, it will error because it needs `horizon` days left in order to compare to the true value. With the 1-day horizon, if you set `initial=X_train.shape[0] - 1` then there will be a single cutoff; let's say again that `X_train.shape[0] = 800`, then that cutoff would be at 799. And the cross validation will do
* Use days 1-799 to predict day 800
to provide a single estimate of the 1-day forecast error.

**Comment by Jakobhenningjensen** [comment]
My bad on the validation-set, please ignore that.

So, as far as I understand;

1) The CV always uses all data available before a `cutoffs` point and predicts `horizon` (days)  from each `cutoffs`-point?

2) If `cutoffs` is specified then `period` and `initial` are ignored since they are only used to create the cutoffs (`cutoffs`=`initial`+`period` ) ?

**Comment by bletham** [comment]
Correct on both points! Essentially `cutoffs = initial + i * period` where i increments from 0 to however large it can get before we have less than `horizon` data left.

(For the sake of exactness: cutoffs are actually computed backwards in time, where the first cutoff is placed at `end - horizon`, and then subsequent cutoffs are placed at `end - horizon - i * period` where i increments until we reach `initial`. But the principle is the same: cutoffs are placed every `period` time between `initial` and `end - horizon`).

**Comment by Jakobhenningjensen** [comment]
Fantastic! It all makes sense now. 

Thanks a bunch!
