### ISSUE TITLE
Cross validation for monthly data on Prophet?

### ISSUE THREAD

**Issue by faouziamrouche** [facebook/prophet#1672]
Is it possible to do cross validation on monthly data, with periods as months, not days? I tried to specify the metrics as 'months' for the function but it is not working.

**Comment by bletham** [comment]
The cross validation tool uses `pd.Timedelta` for specifying the period, and it does not allow 'month' because 'month' is not a fixed amount of time (it is somewhere between 28 and 31 days). The list of valid units is in the pandas documentation here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_timedelta.html

What you'll want to do instead is manually specify the cutoff locations. Suppose I have monthly data from 2018-01-01 through 2020-09-01 and I want to do cross validation with a forecast horizon of 3 months, starting with 1 year of training data and then moving forward with a period of 2 months. I could manually create the appropriate set of cutoffs like:
```Python
>>> import pandas as pd
>>> cutoffs = pd.date_range(start='2019-01-01', end='2020-06-01', freq='2MS')
>>> print(cutoffs)
DatetimeIndex(['2019-01-01', '2019-03-01', '2019-05-01', '2019-07-01',
               '2019-09-01', '2019-11-01', '2020-01-01', '2020-03-01',
               '2020-05-01'],
              dtype='datetime64[ns]', freq='2MS')
```
And then specify those as the cutoffs to use:
```Python
df_cv = cross_validation(model=model, horizon='90 days', cutoffs=cutoffs)
```
Note that the ability to specify the cutoffs is new in fbprophet v0.7.1, so make sure you've upgraded to that.

**Comment by faouziamrouche** [comment]
The solution works and provides better results, thanks.
