### ISSUE TITLE
Is it possible to check a distinct seasonal pattern?

### ISSUE THREAD

**Issue by linchenkarenUT** [facebook/prophet#1676]
Hi everyone,

I am building a model regarding the sales to find categories and items with distinct seasonal patterns to inform monthly product selection. I am building the model using daily data and set the yearly_seasonality as 5 and seasonality_mode as `multiplicative`

I'd like to provide an example of my current situation.

I have some categories at hand, `BunPanRackCover`, `PieCakeCuttersandMarkers`, and `CommercialPatioHeaters`. Here are the daily sales and monthly sales graphs.
`Daily Sales`
<img width="1090" alt="Daily" src="https://user-images.githubusercontent.com/30819084/93362076-9076e700-f813-11ea-8b86-f067748e757d.png">

`Monthly Sales`
<img width="1074" alt="Monthly" src="https://user-images.githubusercontent.com/30819084/93362115-9bca1280-f813-11ea-9323-df3ea56e8df9.png">

By using the `plot_components()` method, it seems that `BunPanRackCover` doesn't have a distinct seasonality(the largest values in the `yearly` plot are just around 10%) while `CommercialPatioHeaters` does have a distinct seasonality in October and November.
From the `Monthly Sales` graph, I'd like to put `PieCakeCuttersandMarkers` as non-distinct-seasonal and its values in the `yearly` plot in Oct and November are around 40%. 

`BunPanRackCover` 
![BunPanRackCovers](https://user-images.githubusercontent.com/30819084/93362694-493d2600-f814-11ea-9147-0dce82b3ba19.png)

`CommercialPatioHeaters` 
![CommercialPatioHeaters](https://user-images.githubusercontent.com/30819084/93362727-535f2480-f814-11ea-9c8d-a0115a80fe39.png)

`PieCakeCuttersandMarkers`
![PieCakeCuttersandMarkers](https://user-images.githubusercontent.com/30819084/93362747-5ce88c80-f814-11ea-957e-b8fa1981a862.png)

**My Question: I am wondering if checking values in yearly plot would be a good method to validate the distinct seasonal pattern.**  Do you guys have any suggestions to address the problem? Any feedback would be appreciated!

Here's a snippet of my code. I am not familiar with Fourier transformation and feel free to give the suggestion of parameter-tuning! Thank you all!

```python
class Forecast:
    """Prophet forecaster that gives seasonality data and outlier detection
    """

    def __init__(self, data: pd.DataFrame, holidays: pd.DataFrame):
        self.data = data[["ds", "y"]].sort_values(by="ds").copy()
        self.holidays = holidays
        self.id = data.id.values[0]

        # model params
        self.__seasonality_mode = "multiplicative"
        self.__holidays_prior_scale = 10
        self.__changepoint_prior_scale = 0.05
        # Yearly default is at 10. Decreasing = less overfitting
        self.__yearly_seasonality = 5
        self.__weekly_seasonality = True
        self.__interval_width = 0.30
        self.__changepoint_range = 1

        if "y" not in data.columns:
            raise Exception(
                "Target variable should be called `y` in the `data` dataframe"
            )
        if "ds" not in data.columns:
            raise Exception(
                "Time variable should be called `ds` in the `data` dataframe"
            )

        if "id" not in data.columns:
            raise Exception("id variable should be called `id` in the `data` dataframe")
        if len(data.id.unique()) > 1:
            raise Exception(
                "The number of unique id in `data` dataframe should equal 1"
            )
        self.model_init()

    def model_init(self):
        self.m = Prophet(
            holidays=self.holidays,
            holidays_prior_scale=self.__holidays_prior_scale,
            changepoint_prior_scale=self.__changepoint_prior_scale,
            seasonality_mode=self.__seasonality_mode,
            yearly_seasonality=self.__yearly_seasonality,
            weekly_seasonality=self.__weekly_seasonality,
            interval_width=self.__interval_width,
            changepoint_range=self.__changepoint_range,
        )
        self.m.add_seasonality(name='monthly', period=30.5, fourier_order=5)
        self.m.fit(self.data)
```

**Comment by bletham** [comment]
Generally, yes I think it is reasonable to use the `yearly` component to identify the seasonal pattern. What it is showing is exactly the model-estimated yearly seasonal effect. If your main goal is to understand seasonal effects, then it would probably be beneficial to try doing MCMC so that you can also see the uncertainty in the seasonality. That will give you a sense of how likely it is that a particular seasonal fluctuation is significant or not (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-seasonality)

I did also note that you are reducing the yearly seasonality Fourier order from the default 10 to 5, to avoid overfitting. The Fourier order basically controls how sharp seasonal changes can be in the time series. This time series actually does have some fairly sharp seasonal changes (especially patio heaters). I don't think the default of 10 is going to be especially prone to overfitting, so I'd recommend keeping that at 10. I think the better way to reduce overfitting in seasonality is with the `seasonality_prior_scale`. This defaults to 10, which applies very little regularization. Pulling that down to something like 1 would be, I think, a better way of regularizing the seasonality than changing the Fourier order. If there were a parameter you wanted to tune, that's the one I'd focus on. There's discussion of hyperparameter tuning and each parameter at the end of the page here: https://facebook.github.io/prophet/docs/diagnostics.html#hyperparameter-tuning
