### ISSUE TITLE
Dispersion of result is too small

### ISSUE THREAD

**Issue by leoknuth** [facebook/prophet#1679]
Blue points are predict result from Prophet. Is there any idea to improve? 

![result](https://user-images.githubusercontent.com/31991086/93653377-84368980-f9cd-11ea-8c7d-3f84aca6285d.png)

Predict doesn't fit actual data well.
![image](https://user-images.githubusercontent.com/31991086/93653462-dbd4f500-f9cd-11ea-93a3-16096c1b044a.png)

**Comment by bletham** [comment]
The fit is pretty poor. One reason it is poor is because it looks like the time series is of something that is always positive, while the model assumes Gaussian noise and that's why you see the lower uncertainty estimate below 0. There is a bunch of discussion of this issue in #1668 and you could try some of the strategies there. I specified there a `ProphetPos` class and I'd be really interested to see what it does on this data. Is there any chance you can share a CSV of this time series?

Besides that, there is a second reason the model fit is poor and it's that these spikes seem to be totally missed. I can't quite tell what the time course of those spikes is. Is this sub-daily data and those spikes take place on a single day? Or do they last for a week? In either case, it won't be captured by the seasonality estimates. I'm guessing each spike is a day, in which case what this means is that the magnitude of the daily seasonality is fluctuating from day to day. Prophet assumes fixed daily seasonality, and so what it fits is something like the average of what is seen in the history. Do you need to forecast at the hourly level? If not, then aggregating the data into a daily total would probably be much easier to forecast.
