### ISSUE TITLE
FBProphet in Python taking too long to run

### ISSUE THREAD

**Issue by blobLead** [facebook/prophet#1680]
Hi @bletham,

Thank you for this wonderful system! I am using Prophet to forecast the next 365 days movement of stocks. I tried different scenarios on what combination of features to use. I only used holidays and special events on the historical data. All worked well. 

But then, I encountered a problem where Prophet is taking too long when I tried adding a seasonality aside from holiday and special event dates, wherein I am trying to find the best self-defined seasonality of the historical data. I am doing this by getting the MAPE of the model when I do add_seasonality method where period is from 1 to number of dataframe rows.

For example, I am looking at Apple stocks and I only have 100 days of data for Apple. I will do the iteration from 1 to 100 to check which is the best self-defined seasonality for Apple based on its historical data. The iteration is all fast for periods 1 to 4 but then suddenly takes too long when it comes to period 5 - still not done after 5 minutes. It took 3 days just to run an iteration until 50. It seems that the problem appears when doing the fitting the model with the iteration for self-defined seasonality. Please help on determining the problem. Thank you!

**Comment by blobLead** [comment]
I also noticed that there are different ways on how convergence is being done. In the images below, one having its iteration from 99, 199, 299 while the run for Apple stock is iterating from 1 to n.. Why is this so?

<img width="538" alt="Screen Shot 2020-09-19 at 10 59 19 PM" src="https://user-images.githubusercontent.com/65531114/93670301-0eb1e280-facd-11ea-9ef4-4b152a014425.png">

<img width="627" alt="Screen Shot 2020-09-19 at 10 59 33 PM" src="https://user-images.githubusercontent.com/65531114/93670305-140f2d00-facd-11ea-935d-84c105918955.png">

**Comment by bletham** [comment]
The different printouts is because there are two Stan optimizers that are used by fbprophet. The first printout is from L-BFGS, the default. The second is from Newton, which is used when L-BFGS fails.

Guessing that the fitting is slow because the model isn't well-specified for the data. I think if you just try to add a seasonality with totally arbitrary period, then it will probably struggle to fit because it's not actually an appropriate seasonality for the data. And if it struggles to fit then it will take a while. I don't know that there's really any more to it than that. Generally, I'm a bit doubtful that the strategy of testing all possible seasonality periods is likely to be useful, especially on a time course of 100 days. There's just no reason to think there would be periodic fluctuations with a period of e.g. 21 days.

**Comment by hansukyang** [comment]
I believe stock price is well understood to be a stochastic process, so forecasting stock price is not meaningful unless you can also model the underlying driver of the price somehow. 

Prophet taking longer to run with ill-defined model is also what I've experienced, so the model fit time has been a good proxy for me to understand how suitable the model definition is for the problem.

**Comment by numeric-lee** [comment]
Prophet is good for quick prototyping, unsuited to stock market forecasting

**Comment by ThoaHoang-vuw** [comment]
We also had this issue when run prophet models. We set up the parameter : uncertainty.samples = 0 in the model. Its running time improved a lot.
