### ISSUE TITLE
fbprophet was installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by bholland** [facebook/prophet#1683]
Hello all,

I get this warning and have for a few months now:

DEPRECATION: fbprophet was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

Is this going to get fixed? I would really like it if facebook maintained their package such that it worked with pip.

**Comment by bletham** [comment]
Thanks for the heads up, that will be extremely obnoxious if they do end up pushing that change because of the long discussion in #401 about needing the build dependencies before building the wheel is a success. Pip install will always be supported, we just may in the future have to specify that all of the dependencies have to be separately pip-installed first.

**Comment by bholland** [comment]
That is fine but honestly, this needs some serious TLC. Pip doesn't install
pystan dependencies properly in windows and I am sure they would love any
support but this is on fbprophet across all distros. I wasn't sure if the
fbprophet team was aware of this particular issue.

**Comment by bletham** [comment]
We weren't, so thanks for the heads up. I spent a whole bunch of effort in #401 trying to set up a pyproject.toml to build the build dependencies prior to the trying to build the wheel and ultimately was not successful as described there. I guess we'll be forced to revisit this.

**Comment by microprediction** [comment]
have you tried upgrading pip first? That solved the issue for me, unexpectedly.

**Comment by bholland** [comment]
Pip just got a massive update. I believe that this doesn't work but it does
build the wheel, which is fine. I can check the logs again to see if there
are pip warnings. It is also possible that pip just doesn't report the
issue if it can build the wheel.

Installing on windows still has issues due to pystan and their lack of
support for msvc but that isn't really fbprophet's problem.

Thanks for keeping this up,
Ben

**Comment by octavd** [comment]
Hey,

I had this problem also but i've managed to make it work with the following workaround.

Before installing fbprophet you have to install pystan.

However if you will install like this -> pip install pystan it will fail at building fbprophet because it will grab version 2.19.. that is not compatible with GCC version.

Solution:

pip install pystan==2.18.0.0

pip install fbprophet

**Comment by bletham** [comment]
I'm going to close this to divert discussion on the `setup.py` and obnixious build requirements to #401, which is the original discussion of these issues.
