### ISSUE TITLE
 ImportError: cannot import name 'Prophet' from partially initialized module 'fbprophet' (most likely due to a circular import)

### ISSUE THREAD

**Issue by crigar001** [facebook/prophet#1698]
ImportError: cannot import name 'Prophet' from partially initialized module 'fbprophet' (most likely due to a circular import) (/Users/Naropa/Downloads/python/fbprophet.py)

runfile('/Users/Naropa/Downloads/python/Euxusd.py', wdir='/Users/Naropa/Downloads/python')
Traceback (most recent call last):

  File "/Users/Naropa/Downloads/python/Euxusd.py", line 11, in <module>
    from fbprophet import Prophet

  File "/Users/Naropa/Downloads/python/fbprophet.py", line 10, in <module>
    from fbprophet import Prophet

**Comment by crigar001** [comment]
please i need help is in mac...

**Comment by bletham** [comment]
The issue here is the file "fbprophet.py". When Euxusd.py is calling `from fbprophet import Prophet`, it isn't importing from the _package_ fbprophet, rather it is importing from the _file_ fbprophet.py (since it is in the same directory). If you rename or remove that file I think things should import properly.

**Comment by crigar001** [comment]
Thanks
