### ISSUE TITLE
under predict, prophet year totals vs simple YTD estimates 

### ISSUE THREAD

**Issue by rquintino** [facebook/prophet#1700]
hey everyone, I was debugging some prophet forecasts (for NY Taxi dataset, test period second semester 2019). 
Without 100% sure but felt on several of the time series (location) a slight tendency for predicting lower that what the data could hint on (visual feeling and based on some simple stats). 

Also relevant because, only going for the full year value, a simple [Prev year value] * (1+%dif YTD vs prev year) seemed to constantly beat prophet year total on several locations (time series). 

If anyone has thoughts.

example, at predict cutpoint we have around -17.49% vs prev year same period year to date. Prophet full year forecast estimates this ratio to ~ -24% at end of year which seems rather excessive, taking into account the yearly trend on this value (below). Actual year vs prev year dif was -19.13%.

![image](https://user-images.githubusercontent.com/10835742/94799702-745e7280-03db-11eb-87d0-59094f5cdfd8.png)

**Comment by rquintino** [comment]
still to find one where simple ytd ratio is beaten by prophet (even with somewhat extensive grid search, though could be picking by the global perc error, vs by period, could change things)

always a possibility that I'm leaking somehow in the simple ytd diff baseline, checking & checking

![image](https://user-images.githubusercontent.com/10835742/94806396-c73d2780-03e5-11eb-8602-18cac8d4a782.png)


![image](https://user-images.githubusercontent.com/10835742/94806601-23a04700-03e6-11eb-8c2b-23bd9201b1c6.png)

**Comment by rquintino** [comment]
tried to pick best model by cutoff aggregate yhat vs y, prob represents the scenario better, 
(some doubts if by always look to period wise absolute perc errors on cv we risk picking models biased to underpredict/overpredict)

Improved from prev, but still, doesnt beat the simple ytd ratio estimate

cv_stats["cutoff_mape"]=**df_cv.groupby("cutoff").sum().eval("abs(yhat-y)/y").mean()**

![image](https://user-images.githubusercontent.com/10835742/94839917-8e19ad00-040f-11eb-9a0c-0f0318ab8e83.png)

**Comment by bletham** [comment]
Just to make sure I'm following fully: we are forecasting at time t. The history ended at time t0. The baseline is
```
yhat_baseline(t) = y[t - 1 year] * (1 + % diff YoY at t0)
```
Is that right? The YoY value being used is at t0 and not at t, right?

From your description it seems that the trend is continuing on at a steeper slope than what actually happend in practic. YoY at t0 was -17.5%; Prophet continued this downward trend to reach -24% at the end of the prediction horizon, the actual YoY at the end of the prediction horizon was -19.1%.  Since the YoY at t0 (-17.5%) is closer to the true value than linearly continuing the downward trend, the YoY model does better.

I don't know that there will necessarily be much to be done about it. Looking at the plots you posted, it looks like there was a pretty clearly decreasing trend that then leveled off. Moving forward into the future, the Prophet trend model assumes symmetry in future trend changes, so the trend is just as likely to head even more negative as it is to flatten out. In this case it flattened out, so using the YoY at t0 was a good choice, but if instead the decrease had further accelerated, it wouldn't have been.

It does look like the trend started to flatten out at the end of the history but that may have been missed by the model. This could be because under default settings the model will not add changepoints to the last 20% of the time series, a pretty conservative default. Increasing the `changepoint_range` parameter to something like 0.9 or 0.95 would probably work better here, and you could validate across the entire set of time series. (see https://facebook.github.io/prophet/docs/diagnostics.html#hyperparameter-tuning for a description of that particular parameter, and a visualization in https://facebook.github.io/prophet/docs/trend_changepoints.html#automatic-changepoint-detection-in-prophet).

If you're able to post the forecast and component plots produced by Prophet (`m.plot(fcst)` and `m.plot_components(fcst)`) I can see if there is anything else that might be happening. I'd be interested to see what the future trend uncertainty looks like, and hopefully the uncertainty interval would reflect the possibility of the trend flattening out in the future.

**Comment by rquintino** [comment]
hi @bletham thanks for sharing your thoughts!

yes that's the formula, a rather simple one but very often used in simple scorecards full year estimates. 

fully understand what you're saying, been looking on this charts very often and try to reason, given all previous information at time t0 is that downwards trend from prophet "acceptable"? was just pure chance that in this case the simple formula beats prophet?

Maybe not exactly related but currently thinking that for medium/long term, trend is the critical component really and easy for prophet to get it wrong. truly have some doubts, more than custom trends, should be something to fine-tune manually by human domain knowledge (at a minimum check between linear and log growth). Also because seems much easier to adjust the trend manually and keep all the prophet calculated coefficients (really hard work).

I have replicated a simple run, now for all locations, default prophet parameters plus holidays, so no grid search (would be a bit complex to get now, but will try to add later), prophet components below, and also updated pbi report

looking with more detail seems after sep 2019 we have a slight inflection of trend, which could be the main reason for the lucky formula to work better. obv prophet follow linear

![image](https://user-images.githubusercontent.com/10835742/95500769-36df8380-099f-11eb-9f57-4d14659dee5b.png)

![image](https://user-images.githubusercontent.com/10835742/95499609-74dba800-099d-11eb-8510-d4759f06cab7.png)

(Forecast)
![image](https://user-images.githubusercontent.com/10835742/95499719-a18fbf80-099d-11eb-863e-a4068ed86d58.png)


![image](https://user-images.githubusercontent.com/10835742/95499497-465dcd00-099d-11eb-98d6-3840afcbe0c4.png)
