### ISSUE TITLE
Are short term (minute/hour) predictions appropriate with prophet?

### ISSUE THREAD

**Issue by nhua6456** [facebook/prophet#1704]
Hi team, this is a general query rather than an issue, but I had not seen much information here or on other sources on whether it's possible to train fb prophet to perform short term predictions for, ie, the next 5-60 minutes.
I have tried to give it a go myself, by using the WorldCup98 dataset and finding my optimal hyperparameters based on the following settings:

```python
for params in all_params:
    m = Prophet(**params).fit(prophet_df)  # Fit model with given params
    df_cv = cross_validation(m, initial='15 min', period='3 min', horizon='5 min', parallel="processes")
    df_p = performance_metrics(df_cv, rolling_window=1)
    rmses.append(df_p['rmse'].values[0])
```
I am still not certain on what would be appropriate choices of initial, period, and horizon, but I have selected the values of 15, 3, and 5min respectively based on the thinking that I would want fb prophet to predict based on the previous 15 minutes of history. 

Any insights, discussion, or suggestions are greatly appreciated!
Thank you

EDIT: I would also like to add that I have begun the model training roughly 2 weeks ago on a 16-core server, and it is still undergoing training. I'm not exactly sure when it will be done.

**Comment by bletham** [comment]
For the cross validation parameters:

`horizon` would be whatever the timeframe of interest for prediction is, so that you can see what the errors look like over that horizon. So a horizon of 5min would be appropriate if you were interested in making forecasts for 5 min in the future and wanted to assess what the model accuracy is likely to be. 

`initial` will be the minimum amount of data used to train a model during CV. That would depend largely on what types of structure you want the model to be able to capture. For instance, if there was weekly seasonality, then you'd want that to be at least a week or two. With daily seasonality, you'd want at least a day or two. I'm not familiar with this WorldCup98 dataset, but if you're interested to make 5 minute forecasts I'm guessing there isn't going to be seasonality at long time scales. The cross validation utility defaults to initial=3*horizon, so I think the choice of 15mins here is good.

`period`: this will determine how many cross validations are done. If the time series is 60 minutes long, then with these settings, cross validation will be done on minutes [15, 55] (keep initial at the start, and horizon at the end) and cutoffs will be placed every 3 minutes. This would mean 13 cutoffs (you should see a printout when you start cross validation that tells you how many cutoffs are being used). That seems reasonable to me. If the time series is several hours long, then this is probably more cutoffs than you need and will just take a really long time to run. So you can choose the period to give you a number of cutoffs that well captures the variance in performance without taking too long to run (since the errors will be correlated across cutoffs anyway). I think 10ish cutoffs is probably usually a good balance.

Which gets us to the running time. 2 weeks is pretty ridiculous. There are three reasons it might be taking so long:
- How many points are in the time series? What is the time frequency and granularity? If it is many thousands of points then it could take a while, and you might want to figure out if there is a way to reduce its size without losing anything.
- How big is the hyperparameter sweep? That is, how large is all_params? If it is really large (e.g. from a giant grid search) then it may be impractical to do the sweep that way.
- As discussed above, how many cutoffs are there in each cross validation? 10 cutoffs means fitting the model 10 times; 30 means 30 model fits, etc. I think especially for the purposes of hyperparameter selection, a coarser number of cutoffs would be appropriate and would help get the runtime under control.

**Comment by nhua6456** [comment]
Apologies for the delayed response, but 18 days later... It is indeed still "training"
I don't believe that there is a predictable pattern to the dataset, below is a plot of the data in question
![image](https://user-images.githubusercontent.com/14882670/97148808-d84c3f00-17bf-11eb-8058-8ff3c55df45b.png)
There's roughly 130,000 data points, and the time frequency is by the minute.

In terms of the hyperparameter sweep, i'm sweeping the following:
```
param_grid = {
    'changepoint_prior_scale': [0.001, 0.01, 0.1, 0.5],
    'seasonality_prior_scale': [0.01, 0.1, 1.0, 10.0],
}
```
so about 16 different combinations.
As I didnt parse a cutoff parameter to the cross validation, there aren't any.

I think what i'll try to do is decrease the number of parameters i'm sweeping, and perhaps feed about 10 cutoffs. Could you suggest other tactics that might help increase the training speed?

**Comment by bletham** [comment]
Model fitting will definitely be slow with 130k data points. With minute-level data, you would probably want to either aggregate to something higher, or not use a full month of historical data (maybe a week is sufficient with such fine granularity).

Predict will also be very slow, but could be made much faster by only predicting for the points you need. For instance, if you use `m.make_future_dataframe` to make the dataframe of future predict points, it will by default include all of the training points. If you use `include_history=False` then it will need to make many fewer predictions and will be a lot faster.

But generally, I'm not especially optimistic about Prophet doing well on this time series. Prophet works best with time series that have consistent seasonal effects. This time series doesn't really have that. If you were to aggregate to daily total it might be able to learn something there, but with just even then the weekly seasonality doesn't look very stable.
