### ISSUE TITLE
Conditional seasonalities for specific weekdays

### ISSUE THREAD

**Issue by com-network** [facebook/prophet#1713]
Hello, I'm new to forecasting and I'm getting started with Prophet to complete my task. So far I have been following the documentation and running the examples provided.

My task is to forecast the number of sales of a store which opens regularly 3 days a week on Tuesday, Thursday and Saturday. The historical data also contains data of these weekdays only. I am trying to use conditional seasonalities as below:

```
is_store_opening_date <- function(ds) {
  dates <- as.Date(ds)
  weekday <- as.POSIXlt(dates)$wday
  return(weekday == 2 | weekday == 4 | weekday == 6)
}

df$on_season <- is_store_opening_date(df$ds)
df$off_season <- !is_store_opening_date(df$ds)
```

and then add it to the dataframe:

```
m <- prophet(changepoint.prior.scale = 0.5, daily.seasonality=FALSE, weekly.seasonality=FALSE, yearly.seasonality=FALSE)
m <- add_seasonality(m, name='weekly_on_season', period=7, fourier.order=3, condition.name='on_season')
m <- add_seasonality(m, name='weekly_off_season', period=7, fourier.order=3, condition.name='off_season')
m <- fit.prophet(m, df)

future$on_season <- is_store_opening_date(future$ds)
future$off_season <- !is_store_opening_date(future$ds)
```

So can anyone please take a look to see if I'm misunderstanding anything here? Thanks very much.

**Comment by bletham** [comment]
Sorry for the slow reply.

Does your time series just have 0s for Monday, Wednesday, Fri, and Sun? If so, then lots of 0s like that can mess up the trend estimate, so I think you'd be better off just dropping those dates entirely from the history. In that case, you don't need the `weekly_off_season` at all.

Otherwise this seems reasonable to me, is there something that looks bad with the forecast? If so then if you're able to plot the output of `m.plot` and `m.plot_components` I could provide some comments on what the model is doing.
