### ISSUE TITLE
Adjustments because of covid

### ISSUE THREAD

**Issue by johnnykahits** [facebook/prophet#1726]
Hi everyone, I was using prophet for a retail company and worked very well until covid appeared. Times series during march to july had a huge decrease and started to using the model now in october but the results are over estimated by a lot. Do you have any idea what I can do? Thanks

**Comment by hansukyang** [comment]
It might sound counter-intuitive but it might help to try with less data. If the model was originally fitted with several years worth of data, the regularity of the data prior to COVID-19 may be causing it to over-estimate (because why wouldn't it?). Time-series forecasting and prediction doesn't work well if there is something that the model hasn't accounted for.

**Comment by bletham** [comment]
There's some discussion of this in #1416, along with some suggestions of things to try! I don't think there's a single right answer and definitely post there if you find things that work well for you for others to try.
