### ISSUE TITLE
Need advise to build a prophet model that should work for multiple department data

### ISSUE THREAD

**Issue by ananthu2050** [facebook/prophet#1727]
I am trying to predict certain organizational financial metric using prophet based on historical data and I have following questions. 

- I have around 100 departments and each have different behavior. Some are sales departments, some are quality control, some are manufacturing etc. Should I build and manage 100 models one for each department?
- Some departments seem to exhibit monthly seasonality and I get better predictions for some departments while considering monthly seasonality. Some departments like sales are greatly impacted by external regressors like country's economic indicators. Models for these departments work better when external regressors are considered. But some other department's models predict well without external regressors. Cross validate functionality helps in hyper parameter tuning? Is there a similar way to experiment and tune the model for these sort of different combinations without using loops?
- Due to COVID impact, most of my predictions are not accurate. I have tried cross validation and chosen the best possible hyperparameters and looking at plots identified other parameters like seasonality, holiday effect etc. Still my predictions are not accurate. Is there a systematic approach to correct the predicted values for these scenarios and make the predictions somewhat useful to users?

Thanks for the inputs

**Comment by bletham** [comment]
* If you need forecasts at the department level, then with Prophet you have little choice but to fit a separate model for each department since there isn't any multivariate forecasting in Prophet. You might find it beneficial to include the top-level aggregate as a regressor in the forecast as described here (https://github.com/facebook/prophet/issues/49#issuecomment-430383681), but that's about the closest you can get to a joint forecast in Prophet. If you don't need a forecast at the level of individual departments, then directly predicting the top-level aggregate would probably be the easiest approach.

* Identifying best parameters for a large number of time series: There's some discussion of this in #1687 . As I described there, I think the alternative would be something along the lines of identifying some small set of prototypical time series such that you expect most time series to be similar to one of them, finding the best parameters for each of those, and then for any other time series just check over that small set of optimal parameters.

* There's discussion in #1416 about handling the effect of COVID. I don't think there is one right solution, but there are various suggestions in that issue.
