### ISSUE TITLE
cutoff point calculation seems to be wrong in diagnostic notebook

### ISSUE THREAD

**Issue by robomotic** [facebook/prophet#1731]
Hi there,
I think there is an issue in the cutoff point date calculation or maybe the description in the documentation is not accurate.
Let me elaborate from the example in the notebook section.

```
df = pd.read_csv('./data/example_wp_log_peyton_manning.csv')
df['ds']=pd.to_datetime(df['ds'], infer_datetime_format=True)  
df.describe(include='all')
```

This shows that ds ranges from 2007-12-10 00:00:00 to 2016-01-20 00:00:00 with 2905 days in total.
You then run:

`
df_cv = cross_validation(m, '365 days', initial='1825 days', period='365 days')
`

which generate one cutoff point at 2013-01-20 because initial = period that is fine.

Now I was expecting that the cutoff point was going to be at this date 2012-12-08:

```
from datetime import timedelta
cutoff_expected = df.ds.min() + timedelta(days=1825)  
```

So in my mind we are in excess of 43 days which I can't really figure out where they come from:

`datetime.datetime(2013, 1, 20)-datetime.datetime(2012,12,8)`

Let me know where my logic is failing.
Cheers!

--

**Comment by ojnas** [comment]
This is because cutoffs are generated backwards from `df['ds'].max() - horizon` so that the last forecast horizon ends at `df['ds'].max()`, see code here:

https://github.com/facebook/prophet/blob/4f34de036390bc0e66bdc9ffe2d89361ccbc3f07/python/fbprophet/diagnostics.py#L20

If there is not a whole number of periods between `min(df['ds']) + initial` and the last cutoff, then the first cutoff will be at a later time. In practice, `initial` should be seen as the minimum initial training period, the documentation could be clearer on this.

**Comment by robomotic** [comment]
Hi,
thanks for the explanation this makes sense now.
Also just to understand why is the fit method required before the cross_validation? I am assuming the training data provided to fit is discarded during the trial.

**Comment by ojnas** [comment]
> Also just to understand why is the fit method required before the cross_validation?

This is a good question to which I don't have a good answer. My guess is that it's mainly a matter of convenience from an implementation perspective but I'm also curious and suggest you post a separate issue about that. From looking at the code, I can see that a new fit and prediction is performed for every cutoff as expected:

https://github.com/facebook/prophet/blob/4f34de036390bc0e66bdc9ffe2d89361ccbc3f07/python/fbprophet/diagnostics.py#L204

I can also see that the largest identified seasonality period of the original fitted model is used for calculating or checking the `initial` parameter:

https://github.com/facebook/prophet/blob/4f34de036390bc0e66bdc9ffe2d89361ccbc3f07/python/fbprophet/diagnostics.py#L125

**Comment by bletham** [comment]
@ojnas thanks for clarifying this, I agree it should be made more clear in the documentation.

As for why the model needs to be fit prior to doing CV: this is because there are various aspects of the model that are chosen automatically during fit based on the data, and during CV these are held constant at whatever they are in the "final" model, rather than changing based on the CV fits. I give more description of this here: https://github.com/facebook/prophet/issues/1409#issuecomment-606832979

The intention is basically to be sure that the model settings we are testing in cross validation are as close to those in the final model as possible. In the code, right here is where all of the settings from the "final" model are copied over to each of the CV models:
https://github.com/facebook/prophet/blob/ad3832bb1957da1ba3efb4f6b0196977fcd13f06/python/fbprophet/diagnostics.py#L287-L304

**Comment by robomotic** [comment]
Yes this is more clear now, but I have two questions:

- during the copy process are we not leaking tuning information (e.g. learned parameters) from the wider training window inside the cross folds (subsets of the training window)? For example we shouldn't copy the fourier coefficients and scale that were learned during the fit method in the training window right?
- does the cv method automatically discards the windows where there are not enough minimum cycles to fit the model? in the example you described maybe the training set has more than 2 year periods but the cross folds that are being built have less than 2 years, so I am assuming those ones are just ignored?

Sorry for the silly questions I am just trying to understand more.
Cheers!

**Comment by bletham** [comment]
These are good questions.

* The _fitted parameters_ are not copied into each CV model, just the model structure (basically settings that can be specified in the `Prophet()` constructor, plus added seasonalities/regressors/holidays). So it would copy over that I have added a monthly seasonality to the model, but would not copy over the actual parameters of that monthly seasonality (the Fourier coefficients); these would be fit from the data inside that CV fold. I hope that clarifies that. Put otherwise, all of the parameters that are fit in the Stan during model fitting are not copied but are re-fit in each CV fold.

* It does not do this automatically. There is a bit of a tension here where on the one hand if I'm fitting a model with yearly seasonality but have a CV fold where it was auto-disabled, that fold probably wouldn't provide a useful estimate of the error of the model when it does have yearly seasonality enabled. But as you note, on the other hand, if I leave yearly seasonality enabled but then try to fit it on a CV fold that is only a few months, that also probably won't provide a very useful error estimate for a model that actually has enough data to fit the yearly seasonality. As you know, we have taken the cross validation in the 2nd direction (keeping the seasonalities on if they are used in the final model), and to avoid this issue we just raise a warning if the CV fold has less data than the seasonality:
https://github.com/facebook/prophet/blob/ad3832bb1957da1ba3efb4f6b0196977fcd13f06/python/fbprophet/diagnostics.py#L152-L159
So if you are doing CV on a model that has yearly seasonality, it will print out this warning if the CV settings are such that there are folds with < 1 year of data.

**Comment by robomotic** [comment]
Hi again,
this was a very productive conversation, thanks for taking the time to explain it.
I feel much more confident now about how I am using those features!
Closing this down and hopefully will be useful to other users when searching.
Thanks!
