### ISSUE TITLE
Cross-validation with conditional seasonality not working

### ISSUE THREAD

**Issue by natashanorsker** [facebook/prophet#1733]
I'm having an issue using cross-validation while using conditional seasonality.

The model looks like this:
`model = Prophet(growth = 'linear',
                holidays=holiday_df,
                interval_width=0.95,
                seasonality_mode='additive',
                daily_seasonality = False,
                weekly_seasonality = False,
                yearly_seasonality=False
                                ).add_seasonality(name='monthly_promo', period=30.5, fourier_order=7, prior_scale = 40, condition_name = 'Promo_cond'
                                ).add_seasonality(name='monthly_non_promo', period=30.5, fourier_order=7, prior_scale = .5, condition_name = 'Non_promo_cond'
                                ).add_seasonality(name='weekly', period=7, fourier_order=3,prior_scale = 5
                                ).add_seasonality(name='yearly_promo', period=365.25, fourier_order=5, prior_scale=40, condition_name = 'Promo_cond'
                                ).add_seasonality(name='yearly_non_promo', period=365.25, fourier_order=5, prior_scale=0.5, condition_name = 'Non_promo_cond')`

The error message looks like this:

![image](https://user-images.githubusercontent.com/57072972/98824454-9fed6780-2433-11eb-814c-74d3383fa21e.png)

The conditions 'Promo_cond' and 'Non_promo_cond' are boolean:
![image](https://user-images.githubusercontent.com/57072972/98825172-78e36580-2434-11eb-9259-01a22b6338a3.png)

I have the following versions installed:
- pandas == 1.1.4
- numexpr==2.7.1
-  fbprophet==0.7.1

I tried downgrading pandas==1.1.2 but it didn't solve the problem

**Comment by bletham** [comment]
I'm not sure what's happening here since this should work. I'm on fbprophet 0.7.1 and pandas 1.1.4. This code works for me doing cross validation on a model with conditional seasonality, using the dataset from the quickstart example notebook:
```Python
import pandas as pd
from fbprophet import Prophet
from fbprophet.diagnostics import cross_validation

# Load the data

df = pd.read_csv('../examples/example_wp_log_peyton_manning.csv')

# Fit a model

def is_nfl_season(ds):
    date = pd.to_datetime(ds)
    return (date.month > 8 or date.month < 2)

df['on_season'] = df['ds'].apply(is_nfl_season)
df['off_season'] = ~df['ds'].apply(is_nfl_season)

m = Prophet(weekly_seasonality=False)
m.add_seasonality(name='weekly_on_season', period=7, fourier_order=3, condition_name='on_season')
m.add_seasonality(name='weekly_off_season', period=7, fourier_order=3, condition_name='off_season')
m.fit(df)

# Check that we are able to make predictions

future = m.make_future_dataframe(periods=366)
future['on_season'] = future['ds'].apply(is_nfl_season)
future['off_season'] = ~future['ds'].apply(is_nfl_season)
forecast = m.predict(future)
fig = m.plot(forecast)

# Do cross validation

df_cv = cross_validation(m, initial='730 days', period='365 days', horizon = '365 days')
```

Could you post some code that I can run that produces the error?

Could you also verify that the model is able to make predictions on the training set by running `m.predict()`?

Lastly, are you able to drop into the debugger (`%debug` in jupyter notebook)  and figure out why the `df[condition_name].isin([True, False]).all()` isn't working? The error message about needing to use `a.all()` is confusing since that line is using `.all()`. Maybe something is mixed up with `condition_name`? What is that in this frame?

**Comment by mcmiralles** [comment]
Hello,

 I'm coming back to this issue as I faced same situation as @natashanorsker describes above. I'd say the issue arises when you want to add more than one conditional seasonality type. 

 My use case is a volume forecasting. Because of covid, I created an interval for the hardest covid impact (exactly same approach of the season on/off described [here](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#seasonalities-that-depend-on-other-factors). In our case, we need to contemplate weekly and yearly seasonality, and for both apply the condition covid_on / off.  When moving to cross-validation, I get same error than in #1733. If I try cross-validation with only one of the seasonality linked to condition (e.g. weekly) it works.

 I stressed the example provided by @bletham and instead running it only for one seasonality type (weekly), I also added the yearly (even if I'm not entirely sure makes sense for the use case itself, but only for testing purposes). Result is that for only one it works, but for two, returns the same error as @natashanorsker got.

Some screenshots to illustrate my words:

1. Example with only one, it works:
 
![image](https://user-images.githubusercontent.com/90398827/133218466-617a9571-8c18-474c-8b8a-2e696a13f1a4.png)
 

2. Example with two, it fails:

![image](https://user-images.githubusercontent.com/90398827/133218683-4b01d02e-03f2-4c8a-8809-7092086c3ded.png)
![image](https://user-images.githubusercontent.com/90398827/133218712-fbf493e9-fef8-412a-8947-66d9e8961b9a.png)

Version installed:
- pandas 1.2.4
- prophet 1.0

Brgrds,
