### ISSUE TITLE
Is it safe to train with multiple timeseries   ?

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#1734]
I found prophet can train and predict multiple timeseries (same product  and `ds` in diffrerent stores) .
For example I have 42 stores , each have 365days records . One-hot encode store_id and feed to prophet can get a proper result as I saw . But I am afraid is it safe and stable in this way ?

**Comment by bletham** [comment]
So basically in the dataframe you pass into Prophet you have multiple datapoints for each day, one for each store? How are you using the one-hot encoding?

**Comment by eromoe** [comment]
1. YES
2. It's simple : 
```
df_store_code = pd.get_dummies(df_new2["store_code"], prefix="store", drop_first=True)
df_new3 = pd.concat([df_new2, df_store_code], axis=1)
```
3. The problem is the result doesn't keep original order, so I add `keep_cols` param to  `predict` : 
```
from fbprophet import Prophet

def predict(self, df=None, keep_cols=[]):
    """Predict using the prophet model.
    Parameters
    ----------
    df: pd.DataFrame with dates for predictions (column ds), and capacity
        (column cap) if logistic growth. If not provided, predictions are
        made on the history.
    Returns
    -------
    A pd.DataFrame with the forecast components.
    """

    if self.history is None:
        raise Exception('Model must be fit before predictions can be made.')

    if df is None:
        df = self.history.copy()
    else:
        if df.shape[0] == 0:
            raise ValueError('Dataframe has no rows.')
        # print(df.index)
        df = self.setup_dataframe(df.copy())
        # print(df.columns)

    df['trend'] = self.predict_trend(df)
    seasonal_components = self.predict_seasonal_components(df)
    if self.uncertainty_samples:
        intervals = self.predict_uncertainty(df)
    else:
        intervals = None

    # Drop columns except ds, cap, floor, and trend
    cols = ['ds', 'trend'] + keep_cols
    if 'cap' in df:
        cols.append('cap')
    if self.logistic_floor:
        cols.append('floor')
    # Add in forecast components
    df2 = pd.concat((df[cols], intervals, seasonal_components), axis=1)

    df2['yhat'] = (
            df2['trend'] * (1 + df2['multiplicative_terms'])
            + df2['additive_terms']
    )
    return df2

Prophet.predict = predict

X_t1 = df_train.fillna(0).reset_index().rename(columns={'sale_count':'y'})
m = Prophet()
for i in X_t1.columns:
    if i not in ('ds', 'y', 'store_code'):
        m.add_regressor(i, mode="additive", prior_scale=None,)

m.fit(X_t1)
pred = m.predict(X_t1, keep_cols=['store_code'])
m.plot_components(pred)
```


![image](https://user-images.githubusercontent.com/3938751/99476739-11756a80-298c-11eb-86cd-3dd3df28d8bf.png)

**Comment by eromoe** [comment]
@bletham 

I also have a question about hierarchy model , 

For example , my target `product sale_count` have 4 level hierarchy structure `category 1/  category 2 / product_in_different_city/ product_in_different_store ` . 
The exogenous features are bound to bottom level `product_in_different_store` and middle level `product_in_different_city` .  Use `product_in_different_store`  or  `product_in_different_city with one-hot encode store features` still doesn't perform well on many products . They are lack of exogenous features , some features may be only happend once , hard to estimate best coefficient . 

The only solution I come up is hierarchy model ,  I looked some models  like https://github.com/CollinRooney12/htsprophet and https://github.com/carlomazzaferro/scikit-hts-examples  , but the calculation seems too huge if I use 40 + features , since it is already quite slow in fbprophet now. 
And in those examples I saw they only had exogenous features on top level , that is also a problem ...

What is be proper way I should do , could you give me some suggestions ?

**Comment by bletham** [comment]
Sorry for the slow reply! I haven't really considered hierarchical modeling in this way before. If I correctly understand what is being done, then it is basically that there is a single dataframe with the data from every store, with binary indicators for each store. These binary indicators are added as extra regressors.

The model this produces is basically one where each store will have the same forecast but with a constant offset. If y_1, ..., y_m are the time series for each store, then the forecast for each of them will be
```
y_1(t) = trend(t) + seasonality(t) + beta_1
...
y_m(t) = trend(t) + seasonality(t) + beta_m
```
where they have the same trend, the same seasonality, and the only difference is the constant offsets `beta_1` and `beta_m` (which is the coefficient to the binary regressor fit by the model).

This seems like a really strong assumption. I haven't done a lot of hierarchical forecasting myself, but the only suggestion I really have is what I described in https://github.com/facebook/prophet/issues/49#issuecomment-430383681 . Basically what that would mean here is:
* Forecast the highest level, `category 1`. This is a single Prophet model.
* Make a separate forecast for each item in `category 2`, each of them using the forecast for `category 1` as an extra regressor. Note that these are all single Prophet models with a single extra regressor (`category 1`)
* You could continue working down into the hierarchy: For each city, forecast `product_in_different_city` with the appropriate `category 1` and `category 2` forecasts as extra regressors. Note again that each city is forecasted separately; the only link between them is that they use the same extra regressors.

This would be a lot faster because you don't have to throw all of the data into a single model. There is no one-hot encoding involved.

**Comment by eromoe** [comment]
Thank you , I would take a try  :)
