### ISSUE TITLE
[Feature Idea] ablility to specify which columns to use in .fit function

### ISSUE THREAD

**Issue by kevkevinpal** [facebook/prophet#1737]
I noticed right now we need to specify `ds` and `y` for the dataframe that we are using in the Prophet.fit() function.

I was wondering if people thought adding an attribute called `date_col` and another called `y_col` to be able to specify the name of the column we want to use and otherwise just default to `date_col='ds'` and `y_col='y'` would be a good idea.

example use 
```
prophet = Prophet(yearly_seasonality=True, daily_seasonality=False)
prophet.fit(df, date_col='date_col_name', y_col='y_col_name' )

```

I can start working on it if people think its a good addition

Thanks,
Kevin

**Comment by bletham** [comment]
@seanjtaylor and I discussed this idea pretty early on. We ultimately decided not to pursue it because the convenience inside the package and in the documentation for having a fixed data representation is pretty high, whereas the difficulty of converting column names to `ds` and `y` outside the package is pretty low (a single line of pandas or dplyr). Is there a particular use case that is driving this, or a situation where it would be a lot more convenient to not have to rename columns?

**Comment by kevkevinpal** [comment]
ahh I see that makes sense would it make sense to be able to pass in those attributes and then mutate the df passed in directly to .fit or would that be confusing as everything else would be referred to as `ds` and `y`?

I didn't have a specific situation that would be a lot more convenient just saw it and thought it seemed a bit strange but your explanation helps!
