### ISSUE TITLE
Are multi-step (seq2seq) predictions possible with Prophet?

### ISSUE THREAD

**Issue by Nestak2** [facebook/prophet#1739]
Hi! Please don't confuse my question with the one before about multivariate predictions!
What I want to do is to train a Prophet model on predicting the air temperature and have it ran once a day to predict the air temperature for the next 3 days, means the model returning for each timestamp in `ds` an array `[t+1, t+2, t+3]`. Is this possible?
I know I can achieve this by training instead 3 different models shifted by t+1, t+2 and t+3 in `ds` and then obtaining time-shifted predictions from them. But I thought that having a model with multi-step predictions would be more accurate because it would include the time correlations between t+1, t+2 and t+3. If prophet can't do this would you recommend me another tool? Thanks!

**Comment by bletham** [comment]
If I understand correctly what you're trying to do, it sounds like it would be pretty straightforward, since yes Prophet can jointly redict multiple days into the future.
At day `t`, you would fit a model using all available data. Then you can predict the next 3 days simultaneously, like
```
m = Prophet()
m.fit(df)
future = m.make_future_dataframe(periods=3, include_history=False)  # these are the next 3 days
forecast = m.predict(future)  # This is a dataframe with 3 rows, one for each of the next 3 days.
```
The following day, you would re-fit the model with the new datapoint for that day and repeat the procedure above.
