### ISSUE TITLE
Mixed additive and multiplicative regressors

### ISSUE THREAD

**Issue by gentnm** [facebook/prophet#1742]
Hey,

I am working on a churn problem, predicting the expected number of churners per week.
We want to use information on the amount of different contracts as an additional regressor, but our seasonalities are multiplicative.
Since this case is mentioned to work, but not explicitly explained and deducted from the predict function that in this case the prediction is computed as `trend(t)*multiplicative_regressors(t)+additive_regressors(t)`. But in my use case, this should be `(trend(t)+additive_regressors(t))*multiplicative_regressors`.
Is it possible to do this somehow? I guess it is hard, since the general stan model is being fixed at compile time, is it?

Thanks for any pointers
Michael

**Comment by bletham** [comment]
Sorry for the slow reply! That's correct, each seasonality is multiplicative or additive just on the trend, not multiplicative on the other regressors.

A log transform of the data would get you something closer to this (albeit all multiplicative instead of a mixture): if we fit a model to `log(y) = trend(t) + seasonality(t) + regressor1(t) + regressor2(t)`, then when we take the `exp(y_hat)` to get that back to the original values, the seasonalities and regressors would all be multiplying eachother.

Otherwise I'm not sure there are any great options. I suppose you could instead of fitting `y(t)`, directly compute `y(t) / multiplicative_regressors(t)` and fit an additive model for that quantity. But the challenge here will be that you'd have to figure out the right weights for the regressors separately from the Prophet model fitting. But that's probably the only thing that could be done other than making changes to the stan model. If you do want to tweak around in the Stan, it is being compiled at install time, but there are some directions here on recompiling if you wanted to go down that road: https://facebook.github.io/prophet/docs/contributing.html
