### ISSUE TITLE
Cross validating monthly data in R

### ISSUE THREAD

**Issue by OleksiyAnokhin** [facebook/prophet#1744]
@bletham, I reviewed multiple issues, but unfortunately did not find clear instructions how to use cross validation on monthly data for R. 
I have 156 data points and just this line of code gives me terrible results: 
`model1_cv <- cross_validation(model1, initial = 156, period = 365/12, horizon = 365/12, units = "days")`

This approach you recommended in [586](https://github.com/facebook/prophet/issues/586)
`model1_cv <- cross_validation(model1, initial = 156, period = 365/12, as.difftime(horizon = 365/12, units = "days"))`

give me an error about `horizon` as unused argument. 

Any tips or recommendations where can I read how to solve it? I read that monthly data is not the best, but people do something. I have data per month between 2008 and 2018. 

Thank you!

**Comment by bletham** [comment]
The challenge with cross validating monthly data has been that since a month is not a fixed amount of time, it's been hard to get consistent one-month-ahead forecasts. Things have been made easier in the latest v0.7 release since it allows you to directly specify the dates of the cutoffs you want to use (see #1351). So let's say you want to make a cross validation prediction every month for the next month. You would generate a monthly sequence of dates, specify those as the cutoffs, and then choose something like 32 days as the horizon (long enough to get the day for next month regardless of how many days are in the current month. Like,
```R
cutoffs <- seq.Date(from=as.Date('2019-01-01'), to=as.Date('2020-01-01'), by="month")
model_cv <- cross_validation(model, cutoffs=cutoffs, horizon=32, units="days")
```
We've been having some CRAN issues with v0.7 so it's not on CRAN yet, you'll want to install it with
```R
devtools::install_github('facebook/prophet', subdir='R')
```

**Comment by OleksiyAnokhin** [comment]
Thanks a lot! Will try!
