### ISSUE TITLE
Cross Validation: Short term versus long term and custom seasonality testing

### ISSUE THREAD

**Issue by GinoWoz1** [facebook/prophet#1746]
Hello Prophet team and community, great product!

Couple theoretical questions I am grappling with in terms of on-going cross validation and would love to see input.

1.  When doing cross validation, I attempted different stretching windows over N weeks choosing the model that performed best over the given time (52 weeks, 26 weeks, 24 weeks, 12 weeks etc). In 2019 a changepoint prior scale of 0.05 performed best while in 2020 a changepoint prior scale of 0.9 performed best. 
    **Question:** Given this information, how should one update the model parameters accordingly taking into account the long term and short term trends? When I used the last 3 months of history a changepoint scale of 0.05 was used but there were some downticks in demand given renewed shutdowns in the US and the election which were not picked up. If I had used the 52 week history a more flexible changepoint would have been chosen.

2.  When taking 'Analyst in the loop' feedback to model additional seasonalities, the model improved greatly. However, when trying to cross validate on 52 weeks 2-3 weeks after the event (since it takes a week to take effect) it would get drowned out by the prior 49-50 weeks in terms of model improvement. 
    **Question 1:** When cross validating for new seasonalities, should the addition of new seasonalities only be tested after the point of the business change to see if it has a significant of an effect to include? 
    **Question 2:** If 2 or more seasonalities are to be tested in combination should the additional seasonalities be tested from the date of the first event? In the latter case if I compare a change April forward versus July forward the comparisons may be unequal since July forward I am not considering the April change so I may want to include both seasonalities April forward.

**Comment by bletham** [comment]
1. If I understand correctly, you've done cross validation with different horizons and found that the optimal parameters are different for different horizons. If there is a particular horizon of primary interest then I guess using that one makes sense, but otherwise I'd probably look at the longest horizon that you want to make predictions for, since the error there will include the error for all of the shorter horizons too.

2. For a conditional seasonality that kicks in on a particular date, you'd want to put your `initial` window for the cross validation to be one period after that date, so that the model is able to fit it in the CV cutoffs.

**Comment by GinoWoz1** [comment]
Thanks for the reply. Do you think it makes sense to create a 'cutoff' point for certain business-input changes for like 2-3 months or should the conditional seasonality be added permanently? I would think after a 3-4 month period that change would potentially be picked up without the seasonality given that the changepoint.prior.scale is flexible enough.

**Comment by bletham** [comment]
I'm a bit confused as to the set-up here, so I'm not sure what you mean by "a model with 5 seasonalities by the end of the year". Are you creating a new conditional seasonality for blocks of months for each year? so the seasonality in 2020 is totally distinct from that in 2019, or something like that?

**Comment by GinoWoz1** [comment]
Say there is a conditional seasonality added in April then another change
found in September . The model at that point would have 2 conditional
seasonalities. My point is that If there are 5 seasonalities tested one at
a time throughout the year and found to have an effect , the model would
have 5 seasonalities added by the end of the year . When adding new  custom
seasonality throughout the year should the inclusion of other ones be
tested? In October for example , should I test all data from April forward
(first seasonality) including the September change?

If there is one more business change in November (say a new deal that
brings in increased volume and changes the week to week business ) should I
test the November change by itself or should I somehow do some cv on
whether I should be including April, September and November custom
seasonalities together or different combinations of them ?

I assume that having 3+ custom seasonality at once on a model may overfit
at some point unless there is a end date set (for no business reason but to
incrementally remove complexity ) .

**Comment by GinoWoz1** [comment]
> I'm a bit confused as to the set-up here, so I'm not sure what you mean by "a model with 5 seasonalities by the end of the year". Are you creating a new conditional seasonality for blocks of months for each year? so the seasonality in 2020 is totally distinct from that in 2019, or something like that?

Say there is a conditional seasonality added in April then another change
found in September . The model at that point would have 2 conditional
seasonalities. My point is that If there are 5 seasonalities tested one at
a time throughout the year and found to have an effect , the model would
have 5 seasonalities added by the end of the year . When adding new  custom
seasonality throughout the year should the inclusion of other ones be
tested? In October for example , should I test all data from April forward
(first seasonality) including the September change?

If there is one more business change in November (say a new deal that
brings in increased volume and changes the week to week business ) should I
test the November change by itself or should I somehow do some cv on
whether I should be including April, September and November custom
seasonalities together or different combinations of them ?

I assume that having 3+ custom seasonality at once on a model may overfit
at some point unless there is a end date set (for no business reason but to
incrementally remove complexity ) .

**Comment by bletham** [comment]
I see, thanks for explaining the situation. I think generally it is going to be a challenge to handle frequent changes to the seasonalities since the seasonality is assumed stationary and when making a forecast it will not be able to account for future changes in the seasonality. I think the approach you have taken of chunking things into conditional seasonalities is probably about the best that could be done.

For the purposes of cross-validation, what I'd probably do is focus on estimating model performance during periods without changes in seasonality. Basically the question you'd be trying to answer is, "As long as the seasonality stays at it's current state, what will my forecast error be?". In order to do this I think you'd want to just manually select the cutoff dates, and pass them in with the `cutoffs=` kwarg to cross_validation. If you are forecasting a 1-month horizon and have a unique conditional weekly seasonalities, then choose cutoff dates that have at least a couple weeks of that seasonality (so it can reasonably be fit), but are more than a month before the end of that conditional seasonality block (so it isn't making forecasts for the next seasonality that it won't be able to model). I hope that helps!

**Comment by GinoWoz1** [comment]
Thanks! Quick clarifying question. 

> For the purposes of cross-validation, what I'd probably do is focus on estimating model performance during periods without changes in seasonality. Basically the question you'd be trying to answer is, "As long as the seasonality stays at it's current state, what will my forecast error be?". In order to do this I think you'd want to just manually select the cutoff dates, and pass them in with the `cutoffs=` kwarg to cross_validation. If you are forecasting a 1-month horizon and have a unique conditional weekly seasonalities, then choose cutoff dates that have at least a couple weeks of that seasonality (so it can reasonably be fit), but are more than a month before the end of that conditional seasonality block (so it isn't making forecasts for the next seasonality that it won't be able to model). I hope that helps!

What do you mean in terms of testing without changes in seasonality? Does this mean to include only the latest seasonality and test if it is still applicable (and remove it is not)? Then subsequent seasonalities would be tested in the same way? Say, only taking 1.5 months (from 9/14 - 10/30) on a 9/1 seasonality?

What is happening currently is that with April and September weekly seasonality don't do well once I get into October, November, December. In the beginning quickly following large changes, it did quite well (1-2 months past the event). Assuming this is because the fourier transformation is insufficient for modelling the long-term curve.

**Comment by bletham** [comment]
The model assumes stationary seasonality. So for the windows where the conditional seasonalities are fixed (Jan through April, April to September, and then September+), the seasonality will be modeled as constant within those windows. It will also be modeled as constant for the entire September+ window, no matter how far into the future that window goes. If the reason the model performance degrades after 1-2 months is because the weekly seasonality is changing after 1-2 months, then the model isn't going to be able to capture that.  Is that what's happening?

**Comment by GinoWoz1** [comment]
Yes . It is degrading after 1-2 months . I am wondering If I should just
set a 1-2 month end date on the seasonalties or test the removal of them
every week after a month . In the days immediately follow the event the
conditional seasonalties do great .
