### ISSUE TITLE
Monthly Data with Quarterly Seasonality

### ISSUE THREAD

**Issue by Mraghuvaran** [facebook/prophet#1748]
I have the monthly data, and there is  a seasonality for every quarter. 
Now When I plot components the X-axis values for quarterly seasonality is giving wrong output.  

`final_model = Prophet(#holidays=holiday,
                      changepoint_prior_scale= 0.4,
                      n_changepoints = 3,
                      seasonality_mode = 'additive',
                      weekly_seasonality=False,
                      daily_seasonality = False,
                      yearly_seasonality = False,
                      interval_width=0.95).add_seasonality(name='quarterly', period=365.25/4, fourier_order=10,
                                                           prior_scale=10)`

My Questions are: 
1. Is the add_seasonality  above is correct for quarterly seasonality for monthly data ? 
2. why values are limited to jan to april for quarterly seasonality ?

![image](https://user-images.githubusercontent.com/53115668/100849289-5af3a880-34a8-11eb-82d5-a59f0ddf847e.png)

**Comment by bletham** [comment]
1. Yes, this is correct.
2. For custom seasonalities, the plot just shows one cycle (so, one quarter) starting in Jan 1 (so, Q1). The pattern for Q2, Q3, etc. will be identical. This happens here:
https://github.com/facebook/prophet/blob/ee592451f2750e780c3e8cbaddab674cff5242a2/python/fbprophet/plot.py#L383-L390

Does that make sense?

**Comment by bletham** [comment]
Though the fluctuations shown in the plot are probably not the real seasonality that is being applied to every month. Since there is only one data point per month, the model doesn't have any way of fitting a seasonality within the month. What you're seeing here is the same thing shown for the monthly data in the documentation here: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data

For a quarterly seasonality with monthly data, there are only 3 data points per cycle. You'd probably be better off modeling this with three binary extra regressors (month1, month2, month3) than with a Fourier-based seasonality.

**Comment by Mraghuvaran** [comment]
Can you add up the code if possible ?

**Comment by bletham** [comment]
https://github.com/facebook/prophet/issues/1168#issuecomment-542859810 has code for how to model yearly seasonality in monthly data with extra regressors; the change here would be that instead of 12 regressors (1 for each month of the yearly cycle) you'd have 3 regressors (1 for each month of the quarterly cycle).
