### ISSUE TITLE
Why Monthly Data with more trining time compared to Day Data

### ISSUE THREAD

**Issue by UlricWu** [facebook/prophet#1749]
Hello, all. Prophet is a great tool for time series forecasting. Thank you.

However, I came up with some issues, and hope you can help me out of there.

First, I have a dataset that contains the day-day data for two features, y_x and x_x. The thing is that I group by the month to get the month data, and used Prophet to do some forecasting, but I found the total training time on the monthly data is longer than the day -based data. Usually, the more data, the longer time. 3 years of daily data sums up to 1095 records and groups by up to 36 records. 

Secondly, in order to avoid the incorrect parameters, I used a grid search to monitor the total training time on different parameters. I found the same issue that on average,  the monthly data takes a longer time to be trained than the day-based data.

Thirdly, some parameters take extreme time to be trained, around 20 times the majority parameters on the monthly data. Not sure what happened, but it's quite interesting.

Additionally, during training, the log would show some information about the iteration, loglikelihood, and so on. I just wonder how to set the max number of iterations and the threshold at the beginning of calling the model.

The dataset that I used is being a little transformed for the sake of the Confidentiality Agreement, but still with the same facts. Here is the.  [source code](https://github.com/UlricWu/1080ti/tree/master/projects/time_series)

**Comment by bletham** [comment]
I think there will generally be two factors behind the training time: how long it takes to compute the likelihood function, and how many optimization iterations (i.e., likelihood evaluations) must be done. Computing the likelihood involves a sum over the data points, so will take longer for 1095 datapoints vs. 36. But I think the second factor (number of optimization iterations) will probably be longer for the monthly data because the model isn't very well-specified with that few data points. This makes the likelihood surface relatively flat, and so the optimizer has a hard time converging and takes a lot of steps. This is the same reason why the fitting time can depend on the hyperparamters - stronger regularization (smaller prior scales) will add more shape to the likelihood surface, which makes the optimization easier and it will terminate in fewer steps. The optimization is being done by PyStan, but if you use kwargs in `Prophet.fit`, they will be passed along to the pystan model optimizing. You can see the kwargs here: https://pystan.readthedocs.io/en/latest/_modules/pystan/model.html#StanModel.optimizing , like `iter` for a max number of optimization iterations.
