### ISSUE TITLE
Missing holidays for AE, HK, SG

### ISSUE THREAD

**Issue by foundinblank** [facebook/prophet#1751]
Hi, The output of `generated_holidays()` seems to be missing United Arab Emirates (AE), Hong Kong (HK), and Singapore (SG), even though all are [in the table](https://pypi.org/project/holidays/) on the `holidays` package website as well as having `.py` files in the repo.

**Comment by bletham** [comment]
Do you mean they are missing in the R package? This is probably because they were added to the holidays package after the holidays table was refreshed for the 0.6.1 release currently on CRAN.

AE, HK, and SG are all in the current R package csv (https://github.com/facebook/prophet/blob/master/R/data-raw/generated_holidays.csv) so if you update prophet you'll have them:
```R
devtools::install_github('facebook/prophet', subdir='R')
```

**Comment by foundinblank** [comment]
Super - thanks, @bletham!

**Comment by bletham** [comment]
This has now been pushed to CRAN.
