### ISSUE TITLE
How to make the model ignore covid for 2021 projections? 

### ISSUE THREAD

**Issue by soliverc** [facebook/prophet#1752]
I have daily sales projetions for 2021. as you can see in the chart below, it predicts a spike (#2)  similar to the one in 2020 (#1)

Spike #1 was the first covid lockdown. This is supermarket data so people were panic buying. 

![image](https://user-images.githubusercontent.com/47222261/101653221-023b8700-3a37-11eb-9895-4f9480646704.png)

It looks like the model predicts more panic buying next year. 

How can I tell it to ignore this anomaly? 

The lockdown dates were used in the model as holidays:

```python

lockdown1 = pd.DataFrame({
  'holiday': 'lockdown1',
  'ds': pd.date_range(start="2020-03-11",end="2020-05-18").to_list(),
})

m = Prophet(holidays=lockdown1)
```

However it seems to want to predict another spike in 2021. Close enough to these dates. 

Can I stop it from doing this?

**Comment by GinoWoz1** [comment]
Have you tried without the lockdown dates as a holiday?  Regressors will be added to the data and therefore the impact will be modelled even more significantly if you did not set them as holidays. You can also create a _prior_scale_ column on the holidays df and set the prior scale near to zero which will have a lasso effect on the regressor ( nullifying it). #1714 

From the paper[ here](https://peerj.com/preprints/3190.pdf): 

> Smoothing parameters: By adjusting τ an analyst can select from within a range
of more global or locally smooth models. The seasonality and holiday smoothing
parameters (σ, ν) allow the analyst to tell the model how much of the historical
seasonal variation is expected in the future.


I had a similar issue for 2021 and ended up predicting for March (where covid had the biggest impact) and used that as actuals to predict 2021. As a result the spike wasnt projected to the next year..

**Comment by soliverc** [comment]
> Have you tried without the lockdown dates as a holiday?

I just tried it. 2021 projections are even more crazy:

![image](https://user-images.githubusercontent.com/47222261/101752994-0b296880-3aca-11eb-94b1-58b7b23af086.png)

This one is with lockdown as holidays, and `prior_scale` set to `0.5`. ( default is 10):

![image](https://user-images.githubusercontent.com/47222261/101753650-cce07900-3aca-11eb-8b34-653ac4d688ea.png)

**Comment by bletham** [comment]
Sorry for the slow reply!

The reason it didn't work when adding the lockdown date as a holiday is because you added the entire set of lockdown dates as the dates for the holiday. Basically what this is doing is applying a single "lockdown1" holiday effect to every day in the range. Since the spike is only on the early days and then things are mostly normal after that, the fitted holiday effect is going to be the average effect across all of these dates that have been labeled as the holiday, and so it will fit a small holiday effect because there is no effect on most of the dates.

What you want to do instead is use the `upper_window` field to specify that the holiday effect spans multiple days:
```Python
lockdown1 = pd.DataFrame({
  'holiday': 'lockdown1',
  'ds': pd.to_datetime(["2020-03-11"]),
  'upper_window': 68,
})
```
The difference is a bit subtle, but what you did says that there is a holiday `lockdown1` that has an effect on 1 day, and there are 69 instances of that holiday (every day between 3/11 and 5/18). The formulation above says that there is a single instance of the holiday (on 3/11), but it has an effect that spans an additional 68 days. Under the hood, each of those 68 days will be treated as having an independent effect size; so the effect on 3/11 will no longer be assumed equal to and averaged across the rest of the window. Since the effect is really limited just to the start of the lockdown you could probably get away with using a smaller upper_window which will save you some model complexity.

This will then be able to fit the spike as a holiday effect instead of grabbing it with the yearly seasonality, and so it will not be propagated into 2021. You might need to reduce the yearly seasonality prior scale a bit but I think it will work either way.

**Comment by soliverc** [comment]
Thank you! That makes sense. I will give it a go. I've been pulling my hair out over these lockdown effects.

**Comment by bletham** [comment]
Just want to also link to #1416 which has a lot of handling-COVID discussion.
