### ISSUE TITLE
How do I add extra_regressors to my model?

### ISSUE THREAD

**Issue by ccfsbmb** [facebook/prophet#1777]
I'm trying to use Facebook prophet for multivariate time series forecasting. It says that I need to have regressors for the future dataframe since I used them to fit my model. I found this function:

>>>from fbprophet.utilities import regressor_coefficients

>>>regressor_df = regressor_coefficients(m)

I'm assuming that I can use it to make my future predictions but I'm not sure how to do it. Could someone please show me example code of how to fit the model and make future predictions using the regressor coefficient as I can't find any example that I can follow.

Thanks very much in advance.

**Comment by benmwhite** [comment]
https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

**Comment by ccfsbmb** [comment]
> https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors

Hi, thanks for your reply. I've already read through the documentation but didn't find it helpful.

**Comment by benmwhite** [comment]
The docs have a link to [a notebook](https://nbviewer.jupyter.org/github/nicolasfauchereau/Auckland_Cycling/blob/master/notebooks/Auckland_cycling_and_weather.ipynb) with python examples of forecasts with extra regressors in the later sections. You'll have to supply predicted values of the regressors for the future timestamps if you're not analyzing historical data though.

**Comment by ccfsbmb** [comment]
> The docs have a link to [a notebook](https://nbviewer.jupyter.org/github/nicolasfauchereau/Auckland_Cycling/blob/master/notebooks/Auckland_cycling_and_weather.ipynb) with python examples of forecasts with extra regressors in the later sections. You'll have to supply predicted values of the regressors for the future timestamps if you're not analyzing historical data though.

Thank you. Do I supply the predicted values for the future time stamps while using the actual past values to train the model?

**Comment by bletham** [comment]
@ccfsbmb the `regressor_coefficients` is just a tool for extracting the fitted coefficient for each regressor, for the purposes of understanding the impact of each regressor in the model. It is not used for making predictions.

The model isn't able to determine what the future values of the regressors are. Suppose you are forcasting `y` with regressor `x`. The model knows how to predict `y` given time `t` and `x`. The model does not know how to predict `x`. You have to supply future values for `x` and can produce them in whatever way you think is reasonable (what is reasonable will depend on what `x` is).

**Comment by ccfsbmb** [comment]
> @ccfsbmb the `regressor_coefficients` is just a tool for extracting the fitted coefficient for each regressor, for the purposes of understanding the impact of each regressor in the model. It is not used for making predictions.
> 
> 
> 
> The model isn't able to determine what the future values of the regressors are. Suppose you are forcasting `y` with regressor `x`. The model knows how to predict `y` given time `t` and `x`. The model does not know how to predict `x`. You have to supply future values for `x` and can produce them in whatever way you think is reasonable (what is reasonable will depend on what `x` is).

This was incredibly useful, thank you! I'm assuming I can use the model to predict future values for each variable individually and then use them as extra regressors to make better predictions of each variable in turn? But that seems like a lot of work, perhaps I should be looking at using something other than fbprophet

**Comment by bletham** [comment]
Yes, you could use a separate prophet model to first make a forecast for `x` as a function of `t`, and then plug that in to a forecast of `y` as a function of `x` and `t`. But now there is error in the forecast of `x` that will effectively be baked into the forecast of `y`. I think the only time this really makes sense is if for some reason `x` is a lot easier to forecast than `y` alone, so that the forecast of `x(t)` will have lower error than that of `y(t)`. One setting where this can happen and does make sense is forecasting subgroups of a total: the top-line total might have stronger signal and be easier to forecast than the subgroups, so you could first forecast the top-line total and then include it as a regressor when forecasting each subgroup (see discussion of this strategy here: https://github.com/facebook/prophet/issues/49#issuecomment-430383681). Another setting where extra regressors can make a lot of sense is when they are things like weather, that have external forecasts that are better than what you would get from Prophet (almanacs for long-term forecasts, weather models for the short term). But if it's just a few general time series that are equally difficult to forecast, there isn't much to do in Prophet as far as multivariate forecasting (see more discussion in #49).
