### ISSUE TITLE
Which hyper-params control memory?

### ISSUE THREAD

**Issue by microprediction** [facebook/prophet#1800]
Hello, 

   In the univariate example below (where the freq is 20min) the predictions are plausible in a panned-out sense. However is there an obvious hyper-param that can be tuned to encourage more attention to the recent data points, especially if the intent is predicting the next value, or the next two or three say? 

Peter

<img width="756" alt="fbprophet_loose" src="https://user-images.githubusercontent.com/57455669/106021526-e47fbb00-6092-11eb-94b5-5c02876b6daa.png">

**Comment by benmwhite** [comment]
What are you using for your changepoints? By default the model stops estimating trend changes in the last 20% of your timestamps, but you can specify them manually over this period. You can also increase the changepoint prior scale so that the model fits the trend component to the training data a bit more aggressively.

However if you know your time series has high dependency on recent timestamps then you might have to look into something like state space models that treat timepoint-to-timepoint transitions explicitly.

**Comment by microprediction** [comment]
Thanks, I'll try a few things. And certainly, the combo with SSM seems reasonable.

**Comment by Shafi2016** [comment]
Hello benmwhite, Can we add the two or three, different change points?. Say one change point is from 1981-1982, then second is 2007-2008 and then third is from  2010-2011.

**Comment by benmwhite** [comment]
@Shafi2016 The changepoints are discrete timestamps, not ranges. But you can specify any vector of timestamps you want as the trend changepoints.

**Comment by Shafi2016** [comment]
Thanks for the clarification.!!

**Comment by bletham** [comment]
Yeah, I think increasing the `changepoint_prior_scale` will enable it to fit these fluctuations, and then as @benmwhite said to give it more flexibility especially for the final datapoints you'll want to increase the `changepoint_range` from its default of 0.8 probably to something like 0.95.

**Comment by Shafi2016** [comment]
Thanks a lot @bletham
