### ISSUE TITLE
Are lags of the target variable a valid regressor?

### ISSUE THREAD

**Issue by ianchute** [facebook/prophet#1802]
Say I'm trying to build a model on `df["y"]`, where df is indexed by dates.
Is it valid for me to add the t-1 lag as a regressor (i.e. `.add_regressor(df["y"].shift(1).fillna(0))`)?
In doing this am I doing any theoretical mistakes or data leakage w.r.t. to the proper usage of the Prophet model?

I am aware that this creates an `AR(1) model` but, again, is it valid for me to do this in conjuction with the trend/growth, season and holiday components of Prophet?

Many thanks in advance!

**Comment by bletham** [comment]
I can't think of any issue with this from a theoretical validity perspective. From a practical perspective, there's a challenge that you need to be able to know the future values of the regressors in order to forecast `y`, and a lag of 1 would only allow you to make a prediction 1 step ahead before you'd have to start imputing y's, and then your forecast would probably be no better than the imputation technique. But if a 1-step forecast is all that is needed, then I don't see any issue here and I'd be interested to hear how it goes :-)

**Comment by ianchute** [comment]
We tweaked our model more and found out that we don't actually need the lag regressor! And, yeah, we did find the dependency on t-1 (or t-n in general) quite a hassle. So, yeah, all good. Thanks!

**Comment by bletham** [comment]
I just wanted to also point to this project that is a pytorch implementation of the Prophet model that has some additional features, including built-in autoregressors: https://github.com/ourownstory/neural_prophet
