### ISSUE TITLE
Prophet not working as expected. 

### ISSUE THREAD

**Issue by uallu** [facebook/prophet#1808]
Hello, 
I am working with fbprophet and the issue is, it keeps running and does not come to a halt. Stan model stop generating logs. 
How I am implementing it? I group the data based on a unique ID and then for each ID I fit the prophet with LBFGS algorithm and  collect the results. 
I did try restricting the iteration to 1000 and 500, yet I am the seeing the same issue. 
Dataset is huge and I am running it on an instance with 40 CPU and 488GB Memory.  
 Also, It did work when I reduced my dataset. (started few more runs with little more load, yet to see results) 
Thank You! 
Note: I am not an expert in data science. Looking for help to solve this issue.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/64159722/107066607-cce7b700-67a3-11eb-85e7-7cc68f6a46b1.png">

**Comment by bletham** [comment]
I think the message "n_changepoints greater than number of observations. Using 9." might be a valuable hint. It looks like this dataset is very small (10 or so data points). It looks like it is trying to fit yearly seasonality, so these 10 datapoints must span more than a year. The model with yearly seasonality will have many more parameters than the 10 datapoints, so the model is really badly underspecified. I have seen issues in the past where the L-BFGS optimizer gets stuck in situations like this where there are many more model parameters to fit than there are datapoints to constrain them.

Can you verify if yearly seasonality is being fit? If so, then disabling yearly seasonality will greatly simplify the model parameterization, and I'd expect the fit to succeed. You will not lose anything in terms of forecast ability by disabling yearly seasonality, because with only 10 datapoints you won't be able to fit it anyway.

**Comment by uallu** [comment]
Yeah, yearly seasonality is set to 'true' as of now. I will make the changes for it. 
Thank You so much Ben for your help on this. :)
 Will let you know how this goes.

**Comment by uallu** [comment]
There were cases where the n_changepoints is greater than 9 or any value. But it passed for them. 
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/64159722/107112718-48d31500-681f-11eb-9139-32dbfa5eed6d.png">
Also, yearly seasonality is set to 'true' as of now. (I am looking for cases where to turn it on/off)

**Comment by bletham** [comment]
Yeah, it's a matter of numerical instability when the model is underspecified, so sometimes it will work othertimes it will not. As a starting point, I'd definitely recommend turning yearly seasonality off for any time series with less than a year of data which is the default behavior; it will not fill correctly anyway with less than a full year. If you do have more than a year of data but less than a datapoint per month you will likely still want to heavily regularize the seasonality by cranking the `seasonality_prior_scale` down from its default of 10 to something more like 1 or 0.1, because you're not going to be able to fit much yearly seasonality with less than a datapoint per month.
