### ISSUE TITLE
Unexpected negative values on additional regressor 

### ISSUE THREAD

**Issue by trajgaria47** [facebook/prophet#1809]
Hello, 
I have a sales dataset for the US that benefits from holiday effects in Q4. To this extent I tried to capture/control for the quarterly effects by introducing monthly bins. However, the effect is coming off opposite of what is expected — Q4 is showing highly negative effects. Is this because I inputed Q4 holidays in the holiday event parameter? 
<img width="589" alt="Screen Shot 2021-02-08 at 12 01 06 PM" src="https://user-images.githubusercontent.com/40258007/107254501-5e099880-6a05-11eb-90e6-0e97aa07aeba.png">
<img width="586" alt="Screen Shot 2021-02-08 at 12 00 55 PM" src="https://user-images.githubusercontent.com/40258007/107254517-62ce4c80-6a05-11eb-81f5-15df9375ba82.png">
<img width="562" alt="Screen Shot 2021-02-08 at 12 00 07 PM" src="https://user-images.githubusercontent.com/40258007/107254530-6530a680-6a05-11eb-81e4-7a9409fce7c8.png">
<img width="562" alt="Screen Shot 2021-02-08 at 11 59 53 AM" src="https://user-images.githubusercontent.com/40258007/107254565-6c57b480-6a05-11eb-922c-765e6b661e2f.png">

**Comment by bletham** [comment]
Yeah it's hard to say what exactly might be happening because there is some confounding between the various seasonal factors; both between the quarterly effect and holiday effects as you note, but also with the yearly seasonality. The model could be adding a little extra yearly seasonality to Q4 and then using the Quarters regressor to back some of it off.

There are a couple things you can do to figure out what's happening. The first is to fit the model without the Quarters regressor and see what happens to (1) model cross validation performance (is Quarters improving model prediction performance?) and (2) yearly seasonality (in the absence of the Quarters regressor, is yearly seasonality capturing Q4 differently?).

To try to get the model to be a bit more parsimonious you could also try reducing the priors for both the yearly seasonality (`seasonality_prior_scale`) and for the Quarters regressor (by passing in a `prior_scale` to `add_regressor`). The defaults are 10, which applies basically no regularization. Cutting that down to 1 or even lower you should start to see some regularization in the estimates, and maybe with some regularization on the yearly seasonality in particular it might prefer to fit the Q4 increase with the Q4 regressor rather than with yearly seasonality.
