### ISSUE TITLE
What does the spike in mape score mean in the cross validation plot from prophet? Does it show signs of overfitting? 

### ISSUE THREAD

**Issue by hubtocode** [facebook/prophet#1810]
Hi,

I am predicting sales for a 90 day horizon. And here are my model's parameters.
```
model = Prophet(
  interval_width=0.95,
  growth='linear',
  seasonality_prior_scale = 0.2,
  changepoint_prior_scale = 0.5,
  changepoint_range = 0.5,
  daily_seasonality=False,
  weekly_seasonality=False,
  yearly_seasonality=True,
  seasonality_mode='additive'
  )
```

To check the performance I am using the below values for cross validation
`df_cv = cross_validation(model, initial='790 days', period='30 days', horizon = '90 [days')]
`
For reference, please look at plots below -
Plotting mape with plot_cross_validation_metric and performance_metrics table
(https://imgur.com/a/NPFvVyb)

How do I ensure better coverage and get a more consistent mape score? And how do I investigate the reason for spikes in graph?

**Comment by bletham** [comment]
It looks like you have monthly data. The CV can give weird results (like what you see here) with monthly data because a month isn't a fixed amount of time. What you'll probably want to do is to manually specify the set of cutoff dates so that they occur exactly at your monthly data points, as described here: https://github.com/facebook/prophet/issues/1672#issuecomment-692930583 
(Except you should probably use 93 as the horizon instead of the 90 that I have in the code there to be sure that you always get 3 test months).
I think that should produce better estimates, but please post if it doesn't!

**Comment by hubtocode** [comment]
Thank you @bletham !
I added a monthly seasonality param and set the cutoff dates manually to get better results like you suggested. I am using 93 days as my horizon now and it is definitely gives a acceptable mape score.   Added my plots for reference.

(https://imgur.com/a/suSX8pN)
