### ISSUE TITLE
Tags, releases

### ISSUE THREAD

**Issue by nicolaerosia** [facebook/prophet#1812]
The latest tag and release I see on GitHub is v0.6 however on pypi/conda there's also 0.7/0.7.1.
Is there a plan to add back tags/releases and changelog?

**Comment by bletham** [comment]
Yeah the last release (0.7) got messed up because we had windows build issues in R that caused the package to be rejected by CRAN. We intended to tag things after that was finished, but we had a really hard time fixing the windows issue and so it dragged on for a few months and still isn't on CRAN. We think the fix is in now, but at this point we might as well just push out another release so we're working on getting that in shape. So sorry for the mess in the tagging. We will update a changelog for 0.7 soon; at this point we probably won't worry about the tagging until 0.8.

**Comment by nicolaerosia** [comment]
@bletham thank you!

**Comment by bletham** [comment]
We just finished a new push and decided to call it 1.0, and now all of the tags/releases are updated.
