### ISSUE TITLE
Fitting Model With Missing Data From the Same Time Every Year

### ISSUE THREAD

**Issue by lleiou** [facebook/prophet#1818]
Hi there, thanks for creating this great tool!

I have one question about missing data: I have daily records for several years, but every year the January & February data is missing, now I need to predict what would January & February data be like but the prediction results gave me a weird trend, which I think is because Prophet cannot learn the seasonality for those two months when their data is always missing. I have tried adding exogenous variables but the problem is that it doesn't change the fact that January & February data is missing, so I don't see improvement of the model prediction. I've tried using [interpolate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html) from `pandas` to interpolate Jan & Feb data and then train the Prophet model, but not sure how reliable that is. 

I'm wondering if there is other options that I could try, thanks!

**Comment by bletham** [comment]
The issue here is that the yearly seasonality in Jan and Feb are completely unspecified by the data. Prophet uses Fourier series to model seasonality, which has many advantages but has as a downside that the seasonality tends to be badly overfit whenever you have a consistent period of missing data (the weird trend you describe). There is description of this in the documentation under the section "Data with regular gaps": https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps

I think if you look at the yearly seasonality in the components plot (`m.plot_forecast_components(fcst)`) then you will probably see that it's doing something really funky in Jan and Feb.

The documentation suggests that the solution is to just not make predictions for the periods in which you don't have training data. That is the right thing to do when e.g. a store is only open on weekdays and so doesn't have data for weekends. But here in your case you do not have data from Jan or Feb but need to make a prediction for Jan and Feb. So what to do about it.

Given that you have daily data, I would not recommend interpolating. That would be fine for getting the yearly seasonality to fit something flat for Jan and Feb (a reasonable prior), but would also destroy any weekly seasonality in those months, which would harm the weekly seasonality in other months too.

In the situation you have described, I expect that the only thing wrong with model (that is, preventing the model from making reasonable forecasts for Jan and Feb) is the overfit yearly seasonality. So what I would do is try to just interpolate the yearly seasonality for Jan and Feb and leave the rest of the model as-is.

* Fit the model as usual with the missing data. The trend and weekly seasonality should all be well fit. The yearly seasonality will be good other than in Jan and Feb.
* Make a forecast on the dates you want to predict. Let's say the output dataframe is called `fcst`. If all of the dates are outside Jan and Feb, you're done, but otherwise we want to adjust `fcst` to remove the effect of the bad seasonality fit.
* Copy out the original (bad) yearly seasonality column: `yearly_old = fcst['yearly'].copy()`
* Remove the values `fcst['yearly']` column for any dates in Jan and Feb. Use `pd.interpolate` to fill in interpolated values for Jan and Feb (so, you're interpolating between Dec and Mar). Do the same for `yearly_upper` and `yearly_lower` columns
* Compute the difference between the old seasonality and the fixed (interpolated) seasonality: `seas_diff = fcst['yearly'] - yearly_old`
* Adjust the forecast `yhat` to remove the bad seasonality: update `fcst['yhat'] = fcst['yhat'] + seas_diff`. Do the same for columns `yhat_lower` and `yhat_upper`.

If you look at the components plot before and after this operation, then you should see that afterwards the seasonality in Jan and Feb will just be a straight line through those two months. And in the forecast plot (`m.plot(fcst)`) you should see the irregularity removed in those months (but features like weekly seasonality will still be present).

That's a little involved but hopefully not too, if you have a chance to try it out I'd be interested to hear how it goes, and to see components plots if you're able to post them.
