### ISSUE TITLE
Cross validation for non-daily data

### ISSUE THREAD

**Issue by domke159** [facebook/prophet#1829]
I am having trouble with understanding facebook's prophet's cross validation. I have an ARIMA model that splits the data into training and test sets and performs a rolling forecast by using the train set to fit the model, and generate a prediction for each element on the test set.
`
def ARIMA_forecast(series):

    X = series.values
    size = int(len(X) * 0.8)
    train, test = X[0:size], X[size:len(X)]
    history = [x for x in train]
    predictions = list()
    for t in range(len(test)):
        model = ARIMA(history, order=(3, 1, 3))
        model_fit = model.fit(disp=0)
        output = model_fit.forecast()
        yhat = output[0]
        predictions.append(yhat)
        obs = test[t]
        history.append(obs)
        print('predicted=%f, expected=%f' % (yhat, obs))
    plt.plot(series, label='Training data')
    plt.plot(series[size:len(X)].index, test, color='blue', label='Actual Price')
    plt.plot(series[size:len(X)].index, predictions, color='red', label='Predicted Price')
    plt.legend()
    plt.show()`

I would like to achieve a similar thing with prophet with my data but I'm struggling to understand the cross validation function of Prophet. Currently I have this function:
`
def prophet_forecast(data):

    data['Date'] = to_datetime(data['Date'])
    data = data.rename(columns={"Date": "ds", "Adj Close": "y"})
    m = Prophet()
    size = int(len(data) * 0.8)
    train = data.loc[0:size]
    m.fit(train)
    df_cv = cross_validation(m, initial=size, period=1, horizon=int(len(data)) - size)
`

The example provided in prophet's documentation uses daily data, however in my dataset the observations vary and are time-inconsistent. My goal is to make a forecast similar to the one in ARIMA model. I would like to split the data into train and test sets, fit the model with the train set and make the forecasts for the rest of the data set (last 20%) and compare them with the test set. In my example, if I understand correctly, I set initial to size, as that is how much train data I want, horizon is set to the size of the test set, and finally I set period to 1 as I want to make a rolling forecast by generating a prediction for each element on the test set. However, it seems to be incorrect and I just can't figure out how to set cross_validaion parameters when the data is non-daily.

My data set is 1 year of Facebook stock prices:
https://finance.yahoo.com/quote/FB/history?p=FB

How can I achieve my goal? Has anyone done anything similar and could share their code? Am I completely misunderstanding the cross_validation function?

Any help is appreciated.

**Comment by bletham** [comment]
I think there are two things going on here.

First for non-daily data: The built-in cross validation can handle non-daily data no problem. The example in the documentation is with daily data since it is so common, but there's no assumption of regularity in the data. The regularity specified by `period` is just a regularity of creating cutoffs, and there's no requirement to have an even spread of data between cutoffs.

The bigger question seems to be about how the built-in CV works relative to what you're trying to do. The CV tool will make predictions from many train/test pairs. Each train/test pair is referred to as a "cutoff", which is the date that splits the train and test sets. For each train/test set, the model will predict out `horizon` time, and will then compare those predictions to whatever test data fell within that window. So if I have 2 years of data and set `initial` to 1 year and horizon to 1 week, then it will fit a model to 1 year of data, and then make a prediction for the following 1 week, and the output (`df_cv`) will have a comparison between the predicted values and the true values for any test points within that 1 week. Note that the test points do not have to be regularly spaced: they can be anywhere within the 1 week horizon window, and they will be predicted for. That's the first cutoff. Then, we advance the cutoff by the amount `period` and repeat. So if my period is 1 month, my second cutoff will be at 13 months (the initial plus 1 month). I'll fit a new model with 13 months of data, make a prediction for 1 week, and will record the predictions for any test points that fell within that window. This will repeat until the cutoff reaches the end of the dataset, and so the test set no longer has >1 week in it.

Relative to your ARIMA code: no frequency for the data is assumed. The fixed frequency is in the specification of cutoffs. It sounds like you want to have something that does "fit a model to T data and predict T+1. Then fit a model to T+1 data and predict T+2. Etc. If you have daily data, then you would get that with initial=T, horizon = 1, period = 1.

There's some more discussion of the CV and performance metrics in particular in https://github.com/facebook/prophet/issues/1773#issuecomment-756276615 that might be useful (there is room for improvement in the documentation around this).

**Comment by domke159** [comment]
> referred

I'd like to believe that I understand how it works a lot better now. However, I am still unsure how to achieve my goal with non-daily data. If I have data from 1 year where observations vary and are not daily, and I would like to use 80% of my data as a train set how could I do this? Because 80% of 365 is 292 days, I have tried doing this:
`df_cv = cross_validation(m, initial='292 days', period='1 days', horizon='1 days')`

However, I get ValueError: Less data than horizon after initial window. Make horizon or initial shorter.

**Comment by bletham** [comment]
Can check what the length of your entire time series is in days? (That is, latest date minus earliest date). Based on the error, it sounds like it's less than 293 days. If the difference in date between the first and last points is a full year, is there any chance you can post code/data to produce what you're seeing? There's a bit of ambiguity here because if the data are irregularly spaced, 80% of the data does not necessarily mean 80% of the year, e.g. if almost all of the data are in the first month.

**Comment by domke159** [comment]
I have provided an excel file as github won't allow to pload a csv. I guess you could say that this data is almost daily, except for weekends. However, I am not sure how to go about that.
[AAPL.xlsx](https://github.com/facebook/prophet/files/6072055/AAPL.xlsx)

**Comment by bletham** [comment]
OK thanks for the code, I see what's happening now.

The built-in `cross_validation` makes train/test splits for you, so you don't have to subset the training data yourself. You give the model the full dataset, and then it handles the splitting.

In this code you are giving Prophet the `train` dataframe, which ranges from 2020-02-07 to 2020-11-23. `cross_validation` will then create train/test splits from that data (that is the only data it has to use). The length of `train` is 290 days, so obviously it won't be able to create the first split to have an initial length of 292 days.

This code works:
```Python
df_cv = cross_validation(m, initial='282 days', period='1 days', horizon='1 days')
```
And it will print this message:
```
INFO:fbprophet:Making 6 forecasts with cutoffs between 2020-11-15 00:00:00 and 2020-11-22 00:00:00
```
so you can see that it has created 6 train/test splits beginning at 2020-11-15 and going up to 2020-11-22 (the day before the last date in the dataset).

The result is, for each cutoff, the forecast for the following day:
```
>>> df_cv
          ds        yhat  yhat_lower  yhat_upper           y     cutoff
0 2020-11-16  112.770132  107.250633  118.013675  120.120506 2020-11-15
1 2020-11-17  113.675078  108.776666  118.844600  119.211861 2020-11-16
2 2020-11-18  115.252808  110.257142  120.601516  117.853889 2020-11-17
3 2020-11-19  115.540607  110.415282  120.460577  118.462982 2020-11-18
4 2020-11-20  115.271163  110.402109  120.006406  117.164917 2020-11-19
5 2020-11-23  113.812123  109.101002  118.698427  113.680122 2020-11-22
```

So for your code with initial=292 to work you just need to pass in the entire dataframe to m.fit(), train/test splitting happens inside cross_validation.

**Comment by domke159** [comment]
@bletham Thank you so much for the help. So with cross validation you always need to fit the whole dataset, right?

**Comment by bletham** [comment]
Yep! And then it will make the train/test splits from that.

**Comment by domke159** [comment]
Thanks again for the help!
