### ISSUE TITLE
How to deal with hourly seasonality

### ISSUE THREAD

**Issue by clonyjr** [facebook/prophet#1836]
Hi Prophet team and community, great work with this tool, congrats to everyone!!

I am not sure if I can open an Issue as it really is a question, so please hope you forgive-me and I am sorry, in advance.

I am learning TS and using Prophet for my Master dissertation  that's why I am having a lot of doubts here and may not understanding it.

I am trying do predict values in near future (28 days ahead) for every 30 minutes within a time window of 12 hours per day. It's a dataset of few months (3). It is the number of clients per half-hour. Here is the hourly component after forecasting:

![hourly_prophet_seasonality_30m_freqs](https://user-images.githubusercontent.com/4035839/110106205-4b367980-7da1-11eb-915b-8de525480a88.png)

I really don't understand the subdaily plot. What means the xlabels? I am assuming it is parts of the 12 hours, which would means that at part 1/1  hour 00:00 there were some quantity (maybe 0.5), at part 01/07 hour 20:34 there were 1, and so on until part 01/13. The thing is, if this interpretation is correct then it predicts 03:25 am which does not belong the interval, since the worktime is from 08:30 to 20:30. The future dataframe is correct (withou the off period - 21:00 until 08:00). Again I am assuming that, when ploting subdaily, Prophets ignores this time limitation and predicts for 24 hours and the one which is analyzing the plot must known that and ignore the time intervals that doesn't belong to the time window setted. Am I correct?

Below are the other components and Prophet parameters:

![Captura de Tela 2021-03-05 às 11 03 03](https://user-images.githubusercontent.com/4035839/110107308-a1f08300-7da2-11eb-9159-2d4a08ef49d7.png)

![Captura de Tela 2021-03-05 às 11 04 34](https://user-images.githubusercontent.com/4035839/110107332-a6b53700-7da2-11eb-8fb3-e3dcb5b7f1d3.png)

I'd appreciate some help to understand and correctly interpret the seasonality components. Thanks in advance.

**Comment by bletham** [comment]
Sorry for the slow reply here. There are a couple issues here that should give you a much better result once they're fixed.

The main issue is on the definition of `period` when adding a seasonality. This has come up a few times and so it seems that it needs to be clarified in the documentation. The `period` in hourly seasonality is always in units of "day". A "daily" seasonality means a seasonal pattern that repeats itself every day. This is what you are interested in modeling, and has a period of 1 (it repeats itself every 1 day).

"hourly" seasonality would mean a seasonal pattern that repeats itself every 1 hour. If you had hourly seasonality, then the correct period would be 1/24 (since that is the length of an hour in units of days).

What you have added (period=12) is a seasonal pattern with a length of 12 days. That is why you see the x-axis in the component plot is of length 12 days.

It looks like what you want to do is just don't add the "hourly" component, because what you want (a seasonal cycle with a period of 1 day) is exactly what is being captured by the "daily" component.

Besides that, there is just one other thing you need to fix and that is that because your training data only has data for 12 hours of the day, the daily seasonality for the other 12 hours of the data will not be identifiable and so ends up with a wonky fit. Read the documentation about this here: https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps . You can see this in the "daily" row of the components plot: there are large fluctations outside of the 12 hours for which you have data. The documentation link explains what to do in this setting: basically you just need to filter your `future_clientes` dataframe to only have points within the 12-hour window each day for which you have data. The documentation link shows how to do it.

With these two things (remove "hourly" seasonality, filter `future` to hours that have data) I expect you'll see good forecasts for this time series.

**Comment by clonyjr** [comment]
Hi, hey no problem at all, I can imagine that you guys are really busy and I really appreciate a lot for your attention.

As I need to predict for every half-hour, then the seasonality period must be 1/48 (right?). About the data with regular gaps It was my mistake, I am sorry about that.

Again thank very much e keep safe everyone!

**Comment by bletham** [comment]
I think there's a mixup here between seasonality and the prediction frequency. A seasonlity with a period of 1/48 would mean a seasonal cycle that repeats itself every 30 minutes (just like yearly seasonality is a seasonal cycle that repeats itself every year). You don't have that type of seasonality in your data; you have yearly, weekly, and daily seasonality.

Prophet is a continuous-time model, meaning the data frequency (here every half hour) doesn't matter. Anything you specify to the model will be in units of calendar time.

When making predictions, you can make predictions at whatever frequency you want. This doesn't have any connection to the seasonality, which is part of fitting the model. In your code you pass the predict frequency to `make_future_dataframe`, and there you are doing the right thing by passing in the frequency as every 30 mins. I guess the confusion is probably coming from the use of the word "period" to refer to the length of the cycle of seasonality, and the use of the word "periods" in `make_future_dataframe` which is referring to how many of whatever freq you specify should be predicted. There isn't any relationship between the `period` of each seasonality and the number of periods that you forecast for.

**Comment by clonyjr** [comment]
aaahhh  I get it now! It makes sense. Dealing with time requires a closer attention, at least for me. Thanks again!! 👍
