### ISSUE TITLE
Cannot pip install prophet in a new clean conda environment

### ISSUE THREAD

**Issue by matbmeijer** [facebook/prophet#1968]
Hi,

I have the following problem when trying to install prophet in a clean new conda environment.

The commands used are the following:
```
conda create --name yourenvironment python=3.8
activate yourenvironment
pip install prophet
```

I get the following errors, which seems to be related to pystan
```
ImportError: DLL load failed while importing _api: The specified module could not be found.
```

I have also tried to pip install first pystan following the suggested version, yet had no luck.
```
pip install pystan~=2.19.1.1
```

I have the following conda version:
```
conda 4.10.3
```

I am running the following specifications:
```
Microsoft Windows 10 Enterprise
x64 based PC
Intel64 Family 6 Model 142 Stepping 9 GenuineIntel ~2511 Mhz
16 GB RAM
```

I have attached an image of the resulting error:
![image](https://user-images.githubusercontent.com/16921170/125792513-a0fcbab8-3b6b-441f-9c51-95d150613587.png)

**The installation works with conda with the following command (` conda install -c conda-forge prophet `), yet should also work with pip**

**Comment by CarlosGuemS** [comment]
It seems that the C++ compiler for pystan is not correctly set up. Try to follow [these steps](https://pystan2.readthedocs.io/en/latest/windows.html) and first install pystan  (remember to install version 2.19.1.1!), then proceed by continuing installing prophet.

Also, some plotly can only be installed in python 3.6 or earlier. It is not a mandatory package, but necessary for interactive plots. If using python 3.8 doesn't work, try using 3.6 instead.

**Comment by ckaldemeyer** [comment]
I also had several issues installing `prophet` on my Windows 10 machine using `conda` and `Python 3.7`.

The following steps made it work:

1. Create a fresh `conda` environment
2. Install `pystan` and other dependencies using `conda install numpy cython matplotlib scipy pandas -c conda-forge` (see https://pystan2.readthedocs.io/en/latest/windows.html#steps)
3. Install `prophet` using `conda install prophet -c conda-forge`

In then still had a numpy error `Importing the numpy c-extensions failed...` as described here: https://numpy.org/devdocs/user/troubleshooting-importerror.html But this was due to my IDE which is VS Code as I could successfully run my `prohet` model using the command line with the activated `conda` environment.

So please also make sure to test the installation from the command line in order to rule out that the error stems from you IDE.

**Comment by WardBrian** [comment]
Closing due to PyStan no longer being a dependency of `prophet`
