### ISSUE TITLE
Help add "Prophet" as a package for pyodide

### ISSUE THREAD

**Issue by cosmosanalytics** [facebook/prophet#2246]
I asked Pyodide to add "prophet" as a package, the following are the responses from pyodide:

"It would likely need some work as there are a number of unpackaged dependencies mainly cmdstanpy and cmdstan (cf https://github.com/conda-forge/prophet-feedstock/blob/main/recipe/meta.yaml#L25)"

"you'll need to work with the authors of those packages to get them distributed as wheels."

Can you please get prophet "distributed as wheels"?

**Comment by tcuongd** [comment]
@WardBrian I'm guessing this can be achieved if we set `PROPHET_REPACKAGE_CMDSTAN=True` on L15 of the recipe? This might be a good default if we want conda prophet to work seamlessly with other packages (correct me if I'm wrong though). 
End users should still be able to override this if they want to use the same cmdstan version installed in their conda env.

**Comment by WardBrian** [comment]
wheels are separate from conda, so I’m not sure I follow. Cmdstan and CmdStanPy are both available as conda packages. That is why cmdstan is not repackaged in the conda build, since we just use a genuine/full cmdstan installation 

Cmdstanpy is available as a wheel, but CmdStan can’t really ever be unless things like gcc or clang are also wheels. 

Prophet 1.1 and up should be available as both wheels and conda packages. I think we’d need some more specifics of what is expected beyond that
