### ISSUE TITLE
Why was wheel added as a requirement for prophet >=1.1?

### ISSUE THREAD

**Issue by DManowitz** [facebook/prophet#2311]
I am wondering why wheel >=0.37.0 was added as a requirement for prophet >=1.1.  In particular, I am concerned because I have an environment in which another package has pinned wheel <0.36, so I am not able to upgrade prophet there.  If there is a way to allow for a lower version of wheel or to remove it as a requirement, it would be appreciated.

**Comment by Nil-Andreu** [comment]
The requirement for wheel >=0.37.0 to be installed in order to use prophet >=1.1 is likely because that version of wheel or later is needed to properly build and install the prophet package. 
For example, it is the version of 0.37.0 that added the support to Python 3.10, which could be the cause of this.

**Comment by Nil-Andreu** [comment]
> I am wondering why wheel >=0.37.0 was added as a requirement for prophet >=1.1. In particular, I am concerned because I have an environment in which another package has pinned wheel <0.36, so I am not able to upgrade prophet there. If there is a way to allow for a lower version of wheel or to remove it as a requirement, it would be appreciated.

The requirement for wheel >=0.37.0 to be installed in order to use prophet >=1.1 is likely because that version of wheel or later is needed to properly build and install the prophet package.
For example, it is the version of 0.37.0 that added the support to Python 3.10, which could be the cause of this.

**Comment by tcuongd** [comment]
Thanks, fixed this in 1.1.2 by separating out the dev dependencies.
