### ISSUE TITLE
unreasonable negatives predict value

### ISSUE THREAD

**Issue by LoremipsumSharp** [facebook/prophet#2484]
I am using prophet to make a forecasting for 24 hours in the future by the sample with interval in 1 minutes in the past 3 weeks, however, the result is undesirable, some weird negative value was predicted
```Python
df = pd.read_csv(forecast_resource_uri)
model = Prophet(daily_seasonality=True,interval_width=0.95)
model.fit(df)
future = model.make_future_dataframe(periods=24*60, freq='1min',include_history=False)
forecast = model.predict(future)
```
the data set is here:
 [data_set](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/img/ds20230823.csv)
the image show the forecast result is here:
![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/img/fig1.png)

for all past data for forecast was positive, it was unreasonable to get such result, what I have missed.

**Comment by bixiadaren** [comment]
I think there are two directions to think about.
1. If you don't want to see the negative result. Maybe you should consider [Non-Gaussian likelihoods #1500](https://github.com/facebook/prophet/issues/1500).

2. If you can accept negative values and just find them outrageous. Then you can change the value of parameters.

Because the raw data does not appear to have a clear trend, we can remove it:
```python
df = pd.read_csv(forecast_resource_uri)
model = Prophet(growth='flat',daily_seasonality=True)
model.fit(df)
future = model.make_future_dataframe(periods=24*60, freq='1min',include_history=True)
forecast = model.predict(future)
model.plot(forecast);
model.plot_components(forecast);
```
![image](https://github.com/facebook/prophet/assets/12690815/c0b4c3dc-9aad-4304-ac6c-87d76e34887b)
![image](https://github.com/facebook/prophet/assets/12690815/adaea1c1-4097-4221-9f69-3946eb7e6385)

If the result is not good enough, we can continue to  modify the parameters, here is one of the reasonable examples:
```python
df = pd.read_csv(forecast_resource_uri)
model = Prophet(
    growth='flat',
    yearly_seasonality=0,
    weekly_seasonality=8,
    daily_seasonality=6
)
model.fit(df)
future = model.make_future_dataframe(periods=24*60, freq='1min',include_history=True)
forecast = model.predict(future)
model.plot(forecast);
model.plot_components(forecast);
```
![image](https://github.com/facebook/prophet/assets/12690815/8df02ba5-0f6a-4680-91cf-ed8aa2d9c1fb)
![image](https://github.com/facebook/prophet/assets/12690815/7c76c1fe-2136-4b75-996b-88dcc45abe52)

**Comment by LoremipsumSharp** [comment]
@bixiadaren thanks for your advice, I would have a try.BTW, I also tried to change the mode from additive to multiplicative, such changed make the negative predict value disappear
