### ISSUE TITLE
Thoughts on adding prophet to caret and automatic tuning philosophy

### ISSUE THREAD

**Issue by JasonAizkalns** [facebook/prophet#292]
Does it make sense to add `prophet` as a model within the [`caret` package](https://github.com/schistyakov/caret)? Seems [easy enough to accomplish](https://topepo.github.io/caret/using-your-own-model-in-train.html)? If so, how much of a tie to this project is required or is that strictly a `caret` pull request (albeit, could probably benefit from expertise here around setting defaults)?

Then again, I'm not sure if this goes against the philosophy of prophet? Reading the the paper, it seems to be more in line with keeping the analyst in-the-loop and playing a more active role in parameter tuning/adjustment than say a grid search?

I apologize if this isn't the best channel for this type of feedback/questions, but I was unable to locate a mailing list or some other avenue.

**Comment by bletham** [comment]
I'm not sure Prophet is a good fit for caret, since it isn't solving either a classification or regression problem. The value of caret is having a lot of models that solve the same problem in one place for comparison / ensembling, and Prophet wouldn't really be useful for that. But if I'm wrong and someone is interested in doing this, let us know.

**Comment by bletham** [comment]
If anyone has any additional thoughts on this feel free to re-open!
