### ISSUE TITLE
Install new version of package

### ISSUE THREAD

**Issue by beloteloff** [facebook/prophet#318]
I'm trying to run new version of fbprophet on Debian Jessie,python version 3.4.2, using git clone methods of installation. Installation finished correctly. But when I'm typing import ,I see this mistake

```
>>> import fbprophet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/belotelov/prophet/python/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/home/belotelov/prophet/python/fbprophet/forecaster.py", line 27, in <module>
    from fbprophet.models import prophet_stan_models
  File "/home/belotelov/prophet/python/fbprophet/models.py", line 35, in <module>
    'linear': get_prophet_stan_model('linear'),
  File "/home/belotelov/prophet/python/fbprophet/models.py", line 30, in get_prophet_stan_model
    with open(model_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory"  : '/home/belotelov/prophet/python/fbprophet/stan_models/linear_growth.pkl'

```

Before that, I work with package w\o any problems.

Please, give me advice

**Comment by beloteloff** [comment]
upd: I installed the package to /usr/local/lib/python3.4/dist-packages/ and after that I see:
```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fbprophet
/usr/lib/python3.4/importlib/_bootstrap.py:321: UserWarning: Module fbprophet was already imported from /usr/local/lib/python3.4/dist-packages/fbprophet-0.2-py3.4.egg/fbprophet/__init__.py, but /home/belotelov is being added to sys.path
  return f(*args, **kwds)

```

**Comment by bletham** [comment]
I'm guessing what happened here in the first post is that you had installed it while inside the `python` directory, and then started python from that same directory. Then when you tried to import fbprophet, instead of importing the installed package fbprophet, it tried to import the directory fbprophet since you were in the directory that contained it.
I'd try: Uninstall prophet, and make sure it is fully gone and when you `import fbprophet` it tells you no module named fbprophet. Then, re-install it. Finally, cd to a different directory before trying to import it.

**Comment by bletham** [comment]
This seems to have been resolved but feel free to reopen if not.
