### ISSUE TITLE
Eliminate weekends?

### ISSUE THREAD

**Issue by grantog** [facebook/prophet#323]
My input data only consists of data M-F. I also include an external regressor for days of the week (1 = Monday, 2 = Tuesday... 5 = Friday). 
So, my input data has the first column as the date (ds), second column as y, and third column as my external regressor. My dates do not include weekends.

However, when I forecast using prophet, it predicts on weekends, which I'm afraid might skew my actual days of the week predictions (which are actually pretty good).

So, is there a way to have prophet not forecast on weekends? Perhaps I can label them as holidays?

**Comment by bletham** [comment]
If I understand correctly, this is related to the issue described for monthly data here: https://facebook.github.io/prophet/docs/non-daily_data.html

The main issue in using Prophet with M-F data is that if you have weekly seasonality turned on, the term for Sat and Sun will be unidentified and so you can get bad behavior if you then try to forecast for Sat and Sun. As described in the docs there, everything is still correct if you just don't make a forecast for Sat and Sun. So remove Saturdays and Sundays from the `future` dataframe that you pass into `predict`. Having missing data on the weekends, in either the history or the future, is not an issue for the model.

One thing about external regressors. Are you using these to try and add weekly seasonality? The built-in weekly seasonality is equivalent to having a dummy variable for each day of the week. If you are adding an extra regressor that is a single column with values [1,2,3,4,5], then the extra regressor is included as a column in the linear part of the model and this column would add an effect that is 5x stronger on Friday than on Monday.

**Comment by grantog** [comment]
Ah, yes, my external regressors are a single column with values [1, 2, 3, 4, 5]. Sounds like I should change it to a non-numeric value, such as a string?

Will try with that and see how it works. Thanks for responding!

**Comment by ryantsullivan** [comment]
Not an expert but if you do need those regressors then you probably want to
set a dummy column for M-F and use a 0 or 1 where appropriate. Better
explained here https://www.otexts.org/fpp/5/2.

**Comment by bletham** [comment]
The link from @ryantsullivan is exactly what it should be, a separate binary column for each day.

**Comment by bletham** [comment]
This seems to be resolved, but feel free to re-open if there is more to discuss here.

**Comment by RSwarnkar** [comment]
Hi there, I am beginner to fbprophet python. 
I tried applying predict with and without the weekend data in source dataframe. Still this gives negative yhats in the prediction. 
(Usually on weekends (St-Su), there is some non zero and non seasonal data points are recorded in original data.)

Could you please help me out how to fix this? Here is the screenshot:

![image](https://user-images.githubusercontent.com/24961188/73733182-7fd09f80-4761-11ea-8f51-b1c3532a4a9d.png)

**Comment by bletham** [comment]
@RSwarnkar if you don't have weekend data in the history, it is best to not make predictions for weekend dates in the future. So when you make the `future` dataframe of future dates to pass into `m.predict()`, just remove any weekend days from that dataframe. See #1291 for example code to do that.

**Comment by fhoang7** [comment]
I was looking at doing this in R and here's how you would do it:
`future <- subset(future, as.POSIXlt(future$ds)$wday >= 1 & as.POSIXlt(future$ds)$wday < 6)`

**Comment by BHIMARAO1984** [comment]
I am facing same problem in Python, model predicting for Saturday and Sunday even after running code 
>>> df_no_weekdays = future[future['ds'].dt.dayofweek < 5]

![Capture](https://user-images.githubusercontent.com/57024628/85931851-e1e29a80-b8e4-11ea-8d68-c316de9c14b0.PNG)

![Capture1](https://user-images.githubusercontent.com/57024628/85931888-3128cb00-b8e5-11ea-9ab2-be44729d082b.PNG)

**Comment by bletham** [comment]
@BHIMARAO1984 it looks like you called `predict(future)` instead of `predict(df_no_weekdays)`.

**Comment by ravise5** [comment]
Hi,
I'm using prophet for predicting on weekdays only ( i.e. Excluding Sat,Sun in both the train and future dataframes as discussed here). The problem is when I make a forecast for every Monday the confidence intervals that I get are extremely high compared to other days. 
I think this is happening because the model is trained till last Friday and is making a forecast skipping Sat,Sun onto Monday which increases the uncertainty in the confidence intervals.

How can I fix this?

**Comment by bletham** [comment]
@ravise5 It sounds like the the trend uncertainty might be very high for Monday, because of the long (relative to minutely data) break from Friday (end of time series) to Monday (day we're trying to predict). The part that I'm a bit unsure of is that you say the Monday CI is higher than other days; does this mean just higher than when other days are also being forecasted one day out? I see three scenarios:
1) Train through Friday, predict Monday
2) Train through Monday, predict Tuesday
3) Train through Friday, predict Tuesday

Are you saying that (1) has higher CIs than (2)? That would make sense, but if you're saying that (1) has higher CIs than (3) that would not so I wanted to check.

As far as what to do about it - I don't think this will be easy to change because Prophet works in a continuous-time model, and forecasting from Friday to Monday is a longer horizon than forecasting from Monday to Tuesday.  So if we think the trend varies according to calendar time, then the longer break means more opportunity for it to change, and so higher uncertainty.

But if the trend only varies according to business days and not all days, then it sounds like what you're trying to do is to get the trend uncertainty in Monday as if it were only forecasting one day into the future. There isn't going to be a very clean way to do this in Prophet because it pretty strongly assumes continuous time / real, calendar time. This is a workaround that might work:

* Make a forecast for Saturday using `samples_sat = m.predictive_samples(future)` to get posterior samples. The output of this will have samples from the trend, and samples for "yhat" (which is trend plus everything else). The trend uncertainty here will be the one-day trend uncertainty. The "yhat" will not be useful because it will have the bad Saturday seasonality in it.
* Make a forecast for Monday, again using `samples_mon = m.predictive_samples(future)` to get posterior samples. This is the opposite of the `samples_sat`: Here the trend has the 3-day trend uncertainty which we don't want, but the "everything else" will be for Monday, which we do want.
* Compute the non-trend component of y-hat for Monday, as `mon_nontrend = samples_mon["yhat"] - samples_mon["trend"]`. Add this to the trend component for Saturday: `samples_final = samples_sat["trend"] + mon_nontrend`. Those are now samples of yhat that have been adjusted to use the trend estimate for Saturday and not for Monday. You can take a mean and quantiles of those samples to get an estimate and CI.

That's a bit of effort but is the only workaround I can think of for this scenario.

**Comment by ravise5** [comment]
@bletham Thank you for responding so quickly.

I'm interested in the case where (1) has higher CIs than (2) only. 
Let me try this workaround. Thanks again! :-)

**Comment by ravise5** [comment]
@bletham This works perfectly!

**Comment by viniciusriosfuck** [comment]
I was searching how to deal with business days within Prophet and find this issue.
For someone else that come up to here another time.

After the presented solution to get rid of weekends in your data with `dt.dayofweek<5`, if you desire a `horizon` business days forecasting, you could make a future dataframe with the `freq='B'`, that stands for business day frequency.
[Offset aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases), [Example](https://pandas.pydata.org/docs/reference/api/pandas.bdate_range.html)

    horizon = 200
    future = m.make_future_dataframe(
        periods=horizon, 
        freq='B'
    )

**Comment by nknauer** [comment]
When doing cross validation and creating multiple models with cutoffs, will the diagnostic values (RMSE, MSE, etc.) be skewed because we cannot filter for no weekend data in final dataframe? My initial dataset does not have weekends.

**Comment by tcuongd** [comment]
@nknauer Sorry for the late reply. The cross-validation is performed on the data that was passed to the original `model`, so if you called

```R
m <- prophet(df = df_weekdays)
mcv <- cross_validation(model = m, horizon = 5, units = "days")
```

then the diagnostic values will be based on the weekday-only data.

**Comment by nanan10** [comment]
Hello @bletham @tcuongd 
I am facing the same problem with my data
 working on compensation amounts on transactions that are made during working days of the week which is automatically excluding Saturday and Sunday from the course I was asking if you have an idea to submit to me to use prophet on data without weekends.

thank you in advance

**Comment by horvaj6066** [comment]
> I was searching how to deal with business days within Prophet and find this issue. For someone else that come up to here another time.
> 
> After the presented solution to get rid of weekends in your data with `dt.dayofweek<5`, if you desire a `horizon` business days forecasting, you could make a future dataframe with the `freq='B'`, that stands for business day frequency. [Offset aliases](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases), [Example](https://pandas.pydata.org/docs/reference/api/pandas.bdate_range.html)
> 
> ```
> horizon = 200
> future = m.make_future_dataframe(
>     periods=horizon, 
>     freq='B'
> )
> ```

This is exactly what I do and it works well and my series has a ton of weekly seasonality
