### ISSUE TITLE
How to set xlabel and ylabel on components?

### ISSUE THREAD

**Issue by pocakka** [facebook/prophet#328]
On forecast _(m.plot(forecast);)_ this works: 
`m.plot(forecast, xlabel='Date', ylabel='Change')`
But how to rename "ds" and "y" on components _(m.plot_components(forecast);)_ chart?

**Comment by bletham** [comment]
There isn't a built-in way of doing this for the component plots. However, `m.plot_components(forecast)` does return a matplotlib figure which you can then modify manually at will. For example, this code would set the xlabel of the first subplot in the components plot to 'Date':
```
components_fig = m.plot_components(forecast)
axes = components_fig.get_axes()
axes[0].set_xlabel('Date')
```
Can you give some context as to what you are trying to do? I'm not sure that there will be a clean way to allowing passing in xlabels and ylabels since the number of plots in the component plot, and what they are, will vary. For instance, if there are holidays or not, extra regressors, custom seasonalities, etc. But if there is a particular common use case here we might be able to do something.

**Comment by pocakka** [comment]
Thank you. It woks well!
I just make tests:
```
import pandas as pd
import numpy as np
from fbprophet import Prophet
import matplotlib.pyplot as plt
df = pd.read_csv('./examples/sample-data.csv')
df['y'] = np.log(df['y'])
df.head()
m = Prophet(changepoint_prior_scale=0.01)
m.fit(df);
future = m.make_future_dataframe(periods=365)
future.tail()
forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()
m.plot(forecast, xlabel='Date', ylabel='Change')
plt.savefig('sample-result.png')
m.plot_components(forecast);
components_fig = m.plot_components(forecast)
axes = components_fig.get_axes()
axes[0].set_xlabel('Date')
axes[0].set_ylabel('Change')
plt.savefig('sample-result-components.png')
```

**Comment by Cobaltikus** [comment]
How would one change the x axis label in R?
