### ISSUE TITLE
ValueError when sigma=0

### ISSUE THREAD

**Issue by sinanonur** [facebook/prophet#334]
In `sample_model` function noise is calculated as:
`noise = np.random.normal(0, sigma, df.shape[0]) * self.y_scale`
this results in a `ValueError` because of `numpy` which is natural.

But I think this shouldn't prevent the forecasting. noise could simply be zero in that case.

Thank you

**Comment by sinanonur** [comment]
apparently this is fixed in newer versions of `numpy` this results in the expected zeros.
I don't know if this should be changed or `numpy` dependency should be updated.

**Comment by bletham** [comment]
Thanks, like you said this was fixed in later versions of numpy but is an issue in 1.10, which is our minimum requirement. I ran into this a few weeks ago and fixed it in the github version here:  https://github.com/facebook/prophet/commit/58173861b1f975fe272432d600fe18c79d76250c . So installing the latest github version will fix the issue, or of course upgrading numpy is the better fix if possible.

**Comment by bletham** [comment]
This issue is fixed in the current PyPI version for the constant-history case. If it arises in a different context we can re-open this.
