### ISSUE TITLE
Cross_validation does not work with custom seasonalities or extra regressors

### ISSUE THREAD

**Issue by nagautier** [facebook/prophet#336]
Hello,

the copy method for forecasters does not copy custom seasonalities. This leads to unexpected outputs for cross_validation.

**Comment by bletham** [comment]
This should be fixed now in the master branch by https://github.com/facebook/prophet/commit/5dbffbaa18f33db463fded276b806c0268f3d0df and https://github.com/facebook/prophet/commit/0addabcad7953b1620c4d46ab5f0edc7e0fa4fbe . Can you install from github and see if it is working better for you?

**Comment by bletham** [comment]
Fix is pushed to CRAN and PyPI in v0.2.1.

**Comment by anguswilliams91** [comment]
I am using a model with extra regressors and am finding that v0.2.1 still has a bug when extra regressors are used. Looking at the source from PyPI and comparing with `master` here, line 102 of `diagnostics.py`

`columns.extend(m.extra_regressors.keys())`

is missing from the code pulled down from PyPI, so the following exception is raised:

`ValueError: Regressor "extra_regressor" missing from dataframe`.

The above discussion seems to suggest that the fix was pushed to PyPI, but I apparently have v0.2.1 and the bug is still present. Apologies if I've missed something.

**Comment by bletham** [comment]
Sorry about that - the problem that caused this issue was fixed and then pushed in the new version. Diagnostics are now fixed for custom seasonalities, but as you see there is still a (different) issue with extra regressors. There is an issue for it here:
https://github.com/facebook/prophet/issues/351

It's been fixed on the github version as you noticed, but we haven't made another PyPI push yet since that fix. But if you can install the github version that should do it.

**Comment by anguswilliams91** [comment]
Thanks for the response! I hacked the version I pulled down from pypi and that did the trick.
