### ISSUE TITLE
charts in my_model.plot and model.plot_components is duplicated

### ISSUE THREAD

**Issue by LeeChang-Soo** [facebook/prophet#344]
Firstly, thank you for your works. 

And, I have a problem that  charts in my_model.plot and model.plot_components is duplicated as below.

How can I fix it?

Thanks. 

![dup](https://user-images.githubusercontent.com/31691882/32191145-64f81de0-bdf3-11e7-8066-4f9d3a37e965.jpeg)

![dup2](https://user-images.githubusercontent.com/31691882/32191389-431db77e-bdf4-11e7-888f-567506f23d39.jpeg)

**Comment by bletham** [comment]
If this is in a notebook, then it is because of Jupyter behavior that displays any plot that is generated, but then also prints the return value of the last line in the cell (if not assigned). In this case, `m.plot()` returns a matplotlib figure, and so jupyter is printing the figure a second time.

You can get around this by either assigning the output of plot, e.g. like `fig = m.plot()`. Or, in the notebook you can also suppress the printing of the last line by ending it with a semicolon, like `m.plot();`. You'll notice in our documentation that the plot lines have semicolons after them exactly for this reason.
