### ISSUE TITLE
plot_components() doesn't show any graph

### ISSUE THREAD

**Issue by melzoghbi** [facebook/prophet#360]
Hi,

I am using a non daily data and using Predict() to predict time series data. As per the documentation article here: https://facebook.github.io/prophet/docs/non-daily_data.html 

The article is saying that the seasonality in the components plot, while when i call plot_components() nothing is showing up!!

Here is how the plot() visualization looks like:

![image](https://user-images.githubusercontent.com/11993393/32855534-f8a27676-ca0f-11e7-92d7-662a6fcdac4d.png)

**Comment by bletham** [comment]
I think if you remove the semi-colon it will print. Usually by default Jupyter will print out any figure that is generated, and will also print out the last result in the cell unless it has a semicolon. The semicolons are in the documentation because otherwise it prints twice. It looks like for you it isn't printout out every generated figure, but if you remove the semicolon then it will print out the figure since it is the last line in the cell. (like for `m.plot(forecast)` above it).

On a side note, the model fit here is quite poor and that is because this time series seems to have these constant values in addition to what looks like a periodic signal on top. These are the straight lines at around -7, -2, -2.5, and +3. If you were to remove those values so that it can focus just on the periodic part of the time series I'd expect the model fit to be much better.

**Comment by melzoghbi** [comment]
@bletham i removed the semi colon and i can see the chart! thanks for the tip!

@bletham Thanks on the side note, i was planning to look at these and remove them but when i am able to use all basic methods of prophet. Thanks again and i will keep you posted as i just got started on this framework.
