### ISSUE TITLE
Extracting non-seasonal changepoints

### ISSUE THREAD

**Issue by fredthedead** [facebook/prophet#365]
I am trying to use prophet to find change points in a time series by reading the changepoints attribute for a fitted model (full code at the bottom).

There are 2 issues with the returned results:

 1. The returned change points seem to be seasonal ups and downs,
    prophet is able to detect seasonality based on the documentation and
    examples - is there a way to filter out all seasonal change points
    and retain only anomalous ones? (in the example below I'd like the
    model to return only the blue points and not the red ones)  
    
 2. The model returns weird choices of change points - some of the
    points in the example below are not at a local minima/maxima... I've
    tried different values for `changepoint_prior_scale` and
    `n_changepoints` and neither returned better results. Any idea why
    is that happening?

----------
Code:

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    
    np.random.seed(0)
    
    base = datetime.datetime.today()
    date_list = [base - datetime.timedelta(days=x) for x in range(0, 1000)]
    
    df = pd.DataFrame({"ds" : date_list,
                       "y" : np.sin(np.arange(1000) * 2 * np.pi/100.0) + 0.1 * np.random.standard_normal(1000),
                       })
    df.set_index("ds", inplace=True)
    df.at[500:510, 'y'] = 2
    plt.plot(df["y"], color='grey')
    
    model = Prophet()
    model.fit(df.reset_index())
    
    plt.plot(model.changepoints.tolist(), df.loc[model.changepoints.tolist()], 'r*')
    plt.plot(df.index.tolist()[500:510], df.loc[df.index.tolist()[500:510]], 'b*')
    plt.xticks(rotation=90)
    plt.figure()

Result:
[![Interested that the model will return only the Blue marker (which it currently is not returning) instead of all the red ones][1]][1]

  [1]: https://i.stack.imgur.com/YSEG8.png

**Comment by bletham** [comment]
There are a few things going on here.

The first is that `model.changepoints` gives a list of the locations where the model is allowed to put changepoints. These locations are chosen uniformly throughout the history (hence the seemingly odd placing). In model fitting, some of them will be used and some of them will not be used. To see which changepoints are being used, you have to look at the model parameter for the slope change at each changepoint. You can get this with `model.params['delta']`. If you look at this for your time series, you will see that the amount of change at almost all of the changepoints is basically zero (1e-9 and lower). This is because the model is using the seasonality component to track the trend, not the changepoints. To see this more clearly, try
```
forecast = model.predict()
model.plot_components(forecast)
```
and you will see that there is little change in the trend.

The 0.3 branch of the R version has a utility for plotting the locations of the significant changepoints - you can see it here:
https://github.com/facebook/prophet/blob/v0.3/R/R/utils.R
It looks for changepoints with delta>0.01.

One more note about the seasonality - by default for a time series with daily data like this one, Prophet will fit weekly and yearly seasonalities. This time series does not have weekly or yearly cycles - the cycle seems to be about 3.5 months. So the seasonality won't work well here unless you add a custom seasonality with cycle of 3.5 months.

A final note is that a cluster of outliers like those will not always result in the model using a pair of changepoints to grab it. See the 2nd example here: https://facebook.github.io/prophet/docs/outliers.html
