### ISSUE TITLE
Plotting methods in Python should return axes, not figures

### ISSUE THREAD

**Issue by teoguso** [facebook/prophet#386]
The main practical reason for this issue is the use of prophet in Jupiter notebooks, where plotting methods return a figure and cause a duplicated cell output, e.g. two equal plots instead of one.

There is also a case of aligning the method behavior with matplotlib standard interface, where `.plot()` returns artist objects. It would also be aligned with the plotting methods of pandas (which are using matplotlib, much like prophet) or seaborn, that return axis objects. It would just make sense in terms of consistency with other Python libraries that make use of matplotlib. 

I think this is of course up for debate so suggestions are very welcome. It shouldn't be too much work and I would be glad to give it a try.

**Comment by bletham** [comment]
This is something that we literally went back and forth on. Originally it returned a fig. Then we merged in a PR that switched it to return the artists since that is the matplotlib recommendation. Ultimately we switched it back to returning a fig in #169. As explained there, it's just more convenient to have a fig and the artists are still available for those that do want them.

The Jupyter thing does get a bit annoying because it will be default show any generated matplotlib plots, but will then also print the output of the last run command and so prints the plot twice. You can avoid this by using a semi-colon after the plot command - this suppresses jupyter's printing of the last output. Like this:
```
m.plot(forecast);
```
You'll notice that our documentation has semi-colons after the plot commands for exactly that reason.

**Comment by teoguso** [comment]
I see. Thanks for your reply.

I was aware of the semicolon trick, but still, it's a workaround and I don't think it is ideal.
I've gone through the links to the issue, and I'm still not convinced of why someone would prefer to return a figure in a practical workflow. The only convincing thing I've read is that it's easier when someone wants to use the `fig.plot()` command. Now, that's a command that nobody will normally use in a notebook-based workflow, so I'm a bit perplexed.
This configuration makes it also harder to incorporate the plots into more complex subplots.  
As I see it now, the plotting methods are good for a quick preview, but for more complex plots is more convenient to ditch the built-in methods and take the data directly from the dataframes with matplotlib or seaborn. I was hoping for something more in the spirit of what pandas does. Oh, well. :-)

**Comment by bletham** [comment]
There are definitely frustrating things either way, and extra code required to extract things from a fig object when desired. But at this point there'd have to be a pretty compelling advantage to make a breaking change to returning artists.

For incorporating in more complex figures one can use `get_children()` on the figure object to get down to the artists. Or just use directly call the plot methods for each of the components, which all return artists: https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1307-L1324

**Comment by teoguso** [comment]
I agree the motivation is not strong enough to introduce such a change. 
The latter option is probably the most compelling one for my usual workflow. Thanks! 
I think we could close the issue now. .
