### ISSUE TITLE
Plot components not showing uncertainty

### ISSUE THREAD

**Issue by brylie** [facebook/prophet#395]
When plotting chart components (using Python/Jupyterlab), the uncertainty intervals are now showing:

![screenshot from 2017-12-28 10-41-06](https://user-images.githubusercontent.com/17307/34405381-bbc8d376-ebbb-11e7-8b54-de0c9f6ec5c4.png)

I have tried adding `uncertainty=True` to the components plot, but that has no effect. How can I display uncertainty bands in the components plot?

**Comment by bletham** [comment]
There are three sources of uncertainty in the model: future trend uncertainty, parameter uncertainty, and a noise term.

Future trend uncertainty gives you the fanning uncertainty as we project forward in time. This uncertainty comes from trend changes in the past. As you can see in the trend plot, there are no trend changes in the fit, and so there is no future trend uncertainty.

Parameter uncertainty would be the uncertainty in the slope itself, and would be indicated by a band around the line in the bottom curve. To measure parameter uncertainty you need to do MCMC. This takes more time but is the only way to estimate parameter uncertainty. This particular time series is very short and so I would highly recommend doing MCMC, like this:
```
m = Prophet(mcmc_samples=500)
```

The final uncertainty component is just a constant noise term in the model. This is what you are seeing in the first figure, and is the reason why the uncertainty is constant across the entire forecast.

See here for more info: https://facebook.github.io/prophet/docs/uncertainty_intervals.html


Related to that, this model fit is very poor because it is not using any changepoints in the trend. Did you specify 0 changepoints? If not could you attach the csv with these data so I can figure out why the model isn't putting in changepoints?

**Comment by bletham** [comment]
Seems to be resolved but feel free to re-open if not.
