### ISSUE TITLE
Large variations in weekly seasonality throughout the year

### ISSUE THREAD

**Issue by adamtay82** [facebook/prophet#425]
Really enjoying Prophet -- thanks for everything.

I have a question about one particular issue I'm seeing in a dataset and I'm not sure how best to handle it.   I have a data set that exhibits the following properties:

a) During winter months: high volume at weekends, low volume during weekdays 
b) During summer months: low volume at weekends, high volume during weekdays 

Just wondering if there's a neat solution that I'm missing ....

**Comment by bletham** [comment]
This is related to the discussion of dynamic seasonality in #391. I don't know that there's a really good simple solution for this at the moment. In this particular case though there is something you could try though if you have daily data.

The weekly seasonality uses a Fourier series the same as the yearly, but the order is such that for daily data it is equivalent to just having a dummy variable for each day of the week. (Except 1 for identifiability). So you could get separate weekly seasonalities for winter and summer months by just adding extra regressors that are dummy variables for each day, separately in winter and summer.

As an example, right now the weekly seasonality is equivalent to using add_regressor 6 times to add the binary regressors `is_monday`, `is_tuesday`, ..., `is_saturday`. (`is_sunday` is left out because it would just be the baseline). The column `is_monday` would look like [1, 0, 0, 0, 0, 0, 0, 1, 0,..] and has a 1 whenever the corresponding date is a Monday. 

You can get two separate weekly seasonalities by using add_regressor 13 times to get `is_summer_monday`, `is_winter_monday`, `is_summer_tuesday`, and so forth. (Again just leaving one out as the baseline, e.g. `is_winter_sunday`). The `is_summer_...` columns would be 0 all winter, and vice versa for `is_winter_...`.

Does that seem reasonable? I'd be really curious to hear if this works.

**Comment by adamtay82** [comment]
This is an awesome idea -- I knew there'd be a creative approach somehow. 

Let me loop and see how I get on.  Will report back!

**Comment by adamtay82** [comment]
As a heads up -- I got improvement in the summer months, but most of the gains were lost during the other months.  Maybe 3-4% reduction in error overall. Still room for me to improve! :)

**Comment by vhpietil** [comment]
I think you can use fourier series as external regressors if there is variation in the weekly seasonality during the year. I have had quite good results using this approach. This way you don't have to predefine the days that are winter and summer but you can possibly learn them from the data.

Please see my comment to issue #434 Capturing different daily profiles where I applied this to hourly series.

**Comment by adamtay82** [comment]
Very interesting -- thanks for posting.  Now just need a few more hours in the day to work on it :)

**Comment by bletham** [comment]
I'm going to go ahead and close this to consolidate all of the issues on this matter in #538.

**Comment by bletham** [comment]
This feature has now been implemented in #538, and if anyone is able to give it a spin and report in that issue how it went that'd be really helpful.
