### ISSUE TITLE
Interpreting seasonlity

### ISSUE THREAD

**Issue by julwin** [facebook/prophet#428]
Hey,

I'm having problems to interpret seasonality: As far as I can see it it a factor which is then added to our linear formula. 

I'm having trouble to understand how the information presented could benefit me: In a real-world-scenario I'd like to have a feeling of how much influence depends on seasonality.

Now would it make sense to normalize the seasonality to a scale of [0..1] to represent a percentage?

**Comment by bletham** [comment]
Correct, it is an additive factor. For an example like the one from the documentation (https://facebook.github.io/prophet/static/quick_start_files/quick_start_14_0.png), I think the right way to understand it is that every Monday, "y" will be 0.3 larger than it would have been without weekly effects, just because it is Monday. If these were data of sales, for instance, then we'd say that we have 0.3 extra sales every Monday just because of the day-of-the-week effect. (And 0.3 fewer sales on Saturday just because its Saturday). The key thing is that it is the raw number of sales attributed to day-of-the-week.

I don't think there's a clear way to turn these into a percentage because it is an additive model, and so (continuing with the example) the percentage of total sales that 0.3 corresponds to will depend on how many total sales there are, which is probably varying throughout the time series.

In the near future when we have multiplicative seasonality, then that would correspond to a fraction of the total that is attribute to day-of-week effect.

**Comment by julwin** [comment]
Thanks a lot for clarification!
