### ISSUE TITLE
How to improve model accurecy

### ISSUE THREAD

**Issue by sushilcmd** [facebook/prophet#431]
Currently i'm using prophet for daily sales forecast but when i match my actual sale then difference between actual and predicted sell is very big.
How can i reduce this difference and improve model accuracy??

#### code
tsData<-newData %>% mutate(ds=nDay,y=log(totalBill))
dataset<-tsData %>% mutate(ds=as.Date(as.character(ds),'%Y%m%d')) %>% mutate(day=day(ymd(ds))) %>% select(ds,y)
 m<-prophet(dataset,growth = "linear",seasonality.prior.scale = 0.1,weekly.seasonality=TRUE)
future <- make_future_dataframe(m, periods = 10, freq = "day",include_history = FALSE)
forecast <- predict(m, future)

**Comment by vhpietil** [comment]
It is very difficult to give suggestions if you can't share any data or plots about the model fit.

**Comment by sushilcmd** [comment]
data which i pass in model :-
@vhpietil 

ds | y
-- | --
2017-08-03 | 50000
2017-08-04 | 140000
2017-08-05 | 40000
2017-08-06 | 170000
2017-08-07 | 90000
2017-08-08 | 120000
2017-08-09 | 47800
2017-08-10 | 80000
2017-08-11 | 78965
2017-08-12 | 47526
2017-08-13 | 45236
2017-08-14 | 14528
2017-08-15 | 145632
2017-08-16 | 125896
2017-08-17 | 32576
2017-08-18 | 45965
2017-08-19 | 47896
2017-08-20 | 213654
2017-08-21 | 85214
2017-08-22 | 95632
2017-08-23 | 78564
2017-08-24 | 125896
2017-08-25 | 47852
2017-08-26 | 125478
2017-08-27 | 155698
2017-08-28 | 123658
2017-08-29 | 127568
2017-08-30 | 45236

**Comment by vhpietil** [comment]
The time series is so short and the data seems to be so random that unfortunately I don't know how to imporove the forecasts. 
Below is the plot of the prophet fit. Weekly component is not very strong in the data.

![image](https://user-images.githubusercontent.com/15958019/35805305-f71afb70-0a83-11e8-9302-698a3bee6f5b.png)

**Comment by sushilcmd** [comment]
Actually this is just a sample data. I have data from 02-02-2017 to 31-01-2018 and i want predict next 7 days sales

**Comment by vhpietil** [comment]
You might want to set the yearly seasonality on, by default it is off if you have less than two years of data. You don't have enough data to make predictions with the yearly seasonality (because you have less than a year) but it might be interesting to see if the model finds some yearly seasonality which would make the fit better. 

In addition, depending on your sales there may be some holidays that increase or decrease the sales. Adding holidays might be beneficial.

**Comment by sushilcmd** [comment]
It means according to you i haven't enough data for forecast daily sales (Next 10 days sales).

**Comment by vhpietil** [comment]
Your data seems to be very hard to forecast accurately. 

Less than a year can be enough data if there is no strong yearly seasonality. If the yearly seasonality is strong, piecewise linear trend model might not capture it well and then the weekly seasonality can be difficult to estimate. In addition if there is strong yearly seasonality (and less than a year of data), it is difficult to predict because one doesn't have any observations of the season one is about to predict.

**Comment by bletham** [comment]
+1 for what @vhpietil says, there aren't any clear periodic trends in this time series for the model to pick up on, and so I don't think there is much hope of getting a better forecast than this. Unless you know why it is really high on some days and then really low a few days later? Is there some predictable effect that is causing this variance?

**Comment by bletham** [comment]
There doesn't seem to be a specific issue here so I'll close this, but if there is more to discuss feel free to reopen.
