### ISSUE TITLE
add_regressor confusion

### ISSUE THREAD

**Issue by andypohl** [facebook/prophet#432]
This is failing for me in multiple ways.   I just want to know the basic way to use this.  I'll try with your example, adding fake data, and ignoring it at first:
```r
library(tidyverse)
library(prophet)
data_url <- "https://raw.githubusercontent.com/facebook/prophet/master/examples/example_wp_peyton_manning.csv"
df <- read_csv(data_url, col_types = cols()) %>% 
    mutate(ds=as_datetime(ds), y=log(y))
extra_dates <- as_datetime(seq(ymd('2007-12-01'), 
                               ymd('2016-03-01'), by='day'))
extra <- tibble(ds=extra_dates, whatever=rnorm(length(extra_dates)))
df <- df %>% left_join(extra, by="ds")
df
# A tibble: 2,905 x 3
##   ds                      y whatever
##   <dttm>              <dbl>    <dbl>
## 1 2007-12-10 00:00:00  9.59   -0.196
## 2 2007-12-11 00:00:00  8.52   -0.178
## 3 2007-12-12 00:00:00  8.18   -1.26 
## 4 2007-12-13 00:00:00  8.07   -0.912
## 5 2007-12-14 00:00:00  7.89    1.54 
## 6 2007-12-15 00:00:00  7.78    1.42 
## 7 2007-12-16 00:00:00  8.41    0.624
## 8 2007-12-17 00:00:00  8.83    0.220
## 9 2007-12-18 00:00:00  8.38    1.52 
##10 2007-12-19 00:00:00  8.07    0.468
### ... with 2,895 more rows
m <- prophet(df)
##Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
##Initial log joint probability = -19.4685
##Optimization terminated normally: 
##    Convergence detected: relative gradient magnitude is below tolerance
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
##|======================================================|100% ~0 s remaining
```
So that works ok.  What if I try to add 'whatever' to the model?
```r
m <- prophet(df)
m <- add_regressor(m, 'whatever', standardize = FALSE)
##Error in add_regressor(m, "whatever", standardize = FALSE) : 
##  Regressors must be added prior to model fitting.
```
OK, trying again:
```r
m <- prophet(df, fit=FALSE)
m <- add_regressor(m, 'whatever', standardize = FALSE)
m <- fit.prophet(m, df)
##Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
##Initial log joint probability = -19.4685
##Optimization terminated normally: 
##  Convergence detected: relative gradient magnitude is below tolerance
future <- make_future_dataframe(m, periods = 365)
forecast <- predict(m, future)
##Error in setup_dataframe(object, df) : 
##  Regressor "whatever" missing from dataframe
```
Alright that error is [coming from here](https://github.com/facebook/prophet/blob/998c90fc053ad693ec7b04aa91c5da3495ae8173/R/R/prophet.R#L330).
If I try to try to add this column to the future data frame manually?
```r
future <- make_future_dataframe(m, periods = 365) %>%
    left_join((m$history %>%  select(ds, whatever)), by=c('ds'='ds'))
forecast <- predict(m, future)
##Error in setup_dataframe(object, df) : Found NaN in column whatever
```
I get the error [from further down the same function](https://github.com/facebook/prophet/blob/998c90fc053ad693ec7b04aa91c5da3495ae8173/R/R/prophet.R#L365)

OK, so what if I get rid of those NAs:
```r
future <- replace_na(future, list(whatever=0))
forecast <- predict(m, future)
##|======================================================|100% ~0 s remaining     
```
It ran.  But is this right?  Is there something basic I'm missing about using extra regressors?  Examples?

**Comment by vhpietil** [comment]
I haven't run the code but I think you are doing it right. You can check m$params$beta (i think) if there is an extra value for wharever-regressor. 

You can also use prophet_plot_components, it will plot the extra_regressors.

Hope this helps

**Comment by andypohl** [comment]
I know my model is incorporating the added regressor, but I don't know if it's doing it in an expected manner.  Because I sidestep a lot of errors, I'm not very confident I am.  And If I am, then either `make_future_dataframe()` or `setup_dataframe()` isn't working as intended.

**Comment by vhpietil** [comment]
Hi, I think you are using the functions currently as expected. At least I use them the same way :) 

It might be nice if the make_future_dataframe -function took extra regressor values as input and the user didn't have to join the values to the "future"-dataframe afterwards.

**Comment by bletham** [comment]
Yes you did things correctly. It looks like the messaging can be improved here.

The extra regressor has to
1) be added prior to model fitting (since it is used in fitting). That was the first one.
2) be present for all of the dates in the `future` dataframe. Since the forecast now depends on the value of the extra regressor, we can't compute a forecast estimate for any dates for which we do not have the value of the regressor. Hence not allowing NaNs there, this would just lead to NaN in the forecast estimate.

That does seem like a really rocky experience for getting the workflow down correctly, though I'm not sure what the better way would be for getting the extra regressor value into the future dataframe besides adding it manually. To have it as an input to make_future_dataframe you'd need to know exactly what dates will come out of make_future_dataframe, and that seems like more effort than just doing the join afterwards.
(As a fun fact there, specifying monthly frequency will give different dates in R and Python because R and pandas have different definitions of 'monthly'.)

**Comment by andypohl** [comment]
I'm speaking from a fairly naive and amateur perspective so I appreciate the explanation.  But if I'm understanding right, my use of an added regressor might not fit its intended purpose.  If we're supposed to know the future values of this regressor, then it would need to be something we know in advance, similar to holidays.  I was using it to store measurements collected on a daily basis like *y".  Setting this to 0 for future data would seem to me like I'm injecting false data into the model, and perhaps need instead their own forecasted values on a univariate level.  Does that sound right?  It would be great to know all the assumptions placed on extra regressors.  I already know from error messages that they need to be either logical or numeric.  Other things like:

- do the values need to be known in advance?  (as I just mentioned).
- are there assumptions of independence from the forecasted variable?  I know this is based on a GAM, and GAMs being non-linear, they handle multicollinearity better than other models, but I'm just wondering.

Thanks for helping me.

**Comment by vhpietil** [comment]
Can you tell what kind of data you are forecasting and what kind of a regressor you are using? Maybe there is a way in which not knowing the future values and using 0 would not feel like injecting false data.

**Comment by bletham** [comment]
* Your point is correct that these do need to be known in advance. So it would either be something that either has known future values, or something that you have separately forecasted elsewhere and believe its forecast to be reasonable.
* The model is y(t) = growth(t) + X(t)*beta + noise, where X(t)*beta is a big linear part of the model. X(t) here contains the seasonality features, indicator variables for holiday effects, and is where the external regressor is put. So, we model y(t) as having some linear relationship with the extra regressor. For independence: the value in having the external regressor is when they aren't independent, so that the future value of the regressor informs the future value of y. If we added two external regressors that were correlated then there would be a multicolinearity in the model, but I wouldn't expect this to cause any issues here because we aren't trying to make inferences about beta (e.g., is beta sig. diff from 0), rather we care only about the forecasted value of y.

This needs to be described more clearly, once your questions are resolved let's leave this task open as a to-do to update the documentation.

**Comment by bletham** [comment]
Having multiple correlated extra regressors isn't a problem in theory, but it could be a problem for the optimizer or for the MCMC if it makes the model unidentifiable - we'll have to do some more testing of that.

**Comment by andypohl** [comment]
OK, it looks like you know what I mean so I don't think you need my data.  Thanks for thinking about it from my point of view.  I know the extra regressors weren't in the first version of prophet, so I understand if the documentation is catching up to a new feature.  But if you're going to add something to the docs anyway, it'd be cool if the Peyton Manning example could be expanded on with an extra regressor somehow.  Thanks again.

**Comment by bletham** [comment]
This specific point was clarified in the documentation. I'll add an example with a continuous regressor in the future but not yet.

**Comment by csetzkorn** [comment]
Thanks - this conversation really helped!

**Comment by alihash** [comment]
Hi there,

I am also in the process of adding regressors to my model. I have done the following:

```

# Fit model - Players Sold, Activations, Churned, First Month Streamed, New Accounts
players_aa <- train_data %>% select(date_key, players_active_accounts, players_sold, players_activations, players_new_accounts, first_month_transactions, players_account_churned) %>% 
  rename(y = players_active_accounts, ds = date_key)

m <- prophet()
m <- add_regressor(m, 'players_sold')
m <- add_regressor(m, 'players_activations')
m <- add_regressor(m, 'players_new_accounts')
m <- add_regressor(m, 'first_month_transactions')
m <- add_regressor(m, 'players_account_churned')

m <- fit.prophet(m, players_aa)
future_m <- make_future_dataframe(m, periods = 24, freq = 'month')

future_m$date_key <- as.Date(future_m$ds)
players_aa$date_key <- as.Date(players_aa$ds)

future_players_activations <- future_m %>% left_join(select(players_aa, players_sold, players_activations, players_new_accounts, first_month_transactions, players_account_churned, date_key), by = 'date_key') %>% 
  select(-date_key)

future_players_activations <- replace_na(future_players_activations, list(players_sold=0))
future_players_activations <- replace_na(future_players_activations, list(players_activations=0))
future_players_activations <- replace_na(future_players_activations, list(players_new_accounts=0))
future_players_activations <- replace_na(future_players_activations, list(first_month_transactions=0))
future_players_activations <- replace_na(future_players_activations, list(players_account_churned=0))

forecast <- predict(m, future_players_activations)

plot(m, forecast) 
```

<img width="1050" alt="screenshot" src="https://user-images.githubusercontent.com/23070309/50048245-acb48580-007b-11e9-8b12-7aa4f2bda86c.png">

**Comment by bletham** [comment]
@alihash Yes, that looks like what is happening. All of the extra regressors need to have something set for their future values. In the join, future values are getting set to NA, which is then being replaced with 0. So what you're seeing is the forecast assuming that all of the regressors (players_sold, players_activiations, etc.) are going to be 0 in the future. You'll need to replace that 0 with a more reasonable estimate.

**Comment by bletham** [comment]
@alihash I'm going to add a link to this in the documentation: https://github.com/nicolasfauchereau/Auckland_Cycling/blob/master/notebooks/paper_day_weather.ipynb

It's a very compelling example of continuous extra regressor.

**Comment by chessplaya2** [comment]
Thank you!

**Comment by Bougeant** [comment]
> * Your point is correct that these do need to be known in advance. So it would either be something that either has known future values, or something that you have separately forecasted elsewhere and believe its forecast to be reasonable.

@bletham 

Hi!

With regards to the fact that we need to know the value of the extra features (i.e. regressor), it seems that it defeats the point of making long-term predictions with additional regressors if you have to provide long-term predictions of the regressors values.

In the application that I am interested in, I would like to predict a cyclical amount (wave nº1), if possible using another cyclical amount as an additional feature (wave nº2). Wave nº2 is expected to have some predictive power for wave nº1 because wave nº1 is delayed compared to wave nº2. The problem is that wave nº1 is not easier to predict than wave nº2.

Would it be possible to use additional features using convolution between the features (e.g. wave nº1 and wave nº2) so you could use the evolution of these features up until the time of your prediction to make your prediction more accurate?

I guess I could offset the features by whatever period I want to make predictions for. But that would mean that if I want to make predictions for the next 3 months, I'd have to use 3 months old values of my features to predict what is going to happen tomorrow, which makes little sense. Ideally, we'd want to use today's data to make predictions for the next 3 months.

Anyway, I'm not sure this is even possible. What are your thoughts on this?

**Comment by bletham** [comment]
The model assumes a linear relationship between `y` and extra regressors, so in this case where there is a feature that is significantly correlated but lagged by 3 months, then I think you would definitely want to do what you proposed and add a lagged version of the the feature (wave2) to the model.

With that, you now know the extra regressor 3 months into the future (because of the lag) and we expect it to improve our forecasts 3 months out.

Past that, there really isn't an easy way to use extra regressors without knowing what they are. In this case if you wanted to make forecasts past 3 months you could forecast the feature (wave2) and then include the forecasted feature. Normally this wouldn't necessarily make sense unless something made wave2 easier to forecast than wave1 alone, but in this particular case there would be value because we would at least have an improved forecast for the first 3 months, and even though for later dates we're relying on a possibly variable forecast for wave2, we should be in a better place than not using wave2 at all because of the 3-month head-start.

**Comment by Bougeant** [comment]
Thanks for the answer. Maybe what I'm looking for is something like Vector AutoRegression but I'll still try the lagged feature with Prophet.

It's an awesome tool by the way!
