### ISSUE TITLE
Capturing different daily profiles

### ISSUE THREAD

**Issue by gs9824** [facebook/prophet#434]
I'm using prophet on the following dataset
[ts_1_week.txt](https://github.com/facebook/prophet/files/1699430/ts_1_week.txt)

I'm trying to fit the model as good as possible. This works reasonably, but weekends seem to have a different profile - which the model does not seem to capture (take up is later on weekend days)

![capture_prophet](https://user-images.githubusercontent.com/36197920/35864558-6ac73a60-0b52-11e8-88be-2a5ce074e129.PNG)

I tried to add a specific regressor for weekenddays, but this does not seem to make a lot of difference.

m_1_week = Prophet(growth='logistic', weekly_seasonality=True)
m_1_week.add_regressor('weekend')
ts_1_week['floor']=0
ts_1_week['cap']=10
m_1_week.fit(ts_1_week);

future = m_1_week.make_future_dataframe(periods=48, freq = "h", include_history = True)
future['floor']=0
future['cap']=10
future['weekend'] = future['ds'].apply(weekend)

forecast = m_1_week.predict(future)

There seems to be only 1 daily profile, while it would make sense to have different ones for different day types

![capture_2](https://user-images.githubusercontent.com/36197920/35865256-546f0a2a-0b54-11e8-979f-efb683d26365.PNG)

Is there a way to model the differences between weekdays & weekends in a better way ?

**Comment by vhpietil** [comment]
Do you have more data to share? I have an approach which I would like to try. But when you have only one week of data, the model easily overfits.

**Comment by gs9824** [comment]
Thanks for your response and willingness to look into this.

Yes, the original series is 4 weeks.  The original data values are in the yy column, the y column is the log of the values -- as that seemed to give better results.

Here it is : 
[ts_4_weeks.txt](https://github.com/facebook/prophet/files/1702898/ts_4_weeks.txt)

**Comment by vhpietil** [comment]
You are right that there is only one daily seasonality that is applied for all dates. This makes sense with temperature and other things that are not interested in weekends.

When you used specific regressor for the weekend, you put constant 1 for every hour of the weekend. It just scales whole weekend up or down but cannot change the shape of the seasonality on weekends.

You can make an external regressor by taking some number of sine and cosine functions (fourier series) in the same way prophet estimates the seasonalities. When you add this external regressor only on saturday and sunday, prophet can estimate how the "normal" daily seasonality need to be changed in order to get right seasonality for the weekends. 

Unfortunately I don't have time to polish my approach more, but here is the code and the results. I code in R.

```
library(prophet)
library(readr)
library(dplyr)

# Read the data
df <- read_csv("ts_4_weeks.txt")

# Fourier series, time_diff and set_date are functions
# from prophet-package
# These are used to make extra regressors
fourier_series <- function(dates, period, series.order) {
  t <- time_diff(dates, set_date('1970-01-01 00:00:00'))
  features <- matrix(0, length(t), 2 * series.order)
  for (i in 1:series.order) {
    x <- as.numeric(2 * i * pi * t / period)
    features[, i * 2 - 1] <- sin(x)
    features[, i * 2] <- cos(x)
  }
  return(features)
}

time_diff <- function(ds1, ds2, units = "days") {
  return(as.numeric(difftime(ds1, ds2, units = units)))
}

set_date <- function(ds = NULL, tz = "GMT") {
  if (length(ds) == 0) {
    return(NULL)
  }
  
  if (is.factor(ds)) {
    ds <- as.character(ds)
  }
  
  if (min(nchar(ds)) < 12) {
    ds <- as.POSIXct(ds, format = "%Y-%m-%d", tz = tz)
  } else {
    ds <- as.POSIXct(ds, format = "%Y-%m-%d %H:%M:%S", tz = tz)
  }
  attr(ds, "tzone") <- tz
  return(ds)
}

# Create extra regressors. 
# These are basically sin and cos signals with varying periods
# Dates are joined to the regressors and then I filter only saturday and sunday
# Names of the columns are V1...V(2*series.order)
series.order <- 3
regressors <- fourier_series(df$ds, 1, series.order) %>% 
  as_data_frame %>% 
  cbind(ds = df$ds) %>% 
  filter((lubridate::wday(df$ds) %in% c(1,7)))

# Initialize prohet
m <- prophet(weekly.seasonality = TRUE)

# Add regressors to the model one by one
for (i in 1:(length(regressors)-1)) {
  m <- add_regressor(m, paste0("V", i))
}
# Join regressors to the data, replace NAs with zeros and fit
m <- fit.prophet(m, df = df %>% left_join(regressors) %>% replace(is.na(.), 0))

# Create future dataframe and extra regressors for those datetimes
future = make_future_dataframe(m, 24*7, freq = 3600)

series.order <- 3
future_regressors <- fourier_series(future$ds, 1, series.order) %>% 
  as_data_frame %>% 
  cbind(ds = future$ds) %>% 
  filter((lubridate::wday(future$ds) %in% c(1,7)))

# Profit
forecast <- predict(m, future %>% left_join(future_regressors) %>% replace(is.na(.), 0)) 

plot(m, forecast)
```

![image](https://user-images.githubusercontent.com/15958019/35922428-3b45ab08-0c26-11e8-93c8-aa9c2ba3c3aa.png)
![image](https://user-images.githubusercontent.com/15958019/35922460-53d37e70-0c26-11e8-91a0-33dcf46059ba.png)

You can see that the extra regressor modifies daily seasonality on the weekends and the overall fit is pretty good. There is a weird artefact/spike in the first hours of the saturday. It probably can be explained some how and dealt with.

@bletham What do you think about this approach. I have noticed that the weekly seasonality can be pretty different during winter and summer and this approach has given me quite promising results. Do you see some problem with this approach? Should I do this in some different way?

**Comment by bletham** [comment]
It looks like the weekly seasonality is a multiplicative factor on top of the daily seasonality.

Currently, seasonality and extra regressors are always additive, which means that
y(t) = trend(t) + daily_effect(t) + extra_regressor(t),
so extra_regressor has a constant effect throughout the day. You can see in the plot that the model estimate dips down a bit on those days, but since it isn't able to scale the daily seasonality (multiplicative factor) it isn't able to fit well.

Multiplicative seasonality is a current priority (#254). In the meantime, what @vhpietil proposed would be the right thing to do: Manually create a separate daily seasonality for the weekend days. It's a bit of a pain as you can see but I would expect it to work well here (and certainly seems to).

This is related to #425 which got some benefit from splitting seasonalities out by time. We should probably think of a cleaner way to do this sort of thing.

**Comment by bletham** [comment]
Just as an FYI, in R you can call the not-exported functions from prophet using :::, like `prophet:::fourier_series` so you don't have to redefine them externally.

**Comment by gs9824** [comment]
Many thanks for your responses & suggestions. I will try these out & report back

**Comment by gs9824** [comment]
I can confirm the results of vhpietil. Maybe there is indeed a need for a feature to do this more or less automatically (add a regressor for specific days, specific weeks, ...).

Many thanks for helping out in this :-)

**Comment by bletham** [comment]
Yeah, let's leave this open as an enhancement to have an easier way to add these types of specific seasonal regressors.

**Comment by bletham** [comment]
I'm going to close this to consolidate the various issues on this matter in #538, so follow along there for updates.

**Comment by bletham** [comment]
This feature has now been implemented in #538, and if anyone is able to give it a spin and report in that issue how it went that'd be really helpful.

**Comment by gs9824** [comment]
@bletham Finally was able to give it a spin, and I must say I'm impressed. It works like a whistle :) Many thanks for the follow up & implementation

**Comment by john-karp** [comment]
An alternative to using the feature in #538 is to disable explicit daily seasonality, and increase the resolution of weekly seasonality so it can capture daily patterns. E.g `weekly_seasonality=28, daily_seasonality=False`. I think this should actually work a bit better than lumping all weekdays together and lumping all weekend days together, because at least in the data I've modeled, user behavior differs between Monday and Friday for example, and likewise between Saturday and Sunday.

**Comment by PeishanR** [comment]
@john-karp May I learn why the weekly_seasonality is set to 28 in your case? I am working on hourly time series data to forecast sales a week ahead. The hourly data ranges from 9am to 21pm and from Monday to Saturday only(Sunday is the regular gap since the store is closed on Sunday). The daily pattern differs but the weekly pattern is quite similar. I tried adding the extra regressor following the suggestions from @vhpietil but without filtering any specific weekday since daily pattern differs. The red line is the predicted values. My model still fails to capture the rising pattern from Thursday onward and the upside-down v-shaped Saturday pattern. So I'm curious how would you handle with weekly seasonality if they differ everyday? Would extra regressors for intra-day pattern necessary?
![image](https://user-images.githubusercontent.com/75792638/115232467-04190380-a117-11eb-9570-b48dba5580ea.png)
