### ISSUE TITLE
Problem using crossvalidation on removed data

### ISSUE THREAD

**Issue by CalebSturges** [facebook/prophet#436]
I'm using cross validation to tune hyperparameters that remove outliers from my dataset. The issue is that I still want the outliers in my testing set so I need their predicted out of sample values ("yhat"). According to the docs the based way to deal with outliers is to declare them to "None". This works for the initial model training but when it comes to cross validation the analysis does not generate the prediction ("yhat") for the data declared "None". This is because in the diagnostics.py "simulated_historical_forecasts" that the model "history" is used:

`df = model.history.copy().reset_index(drop=True)`

Unfortunately "history" drops records with "None" values.  I developed a hack by appending the "None" replaced outlier data to the model "history", running the cross validation to get the out of sample predictions and then joining the actual outliers back in for the out of sample testing:
```
import numpy as np
import pandas as pd
from fbprophet import Prophet
from fbprophet.diagnostics import cross_validation
from sklearn.metrics import mean_squared_error

# Outliers where detected using a hyperparameter and set to "None" in the df_noOutliers Dataframe. 
# The date stamps ("ds") and None ("y") values where where saved in the "outlierData" Dataframe. 
m = Prophet()
m.fit(df_noOutliers)
m.history = m.history.append(outlierData)
df_cv = cross_validation(m, horizon = '30 days')

# Joining the out of sample predictions with the true values of the outliers for the testing data
df_cv_withOutliers = df_cv.join(df_withOutliers.set_index('ds'), lsuffix='_train', rsuffix='_test', on='ds')
outOfSampleMSE = mean_squared_error(df_cv_withOutliers["y_test"], df_cv_withOutliers["yhat"])
```
Unfortunately, this hack conflicts with other uses for model "history" and is inefficient.

A long term solution could be either to create two versions of model "history" (with the second for cross_validation) or the model could have a different way of dealing with outliers/removed data. These solutions would be useful for cross validating other data preparation techniques, not just handling outliers.

Am I missing a better work around?

**Comment by bletham** [comment]
The purpose of the cross validation is to compare forecasted values to realized values (dataframe with y and yhat) in order to make some measurement of forecast error. For this purpose, there isn't any value to making forecasts at points for which we have no realized value (y is null) since we can't compute error at that point.

In your case, you have removed outliers from the training data but still want to get their values in the cross validation. Can I ask what for? If the outlier is possibly a data error or something along those lines, then we might not want to trust its y value at all. If we trust the value but it is just atypical enough to mess up the fitting so we want to exclude it, then it would probably produce an outlier in your error distribution and I'd imagine you'd want to exclude it there too.

If you did really want to do this I think the only way would be to make some edits to the simulated historical forecast function here:
https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py#L63
Instead of using model.history, you'd want to make predictions on a dataframe that uses model.history_dates (these are all dates, including those with NaNs). Then in L105 you would need to do an outer join with the history df instead of appending, since they won't have the same dates anymore.

**Comment by CalebSturges** [comment]
I'm building a time series model to predict ad click rates. There are edge cases where the click rates are unusually high (often due to sample size issues) or unusually low (often due to not yet optimized ads). These data are valid but they create very skewed forecasts, especially when the click rate is very low and I'm feeding a logged model of the click rate to prophet. Removing them from the training data (even while still keeping them in the testing data) can improve the MSE by up to 100 fold. I don't want to remove the identified outliers from testing because:

1. I don't worry about the identified outliers creating an outlier in the out of sample error distribution because the model is trained in log space then tested on the actual click through rates so the effect on the out of sample error distribution is linear, also I weight the mean squared error by the number of ad impressions so when the error is caused by a small sample size the effect on the weighted error distribution is small.

2. I'm training hyperparameters to identify outliers if I don't include the outliers in the testing data the hyperparameters will be trained to remove the parts of the data that don't fit the model - essentially creating a degenerate model that overfits some small subset of the initial data.

I will look at model.history_dates. Thanks for the tip.

**Comment by bletham** [comment]
That's reasonable. But yeah I think the most straightforward thing would be to just do the loop yourself, as you can see it isn't that much code to do the cross validation.

**Comment by bletham** [comment]
This question seems to be resolved so I'll close the issue, but if there is more to discuss feel free to reopen.
