### ISSUE TITLE
Option to treat missing days as implicit zeros?

### ISSUE THREAD

**Issue by allswellthatsmaxwell** [facebook/prophet#438]
Hi there,

I am generating forecasts for around 3000 groups over a history of 2 years. A lot of them have a ton of days where y is 0. It is space-intensive to generate input dataframes for each date for each group for the entire two years. Is there an option to treat missing days in the input data frame as days where y = 0?

Thanks!

**Comment by bletham** [comment]
The Prophet model is a continuous-time model in which missing days would just be treated as not having a data point. In order to set y=0 on these days we would have to explicitly add the 0 value to the data, which would require the same amount of space as if you do this prior to passing the dataframe in.

At some point you must be subsetting the data by group before passing it in to Prophet. If you add the 0s at this step then it seems like it wouldn't require too much space?

**Comment by allswellthatsmaxwell** [comment]
That explanation makes sense. And yes, adding in the zeros to each small group subset at a time is a great idea, though I’m a little embarrassed to not have thought of it! Thanks!
