### ISSUE TITLE
Question on plot_weekly and plot_yearly 

### ISSUE THREAD

**Issue by nabeel-qlik** [facebook/prophet#457]
Cheers on this great forecasting tool.

I'm trying to get the weekly and yearly seasonal components as a DataFrame in the format used in the plot_components method. i.e Weekly seasonality by day of week and Yearly seasonality by day of year.

Looking through how this is done in the plot_weekly method in forecaster.py I came across this:

```
        # Compute weekly seasonality for a Sun-Sat sequence of dates.
        days = (pd.date_range(start='2017-01-01', periods=7) +
                pd.Timedelta(days=weekly_start))
        df_w = self.seasonality_plot_df(days)
        seas = self.predict_seasonal_components(df_w)
```

Similarly the plot_yearly method also uses start='2017-01-01'.

I'm wondering if the value of the start parameter effects the results of predict_seasonal_components. Doing some testing with my data I do see changes, but can't quite figure out what is going on. Appreciate any insights.

**Comment by nabeel-qlik** [comment]
I realized the changes in the numbers are small enough to be because Prophet returns slightly different forecasts at each execution. But still looking for a confirmation that using a fixed year in the 'start' parameter above doesn't have any consequences.

**Comment by bletham** [comment]
The weekly seasonality is the same for every week forever, so we can get it by just evaluating the seasonality on any one week period of timestamps. For the weekly seasonality plot we wanted to show it Sun through Sat, so we just need to evaluate the weekly seasonality part of the model on any set of dates starting on Sun and ending on Sat. Jan 1 2017 was a Sunday and so is a convenient starting point. This could be any other date that is a Sunday and it would work the same. The `weekly_start` parameter will shift the starting date, so that we might e.g. evaluate the weekly seasonality on a period Mon through Sun.

Yearly is the same thing - if we evaluate it on any 1 year range of dates, it will be the same as any other 1 year range of dates. So we use Jan 1 2017 through Jan 1 2018 for convenience. This could also have been Jan 1 2016 and it would be the same.

Does that make sense?

**Comment by nabeel-qlik** [comment]
Thanks for the explanation Ben. That makes sense.
