### ISSUE TITLE
Questions on graph forecasted and time series input

### ISSUE THREAD

**Issue by nmiskandar** [facebook/prophet#458]
Hi there, I am relatively new to data analytics/machine learning please pardon me if I am unsure with technical terms. 
I have been using prophet open source and it has been great. 
However I am quite unsure if the data that I'm using is suitable. I'm using data from an IOT Sensor that logs temperature periodically .
For example,

`df.head(5)`
Output  | Date | Value
2017-11-24 17:55:00 | 7.7
2017-11-24 17:55:00 | 7.6
2017-11-24 17:56:00 | 7.6
2017-11-24 17:56:00 | 7.5
2017-11-24 18:06:00 | 6.6

The question is does prophet support up to hours:min:secs as all of the examples that I have come across uses year-month-day
In addition, i referenced my code based on the Non - daily data documentation

`model = Prophet(changepoint_prior_scale = 0.01)`
`model.fit(df)`
`future_data = model.make_future_dataframe(periods=300, freq = 'H')`

Can I seek clarification on how do I calculate changepoint_prior_scale, periods and frequency ?
Last but not least, referencing to the image, 
![forecast](https://user-images.githubusercontent.com/26727850/36585300-45b7b22c-18b8-11e8-85f2-613a9e48b93d.png)

I am pretty sure the data that I have collected only started in November 2017 whereas the black dots = actual observation can be seen from January 2017. Is there any explanation to this?
Appreciate your help on this. Thanks in advance

**Comment by bletham** [comment]
It does seem that the dates aren't being parsed correctly since in addition to the data from Jan 2017 that shouldn't be there, there is also data for later in 2018 which I'm assuming shouldn't be there either?

The `df.head(5)` that you pasted seems to have dates in the right format - see https://github.com/facebook/prophet/blob/master/examples/example_yosemite_temps.csv for how the timestamps should be formatted.

Somewhere you turned this to have columns named ds and y, and not "Date" and "Value" before passing to prophet. Could you paste the head of the dataframe right before you pass it into `fit`?

**Comment by bletham** [comment]
and also make sure that the whole dataframe is in that timestamp format?

**Comment by nmiskandar** [comment]
Hi @bletham , yes I have done so. Please refer to the refer to the 3 images that I have screenshot from
Jupyter. According to what I have read through the web, it is a must to convert the column naming convention to ds and y if I'm not mistaken. Thank you
![screenshot1](https://user-images.githubusercontent.com/26727850/36715260-6d67f302-1bd0-11e8-86ff-7c183a8743f4.png)
![screenshot2](https://user-images.githubusercontent.com/26727850/36715265-7147720e-1bd0-11e8-8086-02431187b857.png)
![screenshot3](https://user-images.githubusercontent.com/26727850/36715283-832b31ae-1bd0-11e8-9c00-801d723c1af4.png)

**Comment by nmiskandar** [comment]
Hi @bletham, I managed to solve the issue by managing my data to be in date time prior without using python to convert. Thanks
