### ISSUE TITLE
Question about y axis units on trend plots

### ISSUE THREAD

**Issue by benjaminsingleton** [facebook/prophet#467]
How should I interpret the y axis units for the trend / yearly / weekly plots? For example, in my weekly plot, the numbers range from -0.6 to 0.0. In my trend plot, the numbers range from 1.9 to 2.1.

Any guidance is appreciated.

**Comment by zelkhama** [comment]
Prophet  uses  a  decomposable  additive  model  with  three  main components:  trend, seasonality, and holidays. So each plot represents the values corresponding to a specific component. 

For instance regarding weekly seasonality, the values of y in the plot represent the quantity to be added to or substracted from the trend on every specific day, due to weekly seasonality. So if the trend value for a date corresponding to a Monday is 1.9, and the weekly component for Monday is -0.6, then 0.6 is substructed from 1.9. 

The same process is applied to the other components, and the forecasted value is equal to the trend component +- all the seasonalities and holidays components.

**Comment by benjaminsingleton** [comment]
Appreciate the response, @zelkhama. You mentioned that "the forecasted value is equal to the trend component +- all the seasonalities and holidays components," so I'd like to clarify what you mean by that by walking through an example.

For context, my dataset contains daily counts of a certain kind of incident over a 5 year period from 2013-2017. The number of incidents each year increases steadily from 2,400 to 3,000. The trend graph y axis ranges from 1.65 - 2.0. The yearly graph y axis ranges from -0.3 to 0.2. The weekly graph y axis ranges from -0.6 - 0.2. 

The example -- on January 1, 2014, the trend graph value is 1.7, the yearly graph value is -0.1 and the weekly value (Wednesday) is 0.2. If I sum the components, the result is 1.8. Should I interpret this to mean that I expect to see 1.8 incidents on January 1, 2014? There were about 2,500 incidents in 2014 which averages out to approximately 5.5 incidents per day, which is quite far from the 1.8 incidents I predict to see by interpreting the graph, if I'm interpreting it correctly. Am I doing this right? Do I need to do any transformations to the forecasted value? Thanks again.

**Comment by zelkhama** [comment]
You can access the exact forecasted values : 
```

m = Prophet()
m.fit(data);
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)
forecast[['ds', 'yhat']]
```
I supposed you're using daily data. You can then access all the components values in forecast and compare their sum to yhat value. 

That's being said, I'm affraid I didn't get how you proceed to train your algorithm. From what I understood, you only have yearly data, and you manage to get the approximated daily value by averaging on the number of days per year. If this is the case, how do you manage to train the algorithm ? If the forecasts are done on a daily basis, has your model been trained on past daily data ? what is the structure of your training data ?

If your dataset contains "daily counts of a certain kind of incident", why don't you compare the forecasted value directly to the real one corresponding to January 1, 2014 ?

**Comment by bletham** [comment]
This seems to be resolved but if there are further questions in this thread feel free to reopen!
