### ISSUE TITLE
Unpredictable behavior with a mcmc simulation

### ISSUE THREAD

**Issue by ForrestGump** [facebook/prophet#469]
I have a problem with the mcmc simulation.

Step 1: using prophet [model without mcmc_samples](https://yadi.sk/i/y1CbL9yb3TQeoM). Everything is OK, trend is beetween upper and lower bounds.
Step 2: enable [MCMC simulations](https://yadi.sk/i/yZNePetA3TQeoQ). Now trend is lower that it's lower limit.
Step 3: changing `cap` [parametr of the model](https://yadi.sk/i/QK9PnXLv3TQeoz) (other params are the same as on the second step).

What am I missing here? (Raw data for this forecast is [here](https://yadi.sk/d/nGRhUFmf3TRx42)).

**Comment by bletham** [comment]
The "trend" that is given is the MAP estimate. With MCMC, we show posterior quantiles, but the "trend" point estimate given is still just the MAP estimate.

Generally it is possible for the MAP estimate to fall outside the 80% interval of the posterior. I think for something like the trend this could happen more easily because of how it would interact with the seasonality - I'd expect to see less of this with `yhat`. You could get raw posterior samples with `predictive_samples` function/method and then compute posterior means for trend.

For the `cap`, what value did you use here? I'd like to investigate that further.

**Comment by bletham** [comment]
I'm hoping this is resolved but if not please reopen.
