### ISSUE TITLE
How to Calculate & Plot the cross_validation Results?

### ISSUE THREAD

**Issue by saadk408** [facebook/prophet#483]
Can someone provide some example code to show how we can manipulate the "cross_validation" results to calculate the MAPE and plot it against other algorithms? Please see the attached screenshot from the Prophet paper:

![image](https://user-images.githubusercontent.com/5440123/38155950-8a7307da-342f-11e8-9980-df3b5ce42212.png)

- https://facebook.github.io/prophet/docs/diagnostics.html

**Comment by bletham** [comment]
The v0.3 branch has a utility for generating these plots (https://github.com/facebook/prophet/blob/v0.3/notebooks/diagnostics.ipynb) and will be pushed out soon. I'm going to close this issue and leave #194 as the issue for visualizing model diagnostics.

**Comment by pankaj-kvhld** [comment]
@bletham : why does cross_validation() function take model fit on the entire time series? Doesn't this lead to information leaking from the validation test to train?

**Comment by bletham** [comment]
It takes a fitted model just because that was the cleanest way to get all of the information needed to specify the model and do the cross validation. That includes things like the history, specified custom seasonalities or extra regressors. One thing to note is that for seasonalities, cross validation will use whatever seasonalities are used in the final model. Suppose that we have a five year history and yearly seasonality is set to 'auto'. With 5 years of history it will be turned on. Yearly seasonality will then be used for all of the cross validations, even any segments that have <2 years of data and so would typically have yearly seasonality turned off. Basically this makes sure the model features are fixed throughout cross validation.

This does raise a possibility of information leakage, but inside cross validation we use a newly instantiated model that just copies over the model fit settings, from here: https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py#L126 . We've been careful there to be sure that nothing is being leaked.

**Comment by haseebmahmud** [comment]
@bletham The OP asked for a plot of cross validation results (MAPE in the example he posted) from prophet against the other algorithms. From v0.3 we have the possibility to plot the cross validation results of prophet. I am wondering if there is any plan to include the cross validation results from other algorithms/methodologies (e.g. ARIMA & co.) in future releases.

**Comment by bletham** [comment]
We don't intend to add additional methods to the package. It's really an implementation of this particular model and not designed as a platform for time series forecasting methods. (Something that would be valuable but not on our roadmap).
