### ISSUE TITLE
cross_validation hangs when dataset has high number of missing dates 

### ISSUE THREAD

**Issue by roumail** [facebook/prophet#513]
cross_validation hangs when I pass the (attached) object returned by fit.prophet

The data contains ALOT of missing dates and I would expect cross_validation to return an error. 

```
[1] "2010-12-27 GMT" "2011-03-28 GMT" "2011-06-27 GMT" "2011-09-26 GMT" "2011-12-26 GMT"
 [6] "2012-01-02 GMT" "2012-03-26 GMT" "2012-06-25 GMT" "2012-09-24 GMT" "2013-01-07 GMT"
[11] "2013-04-01 GMT" "2013-07-01 GMT" "2013-10-07 GMT" "2013-12-02 GMT" "2014-01-06 GMT"
[16] "2014-04-07 GMT" "2014-07-07 GMT" "2014-10-06 GMT" "2015-04-06 GMT" "2015-07-06 GMT"
[21] "2015-10-05 GMT" "2016-01-04 GMT" "2016-03-28 GMT" "2016-06-27 GMT" "2016-09-26 GMT"
[26] "2016-12-26 GMT" "2017-03-27 GMT" "2017-06-26 GMT" "2017-09-25 GMT" "2017-12-25 GMT

# read in the RDS file in attachment
fit <- readRDS(..)

prophet::cross_validation(model = fit, 
                          period = 92, horizon = 92, units = "days",
                          initial = 700)
```
[faulty_proph_fit.zip](https://github.com/facebook/prophet/files/1978911/faulty_proph_fit.zip)

If I pass a much lower value for initial, such as 10, I receive a helpful error message as expected

```
prophet::cross_validation(model = fit, 
                          period = 92, horizon = 92, units = "days",
                          initial = 20)
Error in fit.prophet(m, history.c) : 
  Dataframe has less than 2 non-NA rows.
In addition: Warning message:
In generate_cutoffs(df, horizon, k, period) :
  Not enough data for requested number of cutoffs! Using 24
```

**Comment by roumail** [comment]
I tried using R.utils::withTimeout to raise a timeout exception when prophet::cross_validation hangs but that doesn't seem to work either.

**Comment by bletham** [comment]
Thanks for raising this issue. I'm able to replicate the hang, it seems to be happening after all of the model fitting is done. I'm not exactly sure what is causing it, but it does seem to be fixed in the current development version. That is, in the current development version I can run
```
library(prophet)
fit <- readRDS('faulty_proph_fit.RDS')
prophet::cross_validation(model = fit, 
                          period = 92, horizon = 92, units = "days",
                          initial = 700)
```
and it finishes successfully. You can install the development version with
```
devtools::install_github('facebook/prophet', subdir='R', ref='v0.3')
```
I'm about halfway finished with adding multiplicative seasonality and then we'll push it out to CRAN once that is done.

In the 2nd setting (initial=20), the error for dataframe less than 2 rows needs to be handled better. What's happening here is that the initial is so small that it doesn't contain the 2 data points required to fit the model.

**Comment by bletham** [comment]
v0.3 pushed so this should now be fixed. Also raises a more meaningful error if there are <2 data points in the initial period.
