### ISSUE TITLE
When linear regression is used or logistic regression

### ISSUE THREAD

**Issue by mengdodo** [facebook/prophet#514]
i am a new user, i dont kown how to choose?

date for example:

ds	                 y
2017-10-15	2912.444895
2017-10-16	2943.715442
2017-10-17	2981.981261
2017-10-18	2988.512413
2017-10-19	3082.750482

**Comment by bletham** [comment]
The main difference is that the logistic trend supports (and requires) a saturation level. A nice example of this is in https://facebook.github.io/prophet/docs/saturating_forecasts.html . (There is also a lower saturation level which defaults to 0 but can be adjusted to something different too). If you believe your forecast should saturate at some value that you know, then you can use the logistic to impose that. Otherwise the linear is a reasonable default that tends to work well.
