### ISSUE TITLE
Random order of seasonality charts

### ISSUE THREAD

**Issue by dfaustryjak** [facebook/prophet#519]
Hello

I have really strange situaation. Sometimes when i generating seasonality charts like trend, weekly, yearly. I suddently i obtain order like -> trend, yearly, weekly. Only chart nr 2 and 3 can be revert.  Is that possible to get chart by name ?

**Comment by bletham** [comment]
Currently the seasonal components are pulled from the keys of `m.seasonalities`, which is a dictionary and so inherently unordered (https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L1299).

It does seem better to sort the seasonalities by name before adding them to that list so that we can guarantee the order they will appear in.

In the meantime, you could either manually construct the plot by following the code in the link above (almost everything is delegated to subfunctions so there really isn't that much code there), or you could figure out which axis is which with something like
```
if ax.get_ylabel() == 'weekly':
...
```

**Comment by bletham** [comment]
This is done in https://github.com/facebook/prophet/commit/635ae5a1a6853619a6e4f4e05702c4f7a54e8795

**Comment by bletham** [comment]
Pushed to PyPI.
