### ISSUE TITLE
Error after import

### ISSUE THREAD

**Issue by Jodahr** [facebook/prophet#530]
Hey,

I have successfully installed fbprophet with python3 by using the command
`sudo pip3 install .` inside the fbprophet directory.

After importing the module I get the following error:

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fbprophet import Prophet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PNW/z001291/fbprophet-0.2.1/fbprophet/__init__.py", line 8, in <module>
    from fbprophet.forecaster import Prophet
  File "/home/PNW/z001291/fbprophet-0.2.1/fbprophet/forecaster.py", line 28, in <module>
    from fbprophet.models import prophet_stan_models
  File "/home/PNW/z001291/fbprophet-0.2.1/fbprophet/models.py", line 35, in <module>
    'linear': get_prophet_stan_model('linear'),
  File "/home/PNW/z001291/fbprophet-0.2.1/fbprophet/models.py", line 30, in get_prophet_stan_model
    with open(model_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/PNW/z001291/fbprophet-0.2.1/fbprophet/stan_models/linear_growth.pkl'

Is this a bug in the modul or a compialtion bug?

Cheers,

Marcel

**Comment by bletham** [comment]
It looks like you have downloaded the source code and started the python process inside that directory. When you `import fbprophet` it is importing the directory fbprophet (since it is in your current directory) rather than importing from the installed package fbprophet. If you start python from a directory that doesn't have fbprophet as a subdirectory it should then load the package and work correctly.

**Comment by bletham** [comment]
I'm hoping this was resolved but if not please reopen.
