### ISSUE TITLE
Log transformation

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#545]
Hello,

Can we apply log transformation and still view the np.exp(y) version of the forecasted variable y in plots?

Currently when I apply log transformation I only can view the log transformed y variable; while I am looking at the plots. I tried using the "yhat" and making a plot outside of the tool: but it would be great to be able to plot it within the tool.

Deniz

**Comment by bletham** [comment]
A couple of people asked for this in #492. My impression is that historically the main use of log transforming has been to get multiplicative seasonality. Since that is now (subject to the impending push) supported natively without a log transform, it seemed less critical so I closed the issue out. If you think there are other uses for this go ahead and re-open #492. Maybe something that would provide the needed functionality without requiring changes in too many places would be to require the user to do the log-transform themselves outside of Prophet (as is currently the case), but then have an option just to `Prophet.plot` to exponentiate the figure. The table produced by `predict` would still be in the log-transformed space, but the exponentiated figure would be easy to produce. Anyway if that sounds useful go ahead and re-open #492 and we can discuss further there.
