### ISSUE TITLE
Order of external regressor application

### ISSUE THREAD

**Issue by deniznoah** [facebook/prophet#550]
Hello,

Is there a certain way of external regressor application?

For example if we have an additive external regressor A and a multiplicative external regressor B.

Can I get one of the regressors to apply on top of the other external regressor?

For example if seasonality has a %150 impact in June, and promotion has a +10000 sales impact would I be able to make the model work in such a way that multiplies %150 with the promotion upside of 10000 as well?

Thank you,
Deniz

**Comment by bletham** [comment]
Multiplicative regressors / seasonalities are applied to the trend, not to eachother. I think to get this sort of effect you'd have to create a set of new regressors that are the interaction between the seasonality and the promition, e.g. "promotion_and_june" would then have an effect of +5000, since it would cover that extra bump from the seasonality to the promotion. Having interactions between seasonalities and extra regressors is on the roadmap in #538.

**Comment by deniznoah** [comment]
Does this mean that if you have multiple multiplicative seasonalities, they would all be multiplied with the trend "separately" and then added to the trend to reach forecast and not be multiplied one after the other in trend x b x c ?

**Comment by bletham** [comment]
It would be `trend * (1 + b + c)` and not `trend * b * c`.

So if the plot shows +20% weekly effect and +30% yearly effect, that means 20% and 30% of the baseline trend, and the final yhat will be +50% on the baseline trend.
