### ISSUE TITLE
Unable to forecast 0 values

### ISSUE THREAD

**Issue by lemondrop99** [facebook/prophet#572]
I have a data set where I have 0 volume every Sundays.  I can't get prophet to forecast a 0 value, however.  Is there a function I can use to do this without just ignoring values forecasted for the Sunday?

**Comment by gulipad** [comment]
Same problem here!

**Comment by bletham** [comment]
If you have a multiplicative weekly seasonality, I would think it should fit the correct multiplier of 0 (rather, -100%). Does this work for your time series?

**Comment by gulipad** [comment]
@bletham , it does not seem to work for me, but maybe I am doing something wrong (I am a beginner). I am calling `m = Prophet(weekly_seasonality=True, seasonality_mode = 'multiplicative')
`

**Comment by bletham** [comment]
Having had a chance to try this out, with multiplicative seasonality, when there is a 0 for every instance of a day of the week, the weekly seasonality will learn a -100% effect. If weekly is the only seasonality then that will give 0s for the forecast on that day of the week. However if there are other seasonalities (like yearly), then that can still push the forecast to be different than 0. This is because the seasonalities are each multiplicative on the trend, but then those multiplicative effects are added.

If you know that the value is always 0 on a particular day of the week, the best thing to do is probably to just remove that day of the week from your training data, and then replace its forecasted value with 0.

**Comment by nehcgnak** [comment]
> Having had a chance to try this out, with multiplicative seasonality, when there is a 0 for every instance of a day of the week, the weekly seasonality will learn a -100% effect. If weekly is the only seasonality then that will give 0s for the forecast on that day of the week. However if there are other seasonalities (like yearly), then that can still push the forecast to be different than 0. This is because the seasonalities are each multiplicative on the trend, but then those multiplicative effects are added.
> 
> If you know that the value is always 0 on a particular day of the week, the best thing to do is probably to just remove that day of the week from your training data, and then replace its forecasted value with 0.

My weekend values are all zeros in my training dataset. I only have weekly seasonality set to True and the mode is multiplicative. However, I still get non-zeros values in the weekend, although the values is around 10% of the weekday forecast values. I am not sure why's that.
