### ISSUE TITLE
Extract Prediction Error / Confidence?

### ISSUE THREAD

**Issue by drcrook1** [facebook/prophet#579]
Hey Folks,

This could be a question or enhancement.  I want to know how much error is associated with my various trend lines and where that came from.  I am creating forecasts across many assets and essentially I want to know what my lowest risk predictions are vs my highest risk predictions where I project upwards of 1 to 2 years into the future using approximately 15 years of historical information. 

Am I to assume that the magnitude of the delta between my upper and lower is my absolute error for that day?  Do we have any insights as to where that came from or how to control that?

**Comment by bletham** [comment]
The `yhat_upper` and `yhat_lower` give an 80% credible interval for the value at that point, so 80% of the time you would expect that the observed value to fall within that interval (if the model were correct). You can change that 80% to something else with the `interval_width` parameter - see https://facebook.github.io/prophet/docs/uncertainty_intervals.html .

Now, if you look back at the history the `yhat_lower` and `yhat_upper` may not actually contain the observed data 80% of the time. This is because the model is certainly not exactly correct (we just hope it to be close enough to be useful). For instance, the model assumes Gaussian noise, and the actual noise variance may not be which would cause the coverage to be different than 80%. But generally, a wider gap between `yhat_lower` and `yhat_upper` means greater uncertainty about the forecast.

Does that answer the question?
