### ISSUE TITLE
How to add Quarterly Seasonality?

### ISSUE THREAD

**Issue by andymancodes** [facebook/prophet#596]
Hi,

In my data, I am pretty sure there is a quarterly seasonality besides yearly.

How do I add quarterly seasonality in Prophet?

Like, monthly seasonality I could add: 

m.add_seasonality(name='monthly', period=30, fourier_order=5) # can do for daily, weekly & monthly seasonalities

**Comment by bletham** [comment]
You can use `add_seasonality` with period set to the number of days in a quarter (365.25/4 = 91.3125). I'd try with the fourier order set to 10 (the default for yearly seasonality). If you have very strong effects on the first or last day of the quarter, you may also want to set a holiday for first-day-of-quarter and one for last-day-of-quarter, since the seasonality may be too smooth to get very strong effects on a single day.
