### ISSUE TITLE
The prophet y needs to be normalized?

### ISSUE THREAD

**Issue by gongshaojie12** [facebook/prophet#627]
Now I use prophet to predict a time series model similar to the Dow Jones index.The y need to be normalized? my data like this:
Date	                     y
2018/7/27	2879.69
2018/7/26	2905.79
2018/7/25	2911.45
2018/7/24	2862.27
2018/7/23	2815.2
2018/7/20	2769.75
2018/7/19	2791.02
2018/7/18	2801.78
2018/7/17	2806.89
I adjusted the following parameters,
changepoint_prior_scale = 0.005
weekly_seasonality = False
daily_seasonality = False
monthly_seasonality = False
yearly_seasonality = False
changepoints = None
seasonality_mode = 'additive'
seasonality_prior_scale = 10
But I got a very bad result，like this:
![default](https://user-images.githubusercontent.com/6407116/43397428-67691aa0-9437-11e8-9d90-e3457f0a40e5.png)
How can I solve this problem?Need to normalize y?please help me,Thanks

**Comment by bletham** [comment]
No, `y` does not need to be normalized, Prophet will actually internally scale `y` before fitting the model.

This is a difficult time series for Prophet and not one that I would expect it to do especially well on, since it does not really have the types of features that Prophet is modeling. In particular, there isn't any seasonality to model (you are turning it off anyway) or holiday effects. Without seasonality and holiday effects, Prophet is just a piecewise linear regression, which is what you are seeing here. I don't think there is anything better that can be done here with Prophet.

(Stock-like data is often not a good fit for Prophet because they usually do not have the same seasonal/holiday structure as a typical business time series that Prophet was designed for).
