### ISSUE TITLE
Retrain an existing model

### ISSUE THREAD

**Issue by 4n4nd** [facebook/prophet#630]
Is there a way to store a model and retrain it every day with new daily data?
I can pickle a model and load it, but I don't know how to retrain it with new data.

I think this is it #46

**Comment by bletham** [comment]
#46 is the relevant issue, and unfortunately still no progress on it. There's some somewhat complicated logic needed for adding changepoints and making sure internal data scaling is handled appropriately, and since the cost of fitting from scratch is usually relatively small it hasn't been as high priority as the other new features we've been working on.

**Comment by 4n4nd** [comment]
I will try to implement something else.
Thanks anyways for working on this model

**Comment by kr1stjans** [comment]
Do you see any problems if I save initial trained model params and then pass them to fit function?

Now self.params is always initialized with stan_init(). If I replace it with existing params, will everything else work out of the box? The goal is to speed up convergence.

**Comment by vlsd** [comment]
@bletham I found your suggestions here very useful. However, I'm having trouble with the practical implementation of the following:
>Initialize 2 and 4 to their fitted values from before, and initialize 6 and 8 to zero (as is currently done by default).

It seems like all this is done deep in the guts of the `fit` function and in order to do this I would have to re-implement that function. Does this sound correct? It's not a big deal if that's the case, just wondering if there's an already implemented mechanism that can be re-purposed for this, so I don't duplicate effort.

**Comment by bletham** [comment]
@vlsd that's right, it's here:
https://github.com/facebook/prophet/blob/d9bea6196981bfcedae40525e702d424d26e7cd0/python/fbprophet/forecaster.py#L1123-L1129

So instead of initializing things to zeros, you'd want to initialize to the previous values (except for the adjustment on `delta` to account for the possibly changed number of changepoints). This will require changing the fit function, but I think it could be a small change (for instance, add a kwarg for optionally passing in `stan_init` directly).

**Comment by vlsd** [comment]
Thanks @bletham! I've actually passed the params to the `init` kwarg of the `fit` function, which seems to flow directly to the stan backend's `fit` function as an initial guess and so far this seems to work!

**Comment by GinoWoz1** [comment]
@vlsd  how are you able to pass the init kwargs via python prophet? I had issues with this (says kwargs not recognized for pystan.Stanmodel) and am interested in your solution here.

**Comment by vlsd** [comment]
> @vlsd how are you able to pass the init kwargs via python prophet? I had issues with this (says kwargs not recognized for pystan.Stanmodel) and am interested in your solution here.

I don't have direct access to the code right now, but I vaguely remember reading the pystan code to see what arguments it expects and renaming the prophet variables as needed before passing them as kwargs. If I manage to find the code I'll post a snippet.

**Comment by bletham** [comment]
There's an example on how to do this now in the documentation: https://facebook.github.io/prophet/docs/additional_topics.html#updating-fitted-models

**Comment by GinoWoz1** [comment]
Per https://discourse.mc-stan.org/t/different-outputs-in-rstan-vs-pystan/211/27 I have to use extra_compile_args and when I input it in the fit the command is not recognized. Rstan and Pystan have different outputs and need to update this. I see **kwargs passes the arguments to sampling and optimizing but I don't see where I can input :extra_compile_args=['-O3', "-march=native", "-mtune=native"]. Any idea ?

> There's an example on how to do this now in the documentation: https://facebook.github.io/prophet/docs/additional_topics.html#updating-fitted-models

**Comment by bletham** [comment]
Model compilation happens during install. If you need to change that, then you'd want to download the source from here and install it that way. These are the default makevars in R: https://github.com/facebook/prophet/blob/master/R/src/Makevars and in Py the building happens here: https://github.com/facebook/prophet/blob/20f590b7263b540eb5e7a116e03360066c58de4d/python/fbprophet/models.py#L218-L227
