### ISSUE TITLE
variation after refit

### ISSUE THREAD

**Issue by rds99** [facebook/prophet#632]
Hi
I have data sampled every 5 seconds.
I fit prophet to data from time 10.00.00 to 10.15.00 and then measure the difference of yhat and y for data point at 10.10.30
Then I refit with additional one minute of data 10.00.00 to 10.16.00 and record the difference of yhat and y for the same point 10.10.30
Repeating this process for 125 times, each time providing additional one minute of data, I get 125 sets of y - yhat for data point at 10.10.30
I was expecting it to swing initially but then settle down and have lesser and lesser difference with each iteration. however what i observed is quite different, the difference is oscillating, initially with a higher frequency and then with a lower one, I have attached the plot of the diff.

Shouldn't the diff be close to zero after a few iterations?
Can I make some inference about the time series with the above observation?

Thanks
[Rplot.pdf](https://github.com/facebook/prophet/files/2252697/Rplot.pdf)

**Comment by bletham** [comment]
I wonder if there might be some seasonality that is not being captured by the model. Could you post a plot of the actual model fit/forecast on one of these tests? (like with `plot(m, forecast)`).

**Comment by rds99** [comment]
Hi
Find enclosed the plot, also included are the model output data file. The data is collected ever 5 seconds and I have made seasonality off for the fit.

The parameters used are
linear
yearly.seasonality  off
weekly.seasonality off
n.changepoints  10
changepoint.prior.scale .15
changepoint range .96
holiday.prior scale 0
mcmc.samples 0
interval.width .85
periods 20
frequency 1 second
[sample-prophet-github-issues.pdf](https://github.com/facebook/prophet/files/2269408/sample-prophet-github-issues.pdf)
[forecast_data-github-issues.xlsx](https://github.com/facebook/prophet/files/2269419/forecast_data-github-issues.xlsx)




Thanks

**Comment by bletham** [comment]
I'm not sure there's too much more that can be done here. There is pretty high variability in the time series that does not seem to be due to any seasonality / modelable factor. For instance, compare the first segment to the last in that plot: the first segment has a fairly long flat region, while the last segment is oscillating. Unless there is some way for the model to know that there should be oscillations (like them corresponding to a defined seasonality) then there won't be any way for it to capture any of that variability. This is reflected in the uncertainty intervals yhat_lower and yhat_upper, which do a pretty good job of covering all of the variability and treating it as noise.
