### ISSUE TITLE
Constraining the Time Series to be Positive 

### ISSUE THREAD

**Issue by vruvora** [facebook/prophet#635]
Are there ways we can constrain the time series to be positive such that it only learns positive values? Currently positive samples negatively on time series that should be constrained to be >= 0.

**Comment by luke14free** [comment]
You could try sampling your y from a left-0 truncated Normal distribution by changing the code here: https://github.com/facebook/prophet/blob/master/python/stan/unix/prophet.stan#L112 
Although this might not be the best solution as you would be placing a lot of probability on 0 (depending on your time series).

Another idea would be to change the stan code to use exponentials instead of laplacians to generate the weights for the model (and half-normals instead of normals). This would force GAM coefficients to be >=0 (so if your regressors are strictly positive you will achieve positive results). Yet, in theory seasonality could still make your time series dip below 0 (depending on your data).

**Comment by vruvora** [comment]
Hmm that requires having our own version of Prophet running.

**Comment by vhpietil** [comment]
How about taking log transformation of you data and then exp of your predictions. Those values would be positive for sure. Not sure if all intervals would behave as expected but yhat values might be useful.
