### ISSUE TITLE
Cross-Validation with hourly, monthly, yearly data

### ISSUE THREAD

**Issue by adamkov86** [facebook/prophet#650]
Dear  Ben and developer Guys,

I am refering to one of your post about cross-validation with daily data:
https://github.com/facebook/prophet/issues/483

**How can i run cross-validation on hourly, monthly or yearly data?
I am using this code, but when i change the  days'.format to month.format or year.format, it does not work.
_# Compute cross-validation y and yhat for the range of horizons in the figure
df_cv = pd.DataFrame()
for h in [30, 60, 90, 120, 150, 180]:
    df_cv_h = cross_validation(m, horizon='{} days'.format(h), period='100 days', initial='730 days')
    df_cv_h['horizon'] = h
    df_cv = pd.concat((df_cv, df_cv_h))_

Thanks!
Adam

**Comment by joaocunha1991** [comment]
I might be having the same problem actually (in R). When I run cross_validation with 'months' as units it gives the error:

**Error in as.difftime(horizon, units = units) : invalid units specified**

The documentation of as.difftime doesn't seem to refer to units = 'months' as an option but i'm not sure

**Comment by bletham** [comment]
In Python, the date string has to be compatible with `pd.Timedelta` (which is what is used to parse it). It only supports days and smaller (https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.Timedelta.html), so for months or years you'd have to convert it to days first.

In R, it uses `as.difftime` (https://stat.ethz.ch/R-manual/R-devel/library/base/html/difftime.html) which also does not support 'months'. As described on that documentation page, 'months' is not specific enough because a month could be anywhere from 28 to 31 days.

See #586 for a discussion of possibly using the `mondate` package in R in the future to get a `years` unit.

**Comment by bletham** [comment]
I'm going to close this and leave #586 as the open issue for monthly cross-validation.
