### ISSUE TITLE
Setting priority / weight of the external regressors

### ISSUE THREAD

**Issue by ystoyanov** [facebook/prophet#655]
Hello, 

I am currently using the model, and i have the following issue.

I have holidays that i can insert in the model, and it works fine. However, once i also set yearly seasonality to True, then the positive effect of holidays is taken by the yearly seasonality, and some of the holidays get negative contribution which is not right.

Is there a way to give priority to the holidays, and leave the yearly seasonality to have a smaller share?

I guess it is a special case of assigning priority across external regressors, and in this case the holidays and yearly seasonality are the external regressors.

Regards, 
Yuliyan

**Comment by bletham** [comment]
The `seasonality.prior.scale` and `holidays.prior.scale` are the parameters that specify the amount of regularization for seasonality and holidays respectively (those are the R names, the Python names are the same but with underscores instead of periods). By default they are both 10, larger means more flexibility. If you increase `holidays.prior.scale` and decrease `seasonality.prior.scale` the model should prefer to use the holiday regressor to fit the holiday effect rather than seasonality.

One thing to check though is if perhaps there are positive effects on the days around the holiday, which might cause the model to try and fit it with seasonality. If that is the case then you'd need to specify the neighboring days as holidays too.

There can genreally be multicolinearity in the model which may make it difficult to interpret individual parameters. Another thing you could do in this situation (that would not require changing prior scales or creating additional holidays) would be to just use yearly_seasonality+holiday_effect as the effect for the holiday. You can pull both of these as columns out of the forecast dataframe returned by `predict`.

**Comment by ystoyanov** [comment]
Thank you!

For other people who may be facing the same issue in the future: the prior scale parameter (of the holidays and seasonality) is also available for external regressors. You set it in the line that you add the regressors. In Python, you do it like this:
m.add_regressor('x', prior_scale=0.05)
