### ISSUE TITLE
Synthetic series with weekly seasonality with poor prediction

### ISSUE THREAD

**Issue by ispmarin** [facebook/prophet#661]
I'm working with a few examples using synthetic data to better understand the behavior of prophet, and came up with a sine series with weekly frequency:

```
idx = pd.date_range('2016-01-01','2017-06-04', freq='D')
phase=0
len_idx = len(idx)
points = np.arange(0, len_idx)
df_week = pd.DataFrame({'y':np.sin(points*2*np.pi/24 + phase)+ points/100}, index=idx)
df_week['ds'] = df_week.index
df_week.y.plot()
```
![image](https://user-images.githubusercontent.com/12247/44594415-82714c00-a79c-11e8-905c-e42ad138e53a.png)

And tried to create a forecast with prophet:

```
mdl_week = Prophet(weekly_seasonality=30)
#mdl_week.add_seasonality(name='monthly', period=60, fourier_order=5)
mdl_week.fit(df_week)
future = mdl_week.make_future_dataframe(periods=3, freq='D')
forecast_week = mdl_week.predict(future)
forecast_week.index = pd.to_datetime(forecast_week.ds)
fig, ax = plt.subplots()
forecast_week.yhat.plot(ax=ax)
df_week.y.plot(ax=ax)
_ = mdl_week.plot_components(forecast_week)
```
![image](https://user-images.githubusercontent.com/12247/44594443-974ddf80-a79c-11e8-95e9-ee690595dc88.png)

The results are not expected. I tried changing some parameters, like adding seasonalities and changing other parameters, to no avail. Any ideas on how to adjust this forecast?

**Comment by bletham** [comment]
In this case the seasonality isn't quite weekly - it's actually 24 days.

So, weekly seasonality can't capture it, and here the yearly seasonality is turned off by default because there is <2 years of history, and so there is nothing to capture this cycle.

The best thing to do is to add a seasonality that actually matches the period of this seasonality. This does the trick:
```
mdl_week.add_seasonality(name='three_weeks', period=24, fourier_order=5)
```

If you tried to grab this by turning on yearly seasonality (`mdl_week = Prophet(yearly_seasonality=True)`), it still won't work because the frequency is too high for the default yearly seasonality. You have to increase the Fourier order of the yearly seasonality and then it gives a good fit (`mdl_week = Prophet(yearly_seasonality=20)`).
