### ISSUE TITLE
Broken Release - v0.3?

### ISSUE THREAD

**Issue by Adorra** [facebook/prophet#663]
It appears that v0.3 wasn't released from master?  

https://github.com/facebook/prophet/compare/v0.3...master

In particular for my usecase the bug identified in #351 was fixed by 5d453c1d05d356e08b5dee19dcce89cd57b53f4a but this commit isn't in the 0.3 release despite having been added in Nov 2017 as can be seen from the diff above.

**Comment by dhirschfeld** [comment]
If I look at the revision graph it looks like v0.3 was branched off v0.2 rather than master:

![image](https://user-images.githubusercontent.com/881019/44641810-49d7a980-aa0c-11e8-8483-839ef8bd9008.png)

**Comment by dhirschfeld** [comment]
...all of which is to say it would be great to have a new release from the current master!

**Comment by bletham** [comment]
Can you paste some code that produces the issue? It should be fixed.

The fix is here:
https://github.com/facebook/prophet/blob/master/R/R/diagnostics.R#L110
and tested
https://github.com/facebook/prophet/blob/master/R/tests/testthat/test_diagnostics.R#L54

and when I do
```
library(prophet)
cross_validation
```
I can see the fixed code in my current version from CRAN.

(Note that after the commit that you reference, the `simulated_historical_forecasts` function was deprecated and that logic was moved into `cross_validation`).

**Comment by bletham** [comment]
I'm assuming this is due to an old installed version, but if anyone is still having this issue on the latest package please re-open this issue.
