### ISSUE TITLE
I get opposite trend and yearly seasonality for 1yr of data

### ISSUE THREAD

**Issue by ystoyanov** [facebook/prophet#673]
Hi, I fit the model on 1 year of data, and i got a strange output in the diagnostics. A screenshot is below. It is strange to interpret the result, i think. There seems to be a trend in the yearly seasonality that can be assigned to, and cancel some of the trend in the trend component.
Again, the model was fit on one year of data, so the horizontal axis in this case is the same.

![q](https://user-images.githubusercontent.com/36866434/44897642-a4b71c80-acfc-11e8-82f6-4eac0b55c6dc.png)

**Comment by bletham** [comment]
This does seem pathological. By default yearly seasonality is turned off for <2 years because otherwise yearly seasonality can easily get mixed up with trend effects. In this particular case, if you reduce the `seasonality_prior_scale` parameter from its default of 10 to something smaller like 1 or 0.1 does that fix the issue? The default value puts very little regularization on the seasonalities, and there is no regularization on the slope of the trend (only on changes in the trend slope).

**Comment by ystoyanov** [comment]
Thank you Ben. I am aware that I am supposed to use more than 1 year of data, and ideally more with the model.  Still, I just wanted to share this.
I tried many set-ups in my experiments, so i don't remember the data i used to get this one. I however believe that your suggestion will solve it.
