### ISSUE TITLE
Get volatile uncertainty interval width for history

### ISSUE THREAD

**Issue by jeesim2** [facebook/prophet#678]
If I predict include_history then plot past dates, 
Uncertainty interval widths are all same across all past dates.

### Prediction uncertainty interval including_future
![image](https://user-images.githubusercontent.com/1100831/45144606-9172e800-b1f9-11e8-8c3b-973a0f3f6a9b.png)

### What about if prediction uncertainty interval changes
Is it possible to get changing interval width according to the changing Volatility?
like RED bar height.
![image](https://user-images.githubusercontent.com/1100831/45144961-7ce31f80-b1fa-11e8-9437-1a0a068c6409.png)

### Another example
from elasticsearch machine learning.
![image](https://user-images.githubusercontent.com/1100831/45145166-f975fe00-b1fa-11e8-9829-c69a1dbd0508.png)

What can I do to get the flexible uncertainty interval width for the include_history prediction?

**Comment by vruvora** [comment]
Are you sampling or solving with LBFGS?

**Comment by jeesim2** [comment]
@vruvora I just put the daily metric to prophet then customized visualization.

**Comment by bletham** [comment]
The uncertainty in the historical model fit comes from two sources: a constant noise term, and parameter uncertainty.

The constant noise term is obviously constant, and that's what you're seeing here. It seems that the bump towards the front is being mostly fit by the noise term, since they happen too quickly to be picked up as trend changes and thus be fit by the trend part of the model. Increasing the number of changepoints would possibly allow the trend to fit those bumps instead of the noise term.

Parameter uncertainty would give you the higher uncertainty around the places where the trend is changing. Parameter uncertainty isn't estimated by default, but will be if you do MCMC. Set the `mcmc_samples` to something like 500 or so and you will see uncertainty in the trend component when you do `m.plot_components(forecast)`. Note however that this will take much longer to fit.
