### ISSUE TITLE
plot_forecast_component errors [R]

### ISSUE THREAD

**Issue by jdumas-fastly** [facebook/prophet#682]
```r
> plot_forecast_component(m, forecast)
Error in paste0(name, "_lower") : 
  argument "name" is missing, with no default
```

if I do specify the `name` argument (_String name of the component to plot (column of fcst)._) I get a singular plot.

`devtools::session_info()`:

```
Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-09-13                  

Packages -------------------------------------------------------------------------------------------------------------
 package      * version   date       source  
prophet      * 0.3.0.1   2018-06-15 CRAN (R 3.5.0) 
```

**Comment by bletham** [comment]
What you are describing sounds like the intended behavior. This particular function (https://github.com/facebook/prophet/blob/master/R/R/plot.R#L161) is meant to plot a single component of the forecast, which is why you get just one plot for whichever one component you specify. If you're looking for the plot of all of the model components, that one is
```
prophet_plot_components(m, forecast)
```
as shown in the example at the bottom of https://facebook.github.io/prophet/docs/quick_start.html

**Comment by jdumas-fastly** [comment]
Wow thanks for the feedback, such a silly miss-read on my part. 

It'd be an improvement for the [documentation](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html) site just to indicate the differences with the singular/plural function also exists for the R package as the note on python is explicit.

**Comment by bletham** [comment]
Sure, that makes sense, we'll see that that is clarified.
