### ISSUE TITLE
expecting lower and upper bounds on yhat to grow over time

### ISSUE THREAD

**Issue by tinyneutrino** [facebook/prophet#740]
Hello, 

I would expect the yhat lower/upper values to increase with the forecasting horizon, e.g. larger uncertainty in forecasting further out in time. However, the spread seem equidistant, like so:
![image](https://user-images.githubusercontent.com/21336267/48545744-ed777e00-e8c6-11e8-92f2-3abc34acb5f5.png)

I've seen similar behaviour to this in examples online, eg. in this figure 
![image](https://user-images.githubusercontent.com/21336267/48545889-3b8c8180-e8c7-11e8-8d61-c61f49728a72.png)

from [https://towardsdatascience.com/an-end-to-end-project-on-time-series-analysis-and-forecasting-with-python-4835e6bf050b](here)

And I see the same behaviour with trying out different horizons (e.g. one year forward from 3 years of data).

Is this expected behaviour?

How would one account for a (what I guess is a rightful assumption) increase in uncertainty with larger forecasting horizons?

**Comment by tinyneutrino** [comment]
ah, taking the "span": yhat_upper - yhat_lower does show this grows for each step in the forecast.

![image](https://user-images.githubusercontent.com/21336267/48553057-c6c34280-e8da-11e8-9bc7-e7011ce5212d.png)

only the values for the first year ahead had minimal growth. So I solved my own question. Thanks for reading.

**Comment by bletham** [comment]
Uncertainty that grows as we get further into the future comes from uncertainty in the future trend. You can visualize this if you plot the components, like at the bottom of https://facebook.github.io/prophet/docs/quick_start.html#r-api . You will see a very narrow band of uncertainty in the trend component.

The reason it is so narrow is because of how future trend uncertainty is estimated (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend). Basically, we assume the future will see the amount of trend changes as the past. In this particular time series, the trend is quite constant and so the trend uncertainty is very low.
