### ISSUE TITLE
FB prophet limits 

### ISSUE THREAD

**Issue by bthornhill417** [facebook/prophet#747]
is there a better way to set limits on a fbprophet forecasting besides the 'interval width' function?

**Comment by bletham** [comment]
The interval width just sets the quantile used for the uncertainty estimates. If you want to put limits on the actual forecast, you can specify both an upper and lower limit when you use the logistic growth trend: https://facebook.github.io/prophet/docs/saturating_forecasts.html

This will ensure that the trend stays within those limits. The overall forecast `yhat` could still pass outside the limits due to seasonality; for now the best that could be done for that would be to clip the forecast at the limits post-hoc.

**Comment by bthornhill417** [comment]
I think my question more has to do with why the upper limit on prophet gets so extreme like this and if there is anyway to manipulate it?

![prophet limit](https://user-images.githubusercontent.com/45239786/49100920-a1b7c380-f23a-11e8-808c-323e73b56302.png)

**Comment by bthornhill417** [comment]
I am trying to forecast a date so I need the limits and the prediction line to converge to 0

**Comment by bletham** [comment]
If you mean that you need the forecast to saturate at y=0, that can be done by using the logistic growth function, as described in https://facebook.github.io/prophet/docs/saturating_forecasts.html#saturating-minimum

In this case, there are several trend changes in the history. The uncertainty intervals are computed by projecting those trend changes forward, as described in https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend . With only 2.5 months of history, there will certainly be high uncertainty in an 8 month forecast. The way Prophet uncertainty is estimated, this means the future 8 months can see >3x the amount of trend change seen in the history (because the future is >3x longer than the history).
