### ISSUE TITLE
How to minimize error in hourly time series data ?

### ISSUE THREAD

**Issue by pranjol2017** [facebook/prophet#778]

**Comment by bletham** [comment]
If there is a specific issue with the forecast, posting a plot of it would be helpful, otherwise the documentation provide some tips for getting the most out of the model.

**Comment by pranjol2017** [comment]
I am currently doing a project with hourly data of two years. 
"yhat" value remain stagnate in the middle and results in high  error value. I am not able to fit seasonality (daily, weekly, mothly....)and holiday event in hourly data. Even if i remove outlier greater than 400 , there is no change in model performance.  How can i best fit and  minimize the error.
This is my  forecast plot:
![rplot of hourly data](https://user-images.githubusercontent.com/30797341/50339880-b6882e00-053e-11e9-8d03-d879623c7630.jpeg)

**Comment by bletham** [comment]
This isn't the sort of time series that Prophet is very well suited for. Prophet assumes regular seasonality, which I don't really see here: the size of the fluctations each day seem to vary really dramatically in block chunks. There must be some external factors driving these really different values for each day (for instance, what causes the big spike? Why is there so much higher variability in Dec than in Apr?) and these would need to be included as extra regressors. You would then need to make it so that the daily seasonality depends on those extra regressors (see #538). Unfortunately, for this time series it is going to require a bit of custom work to get a decent fit.

**Comment by pranjol2017** [comment]
I have few queries regarding the Prophet model:
1. Can we use holiday event and regressors for the same date stamp? 
2. At different cut off we get different value of error percentage. How can we estimate the overall error? 

After fitting custom seasonality, I got the following graph which is better than the earlier one. 
Could you please give some idea where to fit regressors and how? How can i further minimize the error. Should I narrow the data range.

![rplot](https://user-images.githubusercontent.com/30797341/51086633-e4901500-176e-11e9-9d86-3b6092405539.jpeg)

**Comment by bletham** [comment]
This time series has very irregular effects and from what I can see I don't have much hope for Prophet working well here. If you look at the time series in the documentation, they all have consistent seasonal effects over some period of time, and that is really where Prophet does well.

For the general questions, yes there is no issue with having multiple holiday/regressor effects on the same date. Different cuts produce different error estimates, we usually average over them like at the bottom figure here: https://facebook.github.io/prophet/docs/diagnostics.html
