### ISSUE TITLE
can anyone provide the math of MAP estimation of parameters in a detailed way.Thank you

### ISSUE THREAD

**Issue by kumarvrsec** [facebook/prophet#779]
can anyone provide the math of MAP estimation of parameters in a detailed way.Thank you

**Comment by bletham** [comment]
I'm not sure there is a whole lot of math to be provided. Wikipedia provides the basic concept, which is to maximize likelihood * prior (https://en.wikipedia.org/wiki/Maximum_a_posteriori_estimation).

The actual likelihood function and priors are computed by Stan, according to the model in https://github.com/facebook/prophet/blob/master/R/inst/stan/prophet.stan . We have not written down the actual likelihood mathematically, since the great thing about Stan is that it computes it for you.

but if you take everything inside of the `normal` here: https://github.com/facebook/prophet/blob/master/R/inst/stan/prophet.stan#L112
and plug it in as the mean and SD of a normal density function, that would be the likelihood. And those individual components inside the `normal` are written mathematically in the paper: https://peerj.com/preprints/3190.pdf
