### ISSUE TITLE
Different Outputs with Same Parameters

### ISSUE THREAD

**Issue by alihash** [facebook/prophet#782]
Hi there,

I am running two models with the same parameters, but getting different results. Any reason why?

#Model 1
m <- prophet(yearly.seasonality=TRUE)
m <- add_seasonality(m, name='yearly',mode = 'multiplicative', prior.scale = .0001)
m <- fit.prophet(m, df)
#forecast <- predict(m, future)
future_act <- make_future_dataframe(m, periods = 24, freq = 'month')
forecast_act <- predict(m, future_act)
plot(m, forecast_act) 

#Model 2
m_act <- prophet(df,
                 seasonality.mode = 'multiplicative', 
                 yearly.seasonality= TRUE,
                 seasonality.prior.scale=.0001)
)

future_act <- make_future_dataframe(m_act, periods = 24, freq = 'month')
forecast_act <- predict(m_act, future_act)
plot(m, forecast_act) 

Any suggestions?

**Comment by bletham** [comment]
There are a couple things going on in the Model 1.

First, the line `m <- add_seasonality(m, name='yearly',mode = 'multiplicative', prior.scale = .0001)` isn't actually doing anything. If you will run it you will see that it produces an error because you must specify some additional information to add a seasonality: the period and the Fourier order. The values you want for those are `period=365.25` and `fourier.order=10` to match the built-in.

The other, is that if weekly and daily seasonality are not being disabled (they may be by default depending on the spacing of the data), then these would not be the same because Model 1 would be leaving weekly and daily seasonality as additive while Model 2 would be changing them all to multiplicative.

Does that make sense?
