### ISSUE TITLE
main/sub not work for plot function

### ISSUE THREAD

**Issue by woodysung** [facebook/prophet#788]
The main and sub doesn't work for the plot function:

For example: 
plot(m, forecast, main="main", sub="sub")

The output graph is without main and sub title.

**Comment by bletham** [comment]
For Prophet models we provide our own implementation of `plot`, which does not have main and sub as options. You can see the available arguments for our plot in the reference manual: https://cran.r-project.org/web/packages/prophet/prophet.pdf or with `?plot.prophet`

The additional arguments are accepted because that is required when making a `plot` function, but they are just ignored.

**Comment by woodysung** [comment]
Ok, thanks for your clarification
