### ISSUE TITLE
Forecaster error - concat has unexpected keyword 'sort'

### ISSUE THREAD

**Issue by Sherazon** [facebook/prophet#820]
In the forecaster.py script, for the line:
`all_holidays = pd.concat((all_holidays, holidays_to_add), sort=False)`

There is no option 'sort' in the pandas concat function which is now throwing errors.

**Comment by NullGuru** [comment]
Hi Marek, 

I'm having the same issue! any updates on that?

Thanks,
Mina

**Comment by MarekLA** [comment]
Hey Mina,

I eventually found out that the option 'sort' was added to a new version of
pandas. Try updating pandas and seeing if it fixes your issue.

Otherwise you can do what I've had to do and just force install v0.3 of
prophet and manually add in holidays (my code already did that so it was
easier than updating everything and fixing other errors!). It seems
sagemaker hasn't been updated with the latest packages yet.

Marek

**Comment by NullGuru** [comment]
Yeah I updated my pandas to 24.1 and it looks like it is working! but I really appreciate your response.

Thanks,
Mina
