### ISSUE TITLE
Explaining forescast result.

### ISSUE THREAD

**Issue by dajerman** [facebook/prophet#824]
Hi,
I am using Prophet in order to forecast sales of the company using estimated marketing metrics as regressors. Is there a chance to get how much influence does have each of the regressors? For the past an the future? Actually for the future I can change the value, predict again and have influence due to the change against the forecast before the change. Is there a posibility get the influence from the forecast dataframe? Or how can I reconstruct yhat from the forecast using the trend and regressors data of the forecast dataframe?

Thanks.

**Comment by bletham** [comment]
If you want to know what the contribution of each regressor is to `yhat`, then in the forecast dataframe returned by `predict` you will find a column for each regressor that gives exactly that. This will be for whatever range of dates you give to `predict`, and so can be both past and future.

Is that what you mean?

You will have to also specify the values of the extra regressor in the future in the future dataframe, and certainly changing those will give you different forecasts under those assumptions. But for this sort of counterfactual thing I'd strongly recommend using MCMC sampling since you'll want to include the uncertainty in the regressor parameters in these estimates. Also, if your future regressors are very different than your past regressors then there will likely be counterfactual policy bias (especially if you have multiple extra regressors that are correlated with each other). This is the same issue you'd run into with doing counterfactual evaluation with any sort of regression model.

**Comment by dajerman** [comment]
Hi bletham,

Here I show a sample (some columns) of the result of the predict function:
<img width="946" alt="captura de pantalla 2019-01-25 a la s 13 51 34" src="https://user-images.githubusercontent.com/43271531/51760045-60138f80-20a8-11e9-848a-38fb7f40c15d.png">

So you mean that the regressors YoYALWAYS_ON and DIFF_ALWAYS_ON are not affecting the results because the value of the predict function is really small compared to the trend value and the value of the other regressors? Does it matter if the regressor is additive of multiplicative?

I actually didn't used the MCMC sampling because I actually dont have many data in the series. I used monthly data and have information for only 3 years. I don't know if it is possible to apply MCMC sampling in a small dataset like this. What do you think?

**Comment by bletham** [comment]
I would actually recommend MCMC as being even more useful when you have relatively few data points; in that situation there is more potential for uncertainty in the model parameters which only MCMC will capture (and the MCMC should be relatively fast too). Actually the example of monthly data in the documentation uses MCMC: https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data

Correct, if the values are very small it means in the final model that regressor is not playing much of a role at all. One thing that you might find useful is the `plot_forecast_component` function, which you could use like
```
from fbprophet.plot import plot_forecast_component
plot_forecast_component(m, forecast, name='YoYALWAYS_ON')
```
to visualize how much of yhat is coming from that regressor as a function of time.

If seasonality is additive, the value in the dataframe will be a raw value (same as y). If it is multiplicative, the value will be a % that is applied to the trend. (So, 0.01 means 1%). If you generate the plot, the axis will show that it is a %.

**Comment by dajerman** [comment]
Hi Bletham, thanks for the data. I will try the same configuration using MCMC. Actually I am using a kind of grid-search of parameters in order to look for the best configuration. The grid search contains the different seasonality mode and scales for the time series and for the regressors and I compute a MAPE error with the test to find the configuration that best fits. Does this approach decrease the effect of the MCMC or it is compatible anyway?

**Comment by bletham** [comment]
You can definitely still tune the hyperparameters when doing MCMC, although I'd expect that you will find less sensitivity to the hyperparameters when doing MCMC.

Often one would use a log transform to get multiplicative seasonality, which Prophet supports without the log transform. The most significant difference would be on the noise distribution: Prophet assumes normally distributed noise, but if you noise has a lot of skew then a log transform might help. But I'd think in most cases it would not. And for differencing, I would not expect this to be useful with the Prophet model, which already learns a non-stationary trend.
