### ISSUE TITLE
Does fbprophet limit the max rows? jupyter notebook kernel died

### ISSUE THREAD

**Issue by shuiyuejihua** [facebook/prophet#834]
i use it like this:
`fbph = Prophet(daily_seasonality=True, yearly_seasonality=True,n_changepoints=44,
               changepoint_range=0.95,changepoint_prior_scale=0.07)`
`%%time
fbph = fbph.fit(df)`

and the df:
`df.info()`
_<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365521 entries, 0 to 365520
Data columns (total 2 columns):
ds    365521 non-null datetime64[ns]
y     350359 non-null float16
dtypes: datetime64[ns](1), float16(1)
memory usage: 3.5 MB_

`df.head(2)`:
	ds	y
0	2018-07-01 00:00:00.449	405.25
1	2018-07-01 00:00:07.819	405.00

NOW:
 `%%time     
fbph = fbph.fit(df.iloc[:10000])`
it is ok;
BUT:
 `%%time
fbph = fbph.fit(df.iloc[:20000])`
or
 `%%time
fbph = fbph.fit(df)`
the jupyter kernel died

the env:
ubuntu , anaconda 2018.12  python3.7.1  fbprophet 0.4.post2

**Comment by bletham** [comment]
Are you running out of memory?

This is a bit surprising to me since the Yosemite dataset used in the example notebook here (https://github.com/facebook/prophet/blob/master/notebooks/non-daily_data.ipynb) has 18722 rows and doesn't cause me memory issues.

If not that, then I'm not sure what could be producing the error. If you're able to upload the csv I can try to reproduce.

**Comment by shuiyuejihua** [comment]
@bletham  oh, thanks， I solved this problem. 
I should not reduce the y column`s dtype float 64 to float 16.
And  now, the y column's dtype , float 64 or float 32 , it is ok .

**Comment by bletham** [comment]
Oh, interesting, I've never tried with float 16 and would not have guessed that as the issue, glad you were able to work it out.
