### ISSUE TITLE
February month forecast coming in as March

### ISSUE THREAD

**Issue by queenvi** [facebook/prophet#835]
Good Day

Please assist. The February monthvforecast is coming through as "2020-03-01" instead of showing "2020-02-29". How can I ensure the right month end date appears in the predict result?

# A tibble: 6 x 5
# Groups:   group [1]
  ds                  group      yhat yhat_lower yhat_upper
  <dttm>              <fct>     <dbl>      <dbl>      <dbl>
1 2020-01-30 00:00:00 TYE925821  6.55       2.10       10.2
2 2020-03-01 00:00:00 TYE925821  6.66       2.71       10.7
3 2020-03-30 00:00:00 TYE925821  6.77       2.74       10.6
4 2020-04-30 00:00:00 TYE925821  6.88       3.00       10.8
5 2020-05-30 00:00:00 TYE925821  6.99       3.25       10.8
6 2020-06-30 00:00:00 TYE925821  7.10       3.22       10.9

**Comment by bletham** [comment]
`predict` will make a prediction for whatever days you pass in the future dataframe. If you are making that dataframe with `make_future_dataframe`, then it internally uses R's `seq.Date` (https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/seq.Date), which for monthly frequency has this odd behavior:
```
> seq.Date(from=as.Date('2020-01-30'), to=as.Date('2020-06-01'), by='month')
[1] "2020-01-30" "2020-03-01" "2020-03-30" "2020-04-30" "2020-05-30"
```
As explained here (https://stat.ethz.ch/R-manual/R-devel/library/base/html/seq.POSIXt.html), "Using "month" first advances the month without changing the day: if this results in an invalid day of the month, it is counted forward into the next month: see the examples."

So in this case since the sequence is starting at 1-30, it will continue to do X-30 if month X has 30 days, and will bump to the 1st day of the next month if not.

To fix this, just make the dataframe of future dates yourself instead of using `make_future_dataframe`, so you can specify the right dates.
