### ISSUE TITLE
How to deal with a large drop in a time series

### ISSUE THREAD

**Issue by Tinkatoo** [facebook/prophet#836]
Hi All,

I am struggling to get a good fit to a time series that has a large drop in the trend - due to a change in the way the values were recorded.

## BASE model
With the base model code in R for daily volumes I get this ->

m <- prophet(daily.seasonality = FALSE,  weekly.seasonality=TRUE, holidays=holidays_events,  holidays.prior.scale = 0.05)
m <- add_seasonality(m, name='monthly', period=30.5, fourier.order=20)
m <- fit.prophet(m, df)
future <- make_future_dataframe(m, periods = 330, freq ="day" )
forecast <- predict(m, future)
plot(m, forecast) 

![image](https://user-images.githubusercontent.com/13379145/52059059-77072580-2571-11e9-8795-230f19271344.png)

![image](https://user-images.githubusercontent.com/13379145/52059951-ec73f580-2573-11e9-81b4-5788609eb7b1.png)

Which is clearly incorrect.
The change occurred around May 2018 - and the values should be consistently lower but in a similar pattern.

## Manual change point 
If i input a change point manually and play around with the change point scale I get something like this 

pattern_change <- c(as.Date("10/05/2018", format ="%d/%m/%Y"))
m <- prophet(daily.seasonality = FALSE,  weekly.seasonality=TRUE, changepoints = pattern_change, changepoint.prior.scale = 0.005, holidays=holidays_events,  holidays.prior.scale = 0.05)
m <- add_seasonality(m, name='monthly', period=30.5, fourier.order=20)
m <- fit.prophet(m, df)
future <- make_future_dataframe(m, periods = 330, freq ="day" )
forecast <- predict(m, future)
plot(m, forecast) 

![image](https://user-images.githubusercontent.com/13379145/52060687-635dbe00-2575-11e9-9542-530bf55c8b14.png)

It's better but is still overestimating the current values.

## Auto change point
m <- prophet(daily.seasonality = FALSE,  weekly.seasonality=TRUE, n.changepoints = 1, changepoint.range = 0.9, changepoint.prior.scale = 0.02)

![image](https://user-images.githubusercontent.com/13379145/52068381-416c3780-2585-11e9-948b-c375987a2933.png)

## Regressor
I thought I had found the answer with adding a regressor with the value of 0 before the date and 1 after the date
df_regressor <- df %>% mutate(tipping = case_when(call_data_daily$ds < as.Date("10/05/2018", format ="%d/%m/%Y") ~ 0, ds >= as.Date("10/05/2018", format ="%d/%m/%Y") ~ 1))
df <- df_regressor
m <- prophet(daily.seasonality = FALSE,  weekly.seasonality=TRUE, holidays=holidays_events,  holidays.prior.scale = 0.05)
m <- add_regressor(m, "tipping") #, prior.scale= 1)
m <- add_seasonality(m, name='monthly', period=30.5, fourier.order=20)
m <- fit.prophet(m, df)

future <- make_future_dataframe(m, periods = 330, freq ="day" ) %>% mutate(tipping=1)
forecast <- predict(m, future)
plot(m, forecast)

![image](https://user-images.githubusercontent.com/13379145/52068594-a0ca4780-2585-11e9-8e8e-620d08fd1259.png)

Boo! I tried playing around with the regressor mode, and prior.scale but no luck.

Help please before I bang my head against the wall.

THANKS!

**Comment by bletham** [comment]
It sounds like since this is a change in data recording, the extra regressor approach that you proposed is the right thing to do. The reason it looks so bad is because of this:
```
future <- make_future_dataframe(m, periods = 330, freq ="day" ) %>% mutate(tipping=1)
```
`make_future_dataframe` will by default include the 330 future days requested, as well as every date in the history. If you look at `future`, you will see that it has both the history and future dates, but `tipping` is being set to 1 for all of them. So what it is actually producing and thus plotting is a forecast of what the past would have been had tipping=1 for all of the past dates. If you apply to `future` the same function for computing `tipping` that you applied to `df`, then I expect that it is actually working.

As a side note, you'll definitely want multiplicative seasonality for this time series based on how the magnitude of seasonal effects drops in post-adjustment phase.

**Comment by Etistar** [comment]
Hi TarynLeeMoris, 
How do you deal please with the problem ?
Do you do like bletham said ?? ( 0 for the past date and 1 for the later date ?

I am dealing with something like that. 
 Thanks
