### ISSUE TITLE
add_regressor...Found NaN 

### ISSUE THREAD

**Issue by alihash** [facebook/prophet#837]
Hi there. I am trying to add a regressor to my prophet model in R, but I get an error: 

Found NaN in column 'regressor_name'.

I find this strange because I made one of the observations in 'regressor_name' NA as I found that observation to be an outlier. When I ran prophet just with jus that regressor alone, everything runs fine. But when I run it in the add_regressor, I get an error in R and I cannot run my prophet model with that outlier observation set to NA. Any suggestions?

**Comment by bletham** [comment]
If you include the regressor in `df` but do not do `add_regressor`, then it will just be ignored.

The regressor value is necessary in order to compute the forecast y_hat, and so the model does not allow NAs for regressor values (so as to not end up with NAs in the forecast y_hat). All you need to do is filter from your dataframe any rows where the extra regressor is NA. Missing rows do not cause a problem for model fitting.

**Comment by alihash** [comment]
okay. thank you!
