### ISSUE TITLE
Cross validation metrics should compute one value per day for daily data

### ISSUE THREAD

**Issue by fercook** [facebook/prophet#839]
I wanted to implement my own metrics, so I've been working with the code at [fbprophet.diagnostics.performance_metrics](https://github.com/facebook/prophet/blob/master/python/fbprophet/diagnostics.py)
and I am confused at how the rolling average is being used. In particular, performance_metrics first [orders the CV results by horizon](https://github.com/facebook/prophet/blob/ef670eaf6cf87a61bb7ee88008ac954d1ddda972/python/fbprophet/diagnostics.py#L224), but a typical CV dataframe will contain several rows for the same horizon, all for different cutoff dates. This dataframe is then used to compute the metrics, and a right side rolling average is used (by default on 10% of the data). However, this means that the rolling average is computed with data from different CVs, and not from different dates. It seems it doesn't matter except that at the boundary between two horizons, we would me mixing metrics from different CVs and different horizons.
Right now, the sequence is:
* order by horizon regardless of cutoff
* compute metric row by row
* rolling average across index that allows mixing horizons and different cross validations
* take mean of metrics with fixed horizon (but they were mixed in step above)

I think it should be something like
* group by cutoff
* order by horizon
* rolling average (because of grouping, it's for a single cross validation)
* take mean between cross validations for fixed horizons

In this way, the averages are cleanly computed for a given horizon.

EDIT:
I did a quick check with a synthetic cross validation dataframe, and I think I am right:
```
cv=pd.DataFrame()
cv['y']=range(1,41)
cv['yhat']=cv['y']+((cv.y-1)/10).astype(int) #each CV is progressively off by one
cv['yhat_lower']=cv['yhat']-0.5
cv['yhat_upper']=cv['yhat']+0.5
cv['cutoff']= pd.Timestamp('2018-1-1')+((cv.y-1)/10).astype(int)*pd.Timedelta('50d') # cutoff dates for 4 CVs
cv['ds']=cv['cutoff']+(1+(cv.y-1)%10).astype(int)*pd.Timedelta('1d') # 1 day at a time, 100 day horizons
```
This simple example has a staircase MSE, and when ordered by the index values it should look like this:
![image](https://user-images.githubusercontent.com/49636/52244571-8a522200-28de-11e9-9421-908fe01ffe76.png)

However this is the output of the performance metrics calculation:
`performance_metrics(cv).sort_index().rmse.plot()`
![image](https://user-images.githubusercontent.com/49636/52244558-70184400-28de-11e9-96b1-349a1b0797af.png)

**Comment by fercook** [comment]
I did a PR to fix this, #841

**Comment by bletham** [comment]
Thanks for bringing this up. The behavior here is intentional, but I think it is worth discussing if it is the most useful analysis.

The current sequence is as you described it, except for the last step: right now there is no averaging over points with fixed horizon. Step 1 (sort by horizon) produces a dataframe like this:
```
             ds      yhat  yhat_lower  yhat_upper          y     cutoff  \
0    2010-02-16  8.957184    8.433988    9.484351   8.242493 2010-02-15   
1807 2012-08-04  8.478918    7.873273    9.106796   8.120886 2012-08-03   
2534 2013-07-30  7.822173    7.216419    8.409137   7.851272 2013-07-29   
1443 2012-02-06  9.730087    9.186885   10.294712  12.673542 2012-02-05   
2898 2014-01-26  9.514055    8.860420   10.120507   9.490545 2014-01-25   

     horizon  
0     1 days  
1807  1 days  
2534  1 days  
1443  1 days  
2898  1 days  
```
where we have many observations of (y, yhat) at horizon = 1. The values at horizon=1 are a mix of different ds and cutoff. (With daily data, there will be exactly 1 per cutoff).

Steps 2 and 3 (compute metric per row, and then rolling average) produces a rolling average over these points, that mixes across days. If I set the window of the rolling average to 3, then it produces a dataframe like this:
```
             ds      yhat  yhat_lower  yhat_upper          y     cutoff  \
0    2010-02-16  8.957184    8.433988    9.484351   8.242493 2010-02-15   
1807 2012-08-04  8.478918    7.873273    9.106796   8.120886 2012-08-03   
2534 2013-07-30  7.822173    7.216419    8.409137   7.851272 2013-07-29   
1443 2012-02-06  9.730087    9.186885   10.294712  12.673542 2012-02-05   
2898 2014-01-26  9.514055    8.860420   10.120507   9.490545 2014-01-25   

     horizon       mse  
0     1 days       NaN  
1807  1 days       NaN  
2534  1 days  0.213272  
1443  1 days  2.930987  
2898  1 days  2.888442  
```
The mse column is a rolling average of the mse computed from y and yhat. There are two things to note: The first two entries are NaN because we are doing a rolling average with window size 3, and pinning to the right as you noted. The second thing to note is that we have multiple estimates of MSE at horizon=1, which are different averages of the many comparison points we had with horizon=1.

And that's the end - there's no additional averaging over horizon. If we do
```
df_p = performance_metrics(df_cv, rolling_window=3./ df_cv.shape[0], metrics=['mse'])
```
we get the same thing, except the first two rows with NA are dropped (notice the index numbers match above):
```
     horizon       mse
2534  1 days  0.213272
1443  1 days  2.930987
2898  1 days  2.888442
1083  1 days  2.893169
3262  1 days  0.007383
```

The behavior here is a bit strange because we end up with multiple estimates per horizon. I wouldn't say that the current calculation is incorrect since all of the values given for 1-day are a rolling average of MSE at horizons <=1day, but it probably would be more natural to return a single estimate at that horizon.

Where things become a bit complicated is for non-daily data (in particular, irregular data with second-level resolution). Now each cutoff has a different set of horizons, and so there is no way to then average over cutoffs for each horizon as in the proposed new strategy. Any thoughts on handling that situation? I'll think a bit more too about how this can be done more cleanly.

**Comment by fercook** [comment]
Thanks for taking a look at this!

The example you show is exactly what I understood from the library, but I am talking about another thing: what happens below those five rows you are discussing. It also goes to the point of what are we trying to measure (I'll discuss that at the end)

Let's say we have 4 cross validations (cutoff dates), step 1 would leave something like this:

y | yhat | yhat_lower | yhat_upper | cutoff | ds | horizon
--|--|--|--|--| --|--
1 | 1 | 0.5 | 1.5 | 2018-01-01 | 2018-01-02 | 1 days
31 | 34 | 33.5 | 34.5 | 2018-05-31 | 2018-06-01 | 1 days
11 | 12 | 11.5 | 12.5 | 2018-02-20 | 2018-02-21 | 1 days
21 | 23 | 22.5 | 23.5 | 2018-04-11 | 2018-04-12 | 1 days
22 | 24 | 23.5 | 24.5 | 2018-04-11 | 2018-04-13 | 2 days
2 | 2 | 1.5 | 2.5 | 2018-01-01 | 2018-01-03 | 2 days
32 | 35 | 34.5 | 35.5 | 2018-05-31 | 2018-06-02 | 2 days
12 | 13 | 12.5 | 13.5 | 2018-02-20 | 2018-02-22 | 2 days
23 | 25 | 24.5 | 25.5 | 2018-04-11 | 2018-04-14 | 3 days
33 | 36 | 35.5 | 36.5 | 2018-05-31 | 2018-06-03 | 3 days
13 | 14 | 13.5 | 14.5 | 2018-02-20 | 2018-02-23 | 3 days
3 | 3 | 2.5 | 3.5 | 2018-01-01 | 2018-01-04| 3 days

Step 2, compute the metric row by row (we can check it's ok by hand) produces a column with the squared error se:

y | yhat | yhat_lower | yhat_upper | cutoff | ds | horizon | se
-- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 0.5 | 1.5 | 2018-01-01 | 2018-01-02 | 1 days | 0
31 | 34 | 33.5 | 34.5 | 2018-05-31 | 2018-06-01 | 1 days | 9
11 | 12 | 11.5 | 12.5 | 2018-02-20 | 2018-02-21 | 1 days | 1
21 | 23 | 22.5 | 23.5 | 2018-04-11 | 2018-04-12 | 1 days | 4
22 | 24 | 23.5 | 24.5 | 2018-04-11 | 2018-04-13 | 2 days | 4
2 | 2 | 1.5 | 2.5 | 2018-01-01 | 2018-01-03 | 2 days | 0
32 | 35 | 34.5 | 35.5 | 2018-05-31 | 2018-06-02 | 2 days | 9
12 | 13 | 12.5 | 13.5 | 2018-02-20 | 2018-02-22 | 2 days | 1
3 | 3 | 2.5 | 3.5 | 2018-01-01 | 2018-01-04 | 3 days | 0
13 | 14 | 13.5 | 14.5 | 2018-02-20 | 2018-02-23 | 3 days | 1
23 | 25 | 24.5 | 25.5 | 2018-04-11 | 2018-04-14 | 3 days | 4
33 | 36 | 35.5 | 36.5 | 2018-05-31 | 2018-06-03 | 3 days | 9

Notice that our 4 cross validations have very homogeneous numbers: The first one is a perfect forecast (se=0), the second one has always se=1, third one has se=4, and the fourth one has se=9. 

Now, at step 3 is where I think there is a problem: A rolling average of 3 rows will leave this df:

y | yhat | yhat_lower | yhat_upper | cutoff | ds | horizon | se | mse
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 0.5 | 1.5 | 2018-01-01 | 2018-01-02 | 1 days | 0 | NaN
31 | 34 | 33.5 | 34.5 | 2018-05-31 | 2018-06-01 | 1 days | 9 | NaN
11 | 12 | 11.5 | 12.5 | 2018-02-20 | 2018-02-21 | 1 days | 1 | 3.333333
21 | 23 | 22.5 | 23.5 | 2018-04-11 | 2018-04-12 | 1 days | 4 | 4.666667
22 | 24 | 23.5 | 24.5 | 2018-04-11 | 2018-04-13 | 2 days | 4 | 3.000000
2 | 2 | 1.5 | 2.5 | 2018-01-01 | 2018-01-03 | 2 days | 0 | 2.666667
32 | 35 | 34.5 | 35.5 | 2018-05-31 | 2018-06-02 | 2 days | 9 | 4.333333
12 | 13 | 12.5 | 13.5 | 2018-02-20 | 2018-02-22 | 2 days | 1 | 3.333333
3 | 3 | 2.5 | 3.5 | 2018-01-01 | 2018-01-04 | 3 days | 0 | 3.333333
13 | 14 | 13.5 | 14.5 | 2018-02-20 | 2018-02-23 | 3 days | 1 | 0.666667
23 | 25 | 24.5 | 25.5 | 2018-04-11 | 2018-04-14 | 3 days | 4 | 1.666667
33 | 36 | 35.5 | 36.5 | 2018-05-31 | 2018-06-03 | 3 days | 9 | 4.666667

Look at the rows where y=21 and y=22: we are computing the rolling average across two different horizons. The same happens when the rolling average passes by the rows with 2 day and 3 day horizons.

What should be the correct result in this case? The mse row has many different values. But our 4 cross validations were constant. Let's talk about what we are trying to compute:

* Option A: you say "which are different averages of the many comparison points we had with horizon=1", I interpret that we are trying to compute an average among points with the same horizon. But you see above that the rolling average mixes points with different horizons. In the example above each horizon only has values 0, 1, 4, and 9, so an average among cutoff dates for a fixed horizon should give us a constant number for all horizons. I think.
* Option B: the rolling average was used to smooth each cross validation (cutoff) curve independently. 

Put another way, option A means an average across cutoff dates for a fixed horizon, and option B means a smoothing or average across horizons for a fixed cutoff date.

I think the original intention was B, because A I wouldn't know exactly how to cast into the original shape, and it sound weird to use a rolling average if the points are not ordered (cutoff dates do not need be ordered when you sort by horizon). 

If option A was the original intention, then one should do a grouping by horizon before averaging. If option B was the intention, then my pull request is the way I would do it * 

In any case, I still think that the current output is not either of these, and that the averaging across cutoff dates AND horizons is happening and is incorrect.

* (I am trying to get the PR to pass but apparently I messed up with my numpy installation, see issue 599)

**Comment by bletham** [comment]
Our goal in cross validation is to estimate the function `E[error(h)]`, where `h` is the horizon.

When we do the cross validation, we measure a bunch of samples of `error(h)`, for some set of values `h`, and possibly with multiple estimates for particular values of `h` from different cutoffs.

The current approach assumes that cutoffs are exchangeable, meaning that for a specific value of `h`, they all provide equivalent samples of `error(h)`. Hence there is no need to order them.

We then use these samples of `error(h)` to estimates the function `E[error(h)]`. fbprophet does not assume regularly spaced data, so in the general case we may have a set of CV results `[error(h1), error(h2), error(h3), ...]` where `h1 != h2 !=h3 != ...`. So how do we estimate a smooth `E[error(h)]`? The first choice would be to fit something like a GP, but that's a bit overkill here and would require a bunch of extra dependencies. So we do a rolling average. That is, with window size 3, we estimate
```
\hat{E}_{w=3}[error(h3)] = (error(h_1) + error(h_2) + error(h_3)) / 3.
```
For w=1 this estimator is unbiased. For w>1, the bias grows (since we are including more points with horizon less than the one we're trying to estimate) but the variance shrinks (average of more points). This estimate is computed for every point (cutoff+horizon) in the CV results.

That is what is currently done, and is entirely intentional. For irregularly spaced data (every `h` in the CV results is unique), this is the right thing to do. When there are multiple samples at each `h`, we end up with something a little different. In particular, suppose we have daily data with three cutoffs. The CV results are then `[error(h1=1), error(h2=1), error(h3=1), error(h4=2), error(h5=2), ...]` with 3 samples per h. Now suppose we estimate `E[error(h)]` as before with `w-3`, and an estimate at each point in CV. We start with the average of the first three:
```
\hat{E}_{w=3}[error(h3=1)] = (error(h_1=1) + error(h_2=1) + error(h_3=1)) / 3.
```
This is unbiased and great. We then compute the estimate for the next CV point, and get
```
\hat{E}_{w=3}[error(h4=2)] = (error(h_2=1) + error(h_3=1) + error(h_4=2)) / 3.
```
This is similar to what we had above with irregular data; it's biased but lowers the variance relative to only using the one `error(h_4=2)` point. Things get a bit weird when we then compute an estimate for the next CV point, which is also at h=2:
```
\hat{E}_{w=3}[error(h5=2)] = (error(h_3=1) + error(h_4=2) + error(h_5=2)) / 3.
```
This estimate is just as principled as the others (i.e., not incorrect), but it is wasteful to have multiple estimates at h=2, when we could have just had a single estimate at h=2 that was the unbiased one
```
\hat{E}_{w=3}[error(h=2)] = (error(h_4=2) + error(h_5=2) + error(h_6=2)) / 3.
```

So, here is the current strategy:
(1) List all `h` that show up in the CV results, including duplicates
(2) At each h, compute a windowed average of size `w` and use that as an estimate of `E[error(h)]`. For `h` that showed up multiple times in the CV, we will have that many estimates of `E[error(h)]`.

And this is what we really want to do:
(1) List all _unique_ `h` that show up in the CV results.
(2) For each, construct the window of size `w` over which the error samples will be averaged. Start with all points that have horizon `h`, and then decrease `h` until we have at least `w` total points and take the average. We will now have one estimate of `E[error(h)]` at each `h`, and it will include all of the error samples with horizon `h`. If `w` is less than the number of cutoffs, then the estimate will be unbiased.

Note that for irregular data, these two are equivalent, but the new second approach will be better (reduce bias) when we have regular data.

Relative to the option B described above, we're not really interested in cutoff-level results, since cutoff is the thing that we want to take the expectation over. If Option B were followed up by an average across cutoffs that would be reasonable (and equivalent to this), but it would need to also handle the case of irregular data, which is handled here.

**Comment by fercook** [comment]
Wow thanks for the detailed answer! The intent of the code is much more clear now, I see that I was confused by the rolling average into thinking you wanted to smooth across horizons for each CV. And yes, later on I am averaging over cutoffs in order to get a single estimate for each `h`. Although with broad assumptions this would be equivalent to the current implementation, for the particular dataset I have it is not.

But I agree that the current strategy for estimating `E[error(h)]` is a good compromise, now that I understand better the intentions. 

What you mention as the more correct way of estimating might help me a bit, since I am able to compute many CVs and will be able to satisfy the requirements for `w` and `h` so that it is both smooth and unbiased.

Thanks again, I'll close this.

**Comment by bletham** [comment]
I agree it is a bit confusing what is happening with daily data :-)

I'll leave this open since we really should have aggregate across days first as I described above, which would make things much cleaner for daily data.

**Comment by bletham** [comment]
Pushed to PyPI and CRAN
