### ISSUE TITLE
Remove dates from 'future' dataframe before forecasting - no change in result

### ISSUE THREAD

**Issue by needsomehelp4** [facebook/prophet#844]
**Edited for clarity and to simplify the scenario**

I am attempting to exclude dates from the forecast but it seems the model continued to consider them even after removing from the `future `dataframe before forecasting

**The forecast for Feb 25 is pretty much the same whether I skip the preceding 23 days or not! That's not right**

I have removed rows from the `future ` for days I want to exclude from the forecast

`future = future[~future['ds'].isin(holiday['ds'])]`

where 'holiday' contains all the future days i'd like to exclude (Feb 2 - Feb 24).

I verified the future dataframe is now missing the dates I don't want it to forecast.

```
60  2019-01-28
61  2019-01-29
62  2019-01-30
63  2019-01-31
**64 2019-02-01
88  2019-02-25**
89  2019-02-26
90  2019-02-27
```

But when I forecast, it clearly is still taking these days into account but just not showing them. **Most days are decreasing by <100 and then it drops by almost 2,000!**

```
57  2019-01-25  3976.960075 
58  2019-01-26  3896.742934 
59  2019-01-27  3816.525792 
60  2019-01-28  3736.308651 
61  2019-01-29  3656.091510  
62  2019-01-30  3575.874368  
**63  2019-01-31  3495.657227 
64  2019-02-25  1490.228694  **
65  2019-02-26  1410.011552
``` 

What am I missing? According to this: https://facebook.github.io/prophet/docs/non-daily_data.html#data-with-regular-gaps I should just have to exclude the dates I dont want to be included in the forecast from the 'future' dataframe.

**Comment by jcochanc** [comment]
Hi! Do you have any data I can use to try and reproduce this? I also haven't seen 'interval_width=.5' before; can you point me to some documentation? Thanks.

**Comment by needsomehelp4** [comment]
Hi, here's the data (rename to csv as needed)
[Data2Copy.xlsx](https://github.com/facebook/prophet/files/2848131/Data2Copy.xlsx)

Also attached is the full project code with some comments.
[prophet_project.txt](https://github.com/facebook/prophet/files/2848134/prophet_project.txt)


If I comment out the date filters on line 94 and line 100 - output is the same with or without these dates in the Future or input DF

**Comment by needsomehelp4** [comment]
Just for sanity sake, I also tried to reset the index on the 'future' dataframe after removing the dates in case Prophet was using that in any calculations but it does not change anything. I did this using:

`future.reset_index(level=0, inplace=True)`

**Comment by bletham** [comment]
If I understand correctly, you are removing some dates from the `future` dataframe, and it is indeed not making a prediction for those dates, but removing them has not changed the forecast at any of the neighboring points.

I'm guessing here that these dates are also part of the training data. If that's not the case, then let me know. In that case, you have to also remove them from the training data (that is passed into `fit`). When the model is making predictions for the points in `future`, it is doing so based on the training data. So removing points from `future` will generally have no effect on the predictions at other points, because they all depend only on the training data.

**Comment by needsomehelp4** [comment]
I have about 65 days of data that I read in at the beginning and fit that into the model. Then I create the future data frame via the mechanism built into prophet. I believe that mechanism still includes the original data and adds x number of days/periods.

You mean I have to manually remove the original data it includes or am I missing a step entirely somewhere?

I understand the concepts of training data but I assumed prophet handles that splitting on its own.

The future dates are removed from the original training data, if that's what you mean.

**Comment by bletham** [comment]
I see.
The training data (`df` above) has the date 2/1/2019 in it. So if you want those dates out of the model, you'll have to be sure to leave it out.

Otherwise, like I said, the forecast for future days depends only on the dates in the history. So leaving out future days when you make a prediction won't have any effect on any of the other future days. In fact, you can make your predictions for future days 1 day at a time and they will turn out the same as if you had passed them all in together to `predict`. Does that make things more clear?

**Comment by needsomehelp4** [comment]
Gotcha, I think the 2/1/2019 is a typo on my part that I will fix tomorrow, however all future dates do not exist in df

In the example I have above, I'm expecting it to predict Jan 31 as x days into the future and Feb 25 as x+1 days into the future. 

Example: the value for row 64 for Feb 1 in my first reply is 3415. When I remove Feb 1-24, I would have expected Feb 25 to take over row 64 with the value 3415 but it does not. It keeps roughly the same prediction with the gap or not

**Comment by needsomehelp4** [comment]
Fixed typos in post and updated results for accuracy though issue still exists.

**Comment by bletham** [comment]
Oh, I see. The model does not assume daily frequency in the future dataframe. It uses the date given to compute how many days into the future it is.

**Comment by needsomehelp4** [comment]
I'm not following. Do you mean the model doesnt actually use the order of the dates but simply the number between dates? 

So the result for Feb 25 is pretty much the same whether I skip Feb 2 - 24 or not and that's intentional? Why would you exclude dates if it doesnt change anything and what can we do to accomplish this instead?

**Comment by bletham** [comment]
It uses the actual date. If you set
```
future = pd.Dataframe({'ds': '2019-03-01'})
```
it will make a prediction for Mar 1 2019 0:00:00. If you set
```
future = pd.Dataframe({'ds': '2019-03-05'})
```
it will make a prediction for Mar 5 2019 0:00:00.

The prediction at each date depends only on the date, and is independent of any other dates in the `future` dataframe.

As for why you would exclude dates - I think you are referring to the section in the documentation about monthly data (https://facebook.github.io/prophet/docs/non-daily_data.html#monthly-data), which recommends only including in the future dataframe the first day of each month (or whatever was the frequency in the historical dataframe). This isn't because leaving those dates out will affect the forecast on the dates left in - those stay the same. In that case, as described in the documentation page, the model predictions are poor for dates in the middle of the month, so it is best to not ask the model to make predictions in the middle of the month just because it clutters the figure with poor mid-month predictions.

Does that make sense?

**Comment by needsomehelp4** [comment]
Gotcha. To accomplish what I need, I simply overwrote the dates in the forecast dataframe in the sequence I needed. For my case, I'm more interested in the **number of days** into the future more than the actual date because some days will be skipped (like weekends).

I wrote this code to accomplish what I need and it works.

**Create a dataframe with the dates to skip**
```
########### create dataframe with days to skip ##############
holiday = pd.DataFrame({
    'holiday' : 'holiday',
    'ds': pd.date_range(start='2019-02-02',end='2019-02-24'),
})

weekend = pd.DataFrame({
    'holiday': 'weekend',
    'ds': pd.to_datetime(['2019-03-02','2019-03-03','2019-03-09','2019-03-10','2019-03-16','2019-03-17','2019-03-23','2019-03-24','2019-03-30','2019-03-31','2019-04-06','2019-04-07','2019-04-13','2019-04-14','2019-04-20','2019-04-21','2019-04-27','2019-04-28','2019-05-04','2019-05-05','2019-05-11','2019-05-12','2019-05-18','2019-05-19','2019-05-25','2019-05-26','2019-06-01','2019-06-02','2019-06-08','2019-06-09','2019-06-15','2019-06-16','2019-06-22','2019-06-23','2019-06-29','2019-06-30','2019-07-06','2019-07-07','2019-07-13','2019-07-14','2019-07-20','2019-07-21','2019-07-27','2019-07-28','2019-08-03','2019-08-04','2019-08-10','2019-08-11','2019-08-17','2019-08-18','2019-08-24','2019-08-25','2019-08-31','2019-09-01','2019-09-07','2019-09-08','2019-09-14','2019-09-15','2019-09-21','2019-09-22','2019-09-28','2019-09-29','2019-10-05','2019-10-06','2019-10-12','2019-10-13','2019-10-19','2019-10-20','2019-10-26','2019-10-27','2019-11-02','2019-11-03','2019-11-09','2019-11-10','2019-11-16','2019-11-17','2019-11-23','2019-11-24','2019-11-30','2019-12-01','2019-12-07','2019-12-08','2019-12-14','2019-12-15','2019-12-21','2019-12-22','2019-12-28','2019-12-29','2020-01-04','2020-01-05']),
})

#######combine dataframes into one
# concatenation of holidays after removing duplicates
#holidays = pd.concat([weekend, holiday, ztd])
holidays = pd.concat([holiday, weekend])
holidays.drop_duplicates(keep='first')
holidays = holidays.sort_values(by='ds')
```

**After forecasting, overwrite the dates and drop the NA columns**
In my case, I use include_history=False when creating my future dataframe
I use the future dataframe as a basis because i only care about future dates, not historical dates.

```
revised_forecast_dates = future[~future['ds'].isin(holidays['ds'])]
revised_forecast_dates.reset_index(level=0, inplace=True, drop=True)
forecast['ds'] = revised_forecast_dates['ds']
forecast = forecast.dropna()
```

**Comment by bletham** [comment]
I see, so you want to clip those dates out as if they didn't exist at all and time went directly from Feb 1 to Feb 25. In that case, that seems like the best option.

**Comment by needsomehelp4** [comment]
Would it be beneficial to add this functionality as a parameter to one of the existing functions? Something like skip_dates=true and then having to provide a dataframe with the dates to skip just like I have?

**Comment by bletham** [comment]
I'd be inclined to leave this as a manual operation for now since I'm not sure that it comes up that often. (and it isn't too much work to do by hand).
