### ISSUE TITLE
How to run forecast when several spikes exist?

### ISSUE THREAD

**Issue by xluo-ds** [facebook/prophet#847]
I am trying to forecast with historical data look like below, there apparently exist several spikes which seems to be related to a campaign launch whose impact seems to last for several days. Any suggestions on how to run forecast for this type of data? 

I can think about 1) removing all these spike windows and making them as missing data, 2) replacing these spike windows data with some moving average. 

![image](https://user-images.githubusercontent.com/43585436/52769058-0f76be80-2fe4-11e9-8d80-20e65cb84126.png)

**Comment by bletham** [comment]
You could put a holiday on each one, with an upper window that has enough days to contains the full effect. This would put a binary indicator on each of those days that learns an adjustment for that day. This would have a similar impact on the future forecast as dropping the data, but be a bit nicer because you could then see in the components plot the campaign effects that you are being modeled that way.

Since there is a consistent shape to some of them you could also think about a parametric extra regressor - there's some discussion of this in #565 in case you're interested, but I'd expect the holidays approach to be most appropriate here.
