### ISSUE TITLE
Plot Components Showing Negative Effect on Holidays?

### ISSUE THREAD

**Issue by chessplayer2** [facebook/prophet#850]
I ran my prophet model and the components plot is telling me that holidays have a negative effect on the forecast. How does that make sense when the outcome variable and regressor go up on those holidays?

![forecast plot](https://user-images.githubusercontent.com/23070309/52814568-55b63700-3051-11e9-8f7e-379974b71913.png)
![components plot](https://user-images.githubusercontent.com/23070309/52814569-55b63700-3051-11e9-98eb-2fdfecc7b8e8.png)

Regressor Forecast:
![regressor](https://user-images.githubusercontent.com/23070309/52814663-839b7b80-3051-11e9-83dc-040e461964b7.png)

**Comment by bletham** [comment]
What's happening here is that there are a lot of effects all being combined on Jan 1: holiday effect, yearly seasonality, and regressor effect. Yearly seasonality on Jan 1 is being set to 0, so it actually isn't playing a role. The regressor effect on Jan 1 is quite large: Looking in the component plot for Jan 1 2017, it is giving a +4% (80,000) and a +75,000 effect, which combines for +155,000. The holiday effect is meanwhile -30,000. This means that the total effect on Jan 1 is +125,000, which is consistent with seeing the increase in the outcome variable.

Basically, the holiday effect doesn't need to be positive because all of the positive holiday effect is already being captured by the extra regressors.

More generally, when there are multiple ways for the model to capture an effect (holiday vs. extra regressor), there's nothing that forces the model to set one of them to 0 and use only the best one. It can use an arbitrary combination of them to still get a good fit. If you want to avoid that type of behavior, you can add some additional regularization that will encourage the model to set one of them to 0 if it isn't actually needed. In this case, you could add some additional regularization to the holiday by shrinking the `holidays.prior.scale` parameter. The default of 10 provides almost no regularization. You could try making it 1 or 0.1, and I would expect it would drive the holiday effect to 0 without impacting your forecast quality (since the holiday effect can be well captured by the extra regressor).
