### ISSUE TITLE
How to view the prophet's accuracy?

### ISSUE THREAD

**Issue by qhwscream** [facebook/prophet#851]
How to view the prophet's accuracy?And where is the accuracy? Also,How to know the figure's effect is good or not? Thank you!

**Comment by jbanik85** [comment]
Prophet offers many metric to determine the accuracy. You can learn about them in this page: https://facebook.github.io/prophet/docs/diagnostics.html

**Comment by qhwscream** [comment]
@jbanik85  I think you don't know what I want to ask.I also know the Quick Start.The page is not what I  require. I mean that the accuracy might be a percent number,do yo know?

**Comment by jbanik85** [comment]
I am not sure if I understood your questions correctly. It's better if somebody else answers your question.

**Comment by bletham** [comment]
+1 for @jbanik85's suggestion, it sounds like what you're looking for. The plot at the bottom of https://facebook.github.io/prophet/docs/diagnostics.html shows forecast error as a percent (mean average percent error).

**Comment by jbanik85** [comment]
Thanks for confirming my answer :) It was my understanding too that the OP was asking about MAPE, but I got confused with his response.

**Comment by qhwscream** [comment]
@bletham What you said about is the percent error,I asked is the percent accuracy.

**Comment by qhwscream** [comment]
@jbanik85  You should use 'her' neither 'his'.

**Comment by jbanik85** [comment]
oops, my bad! Should have noticed. Editing my response.

**Comment by qhwscream** [comment]
@jbanik85 nothing serious.

**Comment by bletham** [comment]
I see - I guess it depends on how you define accuracy. One possible definition would be that `%accuracy = 100% - %error`? So when there is 0% error there is 100% accuracy, and 100% error means 0% accuracy? Of course with this definition, %accuracy could also be negative, since %error can be >100% if the error is larger than the values. If you wanted to use this definition of accuracy, you could compute MAPE as described in the documentation page and then just subtract it from 1. If you have a different measure of accuracy in mind, you could use the cross_validation function to compute a bunch of pairs of true values `y` and estimates `yhat` (the first table on the documentation page), and then you could apply whatever function you want to those to compute accuracy.

**Comment by qhwscream** [comment]
@bletham thanks a lot!

**Comment by microprediction** [comment]
Googled "Facebook Prophet Accuracy" ?
