### ISSUE TITLE
Fprophet package documentation in python

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#856]
I have found prophet [package documentation in R ](https://cran.r-project.org/web/packages/prophet/prophet.pdf)

Is there a similar documentation in python "not the quick start nor just the help(prophet) method", I want the full documentation containing prophet methods and attributes.

**Comment by bletham** [comment]
No, just the R since it is auto-generated during package creation. There is a complete parallel between the function and methods, and every function/method has a detailed docstring that you can get at with, e.g., `help(Prophet.predictive_samples)`.

There is an open issue in #619 to produce a reference manual for Py. I think it shouldn't be too much effort since the docstrings are already in a consistent format, but it still needs to be done.
