### ISSUE TITLE
Extracting coefficients to store in DB for later use

### ISSUE THREAD

**Issue by MattConflitti** [facebook/prophet#862]
Hello! Love the package and what it has to offer.
I am trying to solve a problem that involves forecasting sales for 1000s of items in a database given their historical sales. I want to find a quick way to store the coefficients of the generated models in a table that is indexed for quick lookup. Upon lookup, it would be nice to reconstruct the model to predict for the next week or two.
1) Is there a way to extract the coefficients for a generated model?
2) Given 1. what would be the formula to plug those coeff back into?

Not even sure if this is the best approach. I know we can pickle these models, but the model expires after a week anyways since new data would be available to train on. Should I try to just do this on the fly for each item and take the couple second hit to train the model and do the forecast?

Any insight into an approach to this problem with Prophet is much appreciated.

Thanks!

**Comment by bletham** [comment]
This makes a lot of sense, and yes while the model does pickle that's a pretty unpleasant way to store something in a db. We typically store tables of forecasts in a db rather than trying to store the model and generate them on the fly. This is done as a recurring job that updates all of the forecasts as new data become available. This works if you know beforehand what range of dates you'll need forecasts for, but obviously wouldn't if you don't. 

Serializing everything needed to reinstantiate the model may be a bit of a pain. We have tried to keep in the `__init__` a list of all of the model attributes, which I think is complete, starting at
https://github.com/facebook/prophet/blob/master/python/fbprophet/forecaster.py#L101 and going through L141. Instantiating a new object and copying over all of those attributes should produce an identical model. The types of the attributes are a mix of numpy, pandas, and base Python types, which could all be serialized safely.

That does seem like a bit of a pain to me, and probably would not be my first choice for trying to solve this problem.

As for the models expiring with new data: There isn't any way currently to update an existing model with new data other than to re-fit from scratch, so in that particular scenario there wouldn't be value to trying to cache the model.
