### ISSUE TITLE
Uncertainty intervals not diverging

### ISSUE THREAD

**Issue by judd5000** [facebook/prophet#871]
Hi All,

Issue: I'm not seeing divergent uncertainty intervals when forecasting out for long periods, where I would expect to see them. This is using only uncertainty in the trend.

I am forecasting Google Trends data out by a few years (I realise the forecast isn't going to be accurate at this level - it was mainly to highlight the problem). I'm using the following settings (sub.events is the holiday data.frame in the format required by prophet):

m <- prophet(y,weekly.seasonality = F, daily.seasonality = F, yearly.seasonality = 10 , holidays = sub.events,seasonality. mode = "multiplicative", growth = "logistic")

I believe this was for 5 years of weekly data regarding the keyword 'spin mop' - although I could give you many examples:

![image](https://user-images.githubusercontent.com/31062360/53633523-9dbb8900-3c0f-11e9-82d8-f66d13902f14.png)

Am I missing something? I've looked at the predictive_samples and the standard deviation on yhat is pretty much flat. Although, there is a slight divergence as time goes on in the trend_upper and trend_lower when looking at the output of predict(m, future), it doesn't seem enough for such a long forecast. I would imagine that so far out it should be massive! I'm sure in older versions of prophet it worked as expected. I'm using v0.4.

Any help would be appreciated.

**Comment by bletham** [comment]
If you just do MAP estimation (the default), there will only be two sources of uncertainty: the noise term, and future trend uncertainty. In this case it looks like the data are pretty well captured by the seasonality and so the noise term is very small. As described in (https://facebook.github.io/prophet/docs/uncertainty_intervals.html#uncertainty-in-the-trend), future trend uncertainty is estimated by assuming that the future will see the same rate and magnitude of trend changes as the past. This means that if the trend has changed a lot in the past, then we will assume that it will continue to change a lot in the future and will have high uncertainty on where the trend will be. Conversely, if the trend has not changed in the past, we will assume that it will not change in the future. In this case, the time series has basically no trend changes in the past. If you look at the components plot with `prophet_plot_components(m, forecast)`, you'll see that the trend looks perfectly like the ramp-up of a logistic function, without any significant changes in rate. And so the future trend uncertainty projects forward that we do not expect significant changes in rate in the future.

If it is the case that we have not had trend changes in the past but we think we may in the future and want to reflect that uncertainty - there isn't really a way to do this right now (#293 is the issue for that).

You can get some more uncertainty by doing MCMC, which will estimate uncertainty in the actual parameter values. But generally, the uncertainty provided by Prophet is under the assumption of correct model specification. If we expect that in the future the model will become misspecified (either due to a change in the rate of changepoints or a change in the seasonality patterns), that possibility will not be covered by the uncertainty estimates.

**Comment by judd5000** [comment]
Unfortunately, the assumption about constant trend changes/constant magnitude doesn't hold true in about 60 - 70% of the data sets I'm looking at - especially 3 years out - as they lie (often quite far) out of the prediction intervals.

I'm only using MAP because of the scale of predictions I'm doing (tried using Linux VM) - it has been noted in any outputs that the prediction interval is based on the trend/noise only.

Thanks for the clarification of how it works - I assumed that was the case, but with the rate Prophet develops I was wondering if there was something I was missing. It's a great tool, especially with the easy to use event considerations - great job and carry on with the good work!

I will try and build in additional uncertainty by cross validating the predictions across 1000 or so forecasts and create a variable which I can attenuate the confidence intervals with. Obviously not a repeatable procedure and I'll have to stick it in as a constant, but I will clarify it in any assumptions that I include in my outputs.

**Comment by bletham** [comment]
Yeah, that makes sense.
If you wanted to inflate the future-trend variance inside the package, so that you can use all of the built-in plots etc. with the higher variance, it can be done here: https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L1569
`lambda` is the scale parameter of the trend change distribution, and increasing that by some factor would increase the trend uncertainty. You could empirically figure out how much inflation you need to improve your coverage in cross validation.

**Comment by bletham** [comment]
You would, of course, have to download the source from here, modify the package, and install the modified version with `devtools::install`
