### ISSUE TITLE
Is it fine to include history in make_future_dataframe ？

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#882]
> make_future_dataframe. By default it will also include the dates from the history, so we will see the model fit as well.

I need predict tomorrow sale count of some products everyday . On my opinion,  if one want to check the correctness of prediction,  have 100 days data,  he need use `data of 1~14 days ` to `data  of 1~100 days` to predict `date 15`  to   `date 101` .

code would be something like 

```
def prophet_scroll_train_predict(ts, start_size, df_extra=None):
    results = []

    for i in range(start_size, ts.shape[0]-1):
        print('prophet_scroll: %s/%s' % (i, ts.shape[0]) )
        forecast = prophet_train_predict(ts.iloc[:i], df_extra=df_extra) # a function only predict tomorrow of ts.iloc[:i]
        results.append(forecast)

    if len(results):
        r = pd.concat(results)
        r = r.set_index('ds')
        return r['yhat']
    else:
        return None
```

But it would be very very slow. 
I wonder is it fine to just include history in make_future_dataframe as the docs suggest,

**Comment by bletham** [comment]
When you make a prediction on the history (as is done by default with `make_future_dataframe`), you will see the model predictions on historical data points but these are in-sample predictions, meaning these data were used to fit the model. They thus do not provide an accurate assessment of the model's ability to forecast (make out-of-sample predictions). That's because the model can do a much better job at predicting values for which it already knows the true values :-)

To get a good estimate of forecast ability, you need to essentially do the procedure that you outlined, where you fit the model to a small amount of data, make a forecast beyond that cutoff point, and then compare the forecast to the actual values.

Prophet has a built-in utility for doing this type of cross validation: https://facebook.github.io/prophet/docs/diagnostics.html

One thing to note is that you don't necessarily need to do this for _every_ day in the history. If you have 100 days of data and want to start from a minimum initial size of 14 days, if you make a cutoff at every day and want to forecast at least 1 day then you will have (99-14)=85 estimates of forecast error, and have to fit the model 85 times. But these estimates will be highly correlated, and so you could get a reasonable estimate with many fewer model fits. For instance, you could do this  once a week, you'd have to fit the model only 12 times, but would still get a reasonable estimate. In the `cross_validation` utility this is the `period` parameter.

Section 4.3 of the paper has some more discussion about cross validation strategies and our philosophy there: https://peerj.com/preprints/3190.pdf

**Comment by eromoe** [comment]
Today, I finally finished reading the paper.  
I have understood the SHFs,  but I want to plot the forecast value with true value . 
df_cv would contain multiple yhat on same date .

And I have a dataset perform as below
![image](https://user-images.githubusercontent.com/3938751/54815723-8aab4e80-4ccd-11e9-89d7-2f29dfed6b26.png)

forecast every day work best . If I mean the yhat by date, would the plot would look much bad.

**Comment by bletham** [comment]
There are multiple forecasts for each date because it has been forecasted from multiple different cutoffs. Typically we are interested in error as a function of how far out we're forecasting (horizon), but if you wanted to see error on each particular day, you could select from that dataframe all of the rows with a particular value of horizon (let's say 1) and then plot the 1-day-before-forecast for each day.
