### ISSUE TITLE
Why is my holidays affect the weekly seasonal component?

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [facebook/prophet#885]
I have added a increase in 2 days in my series to model a holiday case and test it.
and I have added the data this holidays to the model to be fitted.
My remark is that the added holidays have affected the weekly seasonality of the data, as the 2 days where I have added the holiday the weekly seasonality have increased.
Why is that happening and how to prevent that ??

**Comment by bletham** [comment]
Just to be sure I understand the setting - you have a time series. You've selected 2 days and increased the value on those 2 days. You then add each of these 2 days as a holiday, and fit the model. You compare this to a model that was fit without the increased value (and without the holidays), and you find that the weekly seasonality has increased in the increased setting.

Are all of the details there correct? Is it a separate holiday for each of the two days and/or the same amount of increase?

How many weeks of data are there? The model has to distinguish between holiday effect and weekly seasonal effect, and if there are very few weeks that might be challenging.

Usually, putting a holiday effect would effectively remove that point from the seasonality estimation and so changes to the value on the holiday would not effect the seasonality. In this case, the comparison you have made is between original values and holiday values. One possibility is that the original values were actually lower than average, so "removing" them by specifying them as holidays raises the holiday estimation. A better comparison would be to remove those points from the data, fit the model, and then compare that seasonality to the one that puts a holiday effect on them.

If that is still showing an increase, then you can adjust the prior scales to better indicate your preference to prefer to attribute increase the holidays rather than seasonality. By default both the `seasonality.prior.scale` and `holidays.prior.scale` are 10, which is a pretty weak prior. If you reduce `seasonality.prior.scale` (say, to 1) then the model would prefer to use holiday effects to fit effects than seasonality.
