### ISSUE TITLE
Prophet Optimized Search

### ISSUE THREAD

**Issue by perkykooky** [facebook/prophet#886]
Hi!

Do you have any suggested algorithms, aside from an exhaustive grid search, that can quickly identify the best parameters for a dataset? Like the way we have autoarima from arima

**Comment by whitehatty** [comment]
Instead of a grid/random search you can use Bayesian optimization in conjunction with the rolling forecast cross-validation

**Comment by bletham** [comment]
I just want to give a plug for random search rather than grid search for the continuous parameters (prior scales). Figure 1 of this paper gives a compelling example for why one should prefer random search over grid, which I think is very applicable to the hyperparameters here: http://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf

We do not intend to add built-in hyperparameter optimization. I think many of the options (additive vs. multiplicative seasonality, which periods of seasonalities are present, which holidays to model) are things that the person making the forecast likely has domain expertise that would be much better than just trying to minimize cross validation error. For the prior scales, there is value to doing a sweep, but a random search over those using the built-in cross validation is very little code.

**Comment by TheXu** [comment]
> Instead of a grid/random search you can use Bayesian optimization in conjunction with the rolling forecast cross-validation

A Bayesian Hyperparameter Optimization in R Prophet Parameters is detailed here:
http://rpubs.com/tdneumann/351073
