### ISSUE TITLE
Create a good first issue badge?

### ISSUE THREAD

**Issue by raybellwaves** [facebook/prophet#895]
I would like to contribute to this repo but would like to start small (e.g. docs, fairly quick fixes (< 1 hour). Adding a 'good first issue' badge would be helpful. You could also add a documentation badge if people just needed clarification on a question

**Comment by bletham** [comment]
Thanks for the support!
Documentation is actually a little tricker than one might expect since all of the documentation is generated from ipython notebooks and so you have to set up the build environment for that. But, I think there are a lot of minor code issues that are pretty localized and could be handled quickly. Let me next week go through the enhancements/bugfixes that I'd like to get into the next version, and I'll give a brief description of what should be done for each and will label it as a good simple issue.

**Comment by bletham** [comment]
I've flagged a whole bunch of issues for the v0.5 release. Almost all of them are minor bug fixes or small feature enhancements and would be an appropriate first issue. I have a comment on all of them stating what the issue is and how it should be resolved, so if there is one that looks interesting feel free to comment on it and we could discuss further there.
