### ISSUE TITLE
Building a UI for Facebook Prophet - Community Contribution

### ISSUE THREAD

**Issue by garethcull** [facebook/prophet#898]
Hey Facebook Prophet Team,

I'm not sure where this falls within the contributing guidelines, but I recently have been exploring building a UI for Facebook Prophet as a Flask Application. 

At a high level, the UI provide peoples with the ability to build simple baseline forecasts from within a guided user interface.

I open sourced all of the code behind the UI and have a link to a working demo here:
https://github.com/garethcull/forecastr

I also want to say thanks for building Prophet. It truly is an amazing tool! You guys are awesome!

**Comment by bletham** [comment]
Wow, this is really beautiful. At some point before the next version release I'll add a page to the documentation of useful external examples of using / developing on top of Prophet, and I'll definitely add this to the list!

**Comment by garethcull** [comment]
Awesome! I'm glad you like it. Thanks @bletham. I appreciate you doing that :)

**Comment by pankaj-kvhld** [comment]
This is really great. Thought of doing something like this and found you have done it much better than I every could have. Kudos.

**Comment by AntHuntley** [comment]
Hey Gareth, nice job with the UI on top of Prophet. Are you planning to add functionality to allow users to add additional inputs such as holiday effects, or additional regressors? Apologies if you have this already and I've missed it!

**Comment by garethcull** [comment]
Thanks @AntHuntley. I really appreciate that feedback. I'm hoping to add some new features to the UI in the future and have actually had some feedback already about adding in additional regressors. It would be interesting to experiment with ways to add this functionality to the UI. I'm open to ideas :)

**Comment by robomotic** [comment]
Hi @garethcull, read your blog very cool project.
Yes Heroku under free instance has shared CPU therefore it will be a challenge to reach the equivalent performance.
I believe the paid version would improve the training time since you will have a dedicated virtual CPU.
If we want to focus on Heroku we should also partition the training (cross folds) over heroku workers.

Anyway I have also attempted a Dockerization of your application but somehow I cannot get it work.
Could you take a look?
https://github.com/robomotic/forecastr

This will help to deploy on Azure/GCC/AWS to leverage more powerful CPU plans.

Cheers!

**Comment by bletham** [comment]
I added a link to this in the docs in https://facebook.github.io/prophet/docs/additional_topics.html#external-references so others can find it there.
