### ISSUE TITLE
Why plot_cross_validation_metric  show `Horizon( hours)` when input is all by day ???

### ISSUE THREAD

**Issue by eromoe** [facebook/prophet#901]
Hello, 

Here is my df:

![image](https://user-images.githubusercontent.com/3938751/54889226-86a24b00-4ede-11e9-8bc9-329e6366043b.png)

The horizon should be by days, however it is in hours

![image](https://user-images.githubusercontent.com/3938751/54889315-f0225980-4ede-11e9-8c0c-97d76b3da6e6.png)

**Comment by bletham** [comment]
This is because of the logic for automatically selecting the unit to put there. It tries to put about 10 ticks in, and then finds the largest unit that allows for that many ticks. In this case there were only 7 days of horizon, so it ends up choosing hours.

That certainly doesn't make a whole lot of sense here, and it would be better to adjust it so that when we have specifically daily data we use days.

I'll leave this open as a todo for the next version. In the meantime, the code to produce this plot is right here:
https://github.com/facebook/prophet/blob/master/python/fbprophet/plot.py#L422

If you delete L484-486 and replace it with
```
i = 0
```
then that would fix at at "days".

**Comment by bletham** [comment]
We've decided to leave the current behavior as is, but as described in my comment above the plot can easily be modified to change the axis ticks / ticklabels as desired.
