### ISSUE TITLE
Parameter tune for CPU and MEM % usage

### ISSUE THREAD

**Issue by CrashLaker** [facebook/prophet#907]
Hi all.

First of all sorry If I'm posting to the wrong place. If there's a proper place to ask questions about forecast quality or parameter tuning just tell me :)

I'm trying to fit the best parameter to forecast CPU% and MEM% metrics but some forecasts are really not convincing. 
As I'm planning to plot forecasts on different metrics of multiple machines I know it's impossible to perform an in depth diagnostic to a metric on each machine so I'd like to ask you guys if there's some best practice on ideal parameter tuning to forecast computer resources.

Some parameters I'm using:
Other parameters not shown are supposed to be set the default like the "additive" parameter on "seasonality_mode".
```python
df["cap"] = 100
df["floor"] = 1.5
m = Prophet(changepoint_prior_scale=0.01, growth='logistic').fit(df)
future = m.make_future_dataframe(periods=180*24, freq="H")
future["floor"] = 1.5
future["cap"] = 100
```
And without caps and logistic growth when forecasting non percentage metric.

Some results:
![image](https://user-images.githubusercontent.com/4432491/55234548-2b3bca00-520a-11e9-89aa-b0bee592aac8.png)  
By looking at the chart above a human eye would catch that the trending values would be increasing over time. But that's not what it show in the plot.

![image](https://user-images.githubusercontent.com/4432491/55234559-30007e00-520a-11e9-92b1-544dfb5c0e26.png)
Seeing this plot it's hard to believe that CPU% will reach 100% in 2 months.. And even hard to explain..

**Comment by bletham** [comment]
For the first one: I think what's happening here is that the spike at 2018-12-15ish is causing the problem. It definitely isn't seasonal, and so the model is trying to capture it with the trend.  However, by default Prophet will only place potential trend changes in the first 80% of the time series (see https://facebook.github.io/prophet/docs/trend_changepoints.html). This means that the model isn't able to put in the 3 trend changes that would be necessary for the trend to spike up and hit that point, and then get back to the normal upward trend.  So what is happening is that there is a trend segment that is going from the spike down to get back to the 2019-01 data, and then continuing on downwards. I think you'll be able to see this really clearly if you look at the trend component in the components plot `m.plot_components(fcst)`.

There's a sortof related example at https://facebook.github.io/prophet/docs/outliers.html where some outliers drag the trend down. 

There are a few things that could be done to fix this. You could do
```
m = Prophet(changepoint_range=0.95)
```
to allow trend changes in the first 95% instead of 80%, and then trend changes will potentially be able to cover the spike without the final trend getting messed up. The risk of putting changepoints close to the end of the time series is that you may then overfit to small changes in trend near the end, and would still run into this type of issue if these outliers were at the very end of the time series. The alternative is to identify these as outliers and just remove them, as is described on the documentation page above about outliers.

For the 2nd plot, it's less clear to me what is happening. It does look like there is a strong seasonal effect that is not being captured at all. What is the frequency of those spikes? Is it weekly? I'm a bit surprised that the weekly seasonality isn't capturing it. Could you post the output of `m.plot(fcst)` and `m.plot_components(fcst)`?

**Comment by CrashLaker** [comment]
Hi @bletham 
Thank you for your reply.
Like you said I could see that behavior on the components plot. I've read about https://facebook.github.io/prophet/docs/trend_changepoints.html but I wasn't expecting that that slight spike in december to cause such a distortion to the trend.
Got the same results after running it as follows:
```python
df["cap"] = 100
df["floor"] = 1.5
m = Prophet(changepoint_prior_scale=0.01, growth='logistic', changepoint_range=0.95).fit(df)
future = m.make_future_dataframe(periods=180*24, freq="H")
future["floor"] = 1.5
future["cap"] = 100
```
The components are:
![image](https://user-images.githubusercontent.com/4432491/55510249-38a2eb00-5634-11e9-8329-6e265d6965aa.png)  
![image](https://user-images.githubusercontent.com/4432491/55510254-3b9ddb80-5634-11e9-8dc9-1e0bb3b12fe8.png)  


About the second plot I'll paste some plots showing the full dataset and some cropped ones (weekends, bs hour, etc). Those spikes happened on sundays.
I've trained both models using the full dataset. Do you think training it with filtered datasets worth it? I didn't do it yet because the forecast would also plot the time range which I've exclude therefore it'd be biased.
**full dataset plot**:  
![image](https://user-images.githubusercontent.com/4432491/55508010-56ba1c80-562f-11e9-83e2-8cf27a4f7c31.png)  

**weekday plot**:
![image](https://user-images.githubusercontent.com/4432491/55508079-7ea98000-562f-11e9-890f-497b180c8d0b.png)  

**weekend plot**:  
![image](https://user-images.githubusercontent.com/4432491/55508121-91bc5000-562f-11e9-93a8-69450beb5fcf.png)  

forecast plot:
![image](https://user-images.githubusercontent.com/4432491/55508144-a00a6c00-562f-11e9-98d4-65417e2b6cf2.png)  

forecast components plot:
![image](https://user-images.githubusercontent.com/4432491/55508162-a698e380-562f-11e9-895a-eb66c362d33d.png)

**Comment by bletham** [comment]
Oooh, OK I see what is happening now. Thanks for posting the component plots.

For the second one: I ddin't realize that this was sub-daily data. So what is happening here is that the _daily_ seasonality is different on Sunday than on other weekdays (it needs to be much larger on Sunday). The weekly seasonality isn't capturing this very well because it just adds a constant offset for each weekday, whereas here what we're seeing is that the _shape_ of the daily seasonality is different on Sunday vs. other days (it's much more elongated on Sunday).

This is an example of a seasonality depending on another factor (in this case, being Sunday). We recently added a new feature that makes it really easy to model this type of behavior, by creating a separate daily seasonality just for Sundays. It's in the code here on github, but we haven't yet pushed out a new version that contains it. If you're up for installing from github, you could try that out and I'd expect it to do a much better job here (and I'd love any feedback on how it worked since it is a brand new feature). The issue for this new feature (conditional seasonalities) is #538, and over there it explains how to install the latest version from github and then how to use the new feature (it's just a couple lines). It is a bit of a pain to have to download the repo and install from source, but I would really appreciate any feedback if you are able to try it out here.

For the first one: Did you mean to post the components plot for it too? I think you accidentally posted the 2nd one twice. If that spike is too narrow to be covered well by trend changes, you might just have to remove those data points from the time series :-/

**Comment by CrashLaker** [comment]
Hi @bletham.
Thank you so much for clarifying the cause of that increasing trend on the 2nd plot. Also this notebook on #538  helped me a lot on understanding the impact when dealing with different season patterns just like you said. https://github.com/facebook/prophet/blob/master/notebooks/seasonality%2C_holiday_effects%2C_and_regressors.ipynb.

I'll experiment with that new feature and see how it turns out. But.. still.. Seeing the work I'd have to do on drilling to every unconvincing forecast do you think it would be better to me If **1** I aggregated my dataset a daily interval instead of hours or minutes? (Those models were taken by running prophet on 5min interval metrics). Or **2** If I just removed the weekends (as I know harmless but scheduled intensive computation happens on weekends). How would that affect the overall forecast?

Oops! I'm sorry I indeed accdentaly upload the same plot twice.
Here are the components plot of the 1st sample:
![image](https://user-images.githubusercontent.com/4432491/55725898-03f0b400-59e5-11e9-8951-4c108cd487c7.png)  
![image](https://user-images.githubusercontent.com/4432491/55725936-12d76680-59e5-11e9-9de0-62bf49b91ece.png)
![image](https://user-images.githubusercontent.com/4432491/55725941-1539c080-59e5-11e9-8acb-09b76d151b9c.png)


Thank you so much for helping me with this.

**Comment by CrashLaker** [comment]
Hi @bletham 
Did some attempt to correct the model but I'm not sure if I'm still missing some points.
Can you validate what I've done so far?

#### Case 1
```python3
df["cap"] = 100
df["floor"] = 1.5
i = 0.05
x = 0.85
m = Prophet(changepoint_prior_scale=i, growth='logistic', changepoint_range=x, daily_seasonality=True)
m.fit(df)
future = m.make_future_dataframe(periods=180, freq="d")
future["floor"] = 1.5
future["cap"] = 100
forecast = m.predict(future)
```
For case 1 my dataset consists of 5min interval data from dec 2018 to jan 2019.
![image](https://user-images.githubusercontent.com/4432491/56222802-04bbc280-6043-11e9-9f23-687a1d42ceb0.png)  
By running it with the default parameters gave me this: df  `changepoint_range=0.8`, `mode=additive` and `changepoint_prior_scale=0.05`
![image](https://user-images.githubusercontent.com/4432491/56235879-b4525e00-605e-11e9-819c-e45d3d9f9ba4.png)  
![image](https://user-images.githubusercontent.com/4432491/56235893-bae0d580-605e-11e9-8c26-99e1e10bc2b3.png)   
With the regressor gave me almost the same result..  
```python3
def weekend(ds):
    date = pd.to_datetime(ds)
    if date.weekday() > 4:
        return 1
    else:
        return 0
...
df["weekend"] = df["ds"].apply(weekend)
m.add_regressor("weekend")
...
future["weekend"] = future["ds"].apply(weekend)
```
![image](https://user-images.githubusercontent.com/4432491/56236477-15c6fc80-6060-11e9-83fc-5838a1a27cff.png)  
![image](https://user-images.githubusercontent.com/4432491/56236482-18295680-6060-11e9-8d8b-7e0b2dad5a3b.png)  

Aggregating it by day though gave me this which I think it's the one that better represents the trending  
```python3
df = df.resample('d', on="ds").mean().dropna(how='all')
```
![image](https://user-images.githubusercontent.com/4432491/56236709-98e85280-6060-11e9-9d30-781698be87ab.png)
![image](https://user-images.githubusercontent.com/4432491/56236711-9be34300-6060-11e9-9aa4-16a317a3e33a.png)

Adding the regressor also caused no major results:
![image](https://user-images.githubusercontent.com/4432491/56236859-f11f5480-6060-11e9-82d6-3b99c4000c3f.png)
![image](https://user-images.githubusercontent.com/4432491/56236864-f41a4500-6060-11e9-8289-8cf4002295dd.png)

## Case 2
Regarding case 2 i had this dataset:
![image](https://user-images.githubusercontent.com/4432491/56236959-40fe1b80-6061-11e9-8a55-a3cd59619ee1.png)
By using the default parameters I got this:
![image](https://user-images.githubusercontent.com/4432491/56237769-2a58c400-6063-11e9-93d2-20e485431859.png)
![image](https://user-images.githubusercontent.com/4432491/56237775-2cbb1e00-6063-11e9-9c50-3433f38f076f.png)

Aggregating it daily gave me this:
![image](https://user-images.githubusercontent.com/4432491/56237851-612eda00-6063-11e9-891d-e91d4a3d04a0.png)
![image](https://user-images.githubusercontent.com/4432491/56237852-62f89d80-6063-11e9-8e0d-114cb9157b43.png)

which i think is alright for now

any advice?

**Comment by bletham** [comment]
Adding a regressor won't help with the issue with sub-daily data because in this case it is adding a constant effect throughout the entire day, which doesn't well match the actual effect which grows throughout the day to a peak and then falls back.

Aggregating by day does resolve the issue because then it can be handled with a single effect for the day and there isn't any shape to be modeled.

If you don't need to make sub-daily predictions, then aggregating by day definitely would be preferable in this case because the particular sub-daily structure here isn't being well captured by the model. (and it does seem to be doing a lot better.

**Comment by CrashLaker** [comment]
better indeed. really thank you for your patience @bletham :)

**Comment by CrashLaker** [comment]
Hi @bletham sorry to bring up this thread again.
Can you help me understand why is prophet making this prediction?
My dataset is daily.
![image](https://user-images.githubusercontent.com/4432491/56772458-84a70280-6790-11e9-9c16-feed82eb9f91.png)  
![image](https://user-images.githubusercontent.com/4432491/56772467-8670c600-6790-11e9-809b-8d1cac89132b.png)

**Comment by bletham** [comment]
I don't have a whole lot to say about this one - the logistic growth trend means exponential growth up to the saturation point. In this case there is a bit of an uptick, and so the best-fit for that growth trend is that it's the start of the exponential growth. This is probably not a good trend for this type of data (given that it seems to be mostly flat). You might try the default piecewise linear trend instead. The only other thing that I'd note is that generally you'll want to be cautious with how far you extrapolate a forecast. With 3 months of data, I'd be hesitant to forecast out more than a month or so.

**Comment by CrashLaker** [comment]
Hmm! Good thinking. thank you @bletham!

For now I was just skipping the forecast when the overall mean was below 5.
Now I'll just try to use the linear growth to cases where that condition is met.

> With 3 months of data, I'd be hesitant to forecsat out more than a month or so.
About this is there more of a naive universal practice or rule when deciding the forecast ratio that would give some ok accuracy? For instance: 6 months of real data to forecast 2 months in the future, etc.
