### ISSUE TITLE
adding support for subsettable ploting?

### ISSUE THREAD

**Issue by pmaji** [facebook/prophet#910]
@bletham -- I had seen in another issue that there was some interest in expanding the built-in plot's functionality such that one could plot subsets of the full time series. The answer at the time was that one could make a change to the underlying method to do just that. 

As part of [the vignette that I wrote up recently on all-things-prophet](https://github.com/pmaji/data-science-toolkit/blob/master/time-series/forecasting_with_prophet.ipynb), I added to the plot method to allow for precisely that requested functionality. Not sure how y'all handle this repo in terms of willingness to add PRs, but if you're interested in integrating that functionality, [here is the code I used to accomplish it!](https://github.com/pmaji/data-science-toolkit/blob/master/time-series/prophet_helper_functions.py)

**Comment by bletham** [comment]
I've been pretty hesitant to add too many customizations to `m.plot` since I think there's value to it having a really simple interface, and then since it returns the matplotlib `fig` you can really do whatever customization you'd want locally. Like
```
fig = m.plot(fcst)
ax = fig.gca()
ax.set_xlim(...)
```
This has also come up for things like customizing the color scheme, which is not a whole lot of code but including all customizations one might want would really bloat the interface.

For this particular customization of customizing the time range for the plotting: I can see that has some generic value, especially for exploratory work. But it looks like we'll be adding a plotly plot soon (#14) which would have dynamic zooming, and I think that would cover most of that use case while still keeping `m.plot` pretty simple. So assuming the plotly plot is ready for the next version, I'm inclined to not add this feature to `m.plot`.

**Comment by pmaji** [comment]
Sweet! I've been using plotly a lot more since plotly express came out, so looking forward to that PR. Any ETA on release?

**Comment by bletham** [comment]
I just merged it (#915), so if you install the current version on github you can try it out now, but it will be in the next release which I expect will be in the next month or so (one more big feature I'm hoping we can wrap up beforehand so it depends on how that one goes).
