### ISSUE TITLE
Modeling for known seasonal events, but that change significantly from year to year

### ISSUE THREAD

**Issue by nick-popovic** [facebook/prophet#926]
Hi there,

First off, I want to tip my hat off to the developers of Prophet as they have done a remarkable job in developing this framework - I have used it with great success in modeling/predicting some of my data’s seasonal trends that have static seasonal holidays.

I ran into the following issue and I was hoping somebody can shine some light on this for me (if this is the wrong place to ask this, please let me know!)

**Is there a way to model for known seasonal events, but that change significantly from year to year?** Say for Easter, one expects the number of airline passengers to significantly increase around that time since they are likely to fly home to visit family, friends ..etc.

One idea I had was to standardize the Easter holiday with say last year’s date and once Easter rolls around this year, remap this upcoming date to the date from last year (my so-called ‘standard’) then make forecasts based off this. I’m not particularly happy with this approach, however, since I run the risk of confounded effects from overlapping events/holidays that may coincide. Does FB-Prophet have something that can solve this problem?

Many thanks for your time and effort!

**Comment by vhpietil** [comment]
Have you tried using holiday regressors on Easter?

**Comment by bletham** [comment]
+1 for holiday effects suggested by @vhpietil (https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html)

But I'm a bit unclear on what you mean by the effect changing significantly from year to year. If you create a holiday and give it all Easter dates, then that will learn a constant effect for Easter that will be applied to all Easters, past and future.

If the effect changes is changing a lot from year to year then that wouldn't necessarily be the right model, but is there something predictable in how it is changing? If it's just a totally random effect every year, then you could create a separate holiday for each year in the past which would fit those really well, but there would be no way to predict the effect into the future (since we're assuming it's totally random, and so there's no way to use the history to predict the future). That's probably not what you're looking for. If you know that, for example, it should be increasing by a certain factor each year, then you could create an extra regressor with that factor for each date past and future and then it would be able to learn that effect.
