### ISSUE TITLE
From potential changepoints to real ones

### ISSUE THREAD

**Issue by nirvs44** [facebook/prophet#933]
I'm interested in how algorithm chooses real changepoints from array of potential changepoints. 

I've read some articles about sparse prior, Laplace distribution but still have no idea on how it works in practice. For example, with real case of 25 normally distributes potential changepoints (from fbprophet documention). What happens to get from picture 1 to picture 2?
Will be greatful for explanation!
![trend_changepoints_4_0](https://user-images.githubusercontent.com/7073039/56344156-673ccc00-61c5-11e9-90c6-8459b9248281.png)
![trend_changepoints_6_0](https://user-images.githubusercontent.com/7073039/56344162-69068f80-61c5-11e9-80f0-b3b0226d7812.png)

**Comment by bletham** [comment]
The model is a function that depends on these parameters `delta_1, ..., delta_25` which are the amount of change at each changepoint (as plotted in the 2nd plot above), among other parameters.

The model parameters (trend parameters, seasonalities, holiday effects) are all fit by minimizing mean squared error between model and data, plus some extra regularization. In particular, for the slope change parameters `delta_i`, there is a L1 regularization term (like Lasso regression). That means instead of just choosing `delta_i` to minimize mean squared error between model and data, it is chosen to minimize
```
[Mean squared error] + c * sum_i |delta_i|
```
where || is the absolute value.

The first term (MSE) is minimized by having the best possible model fit, but the 2nd term (c * sum_i |delta_i|) is minimized by setting all of the change values to 0. So what the model fitting will actually do is some combination of the two - try to minimize MSE as much as possible, while setting as many of the `delta_i` to 0 as possible. This is equivalent to Lasso regression and there is lots of material about it online.

The trade-off between the value of reducing MSE and setting `delta_i`'s to 0 is determined by the regularization parameter `c`: Increasing `c` means the fitting will be more willing to sacrifice MSE for the sake of setting more `delta_i` to 0, and vice versa. `c` here is basically the inverse of the `changepoint_prior_scale` parameter in the model, so setting the changepoint_prior_scale to be really low means the fitting will sacrifice more MSE for the purposes of setting more `delta_i` to 0, and vice versa. The "right" value of `c` (or, `changepoint_prior_scale`) in Lasso is typically chosen by cross validation, which can be done here as well using the built-in cross validation utilities.
