### ISSUE TITLE
How to fit the data more accurate?

### ISSUE THREAD

**Issue by Blankit** [facebook/prophet#939]
I want to fit a series data with some missing data. Codes are as below. As the figure shows, it doesn't work well. What should I do?   
`m = Prophet(daily_seasonality=15,seasonality_prior_scale = 30,changepoint_prior_scale=0.9)  `
`m.fit(df) `
`future = m.make_future_dataframe(periods=1)    `
`forecast = m.predict(future)`
![pm](https://user-images.githubusercontent.com/23358284/56509680-36a8b980-655a-11e9-9057-5b47f4cca82b.PNG)

**Comment by bletham** [comment]
What's the frequency of this data? Hourly?

The structure that Prophet will model trend, seasonality, and any specified holidays. Basically the only thing being captured right now is trend; there's a super weak seasonal effect being modeled, but it's basically no seasonality.

The difficulty is that there isn't really a clear seasonality that I can see in this time series. There are spikes during each day, but they're not consistent - in 2017-03 the spikes are really high, in 2017-07 they're almost entirely absent. The model doesn't have any way to know whether it should be really high or 0, and so it's ending up as about 0. If you have an extra regressor that explains the difference between the days with large effects and the days with small effects then you could include that in the model. Otherwise, unless you actually need hourly forecasts, you might be better off aggregating the data by day and making daily forecasts. That might make it easier to tell if there are weekly effects in aggregate.

**Comment by Blankit** [comment]
@bletham  Thank you for your reply. I want to make my problem clearly:
1. It's  hourly data.
2.  I have no idea how to  explain _the difference between the days with large effects and the days with small effects_ . Could you offer me some help?
3.  It's a  hourly forecast task.
4. I tried many different  combinations of parameters. The best result is as below.
`m = Prophet(daily_seasonality=8.5, weekly_seasonality=7,n_changepoints=90,changepoint_range=1.0,changepoint_prior_scale=10.0)`
![aa](https://user-images.githubusercontent.com/23358284/57496365-1bcd9780-7305-11e9-9682-b95542b3017e.png)
5. Is there a better way to adjust parameters?

**Comment by bletham** [comment]
I think the only way to improve the performance were if there were some external factor that you knew to explain why variability is very high in some days but very low in others. If you knew what that factor was, then you could include it as an extra regressor but otherwise the model isn't going to be able to pick that up.

**Comment by Blankit** [comment]
@bletham  The data is concentration of PM2.5 hourly, no more information could be provided.

**Comment by bletham** [comment]
In that case I think the time series just fit the model assumptions and unfortunately I'm not very optimistic that the forecast can be substantially improved.
