### ISSUE TITLE
Holiday Modeling

### ISSUE THREAD

**Issue by bsnithin44** [facebook/prophet#948]
Hello,

This is not an issue. I am looking for help in the below topic

I have a data 200 stores selling 30 different items (total 6000 unique TS datasets). The data is of fashion retail and is highly dependent on holidays.

The problem is that effect of a certain holiday might present in few TS datasets but not all, and i have 20 odd holidays ( country: India). If i specify all the holidays for every unique dataset I am getting bad results.

So my question is how to pick the holidays automatically?. Has anyone tried to map the peaks in data with holiday dates and therey by pick holidays? But what if your data is too noisy how do you find the correct peaks? It matters because sometimes two holidays might be very near.

Any help is appriciated.
Thank you.

**Comment by bletham** [comment]
Have you tried decreasing the `holiday_prior_scale` parameter (`holiday.prior.scale` in R)? It defaults to 10 but you could decrease it to 1 or 0.1 (or something in between) and see if that helps. What that will do is apply more regularization to the holiday effects so that the model will (in principle) only include the strongest holiday effects for each time series. If you try a few different values of `holiday_prior_scale` and make the components plot for each of them, you'll see the holiday effects getting set more and more to 0 as you decrease the prior scale.

**Comment by jarodleeyl** [comment]
Hi Ben,

The add_country_holidays function in R only allows the country_name argument, in addition to a Prophet object. The problem is in many countries, the holiday dates differ according to state.
For example, looking at https://github.com/dr-prodigy/python-holidays, the default state for Australia is ACT. Is there an option in add_country_holidays so that I can change the state to NSW for example?

Thanks.

**Comment by bletham** [comment]
@jarodleeyl no, that currently isn't possible. You can see the code to construct the dataframe of holiday dates is quite simple:
https://github.com/facebook/prophet/blob/b0c30454b6111a4a64763999823d3b2630f4196a/python/fbprophet/make_holidays.py#L43

I think the best thing to do for that would be to modify that function to have `holidays` be the output for NSW, and then the last 3 lines of constructing `holidays_df` will turn it into a dataframe you can just pass in to with the `holidays` input to Prophet.
