### ISSUE TITLE
Custom seasonality doesn't show up in components plot if starts with number (R)

### ISSUE THREAD

**Issue by bletham** [facebook/prophet#996]
If a custom seasonality name starts with a number (like "2year"), then in R it won't show up in the components plot because in the forecast dataframe its component will not be named "2year", rather it will be named "X2year".

**Comment by bletham** [comment]
I believe the seasonality will also not be used for model fitting but haven't diagnosed the full extent of this issue.

**Comment by daikonradish** [comment]
@bletham - you seem to be on to something. If the seasonality name begins with a number, then for some reason the associated `params` are set to 0. Try the following:

    library(prophet)
    df <- read.csv("~/Documents/prophet-daikonradish/examples/example_wp_log_peyton_manning.csv")
    
    # This has a name that starts with a number; the `betas` associated with it are set to zero.
    m <- prophet()
    m <- add_seasonality(m, name='2monthly', period=61, fourier.order = 5)
    m <- fit.prophet(m, df)
    m$params

    # This has a name that starts with a letter; the `betas` associated with it are not set to zero.
    m1 <- prophet()
    m1 <- add_seasonality(m1, name='twomonthly', period=61, fourier.order = 5)
    m1 <- fit.prophet(m1, df)
    m1$params

This _probably_ has to do with the following:

1. [**I am extremely sure of this**] This offending [line](https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L546). The function `data.frame()` has an optional argument `check.names` that defaults to `TRUE`. Any column name that begins with a number is prepended with `X`.
2. [**I am only 60% sure of this**] The code usually uses `for (name in names(m$seasonalities))` to iterate through the names of the seasonalities, but then this doesn't generate a match in the column names, which _already_ has a prepended X.

There are two possible fixes:

1. [**easy**] Disallow any name that starts with a number (or any other potentially offensive character), _OR_ warn the user and prepend an X wherever we see a name that has that character.
2. [**hard**] In this [line](https://github.com/facebook/prophet/blob/master/R/R/prophet.R#L546), change the return value to `data.frame(features, check.names=FALSE)`. However, this option is _super_ hard because it then interferes with `ggplot`'s nonstandard evaluation of arguments to match them to column names. We might then go and do something like [this](https://stackoverflow.com/questions/53978122/how-to-use-column-names-starting-with-numbers-in-ggplot-functions), but I'm not sure if this is safe to do since it would mess a lot with `ggplot` internals, and `plot.R` is already doing _the most_ with `ggplot` internals. 🤣 

What do you think?

**Comment by bletham** [comment]
Thanks for looking into this more deeply. I think one of the [easy] options seems like it would be less likely to cause issues in the future.

I think in this case I'd favor renaming the seasonality automatically if it is invalid. It looks like R has a function for doing this: https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html . I think this will be less disruptive than throwing an error and asking them to come up with a different name. It could cause an error downstream if someone were trying to extract the seasonality column from the forecast dataframe and didn't know it had been renamed, but they'd hopefully be able to quickly figure out what had happened.

Although I am now wondering if we need to do something for this with extra regressors too. For extra regressors it has to already be the name of a column in the history dataframe, but if that dataframe was created with `check.names=FALSE` then we might run into a similar issue there. Here though we definitely wouldn't want to auto-rename, because it needs to match the column in the existing dataframe, and so I think the only reasonable option would be to throw an error and ask them to rename it in the history dataframe too. If we throw an error for extra regressors, then maybe it would be a more consistent behavior to throw an error for seasonality. That said I do still lean towards auto-rename for seasonality and error for extra regressor, but would love to hear your thoughts too.

**Comment by daikonradish** [comment]
I actually just lean in favor of the simple solution and error out for both for consistency’s sake. I think it’s not too much to ask for users to rename their columns because of certain preëxisting conventions in R - in that I think it’s reasonable for Prophet come in at the same level as what most R programmers would expect (in this case, column names should not begin with letters), but no more.

**Comment by daikonradish** [comment]
library(prophet)
df <- read.csv("~/Documents/prophet-daikonradish/examples/example_wp_log_peyton_manning.csv")

    # This has a name that starts with a number; the `betas` associated with it are set to zero.
    m <- prophet()
    m <- add_seasonality(m, name='two-monthly', period=61, fourier.order = 5)
    m <- fit.prophet(m, df)
    m$params
    # also zeros everywhere :( 
 
for more evidence that we _should_ be using `make.names` everywhere, it's not just names that start with numbers - it's also names that contain hyphens. I think we should try to just stick to R conventions. 😐

**Comment by bletham** [comment]
ugh, yeah I didn't realize R was that picky with column names.

**Comment by bletham** [comment]
I'm going to leave this open until we actually push it to CRAN

**Comment by bletham** [comment]
This is pushed to CRAN in v0.6
